### ISSUE TITLE
Support for Boto3 instead of s3fs

### ISSUE THREAD

**Issue by PetitSphincter** [dask/dask#10214]
Hi, 

I'm a heavy user of dask on a local s3 servers (scality). 
On my infrastructure, boto3 **download_fileobj** is way faster than s3fs method open (which I assume is used by dask, correct me if i'm wrong). And it seems to be the case for a lot of others usages than local s3 servers.

Apart from having a "pythonic" open method (which makes no difference for a Dask user if it's encapsulated) i don't see any advantages to Dask using s3fs instead of boto3. 

It's also making the install heavier because it needs boto3 for authentication. 

I'm wondering why this decision was made to use s3fs and why boto3 isn't used by dask to open s3 objects ? 
Wouldn't it be cleaner to only use boto3 since you already need it for authentication and s3fs use it anyway ? 
Could it be possible to switch the s3 back-end Dask is using to boto3 (i mean high end boto3 api such as download_fileobj, not low-end API get_objects operation which are similar in speed to s3fs) and is there a reason not to ?

**Comment by jrbourbeau** [comment]
Dask relies on `fsspec` (https://github.com/fsspec/filesystem_spec) because it provides a uniform filesystem interface to a variety of file stores (e.g. local files, S3, GCSFS, Azure, etc). This way we just need to use `fsspec` for file access, and it will make sure files are properly opened, regardless of where they are located. Other libraries in the ecosystem (e.g. `pandas`) also similarly rely on `fsspec`. 

cc @martindurant for the `boto3` vs. `s3fs` performance point

**Comment by martindurant** [comment]
> On my infrastructure, boto3 download_fileobj is way faster than s3fs method open 

Please be very specific about what operations you are doing. I very much doubt that there is any performance difference for equivalent operations. For example, the s3fs verb for "download a file" is `get()` (alias `download`); the verb for "fetch all the bytes of" is `cat()` (alias "read_bytes"). If you `open()` a file, as dask sometimes does, you are asserting you will want random access to its bytes, and the size and type of the internal buffer is *very important*.

**Comment by martindurant** [comment]
> It's also making the install heavier because it needs boto3 for authentication.

I would appreciate clarification on what this point means. s3fs does not depend on boto3.

**Comment by mrocklin** [comment]
I think that @rabernat has mentioned similar things.  He might have different context to offer here (if he has the time).

**Comment by rabernat** [comment]
In https://github.com/martindurant/rfsspec/issues/7 I concluded there was no measurable difference for a basic `get_object` operation in s3fs vs boto3. These operations are i/o bound, and s3fs does not introduce any meaningful additional overhead.

In cloud-native analytics with dask, we are generally not "downloading" anything--we are streaming directly from S3 to the CPU. I would definitely want to see a concrete example of s3fs being slow before considering this very significant refactor.

@PetitSphincter - can you describe how `download_fileobj` is used in your dask workflow?

**Comment by rabernat** [comment]
I think you're comparing apples and oranges here. `s3_client.download_fileobj` downloads the entire object to disk (or in your case, bytes in memory). `s3.open` attempts to retrieve the required bytes on demand. That's why you see that s3fs is actually faster for smaller reads, while the boto3 time is much more constant--with boto3, the entire file is always downloaded.

Have you tried [`s3.download`](https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem.expand_path) instead? That might provide a more fair comparison.

> In fact my question has nothing to do with dask, I just wanted to understand why it used by dask while it seems to be less performant than the standard aws client.

The answer to this question is that s3fs has many desireable features that boto3 lacks. The fsspec documentation [features](https://filesystem-spec.readthedocs.io/en/latest/features.html) section has a good explanation of these features. Serializability of file-like objects is particularly important in the context of dask, where references to files have to be shipped over the network.

If you wanted to replace s3fs with boto3 in dask, you would end up having to re-invent many of the features of s3fs. A much more collaborative path would be to get involved in s3fs development and contribute performance improvements for the cases you care about. I'm sure your contributions would be welcome.

**Comment by PetitSphincter** [comment]
> s3.open attempts to retrieve the required bytes on demand.

Yup didn't understand that until i did that test which changes a lot of things

I think it's far more clear in my brain right now, thanks for your time

**Comment by martindurant** [comment]
It is worth explaining the specific behaviour shown in your graph - thank you for providing specific details here. s3fs uses an internal buffer, normally readahead, to reduce the number of calls to remote. The bigger the buffer (`block_size=...`), the fewer calls need to be made and the closer s3fs's apparent throughput would approach the boto3 download case (which makes exactly one call). 

The default block size is a rather small 5MB. Why so small? With some file types, you will want to read relatively small blocks of bytes from various parts of the file (random access), and if these pieces are smaller than the blocksize, you end up downloading unnecessary data. A user can tune the size of the readahead buffer, but we have found it a reasonable compromise in size.

For dask's use, we typically read whole blocks from some part of a large file in each task. For CSV, we also need "a bit extra" to find the next end-of-record; for parquet we know exactly which byte ranges we need. Therefore, these do not suffer from the many-calls effect shown in the graph, and these two file types alone cover a large fraction of IO for dask. Some others, like zarr, involve reading only whole files, so that's fine too.
