### ISSUE TITLE
dask.dataframe.read_csv fails when dtype isn't a dictionary

### ISSUE THREAD

**Issue by toniatop** [dask/dask#1021]
from dask import dataframe as dd
    df=dd.read_csv(tindx_blk_lst,delim_whitespace=True,compression='gzip',header=0,skiprows=[0,2],dtype=np.float64)

fails with `error TypeError: argument of type 'type' is not iterable`

I think that the logic that fails is in this section of dask/dataframe/io.py

    if 'sep' not in kwargs:
        new_dtype = dict(head.dtypes)
        dtype = kwargs.get('dtype', dict())
        for k, v in dict(head.dtypes).items():
            if k not in dtype:
                dtype[k] = v

        if kwargs.get('parse_dates'):
            for col in kwargs['parse_dates']:
                if isinstance(col, (tuple, list)):
                    del dtype['_'.join(col)]
                else:
                    del dtype[col]

        kwargs['dtype'] = dtype

Should be there an option to consider whether delim_whitespace is passed or not?

(dask version 0.8.0)

**Comment by mrocklin** [comment]
Yeah, I think that generally we should refactor/rewrite `read_csv`.  The current logic is too error prone to things like this.  See #1022

**Comment by jcrist** [comment]
The issue here is not `delim_whitespace`, but that `dtype` is a type, not a dictionary (as the code expected it to be). I'm working on a refactor of `read_csv` right now, and will fix this. For now, if you pass in a dictionary mapping names to `np.float64` (something like `dtype=dict.fromkeys(col_names, np.float64)`), this should work fine.
