### ISSUE TITLE
Error reading CSV

### ISSUE THREAD

**Issue by orlandombaa** [dask/dask#10358]
Hi every one

I just started to use Dask. I working in ptyhon 3.11 under Mac OS Monterrey.  I am following the tutorial on the official webpage.  In the following exercise: 
https://tutorial.dask.org/01_dataframe.html

I am trying to read the csv of the following link: https://storage.googleapis.com/dask-tutorial-data/nycflights.tar.gz
https://github.com/TomAugspurger/dask-tutorial-pycon-2018/blob/master/prep_data.py

which I assume is the same dataset that the tutorial makes reference. The problem comes when I read the set of CSV, dask seams to read it correctly  but once I try to use the `.head()`  function of any action to the dask data frame an error occurs, like the following: 

`CancelledError: ('head-1-5-read-csv-0265b3a2830fc544cbabd0553c416c40', 0)`

the reading: 

`ddf = dd.read_csv(
    os.path.join("nycflights", "*.csv"),  parse_dates={"Date": [0, 1, 2]}, blocksize="100MB")`

I have read the CSV using pandas and the datasets seem pretty normal. I have no idea where the problem comes from. I will  appreciate if someone can give me a hand.  I am using pandas 2.0.2  and dask 2023.6.1. 

Additionally, I tried the same code with the same set of CVS in a Windows machine without error. 

thank you

**Comment by TomAugspurger** [comment]
Just to confirm, did you run the

```
%run prep.py -d flights
```

cell up above the cell reading that data? Can you share the traceback from both the prep cell and the `read_csv` cell?

**Comment by orlandombaa** [comment]
Hello @TomAugspurger , Yes I have run the script prep.py it generated the set of CSV in the folder data.  I delete my environment and try it in a new one and it works.... one time. Once I open again the notebook it gives me the same error:


`CancelledError: ('head-1-5-read-csv-7ec61e786cad1eb9dfaebe5512b69648', 0)`

**Comment by TomAugspurger** [comment]
> Once I open again the notebook it gives me the same error:

Can you explain your steps in detail? Do you stop / restart the jupyter notebook server? Do you have multiple Dask clients / clusters running?

**Comment by GenevieveBuckley** [comment]
Hi @orlandombaa 

I think you are having problems because you seem to be using a mix of old and new scripts (for example the [prep_data.py](https://github.com/TomAugspurger/dask-tutorial-pycon-2018/blob/master/prep_data.py) file you link to is in an archived repository from 2018, so this is out of date).

The easiest way to work through the tutorial exercises on your Mac will be to download the entire [dask-tutorial repository](https://github.com/dask/dask-tutorial). The contents of repository is what you see online at https://tutorial.dask.org/. That way you'll know you have all the notebooks and data preparation scripts up-to-date, and working well with each other.

To be safe, you can also re-do [the preparation steps](https://github.com/dask/dask-tutorial#prepare) to be completely sure everything works. (FYI nothing sounds wrong with your environment setup, I also have Mac Monterey and things seem to work well with python 3.11, dask 2023.6.1 & pandas 2.0.2 - but sometimes it's nice to start fresh).

You won't need to download anything else. The `01_dataframe.ipynb` notebook will automatically download the example flights dataset when you run the cell `%run prep.py -d flights` (that cell executes the [prep.py](https://github.com/dask/dask-tutorial/blob/main/prep.py) file you downloaded along with everything else in the [dask-tutorial repository](https://github.com/dask/dask-tutorial)).

**Comment by GenevieveBuckley** [comment]
I'll close this because I think we've identified the fix (download the whole [dask-tutorial repo](https://github.com/dask/dask-tutorial) rather than mixing and matching scripts). 

If you're still having trouble after trying that, please re-open this thread or make a new issue. I hope it helps!
