### ISSUE TITLE
The Joy and Agony of Categorical Types

### ISSUE THREAD

**Issue by jcorbin** [dask/dask#1040]
## Intro

First off cheers on where you've got dask to today, it's been immediately
useful for my applications of sifting log data.  In fact it's because dask is
so wildly useful that I keep trying to push through the rough patches and
improve what limitations I think I'm finding.

I'm recording a limitation that I hit while trying to do some group aggregation
work to open up discussion in various ways.
## Summary

Using categorical types can drastically speed up a group aggregation
computation (by nearly an order of magnitude) if it worked.  Core issue seems
to be a lack of support for combining slightly different categoricals in
`pandas.concat`.  There's potential to workaround it in dask's dataframe core,
if we can sort out a working hack.

I finish out with some remarks in general about the JSON => dataframe gap.
## Problem
- I've got a pile (~10GiB across ~400 files) of gzipped-json data
- I want to extract dimensions A, B, and C from it; A and B are string labels,
  C is a floating point
- I want to group by the compound (A, B) dimension, and then take the count and
  sum(C) across those groups
## Setup

I've found it fastest to just write my own shard loading function, rather than
deal with the typical pipeline (bag lines, map json, pluck pluck munge,
to_dataframe...):

``` python
columns = ['A', 'B', 'C']

import ujson  # about 2x faster than core json in my experience

def load_record(line):
    record = ujson.loads(line)
    return (record['A'], record['B'], record['C'])

@dask.do
def load_shard(path):
    with dask.utils.open(path, compression=dask.utils.infer_compression(path)) as f:
        records = map(load_record, f)

    shard = pd.DataFrame(records, columns=columns)
    shard['A'] = shard['A'].astype('category')  # XXX these are the contentious parts
    shard['B'] = shard['B'].astype('category')  # XXX ...
    shard['C'] = shard['C'].astype('float')

    return shard

paths = !find path/to/data -type f
shards = map(load_shard, paths)
df = dask.dataframe.from_imperative(shards, columns)
G = df.groupby(['A', 'B'])['C']

with dask.diagnostics.Profiler(watch=True):  # uses the WIP #1030
    # if we don't specify get here, then load_shard is GIL contended and the
    # whole thing takes ~Nx longer (N = num_workers)
    count, total = dask.compute(G.count(), G.sum(), get=dask.multiprocessing.get)
```
## Results

Running over 10 shards (just slice the paths to shards array above) for easy
comparison, the above finishes in ~16 seconds on my machine, but yields the
unsatisfying exception in final result combination:

```
TypeError: categories must match existing categories when appending

Traceback
---------
  File "/.../dask/dask/async.py", line 264, in execute_task
    result = _execute_task(task, data)
  File "/.../dask/dask/async.py", line 245, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/.../dask/dask/async.py", line 246, in _execute_task
    return func(*args2)
  File "/.../dask/dask/dataframe/core.py", line 51, in _concat
    return pd.concat(args2)
  File "/.../lib/python2.7/site-packages/pandas/tools/merge.py", line 812, in concat
    copy=copy)
  File "/.../lib/python2.7/site-packages/pandas/tools/merge.py", line 949, in __init__
    self.new_axes = self._get_new_axes()
  File "/.../lib/python2.7/site-packages/pandas/tools/merge.py", line 1028, in _get_new_axes
    new_axes[self.axis] = self._get_concat_axis()
  File "/.../lib/python2.7/site-packages/pandas/tools/merge.py", line 1080, in _get_concat_axis
    concat_axis = _concat_indexes(indexes)
  File "/.../lib/python2.7/site-packages/pandas/tools/merge.py", line 1098, in _concat_indexes
    return indexes[0].append(indexes[1:])
  File "/.../lib/python2.7/site-packages/pandas/core/index.py", line 4943, in append
    arrays.append(label.append(appended))
  File "/.../lib/python2.7/site-packages/pandas/core/index.py", line 3542, in append
    to_concat = [ self._is_dtype_compat(c) for c in to_concat ]
  File "/.../lib/python2.7/site-packages/pandas/core/index.py", line 3193, in _is_dtype_compat
    raise TypeError("categories must match existing categories when appending")
```

For comparison, if we leave the strings as strings the computation succeeds,
but takes ~2:25 or ~145 seconds, nearly 9x the time of the categorical version.
The data size (as measured by `pd.DataFrame.to_pickle(...)`ing each of the 10
shards) only differs by a factor of ~2.5x, so there must be some sort of an
amplification effect going on as we have to keep (de)serializing between each
of the work units.

What's truly interesting about this performance difference is not simply that
the shard loading takes more time (due to serialization overhead), but that the
actual group sum/count work takes proportionately much more time; with
categorical types the group aggregation work was negligible, but with strings
it dominates over the extraction work.

Here's the task profile using categoricals:
![image](https://cloud.githubusercontent.com/assets/49715/13644918/19154672-e5dd-11e5-8ae2-e33d7fcd34a8.png)

And here's the task profile without categoricals (just using dtype object of strings instead):
![image](https://cloud.githubusercontent.com/assets/49715/13644955/561ea7c0-e5dd-11e5-90b3-642728c685c6.png)
## Attempt to workaround

Based on taking two of my shards and learning how to concat them in isolation:

``` python
a, b = df.compute(shards[:2])

# XXX this will throw a `ValueError: incompatible categories in categorical concat`
#    pd.concat([a, b])

# however if we define:

def align_categories(a, *bs):
    for dim in a.dtypes.index[a.dtypes == 'category']:
        a_S = a[dim]
        bs_S = [b[dim] for b in bs]
        a_cats = set(a_S.cat.categories)
        bs_cats = [set(b_S.cat.categories) for b_S in bs_S]
        all_cats = reduce(set.union, [a_cats] + bs_cats)
        a_S.cat.add_categories(all_cats - a_cats, inplace=True)
        for i, b_S in enumerate(bs_S):
            b_cats = bs_cats[i]
            b_S.cat.add_categories(all_cats - b_cats, inplace=True)
            b_S.cat.reorder_categories(a_S.cat.categories, inplace=True)


# now we can:
align_categories(a, b)
df = pd.concat([a, b])
```

Heartened, we try:

```
diff --git a/dask/dataframe/core.py b/dask/dataframe/core.py
index 9b5e129..7d9e276 100644
--- a/dask/dataframe/core.py
+++ b/dask/dataframe/core.py
@@ -49,12 +49,27 @@ def _concat(args, **kwargs):
         if not args2:
             return args[0]
         return pd.concat(args2)
+    align_categories(*args2)
     if isinstance(args[0], (pd.Index)):
         args = [arg for arg in args if len(arg)]
         return args[0].append(args[1:])
     return args


+def align_categories(a, *bs):
+    for dim in a.dtypes.index[a.dtypes == 'category']:
+        a_S = a[dim]
+        bs_S = [b[dim] for b in bs]
+        a_cats = set(a_S.cat.categories)
+        bs_cats = [set(b_S.cat.categories) for b_S in bs_S]
+        all_cats = reduce(set.union, [a_cats] + bs_cats)
+        a_S.cat.add_categories(all_cats - a_cats, inplace=True)
+        for i, b_S in enumerate(bs_S):
+            b_cats = bs_cats[i]
+            b_S.cat.add_categories(all_cats - b_cats, inplace=True)
+            b_S.cat.reorder_categories(a_S.cat.categories, inplace=True)
+
+
 def optimize(dsk, keys, **kwargs):
     from .optimize import optimize
     return optimize(dsk, keys, **kwargs)
```

However that `ValueError` wasn't actually our problem, we had a slightly
different `TypeError` due to the indicies of the aggregate shards being derived
from a categorical.  Note in my case they're actually `MultiIndex`es and not
actually a `CategoricalIndex`.

Here is where I left of, having decided to write up this summary instead.
## Sidebar: the joy and agony of JSON loading

Also I'm interested in feedback on the approach I've landed on for loading and
extracting JSON here:
- use an imperative shard loading function that goes from file path to
  dataframe in one shot
- allowing me to inline plucking and type casting also at the same time

I don't have numbers on the gains here, since I made the shift away from
equivalents like:

``` python
lines = db.from_filenames(all_the_files)
records = lines.map(ujson.loads) # <-- this is ~2x win over json.loads btw
tuples = records.map(some_plucking_function)
df = tuples.to_dataframe()
df.map_partitions(some_type_casting_function)
```

I tried many variations on this:
- like using a `map_partitions` on records and returning direct tuple-lists
- a pluck/zip network between records and `df = ....to_dataframe()`

But in the end, just writing an imperative shard loader was at least an order
of magnitude faster.

**Comment by mrocklin** [comment]
Yeah, I generally agree with all of this.  

### Categoricals

Categoricals are a potential huge performance win, both for serialization and for computations.  This blogpost on the topic, http://matthewrocklin.com/blog/work/2015/06/18/Categoricals , is consistently one of my most frequently viewed.

There have been attempts to resolve this problem with an extra pass over the data, both in the Castra project (append incrementally adds new categories) and with the full `categorize` method on dask dataframes.  Alternatively if you're doing things by hand and know your categories ahead of time that can save you a lot of pain.

Another option would be to implement auto-aligning categories in Pandas.  This would allow  dask.dataframe to categorize on a per-partition basis as you've done and then mostly ignore the issue.  This is probably fairly costly to do in Pandas though.  The categorical codebase seems to be expensive to develop and maintain. 

We could try to do something fancy here, like auto-aligning all partitions that are likely to meet, but I'm not sure how to do this robustly, mostly because we don't know ahead of time what partitions are likely to interact with each other.  If you have ideas about how to do this cheaply in a sustainable way I'd be very glad of them.

### Serialization

Ideally serialization should not be a large cost here.  Almost all of your computations are embarrassingly parallel and so we should be able to fuse almost all of them.  The fact that you're seeing a performance difference when stepping away from chaining/pipelining operations is a sign that this isn't happening properly.  

You might try the `distributed` memory scheduler on just a single machine.  It manages worker state far more effectively

```
pip install distributed
dscheduler
dworker 127.0.0.1:8786 --nprocs 8
```
```python
>>> from distributed import Executor
>>> e = Executor('127.0.0.1:8786')
>>> ...
>>> count, total = dask.compute(G.count(), G.sum(), get=e.get)
```

**Comment by jcorbin** [comment]
Ahha, good to know, I will try out the distributed scheduler at some point Soon ™ ;-)

In the mean time I'd already started going down the path of "an extra pass" like you say to pre-promote all of my categoricals, will see how that goes and probably toss out a few PRs for convenience features towards doing so.

Thanks for the quick response :-)

**Comment by jcorbin** [comment]
Okay made progress:

## Results

Using a two-pass approach to pre-align all my categoricals ended up finishing
in ~48 seconds for ten shards, with plenty of lost room in the schedule (i.e.
time that would've been filled by other shards once I scale up to the full data
set):

![image](https://cloud.githubusercontent.com/assets/49715/13647670/ff3b9794-e5e9-11e5-96cc-e48c2995bd48.png)

## How do?

Here's how I did it:

```python
def merge_set_dicts(sds):
    a, bs = sds[0], sds[1:]
    for b in bs:
        for key in b:
            a[key] = a.get(key, set()) | b[key]
    return a

def extract_cat_vals(df):
    return {
        key: set(df[key].cat.categories)
        for key in df.dtypes.index[df.dtypes == 'category']
    }

def align_categories(df, acv):
    for key in acv:
        vals = acv[key]
        S = df[key]
        S.cat.add_categories(vals - set(S.cat.categories), inplace=True)
        S.cat.reorder_categories(sorted(vals), inplace=True)
    return df

shards = dask.bag.from_imperative(map(dask.do(load_shard), paths))

all_cat_values = shards.reduction(
    perpartition=extract_cat_vals,
    aggregate=merge_set_dicts,
    out_type=dask.imperative.Value
)

aligned_shards = shards.map_partitions(align_categories, (all_cat_values,))
```

Notes:
- added support for `out_type=Value` to `Bag.reduction` to shorten
  `shards.reduction(..., out_type=Bag).to_imperative()[0]` (will PR this one
  shortly)
- added support for passing extra args to `Bag.map_partitions` so that I can
  thread thru the final reduction result into all calls of `align_categories`;
  maybe this should've been *args? (will also PR this one shortly)
- would like to add a `finalfunc` kwarg to `Bag.reduction` to compose with the
  final aggregate; in this case I'd use it to turn each finalized set into a
  sorted list once, rather than doing the sorting within each
  `align_categories`

I could wrap all of this up into a new `dd.DataFrame` convenience method, which
we start having user call manually.  Later on if we may find places where it
makes sense to add a "peek at the first partition's dtypes, maybe align
categories" heuristic?

**Comment by mrocklin** [comment]
It's fun seeing someone else use the internal bag reduction API.  Yes, I think that adding a `finalize` function to reduction would be reasonable. 

Swapping out Item for Value generally might be worthwhile long term if we could find a way to keep the defaults like `multiprocessing.get` on there.  Supporting `Value` in `out_type` as you suggest seems like a good immediate solution.

It would be interesting to see what the convenience method would look like.  As a warning I'm always a bit hesitant to add convenience functionality onto dask.dataframe, mostly due to maintenance burden.

**Comment by mrocklin** [comment]
@jcorbin what is the status of this issue?  Are you able to summarize work that is reasonable to do in the near future?

**Comment by jcorbin** [comment]
Currently I've got a set of utility functions in my `dask.dataframe` module, rather than carrying them as methods.  I can brush that up and put it in a PR if it sounds like something you'd want to carry.  In short, it's:
- a function to extract any category values from a single pandas.DataFrame
- a reduction function that combines a list of those extracted category values
- a function that up-casts any categories to a given set of known category values (reduces by the last function)
- finally, a top-end function that sets up a dask graph:
  - reduce out all category values using the first two functions
  - then do a second pass map with the third function, with the reduction value passed in

**Comment by mrocklin** [comment]
Ah, you're starting from many pandas dataframes-with-categoricals?

I wonder if some of this might go in the dask.dataframe.categorical module that is there now (was there anything in there of use to you?)

**Comment by jcorbin** [comment]
Good question, I hadn't noticed that module, I'll take a look Soon ™ and reply :-)

**Comment by jreback** [comment]
FYI: https://github.com/pydata/pandas/pull/13361 just merged into 018.2

**Comment by makmanalp** [comment]
I just want to drop in this thread and express my highly enthusiastic support for this functionality. Categoricals are helpful when reading/writing files too - for certain kinds of datasets it's not uncommon for me to see a 10x improvement in file size, even with compressed columnar formats, when using a categorical. This is absolutely amazing, because it's often the difference between the same data fitting in memory or not. Also, smaller files mean much less I/O, which is often the bottleneck in our workloads. Same data with a much more compact representation is a no-brainer for us, and if issues around concatenation across many files are simplified, everything is just 🍑 🍰 🎉 .

**Comment by jcrist** [comment]
Oop, this should have been closed by https://github.com/dask/dask/pull/1877. With dask 0.14.0+ dask supports having different categoricals in each partition. This allows data to be stored in categorical format without needing to pre-compute categories. We also now support reading directly from csv to (unknown) categoricals, just as pandas does. Note that functions that require knowing the full set of categoricals will fail until categories are made known.

Example: https://github.com/dask/dask/pull/1877#issuecomment-273610579.
More information: http://dask.pydata.org/en/latest/dataframe-design.html#categoricals

Closing.

**Comment by makmanalp** [comment]
@jcrist you just made my day. Thank you! I can't wait to try this!

**Comment by jcrist** [comment]
Glad to hear it :). Please file any issues you come across.

**Comment by makmanalp** [comment]
@jcrist Just a quick question - I'm trying to load a bunch of gzipped csv's one by one and append them into a single parquet as I load them. The stupid reason I'm doing it this way is because since they're gzipped, dask can't chunk them bit by bit to fit in memory well, and so doing `df.read_csv("foo*.gz", compression="gzip", blocksize=None)` will exhaust memory and start swapping pretty quickly. Anyway, this gives me:

```
ValueError: Appended dtypes differ.
{('medium', dtype('O')), ('routeorstation', category), ('faretype', category), ('timeperiod', dtype('O')), ('routeorstation', dtype('O')), ('medium', category), ('timeperiod', category), ('faretype', dtype('O'))}
```

Does this mean that the categories don't get written as categories in native parquet, so it thinks they're objects? I should load two dataframes at a time and concatenate them and save?

I realize that this is an edge case that I can probably work around otherwise, but just figured I'd bring it up.

**Comment by makmanalp** [comment]
Ah, OK, I'm slowly figuring this out - it looks like parquet won't preserve complex datatypes pd.Timestamp and category (unlike HDF5), which given its focus on interoperability, makes sense.

**Comment by martindurant** [comment]
@makmanalp , I don't quite follow your question - is there any chance you can reduce it to its parquet part and post an issue on fastparquet? fastparquet *does* save categories (so long as the category values can be stored) and timestamp types.

**Comment by makmanalp** [comment]
@martindurant sorry about the mess here on the issue tracker - just made a ticket.
