### ISSUE TITLE
PyArrow 12 is 50x slower on `read_parquet`

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#10523]
Reopened from https://github.com/coiled/benchmarks/issues/998

python 3.11, dask 2023.9.2, pandas 2.0 or 2.1, coiled
```python
import dask.dataframe as dd

ddf = dd.read_parquet(
    "s3://coiled-runtime-ci/thousandgenomes_dagen/NA21**.parquet",
    engine="pyarrow",
    index="sample_id",
)
part = ddf.partitions[0].persist()
part.head()
```
Time to load the first partition:

#### pyarrow 11: 8s
dtype of string columns is `object`
dask creates a `read_parquet` task

#### pyarrow 12/13: 391s (97% CPU time)
dtype of string columns is `string[pyarrow]`
dask creates a `to_pyarrow_string` task.

The partition is 30 million rows in both cases.

CC @phofl @jrbourbeau

**Comment by phofl** [comment]
The dataset has some columns that are lists, which we convert to PyArrow strings in a post processing step (which is kind of a known bug because we shouldn't be doing this) and converting Python objects to Arrow strings is slow. That's what causing the slowdown here.

pandas has a new option in 2.1 that infers arrow strings automatically for actual strings, which would solve this potentially.

**Comment by jrbourbeau** [comment]
@phofl and I spoke offline a bit about this problem. As he mentioned, there's some new functionality in pandas that we can probably start deferring to instead of manually casting ourselves. That should, in theory, make it so we only cast string columns to pyarrow strings (we do this efficiently for parquet).

**Comment by phofl** [comment]
This is fixed with dask-expr
