### ISSUE TITLE
Alias dask.do to something else?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1084]
The `dask.do` function is powerful but somewhat difficult to teach to people.  I wonder if some of the learning curve could be improved by a different name.  Options that came to mind included the following:

    delay(f)(*args)
    task(f, *args)
    delayed(f)(*args)  # this is what joblib does

Thoughts?

cc @jcrist @shoyer

**Comment by jcrist** [comment]
This has come up enough that I'm +1 with changing it to something people like better. I like `do` because it's short, which makes it nice to use inline. Perhaps 2 functions could be nice to support the 2 usecases:

```
delayed(f)(*args)    # Can be used as a decorator on a function
do(f, *args)         # Or `task`, `delay`, `run`, `submit`, `apply`, etc...
```
For the second one, I like `do` best, but we'd have to do some fancy deprecation thing to make it work.

**Comment by shoyer** [comment]
I like "delayed" for the decorator, in part because it mirrors joblib. For
the version that creates a task, I like task(f, *args, **kwargs), although
I'm not sure we really need both. run/submit/apply have possibly confusing
semantics because they suggest a task might start to be run immediately.

**Comment by mrocklin** [comment]
I'm only suggesting an alias.  It sounds like people are ok with adding the following:

```python
delayed = do
```

**Comment by mrocklin** [comment]
See https://github.com/dask/dask/pull/1085
