### ISSUE TITLE
Replace from_imperative with from_delayed?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1091]
We recently renamed `do` to `delayed`.  In an effort to reduce names should we replace occurrences of `imperative` with `delayed` as well?  In particular I'm considering the `Collection.from_imperative` functions.  Currently we're asking users to know that the terms `delayed` and `imperative` are related.

**Comment by jcrist** [comment]
Sounds reasonable. Just to be clear, I'd prefer to add a deprecation cycle for them instead of just removing (which you may also be suggesting). This brings up a few questions on other names though.

- The file is named `imperative`
- The objects are `Value`s
- The creation functions are `value` and `delayed`

`Value` and `value` are nice if you think of them as objects containing a value. A different point of view is that they're like futures representing a delayed computation. The names could then be `Delayed`, `from_object` (or some other thing), and `delayed`. I'm not suggesting that these are better names, but when doing this it might be nice rethink our other naming choices.

**Comment by mrocklin** [comment]
Thoughts on deprecation warnings?  I'm tempted to just use a print statement instead of the warnings module.

**Comment by mrocklin** [comment]
`Value` -> `Delayed` seems like a gain in specificity.  Not sure what to do with `value`.  A part of me wants to overload `delayed` to work on non-callables.  This is almost always the right thing to do (only becomes ambiguous for callables that we want to be values.

**Comment by jcrist** [comment]
> Thoughts on deprecation warnings? I'm tempted to just use a print statement instead of the warnings module.

Print statements can't be turned off by filtering (whereas warnings can). I'm fine with handling the warnings stuff, it shouldn't be too messy.

> A part of me wants to overload delayed to work on non-callables.

My personal preference is to separate the two, as they do very different things.
- `delayed` takes a function, and returns a callable that returns a `Value`
- `value` takes an object and returns a `Value`

Perhaps `as_delayed`? `to_delayed`?

Backpedaling a bit, I'm not 100% convinced that `Delayed` is a good name for the class. Currently I'm feeling more prone to treating the objects as the result, rather than as the computation (whereas this afternoon I felt the other way). The wrapped functions are "delayed" computations, the objects are the results of those computations. `Result` is a vague term (not that `Value` is better), and `Future` is overloaded (and these aren't really futures). `DelayedResult`?

**Comment by jcrist** [comment]
CC @shoyer, who seems to have a good eye for api.

**Comment by mrocklin** [comment]
How about `delayed, as_delayed, DelayedResult` then?

**Comment by mrocklin** [comment]
(I'm doing this now btw)

**Comment by shoyer** [comment]
I never found "imperative" to be very intuitive, so +1 on renaming everything to use delayed.

I assume you're also renaming `from_imperative` to `from_delayed`?

**Comment by mrocklin** [comment]
Yes.  See #1110

**Comment by jcrist** [comment]
Actually, because of how we handle method access for `Value`, it occurs to me that with some trickery we could just make `delayed` work for everything. Since I'm flip-flopping on opinions all over the place here, feel free to just pick one and roll with it. `as_delayed` and `DelayedResult` sound fine to me.
