### ISSUE TITLE
openssl_md5 overhead?

### ISSUE THREAD

**Issue by alimanfoo** [dask/dask#1093]
Doing some profiling, I came across a simple case where dask appears to be calling openssl_md5() and this is creating significant overhead relative to the time required for the underlying compute. This overhead does not appear when using dask diagnostics but does appear when timing execution via %time or %timeit. Example here: https://gist.github.com/alimanfoo/68f15f57c41db3df1652b54ff9c26a84

I realise this is a bit of an artificial case because the time for the underlying computation is very short and you expect some overhead with dask, but I was just wondering where these calls to openssl_md5() were coming from and what triggers them, because I don't always see them in other cases?

**Comment by mrocklin** [comment]
All keys in a dask graph have a name that should generally be somewhat unique to the data given.  Dask.array generally produces names by combining together all of the names for the inputs, e.g.

```python
>>> x.name
'foo-15487147'
>>> y.name
'bar-2754974242'
>>> (x + y).name
'add-2357829744'  # 'add-' + hash(x.name + y.name)
```

When someone gives us a raw numpy array we determine the name by hashing the full array down, this operates at around 400MB/s but only happens once and only happens if they don't provide a name  themselves.

The code presented in the notebook would avoid this call if you added a `name=` keyword to the `da.from_array` call:

```python
>>> source = da.from_array(source, chunks=chunks, name='x')
```

In this case you the user is taking on the responsibility of naming, so we don't have to hash down the data.

I think that there is value to deterministic and probably unique naming of keys in the long run.  The costs do arise in cases like this, but these cases have so far been somewhat uncommon.

Also, side note, you may enjoy the `%prun` magic in IPython, it handles the CProfile stuff for you.

**Comment by alimanfoo** [comment]
Thanks Matt.
