### ISSUE TITLE
CI is Failing

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#11080]
https://github.com/dask/dask/pull/11079

Alternatively, if we don't care about these runs then we should probably turn them off.

**Comment by mrocklin** [comment]
@quasiben maybe this is something your team can help resolve?

**Comment by phofl** [comment]
these started failing over the weekend because of a pytest release

**Comment by jrbourbeau** [comment]
Yeah, the latest pytest release started emitting a warning that we're elevating to a failure. They seem more related to testing setup than end-user functionality (I haven't looked deeply though)

**Comment by jrbourbeau** [comment]
The first improvement listed here https://docs.pytest.org/en/stable/changelog.html#improvements is what we're seeing, I think. For example, `dask.dataframe` still exists when `pandas` isn't installed, we just raise an `ImportError` whenever anyone tries to use it. Pytest now warns about this (doesn't warn if `ModuleNotFoundError` are raised instead of `ImportError`)
