### ISSUE TITLE
I'm not sure what ’b_dict‘ is, I couldn't find any relevant content

### ISSUE THREAD

**Issue by simplew2011** [dask/dask#11133]
- https://docs.dask.org/en/stable/_modules/dask/bag/core.html#to_textfiles

```
b_dict.map(json.dumps).to_textfiles("/path/to/data/*.json")
```

**Comment by jrbourbeau** [comment]
Thanks for the issue @simplew2011. Can you say more about what this issue is about? It's not clear to me if you're running into an error or something else. If this is an error, the best way for others to help is to construct a [minimal bug report](https://blog.dask.org/2018/02/28/minimal-bug-reports) (or as close as you can).
