### ISSUE TITLE
Pyarrow <NA> filters are not being applied in read_parquet

### ISSUE THREAD

**Issue by benrutter** [dask/dask#11235]
**Describe the issue**:

Pyarrow filters (or at least the one in the below example) appear to be ignored by dask when passed into read parquet.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({"a": [1, 2, 3], "b": [None, "hat", "bat"]}).astype("a": "int64[pyarrow]", "b": "string[pyarrow]"})
df.to_parquet("example.parquet")
dd.read_parquet("example.parquet", filters=[("b", "!=", "<NA>")]).compute()
# <NA> value is still present in data
pd.read_parquet("example.parquet", filters=[("b", "!=", "<NA>")])
# When called with pandas <NA> value has been filtered out as expected
```

**Anything else we need to know?**:

Not sure if this is specific to null strings - seems that other filters such as `("a", "=", 2)` or `("b", "=", "hat")` work as expected.

**Environment**:

- Dask version: 2024.7.0 (dask_expr 1.1.7)
- Python version: 3.10
- Operating System: ubuntu
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
cc @rjzamora git blame points to #9885

**Comment by rjzamora** [comment]
Hi @benrutter !

Filtering on `<NA>` is not well documented because it's still a bit unclear how the this kind of filtering should be represented in "tuple" form (if at all). You can find some background discussion in https://github.com/dask/dask/issues/9845

At the moment, dask doesn't allow you to use `!=` or `==` to compare with "null" values, because pyarrow doesn't really allow this either. Your specific example does work for pandas, but you'll notice that an equality check (like `filters=[("b", "==", "<NA>")]`) does **not** work.

If you want to filter out nulls with dask, you currently need to use `"is"` or `"is not"` (E.g. `filters=[("b", "is not", None)]`).

I'm not convinced Dask is using the "best" solution here, so it could make sense to revisit this topic.

**Comment by benrutter** [comment]
Ah ok, that makes sense! I'd offer to add a helpful note in the docs since its not obvious, but I guess it's a weird one since it's a pyarrow rather than a dask thing.

I'll close this off, since it seems like it's not a bug, just a case where Dask's implementation differs from Pandas I guess?
