### ISSUE TITLE
Dask 2024.8 started failing when indexing result of numpy.flatnonzero

### ISSUE THREAD

**Issue by lagru** [dask/dask#11298]
**Describe the issue**:

scikit-image's CI started failing with Dask 2024.8 when it worked fine before with 2024.7. As described in https://github.com/scikit-image/scikit-image/issues/7491, we traced the failure 
```plain
ValueError: Array chunk size or shape is unknown. 
```
to a line that tries to index the result of a `numpy.flatnonzero` operation. See the MCVE below which fails for 2024.8 but works fine for 2024.7. 

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import dask.array as da

hist = da.from_array(np.arange(256, dtype=int), chunks=(256,))
result = np.flatnonzero(hist)
result[[0, -1]]  # ValueError: Array chunk size or shape is unknown. 
```

**Anything else we need to know?**:

From reading the [docs that are pointed out by the error message](https://docs.dask.org/en/latest/array-chunks.html#unknown-chunks), it seems this behavior might not be entirely unexpected and this might not actually be a bug. However, I'm unsure why it worked before with 2024.7. And since I currently don't really now how to address this on scikit-image's side without adding an extra code path to support Dask 2024.8, I'd be grateful for feedback and context.

Sorry if I missed any existing issues or docs that already describe or explain this.

**Environment**:

- Dask version: 2024.8.0
- Python version: 3.12.0
- Operating System: Linux 6.10.3-arch1-1 (64-bit)
- Install method (conda, pip, source): pip

**Comment by phofl** [comment]
Thanks for the report.

Yeah, unknown chunks are annoying. We can indeed make this work, since there is only a single chunk along the axis with unknown chunks, but we would still raise if you have more than one chunk there. The previous implementation actually let this through, but returned incorrect results, i.e.

```
hist = da.from_array(np.arange(256, dtype=int), chunks=(128, ))
result = np.flatnonzero(hist)
result[[0, -1]].compute()
```

this returned 

```
 array([  1, 127])
```

which is obviously incorrect. So your case will work again, but as soon as you have more than one chunk, it will continue to raise. computing the chunk sizes is the solution for this case

**Comment by lagru** [comment]
We've decided to remove the unofficial dask support & test's for now from scikit-image. Thanks for the feedback @phofl!

**Comment by stefanv** [comment]
Just to put a finer point on it: we removed the failing test, we did not change any of the code paths that previous allowed dask arrays through (they still do).

**Comment by phofl** [comment]
We are moving away from implicit computes in Dask, this can have heavy performance penalties, so it's unlikely that we will add that back in again. This should be an explicit call by users (scikit-image in this case), but I can understand if you don't necessarily want to do this.

**Comment by stefanv** [comment]
Perhaps this is the more relevant question for us: does dask (aim to) support the Array API? If so, that is a path that skimage can follow, but it still would not involve explicit dask-specific code such as `compute_chunk_sizes`.

If the decision here implies Array API incompatibility, then that should raise some warning flags.

**Comment by stefanv** [comment]
Dask is explicitly mentioned as a target at https://data-apis.org/array-api/latest/

However, the following code no longer works with dask:

```
import numpy as np
import dask.array as da
import array_api_compat

d = da.from_array(np.arange(256), chunks=(12,))
nx = nx = array_api_compat.get_namespace(d)
nx.flatnonzero(d)[[0, -1]].compute()
```

Dask was also one of the examples used in [Array Programming with NumPy](https://www.nature.com/articles/s41586-020-2649-2).


I am not yet that familiar with the Array API, so I will chat to @lucascolley here at EuroSciPy to find out whether my understanding is correct, and perhaps @asmeurer to help me understand whether https://github.com/data-apis/array-api-compat does, as the README seems to indicate, fully support Dask.

**Comment by lucascolley** [comment]
This looks unrelated to array-api-compat to me - the following also fails:

```python
import dask.array as da
import numpy as np
d = da.from_array(np.arange(256), chunks=(12,))
da.flatnonzero(d)[[0, -1]]
```

Note that `flatnonzero` is not in the standard, so this seems to be just a Dask regression (perhaps deliberate?).

**Comment by stefanv** [comment]
Should `nx` then have a `flatnonzero` member?

**Comment by lucascolley** [comment]
I think you are looking for [this part of the array-api-compat](https://data-apis.org/array-api-compat/dev/special-considerations.html#special-considerations) docs:

> - Avoid Restricting Behavior that is Outside the Scope of the Standard. All array libraries have functions and behaviors that are outside of the scope of what is specified by the standard. These behaviors should be left intact whenever possible, unless the standard explicitly disallows something. This means
> 	-	All namespaces are extended with wrapper functions. You may notice the extensive use of import * in various files in array_api_compat. While this would normally be questionable, this is the [one actual legitimate use-case for import *](https://peps.python.org/pep-0008/#imports), to re-export names from an external namespace.
> 	- All wrapper functions pass **kwargs through to the wrapped function.
> 	- Input types not supported by the standard should work if they work in the underlying wrapped function (for instance, Python scalars or np.ndarray subclasses).
> 
> By keeping underlying behaviors intact, it is easier for libraries to swap out NumPy or other array libraries for array-api-compat, and it is easier for libraries to write array library-specific code paths.

**Comment by stefanv** [comment]
This would make sense to me for a library that explicitly supports the Array API, but I don't think dask does (there's no `__array_namespace__`), and therefore I suppose it becomes `array-api-compat`s responsibility to filter out functions that don't adhere to the specification, or won't work when called from `nx.*`.

**Comment by fjetter** [comment]
First of all, please note that the above example only worked in the past because there was only one chunk. As soon as you move to a multi chunk array, you saw the same exception on older dask versions, i.e. this never actually worked. Real dask arrays always have more than one chunk. I strongly recommend to use multi chunked arrays (two are typically sufficient) if you write any dask tests.

---

> Perhaps this is the more relevant question for us: does dask (aim to) support the Array API?

There hasn't been an explicit decision about this. I'm not aware of any dask maintainer who is working on compatibility to Array API and this is certainly not something that will come for free. While dask is being mentioned on the Array API documentation page, I do not know which (if any) maintainer participated in the definition of that spec. To the best of my knowledge, we are currently not fully compatible and unless somebody is stepping up and is willing to invest serious time into this, I doubt it is going to happen.

So far, when we encountered requests or issues raised about Array API compatibility, this often affected cases that are notoriously hard to deal with using a distributed or lazy array. Some things are free on a numpy array that are prohibitively expensive on a chunked, distributed array (ravel is a nice example and slicing is also highly nontrivial just to name some examples).

Compatibility alone might be achievable but in our experience these implicit compute patterns are strong anti patterns [1] that are surprising people and are actively harmful in many cases. We are preferring a non surprising and easy to use API and are willing to sacrifice compatibility for this if necessary.
Note, that this kind of problem is even explicitly mentioned (to some extent) in the Array API about lazy implementations, see https://data-apis.org/array-api/latest/design_topics/lazy_eager.html

I'm also not deeply familiar with the Array API spec but as the above page already mentions, Array API is not trying to deal with the different semantics around lazy arrays and I'm not sure where this is actually breaking down.

[1] Think about an array of a couple TB in a remote storage that is being loaded entirely just to allow simple indexing as shown in this example. If we called `compute_chunk_sizes` ourselves, all of this would happen (and cost money) just because a user did `arr[[0, 1]]`

**Comment by lucascolley** [comment]
>  it becomes array-api-compats responsibility to filter out functions that don't adhere to the specification

`flatnonzero` is not in the standard, so I don't think this counts as 'not adhering to the specification'. From [the spec](https://data-apis.org/array-api/draft/purpose_and_scope.html#conformance):

> A conforming implementation of the array API standard must provide and support all the functions, arguments, data types, syntax, and semantics described in this specification.
> 
> A conforming implementation of the array API standard may provide additional values, objects, properties, data types, and functions beyond those described in this specification.

**Comment by asmeurer** [comment]
Just to be clear, there have been Dask developers involved in the array API (for instance, @jakirkham). There have been discussions about adding array API support to Dask itself (most notably at https://github.com/dask/dask/pull/8750, and there's also https://github.com/dask/dask/issues/10994). For now, array-api-compat wraps libraries like Dask that are close to the array API but have various differences. Lazy arrays are definitely something that we care about in the array API and have tried to make allowances for. For instance, APIs in the standard that have value-dependent shapes are optional (like boolean indexing and unique). If you feel that there are issues with the array API that would prevent Dask from adopting it, please bring them up in the array-api repo.
