### ISSUE TITLE
head fails to list all data with empty files

### ISSUE THREAD

**Issue by jseabold** [dask/dask#1134]
Use case: I have a data dump from a distributed system and one of the partitions happens not to hold any of the data. Corner case, admittedly. I haven't tracked down what's going on yet.

```
In [1]: import dask.dataframe as dd

In [2]: cat csv/csv1.csv
1,2

In [3]: cat csv/csv2.csv

In [4]: cat csv/csv3.csv
3,4

In [5]: df = dd.read_csv("csv/*.csv", header=None)

In [6]: df.head(2)
Out[6]:
   0  1
0  1  2

In [7]: df.apply(lambda x: x, axis=1).compute()
/Users/civisemployee/work/dask/dask/dask/dataframe/core.py:1681: UserWarning: columns is not specified, inferred from partial data. Please provide columns if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, columns=['x', 'y']) for dataframe result
  or:     .apply(func, columns='x')        for series result
  warnings.warn(msg)
Out[7]:
   0  1
0  1  2
0  3  4
```

Incidentally, just calling apply without the axis argument fails. Is this expected?

**Comment by mrocklin** [comment]
Actually, I'm not sure that any of this is due to the empty file.  In both cases the unexpected behavior is because dask.dataframe is lazy, and doesn't have access the the underlying values of your data.

For `df.head`, it's restricted to look at the first partition.  It is unable to deliver the requested number of rows efficiently without actually going through and inspecting the values of the data.  We could do this, but it would make the common case much more expensive.

For `df.apply` it's unable to judge the column names and dtypes of the output because it's unable to introspect your function.  Instead what it does is it pulls off the head of the data and tries to apply your function onto that.  This is pretty error prone though and often yields incorrect results (the dask.dataframe thinks that the column/dtype metadata is different from the actual underlying pandas dataframes).  And so we compromise.  We go ahead and guess but we also complain, and ask you to provide more information.

**Comment by jseabold** [comment]
Ah, I didn't realize that head only peaks at the first partition. Makes sense. Thanks.
