### ISSUE TITLE
Multiprocessing shapely/fiona operations  with dask 

### ISSUE THREAD

**Issue by sallamander** [dask/dask#1179]
I've got a somewhat complicated procedure that I need to parallelize across cores. I need to do a bunch of geographical checking, where I compare ~700k lat/long points to a bunch of geographical boundaries and gauge distance from those boundaries. I have some native python code that does this, and can't parallelize it with the standard `multiprocessing` library because the `shapely` objects can't be serialized. I've got some `dask` code that implements this, but just hangs when I run it.

I can see multiple cores fire up, but only one working at a time (there is 0% CPU showing on all but one core). In this post (http://bit.ly/1U8JhmJ), I read @mrocklin comments and wondered if my use case just doesn't lend itself to mutliprocessing with `dask` here because it's pretty memory inefficient. In order to multiprocess, the geographical boundaries have to be farmed out to each of the cores, and I thought with `dask` I may be able to avoid that by taking advantage of shared memory (otherwise it's terribly memory inefficient). But, I think with the GIL a copy of the geographical boundaries still have to be farmed out to each core. Am I off base here, or does this sound right? 

I had come to the conclusion that I would just need to move to a lower level language to get around the GIL, but talked to @chdoig today and she suggested I at least bring this up and let you know what I'm trying to use `dask` for. 

On a less related note, cool product! While I haven't been able to get it to do what I want, I think this is an awesome tool.

**Comment by mrocklin** [comment]
Dask-on-processes will just use `multiprocessing` so there is no fundamental benefit.  Can the shapely objects be serialized with cloudpickle instead?

If your objects really can't move across a wire and your code doesn't release the GIL then you're in a bit of a pickle (pardon the pun.)  Some options:

1.  Try to rewrite your computation in a way that uses numeric code rather than python code and then use threads rather than processes
2.  If you're only seeing 1 CPU fire at a time then check that your computation really is parallelizable
3.  You could use the dask.distributed scheduler on a single machine, which is a bit better about avoiding unnecessary data movement between workers.  There are also options to pin certain computations to certain machines, which would help you to avoid serialization.  See http://distributed.readthedocs.io/en/latest/locality.html#user-control

**Comment by sallamander** [comment]
Thanks for the quick response! That was incredibly fast. These are all great suggestions, thanks! 

1. The unfortunate thing is that the geographical calculations are something that are beyond my knowledge base (otherwise I would move to numeric code and try to leverage `numpy` with threading). 
2. Okay, thanks! I think it should be, as I'm basically trying to farm out 1 lat/long point at a time to check if it's in a number of different boundaries. So, the idea was to hopefully just get a copy of those boundaries on every core (or get every core to point at a shared memory location so I just have one copy), and then check the points against these boundaries. 
3. Is this different from the Dask-on-processes that you mentioned - e.g. will it operate differently than using the `multiprocessing` library under the hood?  Also, if I pin certain computations to certain machines, I'm assuming there isn't a shared memory location I could point to so all machines could still access what I would have wanted to be shared. Does that sound right?

Thanks again!

**Comment by mrocklin** [comment]
No dask library uses posix shared memory by default.  You could do this on your own of course and have your functions point to data from shared memory.  Dask won't do anything automatic for you here though.

Dask.distributed is a separate scheduler.  Documentation here: distributed.readthedocs.org

**Comment by sallamander** [comment]
Gotcha. The `distributed` stuff looks neat as well. I'm going to close this issue, as I think this is resolved (or at least I've got a direction to go). Thanks for help, it's much appreciated. I'll keep you posted on my dask usage.
