### ISSUE TITLE
Pandas version support

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1240]
What Pandas versions do we want to support?  Do we want to restrict users to very recent releases?  

#487

**Comment by jcrist** [comment]
We regularly get issues with pandas  0.17 causing segfaults, so perhaps restrict to >= 0.18.0? That's a bit recent, but I think many people using pandas are also capable of upgrading to recent pandas.

**Comment by jcrist** [comment]
While fixing version incompatible issues in #1314, I found several issues that resulted from bugs in various version of pandas. This is adding a bit of a maintenance burden. Since the current release has known issues for pandas < 0.18.0, and 0.17 had the segfault issues, I'm seriously pushing for only supporting 0.18 >.

**Comment by mrocklin** [comment]
I'm comfortable requiring pandas 0.18.0

**Comment by mrocklin** [comment]
The segfault issues alone are reason to require this I think

**Comment by jcrist** [comment]
Agreed. Should we wait for more consensus, or should I just make the change?

**Comment by mrocklin** [comment]
This is a significant enough decision that I'd like to switch out of open source / community mode for a moment.  I've pinged @teoliphant and @pzwang off list to make sure that they're ok with this decision.  Lets wait for their call.

**Comment by mrocklin** [comment]
I think that we're good to go.  I say that we drop support for anything below 0.18.0.

**Comment by jcrist** [comment]
Fixed by #1314. Closing.
