### ISSUE TITLE
Include dask.distributed as a proper subpackage

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1307]
The distributed memory scheduler has a separate package.  Currently we import a couple of classes/functions in the `dask.distributed` subpackage.  It would be nice to do this in a more mature way.

Presumably other libraries like `backports` handle this through some established packaging solution.  What is this solution?

**Comment by dotsdl** [comment]
I think the solution you already have is actually the best one. A namespace package like ``backports`` or ``datreant`` can't have anything in the top-level namespace, so making ``dask.distributed`` work like ``backports.yourpkg`` would require there be nothing living in ``dask``. 

Since ``dask`` already mostly works this way, though, it is an option if you wanted to keep adding dask submodules without worrying about dependency bloat. This is the approach taken by ``datreant``, but it's probably not worth the effort if that's not a concern.

**Comment by jcrist** [comment]
Thanks for the explanation @dotsdl. Since changing to a namespace package would require a reorganization of files, and prevent a top level namespace, my vote is to close this and leave things as they are. Thoughts @mrocklin?

**Comment by mrocklin** [comment]
Happy to close anything :)
