### ISSUE TITLE
DataFrame.assign behaves unpredictably with pd.Series

### ISSUE THREAD

**Issue by bcyphers** [dask/dask#1373]
Calling `dataframe.assign(key=pd.Series())` causes the resulting dataframe to behave oddly. In particular, head() returns an empty dataframe and sample() is broken; however, tail() performs normally. 

For example:
```
>>> df.head()
...
[5 rows x 24 columns]

>>> df = df.assign(new_col=pd.Series(range(size)))
>>> df.head()
...
[0 rows x 25 columns]

>>> df.tail()
...
[5 rows x 25 columns]

>>> df.sample(0.1).compute()
ValueError: a must be greater than 0

Traceback
---------
  File "/.../python2.7/site-packages/dask/async.py", line 267, in execute_task
    result = _execute_task(task, data)
  File "/.../python2.7/site-packages/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File "/.../python2.7/site-packages/pandas/core/generic.py", line 2572, in sample
    locs = rs.choice(axis_length, size=n, replace=replace, p=weights)
  File "mtrand.pyx", line 1391, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:15395)
```

Assigning an np.Array works fine.

**Comment by mrocklin** [comment]
We should probably raise an `TypeError` in this case.  We should probably only accept `dask.dataframe.Series` objects.

**Comment by bcyphers** [comment]
Issue happens with Dask dataframes too.

Did some more digging; it looks like the base issue is trying to align partitions. E.g. one dataframe

**Comment by bcyphers** [comment]
Did some more digging, looks like the base issue is with aligning partitions when one of the DataFrames' includes None. In my case, the first frame had a partition `(None, None)` and the series has a partition `(0, len(series))`. `multi.align_partitions` flattens the new division list to `[None, 0, len(series)]`, which throws a wrench in things.

Even if the division list is passed as `[0, len(series)]`, `repartition_divisions` will break with "left side of the new division must be equal or smaller than old division", because None (left side of old division) < 0.

What's the best way to fix these? Should we force frames with None divisions to (0, len(df)) before aligning? Should repartition_divisions handle the case where the old division contains None, or throw a better exception?

**Comment by nirizr** [comment]
The core issue here is that when receiving a `pd.Series` dask converts it to a dask series, and tries to partition the one series the same was as the dataframe is partitioned, so each dataframe partition could be merged with the right slice of the original `pd.Series`. This is done to optimize the data stored and shared with workers.

In your case dask cannot slice the pd.Series to fit to the dataframe's partitions simply because they're unknown.

I can see two ways to handle this:
1. Explicitly declining assignments of `dask.Series` (or anything else, actually?) when partitions don't fit. Suggesting the user should `repartition` or `set_index`. `None` partitions should never fit. This should probably be implemented by raising an exception in `align_partitions` (or `repartition`) if any df has a `None` partition.
2. Dropping a small portion of dask's usability here (since data is already in memory to begin with, there's only some profit from converting the `pd.Series` to `dd.Series`). This should not be the default behavior and raise a warning.

the way to "force frames with None divisions to (0, len(df))" is by explicitly calling (the expensive) `dd.set_index` method. Keep in mind indices in both the dataframe and series should align, and that assign will use those indices. Choose your index properly.
