### ISSUE TITLE
Add a test case to histogram

### ISSUE THREAD

**Issue by rainwoodman** [dask/dask#1377]
I'd like to file a PR to resolve this, but I am not sure where to start. 

test_core.py does not seem to be the correct place for these tests.
But it would be nice to have a test case to ensure histogram function works and produces expected result, even on a very small, chunked array. 

Related to #1349

**Comment by mrocklin** [comment]
It looks like the current `test_histogram` is in `dask/array/tests/test_array_core.py`.  For better or worse most of the array tests live in that single file.

The simplest way to add dask.array tests is to test dask.array behavior against NumPy behavior.  Here is a small representative example test from the test suite:

```python
def test_cov():
    x = np.arange(56).reshape((7, 8))
    d = da.from_array(x, chunks=(4, 4))

    assert_eq(da.cov(d), np.cov(x))
    assert_eq(da.cov(d, rowvar=0), np.cov(x, rowvar=0))
    assert_eq(da.cov(d, ddof=10), np.cov(x, ddof=10))
    assert_eq(da.cov(d, bias=1), np.cov(x, bias=1))
    assert_eq(da.cov(d, d), np.cov(x, x))

    y = np.arange(8)
    e = da.from_array(y, chunks=(4,))

    assert_eq(da.cov(d, e), np.cov(x, y))
    assert_eq(da.cov(e, d), np.cov(y, x))

    assert raises(ValueError, lambda: da.cov(d, ddof=1.5))
```

This page on development guidelines may also be useful.  We added it very recently.  If you run into other questions I'd love to hear them so that we can improve the getting started with development guidelines.

**Comment by rainwoodman** [comment]
Thanks for the reference. I will look into this after my talk.

**Comment by rainwoodman** [comment]
Indeed. Thanks!
