### ISSUE TITLE
infer_storage_options lower-cases bucket names

### ISSUE THREAD

**Issue by martindurant** [dask/dask#1417]
Because `dask.utils.infer_storage_options` interprets a path as a generic URL, the bucket part of a path like "s3://mybucket/loc/mykey" becomes the host. Actual hosts are always lower-case, so the consequence is that only a lower-case version of the bucket name is kept. Thus, buckets with upper-case letters cannot be found.

@frol , do you have a moment to consider this?

**Comment by mrocklin** [comment]
I've also run into some trouble with `infer_storage_options` and Windows paths, which often start at `C:\...`, so that `C:` gets mistakenly read as a protocol.  I special cased it in `infer_storage_options` to solve the problem short term, but as you point out it's clear that the URL handling makes some inaccurate assumptions.  On the other hand the url handling is quite convenient for picking out username/password combinations and such.  I don't know what the right course of action is.
