### ISSUE TITLE
Bag.to_dataframe fails on scalar data

### ISSUE THREAD

**Issue by frol** [dask/dask#1429]
```python
>>> dask.bag.from_sequence([1,2]).to_dataframe()

TypeError                                 Traceback (most recent call last)
<ipython-input-140-756073df0a62> in <module>()
----> 1 dask.bag.from_sequence([1,2]).to_dataframe()

/opt/conda/lib/python3.5/site-packages/dask/bag/core.py in to_dataframe(self, columns)
   1044 
   1045         return dd.DataFrame(merge(optimize(self.dask, self._keys()), dsk),
-> 1046                             name, columns, divisions)
   1047 
   1048     def to_imperative(self):

/opt/conda/lib/python3.5/site-packages/dask/dataframe/core.py in __new__(cls, dsk, name, columns, divisions)
   1495         result._name = name
   1496 
-> 1497         result._pd, result._known_dtype = cls._build_pd(columns)
   1498         result.divisions = tuple(divisions)
   1499         return result

/opt/conda/lib/python3.5/site-packages/dask/dataframe/core.py in _build_pd(cls, metadata)
    200         else:
    201             if np.isscalar(metadata) or metadata is None:
--> 202                 _pd = cls._partition_type([], name=metadata)
    203                 known_dtype = False
    204             elif isinstance(metadata, datetime):

TypeError: __init__() got an unexpected keyword argument 'name'
```

**Comment by jcrist** [comment]
Currently `to_dataframe` is only intended to work when the element is a dict or tuple (as explained in [the docstring](http://dask.pydata.org/en/latest/bag-api.html#dask.bag.Bag.to_dataframe)). What is the expected behavior here, return a `dd.Series`? Without knowing the type of the elements, we can't pick a series or a dataframe easily at graph build time.

One option would be to return a `dask.Series` if `columns` is just a string (for the name of the series), otherwise return a dataframe (which would expect records as elements).

**Comment by frol** [comment]
@jcrist The expected behavior: fail with a meaningful error.

Also, it seems that the `if` branch in `_build_pd` will fail on any data due to the fact that `cls._partiton_type` doesn't expect `name` keyword argument, but it is passed there explicitly.

**Comment by jcrist** [comment]
A meaningful error is a good fix. The `_build_pd` stuff is being reworked in #1422, and is already fixed there.
