### ISSUE TITLE
is there a changelog?

### ISSUE THREAD

**Issue by fmv1992** [dask/dask#1486]
Is there a changelog?

If there is not there's no way to know what have changed since last update which is... disappointing!

**Comment by mrocklin** [comment]
Major change notes go out in release e-mails on blaze-dev.  I agree with you that a single changelog would be nice.  

Rather than be disappointed I recommend that you contribute and help to make this open source project better.  Perhaps start writing up backlogs of release notes based on PR descriptions?  I suspect that once momentum around a changelog is started that it will continue.

**Comment by fmv1992** [comment]
Yes I agree with you. I'm not complaining.

I'm still getting the grasp of how to do basic things.

I have just noticed that an upgrade was made in the last 24h and was curious to know what changed.
I hope to be able to contribute soon.

: )

Thanks!

**Comment by mrocklin** [comment]
Adding backlogs for the releases would be a huge help and probably pretty informative.  I think the best way to do this would be to search through the [blaze-dev archives](https://groups.google.com/a/continuum.io/forum/#!forum/blaze-dev) for all [dask release](https://groups.google.com/a/continuum.io/forum/#!topicsearchin/blaze-dev/release) e-mails, copying down the notes there, and adding them to a new release document in this repository.

I'll send out an e-mail with notes for the recent version after binaries get uploaded to conda-forge.  There is a bit of a delay between uploading to PyPI and uploading to conda-forge

**Comment by shoyer** [comment]
One thing that really helps is to update the changelog with every PR. You still need to give it a review when you make a release to ensure it has the appropriate emphasis, but it makes the process much easier.

There's certainly little more frustrating than being blocked on making a release (e.g., with important bug fixes) because you haven't updated the docs yet. This helps avoid that situation.
