### ISSUE TITLE
[Regression] How to detect meta inference in map_partitions?

### ISSUE THREAD

**Issue by frol** [dask/dask#1521]
Dask 0.10.x passed an empty dataframe into a `map_partitions` function to infer the output types, but Dask 0.11 introduced a sort of regression by passing a two-record fake dataframe instead of an empty one. It used to be quite handy to catch an empty dataframe and return an empty output of a relevant type and immediately return an empty result for meta-data inference purposes only. Currently, the inference became slower (due to a data construction for a fake dataframe) and hard to catch (should I check for the passed dataframe shape and compare the first two records now?). Was there a good reason for the change?

Demo Dask 0.10:

```python
EMPTY_CUSTOM_COMPUTATION_RESULT = pandas.DataFrame(columns=['value', 'summary'])

def custom_computation(df):
    if df.is_empty:
        return EMPTY_CUSTOM_COMPUTATION_RESULT
    ...
    return pandas.DataFrame(data={'value': aggregated_value, 'summary': aggregated_summary}, columns=EMPTY_CUSTOM_COMPUTATION_RESULT.columns)

dask_df.map_partitions(custom_computation)
```

Here is what I have to do with Dask 0.11 (`is_empty` doesn't catch the fake inference call now):

```python
...
def custom_computation(df):
    if len(df) == 2 and (df.ix[0] == df.ix[1]).all():
        return EMPTY_CUSTOM_COMPUTATION_RESULT
    ...
```

`if len(df) == 2 and (df.ix[0] == df.ix[1]).all():` is slow, ugly, and error-prone, but I cannot find other way around it.

P.S. I do know that I can pass `meta` to `map_partitions`, but this will introduce an unnecessary code duplication.

**Comment by jcrist** [comment]
> Was there a good reason for the change?

The old way had many issues, see more thorough discussion [here](https://github.com/dask/dask/issues/1209) and [here](https://github.com/dask/dask/pull/1422). The reason to not use an empty frame is that many pandas operations give different results when empty or error completely. Same goes for only 1 row, which is why we use 2.

> P.S. I do know that I can pass meta to map_partitions, but this will introduce an unnecessary code duplication.

If you have the `EMPTY_CUSTOM_COMPUTATION_RESULT` already figured out, then isn't it only a slight reorganization?

```python
# --Old way--
EMPTY_CUSTOM_COMPUTATION_RESULT = pandas.DataFrame(columns=['value', 'summary'])

def custom_computation(df):
    if df.is_empty:
        return EMPTY_CUSTOM_COMPUTATION_RESULT
    ...
    return pandas.DataFrame(data={'value': aggregated_value, 'summary': aggregated_summary}, columns=EMPTY_CUSTOM_COMPUTATION_RESULT.columns)

dask_df.map_partitions(custom_computation)


# --New way--
EMPTY_CUSTOM_COMPUTATION_RESULT = pandas.DataFrame(columns=['value', 'summary'])

def custom_computation_chunk(df):
    ...
    return pandas.DataFrame(data={'value': aggregated_value, 'summary': aggregated_summary}, columns=EMPTY_CUSTOM_COMPUTATION_RESULT.columns)

def custom_computation(ddf):
    return ddf.map_partitions(custom_computation_chunk, meta=EMPTY_CUSTOM_COMPUTATION_RESULT)

custom_computation(dask_df)
```

This isn't so much a duplication as it is a reorganization of your code into two methods (one for the task, and one user facing). Trying to detect the inference process (even in the previous version) seems more fragile to me than being explicit about it (IMO).

**Comment by frol** [comment]
OK. Thank you!
