### ISSUE TITLE
Caching of intermediate results and warm-start

### ISSUE THREAD

**Issue by twiecki** [dask/dask#1534]
Currently we use luigi to load data from a SQL DB, then run various stages of processing on it, until some extracted features are saved to another DB. The way luigi is set up, is that every stage of the pipeline outputs a file (e.g. csv) and tells the next stage the location of that file. Thus, when a luigi pipeline gets restarted (e.g. it crashed) it picks up where it left off because it sees the files that are already present and skips computation of these jobs.

Another use-case is I add a single feature and want to compute that over all the old data. In that case I don't have to repool everything from the DB as the prior stages are already cached and that data will be used.

Does Dask have similar functionality?

**Comment by mrocklin** [comment]
Workers persist all data that any client is holding a reference to, even if dependent references fail.  If a computation of many tasks fails because some component fails but subcomponents completed successfully and are pointed to by some client then those will stay in memory.  If the computation (or a similar computation) is resubmitted then the scheduler will be intelligent enough to only recompute what is necessary.

### First try

```python
a = e.submit(inc, 1)  # stays in memory
b = e.submit(div, a, 0) 
b.result() # fails because 2 / 0
```

### Second try

```python
a = e.submit(inc, 1)  # already complete, no need to recompute
b = e.submit(div, a, 10)
b.result()  # works fine
```

However, this requires that you have futures to the intermediate values.  The lazy APIs, like dask.dataframe and dask.delayed will garbage collect intermediate results as soon as possible, limiting the ability for reuse-on-error.  In these cases you are encouraged to explicitly persist staging points with the `Client.persist` method.

```python
df = e.persist(df)  # persist dataset in memory
```

**Comment by twiecki** [comment]
I like that it's explicit. You say in memory, is there a way to cache to disk?

**Comment by mrocklin** [comment]
As of https://github.com/dask/distributed/pull/485 spilling to disk can be made automatic with an LRU scheme.  

You could also just make whatever function you call write to local disk (workers have an accessible local_directory that is cleaned up when they are) or have your result be something that is backed off of disk.  Dask isn't handling anything here for you, but it also doesn't mandate anything.  You can get pretty creative if you want to.

**Comment by mrocklin** [comment]
Other questions @twiecki or can this be closed?

**Comment by twiecki** [comment]
This is great, thanks.
