### ISSUE TITLE
boolean slicing was very slow to error

### ISSUE THREAD

**Issue by jc-healy** [dask/dask#1628]
Using the pydata DC notebook this was very slow to error.

    x = da.random.normal(loc=10,scale=0.1,size=[20000,20000],chunks=[1000,1000])
    y = x[x>10]

**Comment by jcrist** [comment]
Thanks for the bug report. Boolean slicing isn't implemented, and can't be under the current design since we don't know the size of the output (it depends on the values of x, not the shape/dtype). What's happening here is that we're accidentally calling compute here when we should just error immediately. Fixing now.

**Comment by jcrist** [comment]
Fixed in #1629.
