### ISSUE TITLE
Dask Graph Progress Visualization

### ISSUE THREAD

**Issue by kaloramik** [dask/dask#1742]
Hi, 

Sorry if I missed this in the documentation, but I saw a cool looking real time visualization of a dask graph being computed here

https://www.continuum.io/blog/developer-blog/dask-and-scikit-learn-3-part-tutorial

I was wondering if this type of visualization can be found in the scheduler? If not, I am open to help building it if this is something that would be interesting for many people. 

For us it would be useful, as we are considering switching from luigi -> dask, and one of the helpful things about luigi is the DAG visualization that allows you to quickly see where in the pipeline something is bottlenecked.

**Comment by mrocklin** [comment]
I believe that @jcrist built that with a custom [scheduler plugin](http://dask.pydata.org/en/latest/diagnostics.html#scheduler-callbacks).  He has made similar things before and might be able to point you to code living somewhere.

Generally we haven't gone down the path of node-link diagrams because commonly graphs range into the 10's to 100's of thousands in size, for which node-link diagrams tend to fail.  

However, I agree that it would be nice to have these for smaller scales.  

You may also be interested in the web interface of the distributed scheduler (which also works fine on a single machine) and has a wealth of other visualizations: http://distributed.readthedocs.io/en/latest/web.html .  Here is a [youtube video](https://youtu.be/EEfI-11itn0?t=181) of part of it in action.

**Comment by jcrist** [comment]
Here's the gist for a scheduler plugin to make something like that: https://gist.github.com/jcrist/0c28f632513aa13d4edea3d482bf47d1. The one in that blogpost was made using something like this, but with some small tweaks.

**Comment by kaloramik** [comment]
Thanks! I'll close for now and see if I can mess around with the scheduler plugin
