### ISSUE TITLE
Trouble loading from HDFS

### ISSUE THREAD

**Issue by bkj** [dask/dask#1896]
Hi All --

I'm having trouble reading data from HDFS into a `bag`.  I try:

```
import dask.bag as db
db.read_text('hdfs://<my-name-node>:8020//user/bkj/data.txt').take(1)
```

throws the error

```
dask.async.IOError: Could not open file: <my-name-node>:8020//user/bkj/data.txt, mode: rb File does not exist: /user/bkj/<my-name-node>:8020/user/bkj/data.txt
````

So it looks like the path is getting messed up somehow? (URL of namenode getting inserted into the middle.) Any ideas?

If I parameterize it like this:

```
db.read_text('hdfs:///user/bkj/data.txt', storage_options={
    "host" : "<my-name-node>",
    "port" : 8020
}).take(1)
```

then it works, but if I try to use a wildcard in the path name, I get

```
TypeError: glob() got an unexpected keyword argument 'host'
```

(Open to any and all hacky fixes -- I'm just trying to get it to run)

Thanks

**Comment by mrocklin** [comment]
You might have to import the relevant dask.distributed library beforehand.

```python
import dask.distributed.hdfs
```

Just importing this *might* resolve things.

**Comment by bkj** [comment]
Get an error on that, after installing the most recent version:
```
pip install git+https://github.com/dask/dask
```
```
>>> import dask.distributed.hdfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named hdfs
```

**Comment by jcrist** [comment]
This is quite outdated, the hdfs functionality has been moved out of `distributed.hdfs` and into `dask.bytes.hdfs`. Testing coverage has been improved, and I would be surprised if you still had this issue. I suggest trying again with recent versions of dask/hdfs/distributed, and seeing if your problem is resolved. Closing as stale, feel free to reopen if you can provide a [reproducible example](https://stackoverflow.com/help/mcve).
