### ISSUE TITLE
Add persist function

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1908]
The distributed scheduler makes heavy use of `persist`, which creates a new dask collection with a collection that points to more evaluated data.  

It might be convenient to add this verb to dask generally.

```python
df = dd.read_csv(...)  # lazy loading
df = dask.persist(df)  # df is dask.dataframe that points to pandas dataframes
```

Persist would be a blocking call (to support general dask schedulers) that in the distributed case would be the same as 

```python
def persist(...)
    collection = global_client.persist(collection)
    wait(collection)
    return collection
```

In the single machine case it would probably be more like the following:

```python
def persist(...):
    keys = collection._keys()
    evaluated = get(collection.dask, keys)
    dsk = zip(keys, evaluated)
    return redict_collection(collection, dsk)

def redict_collection(c, dsk):  # this was taken from distributed/client.py
    if isinstance(c, Delayed):
        return Delayed(c.key, [dsk])
    else:
        cc = copy.copy(c)
        cc.dask = dsk
        return cc
```

Having a general `persist` function would make it easier to build algorithms that were consistent between single and distributed schedulers, such as occurs in dask-glm (cc @moody-marlin).  It would also help users who want to use dask for parallelism needs rather than out-of-core computation (cc @jbednar)

@jcrist @shoyer thoughts?

**Comment by jcrist** [comment]
I like the idea. It may be nice to also support a general mutable-mapping to persist to, to allow for spilling to disk. I could see a few options for how to do this:

- Set persist mapping globally using `set_options`
- Pass a mapping to the persist call `persist(collection, cache=cache)`

The graph returned from `persist` might then look like `{new_key: (getitem, cache, key), ...}` instead of just `{new_key: result_of_old_key}`.

---

Alternatively, persist could be a method on a context instead of a function. Something like:
    
```python
# Needs a better name than `Context`
context = Context(cache=my_spill_to_disk_dictionary_thing)
result = context.persist(collection)
# The compute method would then pull results from the local
# cache before computing
context.compute(other_collection_maybe_based_off_this_one)
```

One perk of this instead of a global/parameter method is that it mirrors the distributed client context, and would allow for a mimicking of the incremental computation api distributed allows. The global compute/persist could then just be

```python
global_context = Context(cache={})
compute = global_context.compute
persist = global_context.persist
```

This isn't as simple as a global thing though, and I'm unsure that it's needed. Just a thought.

**Comment by mrocklin** [comment]
I guess this would help to organize the current set of globals that we keep around in `set_options`.  

@jcrist do you have any desire/time to experiment with implementing this?

**Comment by shoyer** [comment]
Yes, I think this is a good idea. With xarray, I found myself writing things like `.compute().chunk(...)` with some frequency, both for parallelism and to solve scheduler fail cases like https://github.com/dask/dask/issues/874. Persisting to a dictionary with automatic spilling to disk could make this very convenient.

**Comment by jcrist** [comment]
Yeah, I'd be interested in working on this. I'm trying to finish up the categorical work today, then should have some time to work on this.
