### ISSUE TITLE
Visually inspect outstanding tasks 

### ISSUE THREAD

**Issue by cmardiros** [dask/dask#1925]
I cam across this article: https://jcrist.github.io/dask-sklearn-part-1.html and particularly this image: https://jcrist.github.io/images/grid_search_schedule.gif which shows progress visually (when there are many parallel tasks with varying running times, I find this is more helpful than the progress bar -- Luigi does this very well).

I've searched the docs and googled but cannot find how/where to implement this kind of monitoring. Have I missed something? How was this gif created? If this isn't an actual feature, are there any existing features built-in that could approximate what I'm trying to achieve?

Thanks!

**Comment by mrocklin** [comment]
Dask doesn't have anything builtin to display those sorts of graphs.  Generally dask graphs often reach into the millions of nodes, and these visuals generally don't scale.  Instead, there are some other visuals available if you use the distributed scheduler (see http://distributed.readthedocs.io/en/latest/web.html).  I think that @jcrist also has code somewhere to produce visuals like what he produced in his blogpost.

**Comment by cmardiros** [comment]
Thanks for the quick reply. That makes sense.

Just in case someone is thinking along the same lines and coming across
this post: would an alternative be to create a custom callback to record an
entry for each task in a database with a start/end/duration/status and
update these values on start/end? I've not looked at the callback docs yet
but sounds like this could work. Do you see any issues with this approach?

Thanks!

**Comment by mrocklin** [comment]
I suspect that Jim's solution used the callback mechanism, yes.  I think
that what you say makes sense.

http://dask.pydata.org/en/latest/diagnostics.html

**Comment by jcrist** [comment]
> would an alternative be to create a custom callback to record an entry for each task in a database with a start/end/duration/status and update these values on start/end?

This is basically what the [`Profiler`](http://dask.pydata.org/en/latest/diagnostics.html#profiler) callback does, logging the start, end, and execution times for each task. If you wanted to branch off that, you can look at the code [here](https://github.com/dask/dask/blob/master/dask/diagnostics/profile.py#L18).

> I suspect that Jim's solution used the callback mechanism, yes.

That gif was created by periodically generating a plot with graphviz during execution. This is quite slow for large graphs (due to graphviz overhead), and isn't something you'd want to do during actual execution. It does make nice visuals for docs/talks though :). You can see the code [here](https://gist.github.com/jcrist/0c28f632513aa13d4edea3d482bf47d1).

**Comment by jcrist** [comment]
Closing for now, feel free to reopen if this isn't resolved.
