### ISSUE TITLE
nan vs mask

### ISSUE THREAD

**Issue by bjlittle** [dask/dask#1928]
I have a use case where I want to perform some statistical processing over a large data set. So, naturally I want to leverage all the awesome goodness that's baked into dask ... however, my data has an MDI.

I'm glad to see that there is nan support already in dask.array, and as a strategy that helps me move forward somewhat - although things are a wee bit clunky in the case of integral data types.

Normally, I'd turn to masked arrays, but that's clearly not an option currently within dask. I've seen peppered requests over time from the community for masked support in dask, but it seems to be a big ask, otherwise I guess it would've been already implemented.

Would it be possible to have some guidance/clarity from the dask devs as to whether such a feature is realistically and technically viable? and just as importantly, is it really desireable from your point of view?

It would be most helpful to understand if there is a genuine appetite to have masked array support within dask, or whether the effort/issues involved simply outweigh the benefit, rendering such a feature request not feasible/worthwhile.

Many thanks in advance

**Comment by mrocklin** [comment]
Hi @bjlittle,

Generally I think that masked arrays are in scope for dask.array.  Generally we just copy numpy's scope.  If the numpy community was likely to move to a different model for missing data we might consider adopting that instead, but that doesn't appear likely any time soon.  

Yes, I think that such a feature is technically viable.  I suspect that with sufficient cleverness it would be doable without too much pain, though I may be thinking naively on the subject (I am not as intimately familiar with numpy's masked arrays as I should be).  My recent experience has been that *if* you can get a few of the core dask.array operations to work well, notably `dask/array/core.py::atop`, then you can build new features like this surprisingly cheaply for a broad subset of the project.

I personally have no immediate burning desire to build masked arrays, however I would be happy to support others if they want to take this on.  I certainly wouldn't oppose such an effort *if* it doesn't significantly increase the maintenance burden of core dask.array.

cc @shoyer @pelson

**Comment by shoyer** [comment]
There are basically two ways to write masked arrays for dask:

- Write an implementation wrapping Dask Array instead of NumPy. The implementation looks a lot like `numpy.ma`, omitting some numpy specific details.
- Write an implementation wrapping NumPy masked arrays in Dask. The implementation looks a lot like `dask.array` (e.g., reimplementing `atop`).

I think both paths are viable, with clear templates to start from, but would still be a lot of work, given that both `numpy.ma` and `dask.array` are thousands of lines of code. Personally, I would be reluctant to start down this path.

In an ideal world, NumPy's masked array could simply do duck-typing well enough that it works on generic duck array types, but glancing at the code that is clearly not the case now.

**Comment by mrocklin** [comment]
@shoyer, going along with your second option (wrapping numpy masked arrays) what would have to change in atop if the constituent elements were numpy masked arrays?

Even though numpy.ma is thousands of lines of code, we still get to benefit from those thousands of lines when wrapping.  I don't think that it we would *necessary* have to write thousands of lines to compose the two.

**Comment by shoyer** [comment]
> going along with your second option (wrapping numpy masked arrays) what would have to change in atop if the constituent elements were numpy masked arrays?

Which version of `atop` do you have in the mind? The version where `func` acts on masked arrays or numpy arrays?

For the former, I think no modification would be necessary, but `atop` wouldn't give you much -- you would still need to rewrite all dask masked array operations in terms of `dask.array.atop` and masked array primitives.

For the later, you would need to write an operation to propagate masks, and then combine the result of `atop(func, out_ind, arg_0, indices_0, ...)` with `atop_mask(out_ind, arg_0, indices_0, ...)`. This would be more scalable (you only need to write `atop_mask`), but I'm not entirely sure the scheduler would handle this well.

Anyways, I agree that it would be easier to wrap masked arrays and duplicate some of the dask.array logic (which is generally much more cleanly abstracted than masked array).

**Comment by pelson** [comment]
I'd love to see this happen. @bjlittle - are you able to pull some strings to get this onto the SciTools agenda?

For completeness (since @bjlittle already knows), there is some out-of-code masked array support in biggus that could be re-implemented in the cleaner ``dask.array`` abstraction style. For example, the streaming/out-of-core standard dev algorithm can be found in [```biggus._init._StdMaskedStreamsHandler```](https://github.com/SciTools/biggus/blob/master/biggus/_init.py#L2490).

**Comment by jcrist** [comment]
I've added initial support for masked arrays in #2301. This adds support for chunks to be instances of masked arrays, and makes most operations with them work. We also support many of the masked array specific functions in the `dask.array.ma` namespace (e.g. `da.ma.masked_greater`, etc...)

Note that because we keep the same outer `Array` class, static access to the `fill_value` doesn't work (e.g. you can't inspect the `fill_value` by `x.fill_value`) because we don't track that with the metadata (as we do for `dtype`). You can however set it with `da.ma.set_fill_value`.

Demo:

```python
In [1]: import dask.array as da

In [2]: x = da.random.random((10, 10), chunks=5)

In [3]: mx = da.ma.masked_greater(x, 0.2)  # mask values > 0.2

In [4]: mx[:4, :4].compute()
Out[4]:
masked_array(data =
 [[-- -- -- --]
 [0.13436558733596338 -- -- --]
 [-- 0.09774187207397944 -- --]
 [-- -- 0.15060314411709008 --]],
             mask =
 [[ True  True  True  True]
 [False  True  True  True]
 [ True False  True  True]
 [ True  True False  True]],
       fill_value = 1e+20)

In [5]: mx.dot(mx.T).sum().compute()  # dot and reductions work
Out[5]: 0.98678638692978504

In [6]: da.ma.filled(mx, 0).compute()  # Fill missing with 0
Out[6]:
array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.01256106,  0.16551167,  0.        ,  0.        ],
       [ 0.13436559,  0.        ,  0.        ,  0.        ,  0.17200201,
         0.        ,  0.        ,  0.        ,  0.        ,  0.18279078],
       [ 0.        ,  0.09774187,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.04618743,  0.09385341,  0.        ],
       [ 0.        ,  0.        ,  0.15060314,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.19307299,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.1757851 ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.03385781,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.16630388,  0.        ,  0.15377459,  0.08695276,
         0.        ,  0.        ,  0.        ,  0.        ,  0.08303051],
       [ 0.        ,  0.19929265,  0.        ,  0.        ,  0.        ,
         0.19556017,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.17384505,  0.04375032,  0.        ,  0.02915479,
         0.        ,  0.        ,  0.18237864,  0.        ,  0.        ]])

In [8]: da.ma.set_fill_value(mx, 0)  # set fill_value inplace

In [9]: da.ma.filled(mx)[:4, :4].compute()
Out[9]:
array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.13436559,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.09774187,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.15060314,  0.        ]])
```

**Comment by marqh** [comment]
@jcrist this is most interesting

a more detailed comment is on the pr
https://github.com/dask/dask/pull/2301#issuecomment-308992198
