### ISSUE TITLE
SQL predicate pushdown in dask.DataFrame

### ISSUE THREAD

**Issue by jseabold** [dask/dask#1957]
I've been hoping for something like predicate pushdown in the spark dataframes. In spark, if I back a dataframe with, say, a redshift database and start doing transforms, those transforms are executed in the SQL backend as long as possible before needing to unload the data. [Example](https://github.com/databricks/spark-redshift/blob/1092c7cd03bb751ba4e93b92cd7e04cffff10eb0/src/main/scala/com/databricks/spark/redshift/FilterPushdown.scala#L24)

I know I can write Python-code against a SQL-database with blaze, but the blaze API is not the dataframe API. Does a DataFrame API + blaze-driven computation engine exist?

If not, there's some gray area about whether this belongs in blaze or dask (#296) I suppose.

Something like

```python
import dask.dataframe as dd

data = bz.data(sqlalchemy_metadata)
table = data.table_name

data_frame = dd.from_blaze(table)

# computations done in database via blaze
# API provided by dask
# groupby, filter, etc. can all be pushed down until a transform that triggers an UNLOAD
data_frame.groupby([data_frame.x, data_frame.y]).z.mean().head()
```

I've started and stopped on doing this a few times now given the state of blaze, dask, and ibis.

In scope? Any takers?

Overlap with #943 and #1181

**Comment by mrocklin** [comment]
I appreciate and agree with the value of predicate push down.  We can do this for a few situations (generally directly after load) using Dask's optimizations (to be clear, one would have to build these).  Generally though Dask's abstraction doesn't lend itself to doing high level optimizations well.  It chose the "flexible" pill rather than the "query optimizer" pill.

Generally the solution to this is "write smarter dask.dataframe queries".  For example the `dd.read_parquet` method takes in optional filters to apply when reading.  We don't optimize this after the fact, but do allow users to fine-tune their own optimizations.  This is obviously not as good, but a decent release valve.

Dask driving Blaze driving a database is strictly out of scope.

**Comment by jseabold** [comment]
Sure. That's reasonable, and kind of what I figured.

The reason I like the interactive approach is I can peek while I'm building up the expression graph or do some plotting without having to commit to taking over the data/being responsible for partitioning and thinking about it. Just think about visualize == explain :).

For smarter filters at read, I'll just write the SQL.

I think I'll just stick with my homegrown solution, leveraging blaze until I have a better idea.
