### ISSUE TITLE
cloudpickle requirement

### ISSUE THREAD

**Issue by francisco-dlp** [dask/dask#2013]
``multiprocessing`` imports  ``cloudpickle`` since deb74696e859c. Shouldn't  ``cloudpickle`` be in ``setup.py``'s ``install_req``?

**Comment by jcrist** [comment]
`multiprocessing` imported cloudpickle before then (scroll down to https://github.com/dask/dask/commit/deb74696e859cd50fcb2271a810811364aa27a59#diff-5edbcf144004ac2002f1bf6310a31500L22 and you can see the import was just moved). 

Cloudpickle is in the `setup.py`, but in the `extras_require`. Dask is broken into small components - the core (really just the spec) has no dependencies, but each of the extras do require things. To install everything, do `pip install dask[complete]`. This allows subprojects to use dask, but not require everything (e.g. numpy).

**Comment by francisco-dlp** [comment]
The thing is that cloudpickle is in ``extra_requires`` for ``bag`` and ``dataframe``, but we are not using any of them and still dask seems to require cloudpickle. With dask 0.13 we didn't need to install cloudpickle manually.

**Comment by jcrist** [comment]
Oh, I see what the issue is. The multiprocessing scheduler has required cloudpickle for a long time (well before `0.13.0`), but cloudpickle has never been (and shouldn't be) a requirement for dask core. The issue is the addition of [this import](https://github.com/dask/dask/blob/master/dask/utils.py#L20) in https://github.com/dask/dask/pull/1919. Will fix, and add a test that importing with no dependencies works.

**Comment by francisco-dlp** [comment]
Great, thanks!
