### ISSUE TITLE
Timed out trying to connect to 'tcp://localhost:8786'

### ISSUE THREAD

**Issue by QuantScientist** [dask/dask#2038]
Hi,
is this the correct sequence of events for this to work?

`
from dask import *
import dask.dataframe as dd

from distributed import Client, progress, Executor
e = Executor('localhost:8786')
`

![dask-parquet-df_](https://cloud.githubusercontent.com/assets/18743986/23581180/e4fe2c12-0117-11e7-9a64-7b271d1edcb7.jpg)

**Comment by martindurant** [comment]
If you are trying to set up a distributed session using the default cluster - a set of processes on your local machine - then you should use Client rather than Executor
```
client = Client()
```
Without arguments, this will starts a scheduler, some workers *and* a client for you. For more information on possible ways of setting up a distributed cluster see [here](http://distributed.readthedocs.io/en/latest/setup.html).

**Comment by QuantScientist** [comment]
Its on a local machine at the moment, I changed the code and its working thanks.
