### ISSUE TITLE
Please consider added da.argwhere and da.partition

### ISSUE THREAD

**Issue by seanlaw** [dask/dask#205]
This is mostly a feature request but dask contains the majority of the function that I want but I also need da.argwhere and da.partition.

I'd also be willing to contribute if somebody can guide/point me in the right direction as I understand that the implementation may not be trivial or high priority.

**Comment by cowlicks** [comment]
Ref to mailing list thread:
https://groups.google.com/a/continuum.io/forum/#!topic/blaze-dev/ISiyskSSTT8

I think these would go in [`dask.array.core`](https://github.com/ContinuumIO/dask/blob/master/dask/array/core.py). Or perhaps a separate searching/sorting/counting module. There are other dask array functions in that module, like [`da.where`](https://groups.google.com/a/continuum.io/forum/#!forum/blaze-dev).

**Comment by mrocklin** [comment]
To briefly summarize the mailing list conversation.  da.where is hard because dask.array needs to know the size of the result before computation.  One could compute this but it would have to force execution (the result would be a numpy array, not a dask array).

da.partition is hard because parallel partitioning is hard.  @seanlaw if you'd like to contribute here an interesting place to start might be to look up parallel sort algorithms on google scholar or [external sort on wikipedia](http://en.wikipedia.org/wiki/External_sorting)

**Comment by mrocklin** [comment]
This isn't anywhere near easily doable.  Closing until someone pops in with a pull request.

**Comment by jakirkham** [comment]
Am adding `argwhere` in PR ( https://github.com/dask/dask/pull/2539 ).
