### ISSUE TITLE
dask.array.meshgrid

### ISSUE THREAD

**Issue by shoyer** [dask/dask#2057]
I think this would be pretty easy to add and some would find it useful.

It came up on the xarray bug tracker: https://github.com/pydata/xarray/pull/1260#issuecomment-284225363

CC @fmaussion

**Comment by mrocklin** [comment]
I'm in favor

**Comment by magonser** [comment]
I have had some look into it and attached my implementation study as ipython notebook. The main punchline is: do not use `dask.array.broadcast_to`, as in its current implementation the newly created dimensions are not chunked. Therefore a subsequent rechunk operation is required (explicitly or triggered implicitly) if the meshed arrays are used together. 

The implementation proposed, does create a chunked array right away. 

Comparison with the different schedulers reveals, the dask native scheduler does not seem to care, which implementation version it is (probably, because it is shared memory and numpy array views work fully). However the distributed scheduler performance is better for the latter implementation. 

I would appreciate if you can have a look at it and indicate me, if you want me to go forward in preparing a pull request.

[dask_meshgrid_implementation.ipynb.zip](https://github.com/dask/dask/files/1346715/dask_meshgrid_implementation.ipynb.zip)

**Comment by jakirkham** [comment]
I think one can probably refactor and/or copy the code inside `indices` to do this. Probably can skip the flags `sparse` and `copy` for the initial implementation. Not sure that `copy` even would have meaning for Dask.

**Comment by jakirkham** [comment]
Provided an implementation in PR ( https://github.com/dask/dask/pull/2938 ).
