### ISSUE TITLE
Read_csv dtypes= for integer NA columns

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2097]
A common problem with dask.dataframes is that we think a column is of integer dtype, when it actually has missing values and needs to be represented as a float.  Because no missing values occur in the first few megabytes we incorrectly call it an integer dtype.  

Normally we tell people to identify this situation and then redefine their dtypes as float explicitly

```python
df = dd.read_csv(..., dtype={col1: float, col2: float})
```

This seems to not always work, and output the dtype remains integer.  Generally this is a pain for new users.  It has come up many times.  How can we help this experience?

Some options:

1.  Always use floats
2.  Provide a keyword option that turns all integers into floats
3.  Improve the error handling around the integer/float situation to point to a longer explanation
4.  Do some sort of flexible computation where we allow columns of different dtypes

cc @moody-marlin cc @jcrist

**Comment by jcrist** [comment]
> This seems to not always work, and output the dtype remains integer.

Can you explain/provide a reproducer for this? If a dtype is specified, the output dtype should always match the specification. If not, then that's a bug.

Of your options above, I'd prefer either the keyword option (`assume_missing=True`, default of False)? or improving error messages.

Flexible dtypes may also be doable. We already have a hard time predicting between int and float for *some* operations due to operations that involve missing values - allowing flexible dtypes between partitions for numbers in `read_csv` may not be that tricky to add. The options above would be easier though, and maybe less confusing.

**Comment by mrocklin** [comment]
> Can you explain/provide a reproducer for this? If a dtype is specified, the output dtype should always match the specification. If not, then that's a bug.

I experienced the buggy behavior.  I can work to produce a reproducer later, but not today.

I'm in favor of a keyword argument.  I would suggest that we either make it true (permissive) by default or that we make it false by default but improve the exception and point users to it (preferred).

**Comment by jcrist** [comment]
Cool. Fixing now.

**Comment by apiszcz** [comment]
I am trying to read 3 columns from a set of CSV files, however I get the following error on columns I am not interested, usecols=['a','b','c']... however I get the following message on columns d,e,f,g,... etc.

Usually this is due to dasks's type inference failing and "may" be fixed specifying dtypes manually by adding.
