### ISSUE TITLE
User mailing list?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2140]
Do we want to have dev and/or user mailing lists for Dask?

Currently people are encouraged to use StackOverflow for questions and Github for bug reports.  This is ideal when appropriate and it has more long-term value than a mailing list.  However some people have usage problems that are too complex for StackOverflow and it would be ideal if they could help each other.

I think that a user mailing list would be useful *if* people actively watch and respond to it.  I personally don't intend to monitor such a list and I'm concerned that people will put questions there and have them go unanswered.

Thoughts?

**Comment by dhirschfeld** [comment]
It might just dilute the pool of people available to help on any particular forum. I used to use Gmane to keep abreast of the mailing lists but since that went offline I've correspondingly mostly stopped following the lists and just check GitHub.

If you were to have a "mailing list" I'd suggest Google Groups as the barrier to entry is much lower IMHO. I actually wouldn't recommend it though - I think there's more value in concentrating support in fewer forums and SO seems to be working pretty well.

For complex problems perhaps a GitHub issue would work better than SO?

**Comment by mrocklin** [comment]
I'd prefer to keep github issues mostly for development and bug reports if possible.  I wouldn't mind a separate issues-only repository though.

**Comment by martindurant** [comment]
As far as I see, mailing lists are less used, and material gets ignored or lost more easily. I wouldn't add to the number of media needing monitoring.

**Comment by bryevdv** [comment]
Just my $0.02: it's definitely possible to develop a heavily trafficked mailing list (Bokeh has much more ML usage than SO) but I doubt you can get from nothing to that point without spending fairly significant time and effort "priming the pump".

**Comment by wesm** [comment]
Do you use the issue tracker to discuss the roadmap for the project and other coordination with collaborators? There are sometimes users or occasional contributors who might use a mailing list for communication, but don't want to be subscribed to the GitHub firehose. 

I don't think that "mailing lists are dead" -- there are plenty of thriving open source communities that rely mailing lists as a central communication tool (e.g. Apache Spark, or any other ASF project), but it's community-specific. If it doesn't help this one, then there's no reason to use it.

**Comment by TomAugspurger** [comment]
https://github.com/dask/dask/pull/3045 spells out the process we're currently using.

**Comment by kitaev-chen** [comment]
Just a stop by comment: 
forum is useful for discussion, see 
https://discuss.pytorch.org/
https://discourse.julialang.org
