### ISSUE TITLE
Odd pytest issue in CIs

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2189]
Seeing a rather strange issue with pytest in some builds like this [one]( https://travis-ci.org/dask/dask/jobs/219864167#L313-L318 ). Snippet from the build shown below.

```
$ source continuous_integration/travis/run_tests.sh
WARNING: assertions not in test modules or plugins will be ignored because assert statements are not executed by the underlying Python interpreter (are you using python -O?)
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: -n3
  inifile: None
  rootdir: /home/travis/build/dask/dask
```

**Comment by jakirkham** [comment]
Not sure if this missing flake8 issue is related or not, but also seeing this in some [builds]( https://travis-ci.org/dask/dask/jobs/219864167#L321-L323 ).

```
The command "source continuous_integration/travis/run_tests.sh" exited with 2.
$ flake8 dask
/home/travis/.travis/job_stages: line 53: flake8: command not found
```

**Comment by jreback** [comment]
we are getting some errors like this in pandas as well - restarting sometimes helps - looks like travis having some issues

**Comment by mrocklin** [comment]
Everything started going a little crazy yesterday.

**Comment by honnibal** [comment]
This is a shot in the dark, but maybe Travis have `PATH` and `PYTHONPATH` with different orders, so that `which pytest` produces a different result from `python -m pytest`? This happens to be sometimes when I'm using `pyenv`.

If this is the problem, the solution would be to change your CI scripts to run `python -m pytest`, `python -m flake8`, etc. This way you know that you're running the Python from your virtualenv, and not a version of te command that's coming from somewhere else on `PATH`.

**Comment by jreback** [comment]
travis looks all fixed - just restart things

**Comment by jakirkham** [comment]
Agreed. Unclear as to why it occurred, but am happy to see it gone.
