### ISSUE TITLE
Support `[` and `?` in glob

### ISSUE THREAD

**Issue by mattilyra** [dask/dask#2212]
The `dask.bag.read_text` documentation says that the function takes a `glob` pattern. It only seems to expand patterns with `*` in them not any other special characters.

`bag = db.read_text('0[5-8]0.json.gz').map(json.loads)`

gives a `FileNotFoundError`, similarly for 

`bag = db.read_text('0?0.json.gz').map(json.loads)`

Is this the intended functionality? If so then the documentation should probably be changed to make it explicit that only `*` patterns are expanded.

**Comment by mrocklin** [comment]
Is this what is being handled here: https://github.com/dask/dask/pull/2078 ?

**Comment by martindurant** [comment]
Yes, #2078 would fix this. The reason it has stalled, is because the backends (s3fs, hdfs3) don't necessarily implement all the glob patterns. Note that "*" being in a string isn't sufficient for it to be a glob pattern: it might have been escaped; but then glob should bring back the one single file path.

**Comment by TomAugspurger** [comment]
@martindurant this is handed by fsspec, correct?

**Comment by martindurant** [comment]
correct
