### ISSUE TITLE
Support rechunk with unknown dimensions

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2236]
Sometimes we have arrays where some dimensions are known and some dimensions are unknown.  In these cases rechunking currently fails.  It would be nice if we could rechunk naively in these cases only along the known dimensions, leaving the chunk structure in unknown dimensions untouched.

**Comment by mrocklin** [comment]
cc @pitrou because he knows the rechunking code well (although no rush)

**Comment by mrocklin** [comment]
@TomAugspurger if you find yourself with free time you might find this issue interesting.

**Comment by TomAugspurger** [comment]
I'm slowly looking into this. One question I have (which is probably just me not understanding the code): Is there a potential optimization when you don't change the chunks on a certain axes?

Consider these two cases:

```python
import dask.array as da
from dask.array.rechunk import plan_rechunk

In [20]: x = da.ones(shape=(20, 30), chunks=(4, 6))

In [21]: plan_rechunk(x.chunks, ((10, 10), (5, 5, 5, 5, 5, 5)), x.dtype.itemsize)
Out[21]: [((10, 10), (5, 5, 5, 5, 5, 5))]
```

```python
In [15]: y = da.ones(shape=(20, 30, 40), chunks=(4, 6, 8))

In [16]: plan_rechunk(y.chunks, ((10, 10), (5, 5, 5, 5, 5, 5), y.chunks[-1]),
                      y.dtype.itemsize)
Out[16]:
[((10, 10), (6, 6, 6, 6, 6), (8, 8, 8, 8, 8)),
 ((10, 10), (5, 5, 5, 5, 5, 5), (8, 8, 8, 8, 8))]
```

I would have expected the two plans to be similar, aside from the second plan having the extra chunks in the tuple for the extra dimension. My hope is that we can treat rechunking with some unknown axes similarly, since those axes won't be changing.

Again, I don't fully understand the code, so perhaps this is addressed later on. I'll keep looking.

**Comment by TomAugspurger** [comment]
Oh, it seems that `plan_rechunk` hit the `threshold` in the second case.

```python
In [18]: plan_rechunk(y.chunks, ((10, 10), (5, 5, 5, 5, 5, 5), x.chunks[-1]), x.dtype.ite
    ...: msize, threshold=10)
Out[18]: [((10, 10), (5, 5, 5, 5, 5, 5), (8, 8, 8, 8, 8))]
```

**Comment by pitrou** [comment]
You may have to create a separate version of `plan_rechunk` for the unknown axes case, since `plan_rechunk` currently assumes it can compute the size of intermediate results.

**Comment by pitrou** [comment]
One easy way to do that would be for that `plan_rechunk` implementation to never create intermediate steps when there are unknown axes.

**Comment by TomAugspurger** [comment]
Ok. I think I have a solution that should work here. Need to add more testing and fix up one edge case. Should have it tonight or tomorrow morning.
