### ISSUE TITLE
Get sub-arrays from dask.array without known chunk values

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2271]
OK, so I have a dask.array with unknown chunk values along one axis (my array comes from a dataframe) and with a few chunks along the other axis

```python
>>> x.chunks
((nan, nan, nan, ..., nan), (10, 20))
```

I want to turn this into many dask arrays with one chunk along the first axis

```python
>>> L = x.get_chunks(axis=0)
>>> L[0].chunks
((nan,), (10, 20))
```

I plan to do this with `x.to_delayed()`, `da.from_delayed`, `da.concatenate`, and some elbow grease.  Is this something that should make it into the API?  The equivalent (but much simpler) function in dask.dataframe would be `df.get_partition(i)`.

**Comment by shoyer** [comment]
This seems useful.

For the API, you might consider writing this as another "indexer", that allows for indexing based on chunks (with integers or slice objects) instead of array values, e.g., `x.chunks_index[0, :]` to select the first chunk along first axis.

In principle, this could even support mutation in a sane way.

**Comment by mrocklin** [comment]
See the blocks attribute
