### ISSUE TITLE
Add fftfreq to dask.array.fft

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2319]
Would be nice to add the Dask equivalent of NumPy's [`fftfreq`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.fft.fftfreq.html ) to Dask Array's FFT module. Should be simple enough to add and have something along these lines already that I would be willing to contribute.

**Comment by jcrist** [comment]
Sounds good to me. I look forward to your PR.

---

Since you've filed a few issues like this recently, I'll just note that anything that matches an existing numpy interface (meaning is part of the `numpy` library)  and can be done at least mildly efficiently with dask is likely to get merged. In these cases you can just submit a PR and we'll gladly take a look - not every fix needs a matching issue (though there's no harm in opening one :) ).

**Comment by jakirkham** [comment]
Should be addressed by PR ( https://github.com/dask/dask/pull/2320 ).

Ok, I'll keep that in mind. In some cases I have opened issues to partially remind myself for later. Hope that is ok. If not, maybe we can work to consolidate these sorts of issues in the future.

**Comment by jcrist** [comment]
> Hope that is ok.

It's perfectly fine. Just wanted to let you know that we don't require a matching issue for each PR.
