### ISSUE TITLE
Variadic arguments in dask.bag.map

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2332]
Do we want to support args in `Bag.map`?  We would broadcast over anything that was not a Bag.

```python
b = db.range(4, npartitions=2)
b2 = b.map(add, 100)

>>> list(b2)
[100, 101, 102, 103]
```

**Comment by mrocklin** [comment]
Extending this.  Any thoughts on having a top level `db.map` function that handled both multi-bag mapping as well as broadcasting singleton elements?

```python
def test_bag_top_level():
    a = db.range(5, npartitions=3)
    b = db.range(5, npartitions=3)

    assert list(db.map(inc, a)) == [1, 2, 3, 4, 5]

    assert list(db.map(add, a, 1)) == [1, 2, 3, 4, 5]
    assert list(db.map(add, 1, a)) == [1, 2, 3, 4, 5]
    assert list(db.map(add, a, b)) == [0, 2, 4, 6, 8]

    assert list(db.map(add, a, a.count())) == [5, 6, 7, 8, 9]
    assert list(db.map(add, a, delayed(5))) == [5, 6, 7, 8, 9] 
```

The danger here is the same as with `zip`, that we can't guarantee correct behavior on bags whose partitions are not aligned.  I think that this is a question of balancing ease in the common case vs surprising errors in the complex case.

cc @jcrist @eriknw

**Comment by jcrist** [comment]
`Bag.map` already does this, but requires that they are keyword arguments (both by use and defined as):

```python
In [1]: import dask.bag as db

In [2]: b = db.range(4, npartitions=2)

In [3]: def add(a, b=0):
   ...:     return a + b
   ...:

In [4]: b.map(add, b=1).compute()
Out[4]: [1, 2, 3, 4]
```

This is because of the magic behavior of `Bag.map` that detects variadic functions and decides that the bag must contain tuples and "splats" the arguments into the mapped function (e.g. does `(func(*item) for item in bag)`). Because of this behavior, there's no easy way to take a variadic function and a positional argument and infer that the bag must contain the first argument and the extra argument the second. I've spoken up about my dislike of this magic behavior before, and we have a few issues about it: (https://github.com/dask/dask/issues/1906, https://github.com/dask/dask/issues/1572, https://github.com/dask/dask/issues/472).

My preference would be the following:

- Implement `db.map` as you describe above (I think the caveat about aligned lengths is fine). This function should match python's map with the exception that it takes non-sequence arguments and "broadcasts" them. We probably want to support keyword arguments as well.

- Deprecate the existing magic in `Bag.map`. Add `Bag.starmap` to do the splatting explicitly, which is a lot easier to reason about (and doesn't require `inspect`).

- After the deprecation period is over, `Bag.map` will just be a thin wrapper around `db.map`.

**Comment by mrocklin** [comment]
I can live with that.  @jcrist do you have any interest in implementing this?

**Comment by jcrist** [comment]
Sure.

**Comment by eriknw** [comment]
I like Jim's suggestions. +1
