### ISSUE TITLE
Support numpy ufuncs with __array_ufunc__

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#2334]
NumPy 1.13.0 supports dispatching on numpy ufuncs with the `__array_ufunc__` protocol.  This should enable us to make it so that `np.sin(my_dask_array)` is the same as `da.sin(my_dask_array)`.  A release candidate for 1.13.0 is out now.  I suspect that the numpy community would appreciate it if we tested this prior to their full release.

cc @shoyer @jcrist

**Comment by shoyer** [comment]
As a template, I would suggest the implementation of `__array_ufunc__` from `np.lib.mixins.NDArrayOperatorsMixin`:
https://github.com/numpy/numpy/blob/8ea619a8717d2c82d42e4662b2266121faba58e4/numpy/lib/mixins.py#L84

This should work sensibly even without inheriting from the base class.

In dask's case, it is probably best to unilaterally return `NotImplemented` (for now) if `method != '__call__'` or `ufunc.signature is not None` (indicates a generalized ufunc), and otherwise implement the operation with `da.elemwise`.

**Comment by mrocklin** [comment]
This is implemented.
