### ISSUE TITLE
apply + assign slows down further computations (possibly related to #1590)

### ISSUE THREAD

**Issue by aavanian** [dask/dask#2358]
Hi,

Notebook is [here](https://gist.github.com/aavanian/f4340a2656d69a3a767cf613712ae072) and code below for reference.

If you run comment the assignement lines in the `MAP` and `APPLY` cells, everything runs as expected.
If you uncomment the assignment in `MAP`, everything still ok
if you uncomment and run `APPLY`, it's much slower (expected) but the `MAP` cell also becomes slower.

I encountered the issue with pd.DateOffset operations. I didn't check if it's related.

It's not really a problem for me at the moment but I wonder if it's the expected behavior and something to plan for or i am doing something wrong (other than using apply!) or a bug...

```
import dask
import dask.dataframe as dd
from dask.diagnostics import ProgressBar, Profiler, ResourceProfiler, CacheProfiler
import numpy as np
import pandas as pd
from pandas.tseries.offsets import DateOffset

# Versions
print('pandas:', pd.__version__)
print('numpy:', np.__version__)
print('dask:', dask.__version__)


df = pd.DataFrame(index=pd.DatetimeIndex(end=pd.Timestamp('2017-05-18'), periods=25000, freq='1B', name='date'), columns=['value'], data=np.random.rand(25000)).reset_index()
ddf = dd.from_pandas(df, npartitions=10)
def my_func(d):
    return d + DateOffset(months=3)

f = lambda x: my_func(x.date)

# MAP
z = ddf.map_partitions(f, meta=(pd.Timestamp))
ddf = ddf.assign(date2=z)   # Assignement
with ProgressBar():
    ddf.compute()
ddf.head()


# APPLY
z = ddf.apply(f, axis=1, meta=pd.Timestamp)
ddf['date2'] = z  # Assignement
with ProgressBar():
    ddf.compute()
ddf.head()
```

**Comment by TomAugspurger** [comment]
I think it's a couple things.

1. When you assign `z = ddf.apply(f, axis=1, meta=pd.Timestamp)`, the meta isn't quite right.

```python
>>> ddf.apply(f, axis=1, meta=pd.Timestamp).dtype
dtype('O')
```

I think you want `z = ddf.apply(f, axis=1, meta=pd.Series(dtype='datetime64[ns]')).dtype`

If you run your "APPLY" and then followup with your "MAP" again, I think the apply still has to run, since when you've assigned that column to `ddf`. And when you `ddf.map_partitions(f)`, all the columns are passed down to `f`. You could try something like `ddf['date'].map_partitions(my_func)`.

**Comment by aavanian** [comment]
Noted for the meta but I don't think that changes the situation.

Maybe to clarify my question: the MAP and APPLY blocks perform the same thing. I was trying both and discovered the performance of MAP depended on whether I did the APPLY assignement or not:

MAP (0.1s) followed by APPLY (6s). Ok
APPLY (6s) followed by MAP(6s) << I don't understand why MAP is slower now
MAP (0.1s) followed by MAP (0.1s) << That second MAP also get passed all columns, right? so it can't be the explanation

**Comment by TomAugspurger** [comment]
I believe it just comes down to `.apply(f, axis=1)` being so slow in pandas:

```python
def mkdf():
    df = pd.DataFrame(index=pd.DatetimeIndex(end=pd.Timestamp('2017-05-18'), periods=25000, freq='1B', name='date'), columns=['value'], data=np.random.rand(25000)).reset_index()
    ddf = dd.from_pandas(df, npartitions=10)
    return ddf

def my_func(d):
    return d + DateOffset(months=3)

f = lambda x: my_func(x.date)
```


This is just pandas, no dask:

```python
%timeit f(df) 
100 loops, best of 3: 3.08 ms per loop

%timeit df.apply(f, axis=1)
1 loop, best of 3: 2.67 s per loop
```

If you define your assignments as functions:

```python
def my_map(ddf):
    z = ddf.map_partitions(f, meta=pd.Series(dtype='datetime64[ns]'))
    ddf = ddf.assign(date2=z)
    return ddf

def my_apply(ddf):
    z = ddf.apply(f, axis=1, meta=pd.Series(dtype='datetime64[ns]'))
    ddf['date2'] = z  # Assignement
    return ddf
```

And look at the graph produced by `.visualize`

```python
r1 = my_apply(ddf)
r2 = my_map(r1)

r2.visualize()
```

You get
![graph](https://cloud.githubusercontent.com/assets/1312546/26246573/7b8296a0-3c5f-11e7-8cbe-12d60ccb082a.png)

so the `apply` version is still running, since `map` version comes after it in the dag. It's not that the map version is slower now, it's that both are running.

**Comment by aavanian** [comment]
Ugh... my bad. Of course it does that. Calling APPLY then MAP stacks both operations and the `.compute()` in MAP compute both actually.

Sorry about that, closing.
