### ISSUE TITLE
diagnostics fail with nested dask schedulers

### ISSUE THREAD

**Issue by Joshuaalbert** [dask/dask#2385]
## Issue:
Example:
I have a custom graph which describes a flow of an algorithm with complex  inter dependencies.
Dask helps me efficiently pass data around.

Some subroutines of the algorithm use dask to parallelize the array computations.

I use the dask.get to handle the algorithm workflow so it's single threaded and there is no "daemon creating children" error.
I use dask.multiprocessing.get in the subroutines using dask (because there is some python bytecode).

When I try to use diagnostics:
```
with Profiler() as prof, ResourceProfiler(dt=0.25) as rprof, CacheProfiler() as cprof:
        get(dsk,'pull_m2')
    visualize([prof,rprof,cprof])
```
I get:
```
C:\Users\josh\Anaconda3\envs\compute\lib\site-packages\dask-0.14.3+28.gb0cf627-py3.5.egg\dask\diagnostics\profile.py in _finish(self, dsk, state, failed)
    329         t = default_timer()
    330         for k, (metric, start) in self._cache.items():
--> 331             self.results.append(CacheData(k, dsk[k], metric, start, t))
    332         self._cache.clear()
    333 

KeyError: ('sub-6b0bfecfb11b78fc1a21be54f83b65c1', 0, 0, 4)
```

This is a key from a subroutine. The routines them selves create the dask objects inside and do all the computing separately. The `with` context is trying to run diagnostics on all dask computations, when I only want it to work on the custom graph.

## Version:
dask-0.14.3+28.gb0cf627-py3.5
Windows 10 64 bit

**Comment by jcrist** [comment]
This is fixed in #2397. Note that using the profilers this way (at least the resource profiler) will be misleading as the processes created in the sub-tasks won't be tracked by the resource profiler (we only look at processes that exist when the scheduler is started). And really, none of the local diagnostics were designed for this situation. #2397 will at least fix things so that nested scheduler calls don't break the callbacks.

In general, I recommend using the [distributed scheduler](http://dask.pydata.org/en/latest/scheduler-choice.html#distributed-scheduler-on-a-single-machine) on a single machine over using the multiprocessing scheduler. This will usually be more performant than the multiprocessing scheduler (the doc I linked explains why) and also provides [better diagnostics](https://distributed.readthedocs.io/en/latest/web.html). You can still have the single threaded scheduler call start multiple tasks this way, and submit them all to the same distributed scheduler:

```python
from dask.distributed import Client
import dask
from dask.diagnostics import Profiler

# Start a local distributed scheduler, and set it as the default scheduler
client = Client()

@dask.delayed
def does_some_dask_stuff():
    # Do some dask stuff, use the default scheduler which is the
    # distributed scheduler setup by `client`
    ...

@dask.delayed
def does_more_dask_stuff(x):
    ...

x = does_some_dask_stuff()
y = does_more_dask_stuff(x)

# will display progress for the top-level graph, with the sub-graphs all submitted
# to the same distributed scheduler
with ProgressBar():
    y.compute(get=dask.get)
```
