### ISSUE TITLE
Using map_blocks/map_overlap on two arrays

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2403]
In some cases one needs to be able to use `map_blocks`/`map_overlap` or similar on two large arrays (i.e. Dask Arrays). Some examples include convolutions/correlations and some morphological operations (e.g. see [binary_dilation]( https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.ndimage.binary_dilation.html )'s `structure` and `mask` parameters). It would be nice if there were some API function(s) to help with this case.

**Comment by jcrist** [comment]
Can you explain how the current interface is insufficient? Both the `map_blocks` function and method take multiple arrays.

For multi-array `map_overlap`, support could be added.

**Comment by jakirkham** [comment]
Sorry. Some of the lines in the docs lead me to believe `map_blocks` did not support this (e.g. ["Map a function across all blocks of a dask array."]( http://dask.pydata.org/en/latest/array-api.html#dask.array.core.map_blocks )). Though the examples do paint a different picture. Would still like to see this for `map_overlap` as handling extended borders is quite common.

FWICT from the examples it seems that `map_blocks` just takes the corresponding regions in each array and operates on them. Once halos/ghosting is addressed, this would solve the issues involving morphological operations noted above

However in the case of things like `convolve`, a bit more is needed. First one would need to take all permutations of all ghosted chunks from both arrays, compute their results, and then reduce them. Thinking on this, using the term map here was confusing. Perhaps product or permute or similar would be more appropriate.

**Comment by chrisroat** [comment]
I'd love to help write a multi-array `map_overlap` method.  I've just hit my second need for it. Is anyone aware of work towards this already?

**Comment by mrocklin** [comment]
There are gufuncs, which sort of do this today. There are no other efforts to my knowledge.

**Comment by chrisroat** [comment]
I haven't used gufuncs, but it looks like the `map_overlap` interface would be somewhat simpler interface for common use cases.  And `map_overlap` is just calling `map_blocks` under the hood, so it looks like a fairly straightforward thing to implement.   I could imagine I'm missing some checks that need to be done.   Deciding the function signature is probably a bit tricky.

Here's something I've tried using.

```
import dask.array as da
from dask.array import Array
from dask.array.overlap import coerce_depth, coerce_boundary, overlap, trim_internal

def map_overlap_multi(func, *args, depth, boundary=None, trim=True, **kwargs):
    arrs = [a for a in args if isinstance(a, Array)]
    
    overlap_arrs = []
    
    for arr_index, arr in enumerate(arrs):
        depth2 = coerce_depth(arr.ndim, depth)
        boundary2 = coerce_boundary(arr.ndim, boundary)

        for i in range(arr.ndim):
            if isinstance(depth2[i], tuple) and boundary2[i] != "none":
                raise NotImplementedError(
                    "Asymmetric overlap is currently only implemented "
                    "for boundary='none', however boundary of array #{} for dimension "
                    "{} is {}".format(arr_index, i, boundary2[i])
                )

        assert all(type(c) is int for cc in arr.chunks for c in cc)
        g = overlap(arr, depth=depth2, boundary=boundary2)
        assert all(type(c) is int for cc in g.chunks for c in cc)
        overlap_arrs.append(g)
    
    g2 = da.map_blocks(func, *overlap_arrs, **kwargs)
    assert all(type(c) is int for cc in g2.chunks for c in cc)
    if trim:
        return trim_internal(g2, depth2, boundary2)
    else:
        return g2
```

**Comment by eric-czech** [comment]
Hey @chrisroat did that end up working well for you?  I keep bumping into use cases for this as well.

I'd be happy to work a PR for it.

**Comment by mrocklin** [comment]
In general I agree that `map_overlap` could probably be made to be multi-array friendly by ...

1.  Rechunking everything to a common chunking
2.  Doing the overap stuff on all of the arrays
3.  Calling map_blocks
4.  Calling trim on all of the arrays

We'll need to do boundary filling and trimming in a consistent way of course, but hopefully that's somewhat straightforward. 

Ideally this is added to the existing map_overlap function so that it is made more general, rather than making a new function and expanding the API.  The `dask.array.overlap.map_overlap` function seems to be relatively straightforward, and hopefully has the necessary pattern to follow.

A PR would be welcome.

**Comment by chrisroat** [comment]
I have a variation on this that I use regularly, but it's specific.  I got a bit gun-shy of dealing with the depth question in a general way.  I only needed overlaps in one array, and had just one auxiliary array, so made.  I put it in this gist, along with a blockwise-overlap variation.
https://gist.github.com/chrisroat/07714f2fd3a4f49cc832e8f8ab868a79

I think I would throw an error if the arrays have dissimilar chunking, rather than try to figure out what the common chunking would be.  Or have a way to turn off the checking, like the `align_arrays` parameter in blockwise.  In my case, my arrays different numbers and sizes of dimensions.

The tricky part is dealing with how to represent depth and boundary.   They already have a lot of different representations (number, tuple, dict), and now there needs to be yet another layer, to handle with it being different for each array.

**Comment by jakirkham** [comment]
FWIW it's probably sufficient these days to just solve the `map_blocks` problem. With tools like [`da.pad`]( https://docs.dask.org/en/latest/array-api.html#dask.array.pad ) users should be able to pad before going into `map_blocks` and slice off the overhang afterwards. Admittedly that is 3 lines instead of 1, but that is probably reasonable as we consider making `map_blocks` more flexible.

**Comment by chrisroat** [comment]
I think we've converged on the thought that `map_blocks` already does handle the multi-array case.

I do not understand the da.pad statement.  Are you suggesting people do the work of map_overlap in their own code.  That's effectively what I had to do in `map_overlap_multi` in my gist linked above.  It's not pad/trim, but da.overlap.overlap/da.overlap.trim_internal -- every chunk needs to be padded and trimmed.

The map_overlap method also handles the coercion of depth/boundary into the forms that da.overlap.overlap uses.

**Comment by eric-czech** [comment]
Thanks for the updates @chrisroat!  Very helpful.

@mrocklin how do you feel about enforcing a common chunking rather than trying to rechunk to one?  I'm trying to think about how that could work but it seems dangerous to have to pick between increasing or decreasing chunk sizes of certain arrays transparently.  At least in my case, I definitely wouldn't want that -- I'd rather have to think about which arrays represent the best structure given what I know the function will be doing.  Or is this something other functions somewhere in the array API already do?

I am going to take a crack at a PR that builds off of what Chris did so any further guidance/suggestions would be awesome.

**Comment by mrocklin** [comment]
I think that fundamentally you're looking for dask.array.core.unify_chunks.  It may also be that the `broadcast_arrays` function does what you want more simply.

```python
In [1]: import dask.array as da                                                                                                                                                                                                                                                                                                                                                                                                        

In [2]: x = da.ones(10, chunks=(4,))                                                                                                                                                                                                                                                                                                                                                                                                   

In [3]: y = da.ones(10, chunks=(5,))                                                                                                                                                                                                                                                                                                                                                                                                   

In [4]: da.broadcast_arrays(x, y)                                                                                                                                                                                                                                                                                                                                                                                                      
Out[4]: 
[dask.array<rechunk-merge, shape=(10,), dtype=float64, chunksize=(4,), chunktype=numpy.ndarray>,
 dask.array<rechunk-merge, shape=(10,), dtype=float64, chunksize=(4,), chunktype=numpy.ndarray>]
```

This should also handle mixed dimension arrays sensibly?

**Comment by chrisroat** [comment]
The use cases may not be covered by broadcasting, though I feel automatically broadcasting may be useful.  For example, one of my use cases arrays that are not equal size but I prechunked them the way I need, like the following:

```
import dask.array as da
x = da.ones(10, chunks=(5,))
y = da.ones(20, chunks=(10,)) 
da.broadcast_arrays(x, y)     # ValueError
```

We might take some hints from `blockwise` (for which my gist above also has a workaround to do overlaps on one array).  The work around in `blockwise` is the `align_arrays` parameter.  Perhaps we can add that here, to allow people to skip any automatic stuff.

**Comment by eric-czech** [comment]
Here's a sketch of one possibility, based on what you guys said (omitting assertions for brevity):

```python
from dask.array.core import map_blocks
from dask.array.core import unify_chunks
from dask.array.overlap import coerce_depth, coerce_boundary, trim_internal, overlap
from tlz import concat

def map_overlap(func, *args, depth=None, boundary=None, trim=True, align_arrays=True, **kwargs):
    
    def coerce(xs, arg, fn):
        if not isinstance(arg, list):
            arg = [arg] * len(xs)
        return [fn(x.ndim, a) for x, a in zip(xs, arg)]
    depth2 = coerce(args, depth, coerce_depth)
    boundary2 = coerce(args, boundary, coerce_boundary)

    if align_arrays:
        inds = [list(range(x.ndim)) for x in args]
        _, args = unify_chunks(*list(concat(zip(args, inds))), warn=False)

    args = [overlap(x, depth=d, boundary=b) for x, d, b in zip(args, depth2, boundary2)]
    x = map_blocks(func, *args, **kwargs)
    return trim_internal(x, depth2[0], boundary2[0]) if trim else x
```

That certainly covers my use cases and would have these properties:

- It won't work for arrays of different sizes along any one dimension, which I thought was kind of an odd fit for `depth` values as fixed numbers of cells rather than some kind of percentage
- It would work for differing chunk sizes
- You can opt out of chunk unification with `align_arrays`
- It wouldn't automatically broadcast all arrays to the same shape (which would be very bad in my case), but users could easily call `broadcast_arrays ` first if they want a quick fix on chunk alignment and don't care about the data duplication
- It would be reverse compatible minus the signature change (question on that later)
- Choosing of `boundary` and `depth` for the final trim is based on first argument, which is arbitrary but makes it reverse compatible
- It would support arrays with different `ndim`, though the automatic chunk unification means that in order for the blocks to be broadcast together, the unified chunks have to work out to have the same counts along matching broadcast dimensions.  I'm not sure it makes sense to allow this much magical behavior but I suppose it might have some uses:

```python

# Example where things occur as expected:
x = da.ones((10, 1,  1), chunks=((5, 5),    (1,),  (1,)))
y = da.ones((10, 12, 1), chunks=((2,3,5),  (12,),  (1,)))
z = da.ones((10, 12, 8), chunks=((5,3,2),  (12,),  (8,)))
# Func gets called with a row slice from each array (with 2, 3, 3, then 2 rows)
map_overlap(func, x, y, z)
# numblocks after unification: x, y, z = (4, 1, 1), (4, 1, 1), (4, 1, 1)

# More complicated example where this doesn't fail, but the way the blocks 
# become broadcastable is somewhat coincidental:
x = da.ones((10,), chunks=((5, 5))) #  <---  (5,5) happens to expand to 4 chunks 
y = da.ones((10, 12), chunks=((2,3,5), (6,6)))  #  <--- much like (6, 6) does
z = da.ones((10, 12, 8), chunks=((5,3,2), (4,4,4), (2,2,2,2)))
# Func gets called with 4 row slices from `z` but full copies of other arrays by broadcast
map_overlap(func, x, y, z)
# numblocks after unification: x, y, z = (4,), (4, 4), (4, 4, 4)
```

At this point it would be easy enough to make my own functions for things like this, but I'd still be happy to push upstream if this is in the ballpark of a good general-purpose solution.  Ultimately, I'd like to see https://github.com/pydata/xarray/issues/3147 happen and I imagine it would be easier with multiple-array `map_overlap` support here.

Along those lines, how crazy is it to propose something like this in a PR?  Changing these signatures:

```python
def map_overlap(x, func, depth, boundary=None, trim=True, **kwargs): ...
def map_blocks(func, *args, name=None, token=None, ..., **kwargs): ...
```
to:
```python
def map_overlap(func, *args, depth=None, boundary=None, trim=True, **kwargs): ...
def map_blocks(func, *args, name=None, token=None, ..., **kwargs): ...
```

Looking at the `map_overlap` tests and other references, I'm not opposed to trying to change them all but since it'd be my first contribution, it would be great to get a general sense of tolerance for API changes like that.

**Comment by mrocklin** [comment]
From my perspective the signature change is fine if we can identify the old form, and change it automatically for the user, while emitting an informative warning.

**Comment by hammer** [comment]
Is #6165 sufficient to close this issue?

**Comment by jakirkham** [comment]
Sure, let's go ahead and close this out. If there are other use cases, it's probably best to start with a new issue :)
