### ISSUE TITLE
Categorical types in (empty) meta df's cause empty categories, which cause confusing downstream errors

### ISSUE THREAD

**Issue by jdanbrown** [dask/dask#2480]
Constructing a ddf from a meta (i.e. empty df) with categorical types results in a ddf with a "known" categorical that has 0 values, which then causes weird behaviors when you try to use it. Example:

```py
# Schema + rows, like you might get from file storage
>>> schema = {
...     'i': 'int',
...     'cats': 'category',
...     'strs': 'str',
... }
... rows = [
...     {'i': 1, 'cats': 'foo', 'strs': 'x'},
...     {'i': 2, 'cats': 'bar', 'strs': 'y'},
...     {'i': 3, 'cats': 'foo', 'strs': 'z'},
... ]

# Parse the file lines using a bag so we can convert to a ddf
>>> bag = dask.bag.from_sequence(rows)

# Make the ddf meta from the stored schema
>>> meta = pd.DataFrame({name: pd.Series(data=[], dtype=dtype) for name, dtype in schema.items()})

# Convert bag to ddf and then try to use the ddf, e.g. write to parquet:

# .to_dataframe without meta: no categorical types, and to_parquet works fine
>>> ddf = bag.to_dataframe()
>>> ddf._meta.cats
Series([], Name: cats, dtype: object)
>>> ddf.to_parquet('/tmp/foo')

# .to_dataframe with meta: we have a categorical type with 0 categories (!), and to_parquet fails
>>> ddf = bag.to_dataframe(columns=meta)
>>> ddf._meta.cats
Series([], Name: cats, dtype: category
Categories (0, float64): [])
>>> ddf.to_parquet('/tmp/foo')
ValueError: could not convert string to float: 'foo'

# .to_dataframe without meta, and then make the categorical type "unknown": to_parquet works fine again
#   - Also works if we .to_dataframe(columns=meta)
>>> ddf = bag.to_dataframe().astype({'cats': 'category'})
>>> ddf._meta.cats
Series([], Name: cats, dtype: category
Categories (1, object): [__UNKNOWN_CATEGORIES__])
>>> ddf.to_parquet('/tmp/foo')

# .to_dataframe without meta, and then .categorize to make the categorical types "known": to_parquet works here too
#   - However, if we .to_dataframe(columns=meta) then .categorize doesn't suffice to get us out of 0-categories territory
>>> ddf = bag.to_dataframe().categorize(['cats'])
>>> ddf._meta.cats
Series([], Name: cats, dtype: category
Categories (2, object): [foo, bar])
>>> ddf.to_parquet('/tmp/foo')
```

A few options I can imagine here:
1. Lightweight: fail instead of constructing a "known" category with 0 values
2. Lightweight: coerce "known" categories with 0 values into "unknown" categories
3. Heavyweight: rethink something higher level

(1) would have sufficed to avoid my confusion, and I'm not sure (2) would be any more helpful than (1), and maybe just more surprising.

# Versions
```sh
$ python --version
Python 3.6.0

$ cat requirements.txt | egrep 'dask|distributed|fastparquet'
git+https://github.com/dask/dask.git@d0aa50a
git+https://github.com/dask/distributed.git@312a41a
git+https://github.com/dask/fastparquet.git@0.1.0
```

**Comment by TomAugspurger** [comment]
Thanks for the report. I think it would be OK for

```python
>>> ddf = bag.to_dataframe(columns=meta)
```

to treat zero categories as unknown categories. If you *do* require zero categories for whatever reason, you can do that with a `.cat.as_unknown`, but treating zero categories as unknown seems like the better default.

**Comment by martindurant** [comment]
Fastparquet is not able to write a categorical column without any categories (even if it has no rows or only null values), and I don't know if the parquet spec in general allows this. I think the specific error, though, is because `pd.Series([], dtype='category').cat.categories.dtype -> float64` and does not match the data.
 
The problem should be fixed before it gets to the parquet side, so I would go with @TomAugspurger 's comment above.

**Comment by jdanbrown** [comment]
> treating zero categories as unknown seems like the better default.

Yeah, on second thought I do agree that (2) is a better default behavior than (1).

> The problem should be fixed before it gets to the parquet side, so I would go with @TomAugspurger 's comment above.

Yep, agreed. Zero categories are confusing in dask alone, even before you hit the parquet write path. I was using parquet writes here just as an example of where zero categories cause trouble.

**Comment by jcrist** [comment]
So the issue here is that `dask.dataframe` trusts the user to provide accurate information to the `meta` kwarg. The current behavior is:

- If the input is a pandas object (`DataFrame`/`Series`) it is used as is (including all category information).
- If the input is a spec (e.g. a dict, list of tuples, etc...) then the categories are inferred as unknown.

I'm slightly against changing this - it seems weird to me to special case empty categories when we take everything else the user passed in at face value.

To achieve your desired behavior, you should be able to pass in `schema` directly, but that doesn't currently work because `to_dataframe` doesn't use `make_meta` currently (fixed in #2480). Using that patch you get the following behavior:

```python
In [1]: import dask.bag as db

In [2]: %paste
>>> schema = {
...     'i': 'int',
...     'cats': 'category',
...     'strs': 'str',
... }
... rows = [
...     {'i': 1, 'cats': 'foo', 'strs': 'x'},
...     {'i': 2, 'cats': 'bar', 'strs': 'y'},
...     {'i': 3, 'cats': 'foo', 'strs': 'z'},
... ]

## -- End pasted text --

In [3]: bag = db.from_sequence(rows)

In [4]: df = bag.to_dataframe(meta=schema)

In [5]: df
Out[5]:
Dask DataFrame Structure:
                            cats      i    strs
npartitions=3
None           category[unknown]  int64  object
None                         ...    ...     ...
None                         ...    ...     ...
None                         ...    ...     ...
Dask Name: to_dataframe, 6 tasks

In [6]: df.compute()
Out[6]:
  cats  i strs
0  foo  1    x
0  bar  2    y
0  foo  3    z
```

**Comment by jdanbrown** [comment]
> I'm slightly against changing this - it seems weird to me to special case empty categories when we take everything else the user passed in at face value.

@jcrist But pandas df's have no concept of "known" vs. "unknown" categories, whereas dask ddf's do. I'd argue that's sufficient reason to add special handling in the translation from pandas categories to dask categories. In particular, the current behavior is to translate a pandas `category` dtype into a dask `category[known]` dtype with 0 values, which is confusing and afaict not useful for anything, and the argument above is to instead translate a pandas `category` into a dask `category[unknown]`, which would avoid the confusion.

**Comment by jcrist** [comment]
In your example above the empty categorical showed up because you sere creating an empty dataframe yourself. If you're creating the dataframe yourself why can't you use the metadata syntax instead (as I did above)?

Empty categoricals can show up (although I agree that they aren't terribly useful in practice). I'd rather say "if you pass in a pandas object it is used as the metadata" rather than "if you pass in a pandas object it is used as the metadata, except when it has empty categoricals in which case these are converted to unknown categoricals". Simpler to understand and to implement.

With the fix provided in my PR you have the following options:

- Pass in a dictionary/list of tuples and have dask create the meta for you with unknown categoricals.
- Pass in a pandas object, and then call `.cat.as_unknown()` on the unknown categorical columns.

Do neither of these satisfy your need? I'm not 100% against this, but I still don't see a strong enough argument to special case empty categoricals. @TomAugspurger, I see you also responded in favor of making empty -> unknown. Do you also still feel this way?

**Comment by TomAugspurger** [comment]
Nope, I think you're correct that it isn't worth special casing.

FWIW, I hope to have my refactor of the pandas categorical dtype for the next pandas release. Then pandas will essentially have a categorical with unknown categories

**Comment by jdanbrown** [comment]
Sorry for the delayed response here.

> - Pass in a dictionary/list of tuples and have dask create the meta for you with unknown categoricals.

Yep! Passing in `meta` as a dict/list instead of a df works great. We've switched to that.

> I'm not 100% against this, but I still don't see a strong enough argument to special case empty categoricals.

I still find the empty df case surprising as a user, but I also agree it's a thorny issue and the tradeoffs are subtle. But if pandas adds its own notion of known vs. unknown and dask `meta=df` aligns its known/unknown behavior with that then I think my surprise will be successfully avoided.
