### ISSUE TITLE
dask.bag.map argument splatting should check for passed in **kwargs as well

### ISSUE THREAD

**Issue by mattilyra** [dask/dask#2524]
There's I think an unwanted behaviour in the current implementation for checking if `bag.map` should "splat" the arguments or not, i.e. fall back on `starmap`.

It is not uncommon to have functions with `args` that have no default values that at call time are defined by name by the callee, as in

    def f(a, b, c=1):
        return a+b+c

    f(0, b=10, c=11)

Currently `dask.bag.map` checks if the mapped function takes `*args` and if `*args` are provided to `bag.map`, if not it throws a depracation warning and falls back on `starmap`. The `bag.map` function should instead check if the `*args` and `**kwargs` provided jointly satisfy everything except the first argument in the mapped function, and only then fall back on `starmap`. 

Falling back on `starmap` is problematic when the `bag` contains dictionaries, which is often the case when handling JSON files for instance. Calling `map(*args) for args in bag` passes in the keys of the dictionary, which ends up producing very unhelpful error messages.

Consider the following two examples that should produce the same results

```python
from dask import bag as db
dummy_bag = db.from_sequence([{'a': 1, 'b': 2}, {'a': 1, 'b': 2}, {'a': 1, 'b': 2}])

def dummy_map(item, c):
    item['d'] = item['a'] + item['b'] + c
    return item

dummy_bag.map(dummy_map, 10).compute()    # works fine
dummy_bag.map(dummy_map, c=10).compute()  # TypeError: dummy_map() got multiple values for argument 'c'
```

**Comment by jcrist** [comment]
The reason for the current behavior is to accurately mirror the old behavior, while also deprecating it. The issue you point out here (difference between args and kwargs handling) is one of the reasons why we deprecated the old behavior.

Luckily, we've had 2 releases since the deprecation, so I'm fine deleting all the old code now. Fixed in #2525. Note that you can also make this work on the current release by calling `db.map` directly instead of using `Bag.map`, e.g.:

```python
db.map(dummy_map, dummy_bag, c=10).compute()
```
