### ISSUE TITLE
rpy2 head() vs compute()

### ISSUE THREAD

**Issue by rpanai** [dask/dask#2533]
This is pretty similar to the other issue.
I have a dask dataframe which I groupby and apply a custom R function and this calls another custom R function. If I try to see the `.head()` of the resulting dask Series I don't have any errors but if i try to `.compute()` the error is

    RuntimeError: Concurrent access to R is not allowed.

I guess that the culprit is the second call to a R custom as in a similar situation with calls from a library I don't have problems.

**Comment by jcrist** [comment]
Apologies for the late reply here. It looks like `rpy2` doesn't allow concurrent access to the R interpreter. As such, any calls to `R` need to be serialized per-process.

When you call `head`, you're likely only calling that R function once, which doesn't run into the issue. However, when you call `compute`, you're computing multiple partitions, and the added parallelism results in concurrent calls (and the error message you see above).

A few options:
- Switch to using processes instead of threads. This was mentioned in #2532.
- Add a lock around all calls to R functions. Something like:

```python
# Note: this *must* be imported from a file
# if using the multiprocessing or distributed scheduler
# as the lock can't be serialized.
from threading import Lock

your_function_lock = Lock()

def your_function(*args, **kwargs):
    with your_function_lock:
        return your_r_function(*args, **kwargs)
```

**Comment by jcrist** [comment]
Closing as not an issue with dask.
