### ISSUE TITLE
Should da.core.elemwise force dtype on actual operation?

### ISSUE THREAD

**Issue by bmerry** [dask/dask#2575]
When `da.core.elemwise` infers the dtype of the result, it cannot always be 100% accurate, because in numpy the value of scalars (including 0d arrays) can affect the dtype of the result. `elemwise` deliberately doesn't compute the value of 0d dask arrays (because it could be very expensive). This can lead to cases where the dtype of a dask array doesn't match the dtype when it is actually computed.

Example (due to #2574 this actually has undefined behaviour, but this is what I get at the moment):
```python
>>> a = da.ones(1, dtype=np.float32, chunks=1)
>>> b = da.from_array(np.array(1e200), chunks=())
>>> (a + b).dtype
dtype('float32')
>>> (a + b).compute().dtype
dtype('float64')
```

Suggestion: the dtype should be passed as a keyword argument to the underlying function, to force the result to match the inferred dtype. In typical cases this should make no difference, but in these corner cases it would make the graph and computed dtypes consistent.

This assumes that all functions given to `elemwise` take a `dtype` argument - I haven't checked. If not, presumably `getargspec` could be used.

**Comment by shoyer** [comment]
Yes, dtypes matching before and after computing an array is an important invariant to maintain.

I'm not sure about passing in a dtype argument to ensure this, since many elementwise functions don't support such an argument or they may interpret it differently (I recall some bugs wth `np.true_divide`). I would rather use an explicit cast with `astype()` in the few cases where the dtype of the result from NumPy cannot be predicted ahead of time.

**Comment by bmerry** [comment]
Okay, I'll look at adding an `astype` wrapper. It would still be nice to avoid making numpy compute at one precision and then convert the result, as opposed to computing directly at the desired precision, but I guess that can be improved later.

What do you think is the appropriate casting rule for the `astype` call? Perhaps `same_kind`?

Do you think it makes sense to do this unconditionally in `atop` (so that any dtype passed to `atop` is enforced) or would that be too heavyweight?

**Comment by jcrist** [comment]
This and #2574 are intertwined. I posted my thoughts there: https://github.com/dask/dask/issues/2574#issuecomment-319660869. In short, I think we should add the casting call to `elemwise`. `same_kind` might make sense, the dtype inference issue should only fail resulting in different precisions, never float instead of int.

---

On a higher level, the handling of keyword arguments to `elemwise` and `atop` has always bothered me. Some of the arguments are swallowed up by dask and never forwarded to the function, while others aren't. I'm not sure of a good backwards compatible way to fix this. Two ideas for best case solutions might be:

- Come up with a different keyword for specifying the inferred dtype, something that is less commonly used in numpy. Perhaps `dask_dtype`, `output_dtype`, etc... This would make it easier to deprecate the old behavior (warn when `output_dtype` is missing, then error in later release). The `dtype` kwarg could then be forwarded on to functions only if specified.

- Switch to passing in keyword arguments to functions as a dictionary. This would keep the arguments to the wrapped function separate from the arguments to the dask caller (e.g. `atop`). This has a less easy deprecation cycle, as it's not clear whether the `dtype` kwarg was meant for the function or to specify the dtype to dask. It also doesn't match how we do higher-level-functions in other parts of dask (e.g. `dask.dataframe.map_partitions`).

My vote is for option one. The only keyword to `atop` that is likely to collide with numpy keyword arguments is `dtype`.

**Comment by jakirkham** [comment]
Is this solved now @bmerry or was there more to do here?

**Comment by bmerry** [comment]
It's been a while so my memory is pretty hazy, but I think the issue has been addressed. I'm closing it, and we can open a new issue if there is a corner case that was missed.
