### ISSUE TITLE
Dropping columns results in kernel died, restarting

### ISSUE THREAD

**Issue by lamenramen** [dask/dask#2585]
`dask_df = dask_df.drop(['middle_name',],axis=1,errors=True).compute()`
This just keeps processing and processing, and then the kernel dies after about 10 minutes or so.
df is a valid parquet dataframe....it has length of 330 million and takes up 18 gb on a laptop with 8gb ram running Mac Sierra
if the same data frame is only 1 million rows, then the drop() command does not result in a kernel died.

**Comment by jcrist** [comment]
When you call `compute` the dataframe, you're pulling the whole thing into memory. Since your laptop has 8 GB, but the whole frame is 18 GB, then you're running into an out-of-memory error, which is probably swapping and eventually kills the process. I recommend either:
- Doing more processing of your data to get a smaller result size (whether this is statistics, a filtered subset, etc...). Of course this only makes sense if this is what you're after.
- Writing the output to some format (using `.to_csv`, `.to_parquet`, `.to_hdf`, etc...). Dask should handle this efficiently, without requiring the whole frame to be in memory.

**Comment by lamenramen** [comment]
Hi thank you very much, but my "`df`" is a dask data frame already.  (Sorry for the bad nomenclature. )....I read a 71 gb csv file into a dask data frame. Then saved it to parquet using `to_parquet`(). Then I immediately called `read_parquet`() to read into daskified_data.  daskified_data is the 18gb parquet file.  Now I just want to drop a column from `daskified_data `.

So the code looks like: 

```
import dask.dataframe as dd
raw_data.to_parquet('~/df_parquet') 
daskified_data = dd.read_parquet('~/df_parquet')
daskified_data = daskified_data.drop(['middle_name',],axis=1,errors=True).compute()
```

Isn't `daskified_data` allowed to be larger than my 8gb of ram since it is a dask data frame?

**Comment by jcrist** [comment]
> Isn't daskified_data allowed to be larger than my 8gb of ram since it is a dask data frame?

Yes, dask-dataframe is able to work on data that is larger than memory by intelligently handling blocked operations. However, if your output datasize is larger than memory, we can't do anything about that. In this case you're reading in all but the `middle_name` column, which results in an output size larger than your memory size.

If you instead try to do further computations that result in a smaller output size, everything  should work fine.

```python
import dask.dataframe as dd
raw_data.to_parquet('~/df_parquet') 
daskified_data = dd.read_parquet('~/df_parquet')
daskified_data = daskified_data.drop(['middle_name',],axis=1,errors=True)  # don't call compute here
daskified_data.head()  # should work
daskified_data.some_other_column.mean().compute()  # should_work
```

**Comment by lamenramen** [comment]
Thank you, this was my fundamental error then.  I apologize for this.
