### ISSUE TITLE
add pandas merge_asof function

### ISSUE THREAD

**Issue by sfrodrigues** [dask/dask#2619]
Hey guys,

trying to joing two dataframes by closest timestamp (in both directions). The [merge_asof function](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.merge_asof.html) allows to do this easily. Is there something similar in dask?

**Comment by TomAugspurger** [comment]
@sfragosorodrig that would indeed be a useful addition.

To make it easier to implement, I think we could limit it to just cases where we join on the index (`left_index=True`, `right_index=True`).

The implementation should be fairly similar to `dd.merge` https://github.com/dask/dask/blob/d8d1507059c2e34463386b10911bf6d7fa66b571/dask/dataframe/multi.py#L326 if you're interested in taking a look. Otherwise I should have a chance next week.

**Comment by sfragosorodrig** [comment]
@TomAugspurger I implemented the merge_asof in dask. However the results are not always correct because sometimes the necessary entries belong to adjacent partitions. 

Is this something you guys would find useful?

**Comment by TomAugspurger** [comment]
@sfragosorodrig yes I expect this would be broadly useful to others.

> However the results are not always correct because sometimes the necessary entries belong to adjacent partitions.

You might look into `overlap_chunk` here: https://github.com/dask/dask/blob/master/dask/dataframe/rolling.py#L16

For interger `tolerance` that should work for you. For time-based `merge_asof`, where `tolerance` is a Timedelta, there's probably some extra work to do. IIRC, I needed this once before.

Feel free to put up a PR and I can take a look.

**Comment by anderl80** [comment]
Hi all, is this still open? This might be very useful for some of my IoT applications..

**Comment by jrbourbeau** [comment]
Closing this issue as `dask.dataframe.merge_asof` was added in https://github.com/dask/dask/pull/4877. Hopefully that helps for your use case @anderl80. Feel free to open up any follow-up issues.
