### ISSUE TITLE
Dask.Delayed for functions operating on iterable classes

### ISSUE THREAD

**Issue by ckemere** [dask/dask#2785]
I've been trying to convert a for-loop based computation using dask. I've had success using the dask.distributed backend for joblib, but I was hoping to get more granularity of task specification. The challenge I ran into is that many of the functions that I want to wrap with delayed() operate on classes which are iterable. The functions in question don't use the iterators, but the classes define __iter__ and __next__. This causes the error "IndexError: too many indices for array" (or sometimes a recursion error).

Note that a key feature of the "bug" I'm reporting is that the iterators return copies of the objects. (We've found this very useful in our data analysis routines!)

If I get rid of the class iterate-ability, things work, but there are other cases where it's useful for us to be able to iterate. Is there any workaround for this?

Minimum example:

    import copy
    from dask import delayed

    class example_class:
        def __init__(self):
            self.foo = 0
            self._bar = np.random.rand(100,1)

        def __iter__(self):
            self._index = 0
            return self

        def __next__(self):
            index = self._index
            if index > 99:
                raise StopIteration
            out = copy.copy(self)
            out._bar = self._bar[index,:]
            self._index += 1
            return out

    ex1 = example_class()

    def evaluate(datum,i):
        foo = datum.ratemap
        return foo

    gg = delayed(evaluate)(ex1,0)

**Comment by jcrist** [comment]
Hmmm, this is because `dask.delayed` converts iterators into lists internally. I don't remember why this was added (@mrocklin?), and I'd be all for removing it as it's slightly unintuitive. It may have been to support things like `delayed(sum)(i * 2 for i in args)`, but this can be rewritten to `delayed(sum)([i * 2 for i in args])`. Users that want this behavior should really be passing in lists directly.

For now, you can call `delayed` on your iterable arguments beforehand, passing in `traverse=False` to skip the conversion. This isn't pretty, but works fine:

```python
In [12]: gg = delayed(evaluate)(delayed(ex1, traverse=False), 0)

In [13]: type(gg)
Out[13]: dask.delayed.Delayed
```

Note that this only needs to be done for arguments that are iterators, not delayed objects that may evaluate to them.

---

Alternatively, you could switch from defining an *iterator* (as you've done here) to defining an *iterable*. Your class would only define the `__iter__` method, which would return a new object that defines `__next__` (the iterator). `delayed` only converts iterators to lists, not iterables.

**Comment by ckemere** [comment]
The "traverse" option is very helpful. Also exploring to see if there's any downside of switching to creating a separate iterator option. Thanks!

**Comment by mrocklin** [comment]
Sorry for the very late response here, but I think the fact that iterators
are mutable is sufficient reason to disallow them in a task graph.
