### ISSUE TITLE
Keep original filenames in dask.dataframe.read_csv

### ISSUE THREAD

**Issue by kmader** [dask/dask#2802]
For the data I am reading, the path (directory name) is an important trait, and this would be useful to access (possibly as an additional column, ```path_as_column = True```) or at the very least in the collection of delayed objects
```
import dask.dataframe as dd
dd.read_csv('s3://bucket_name/*/*/*.csv', collection=True)
```

![image](https://user-images.githubusercontent.com/116120/31818992-d702cd1a-b59a-11e7-9636-dfca278ea320.png)

The collection version of the command comes closer

```
all_dfs = dd.read_csv('s3://bucket_name/*/*/*.csv', collection=True)
print('key:', all_dfs[0].key)
print('value:', all_dfs[0].compute())
```
but returns an internal code as the key and doesn't seem to have the path (s3://bucket_name/actual_folder/subfolder/fancyfile.csv) anywhere
```
key: pandas_read_text-35c2999796309c2c92e6438c0ebcbba4
value:    Unnamed: 0   T   N   M   count
0           0  T1  N0  M0  0.4454
1           5  T2  N0  M0  0.4076
2           6  T2  N0  M1  0.0666
3           1  T1  N0  M1  0.0612
4          10  T3  N0  M0  0.0054
```

**Comment by mrocklin** [comment]
You are correct that `dd.read_csv` does not include the filename or directory structure within the dataframe. 
 You might find this notebook on custom data ingestion useful: https://gist.github.com/mrocklin/e7b7b3a65f2835cda813096332ec73ca

**Comment by kmader** [comment]
Thanks, that seems to do it, I guess part of me was hoping it would be possible to stay inside the elegant environment of dask.dataframe and not dive into the lazy_dataframes/dd.from_imperative/metadata world, but maybe the use cases are just one-off

**Comment by mrocklin** [comment]
Finding a general solution here would be welcome.  However my experience is that the directory-of-csv-files situation is somewhat open ended.  Everyone has a different way in which they expect the resulting dataframe to look, which makes it difficult to make a proper solution for everyone.  Dask.delayed has proved doable for most people, so we just encourage that.

Closing.  Thanks for the issue.

**Comment by twiecki** [comment]
I think automatically adding the filename to the index would be pretty general.

**Comment by mrocklin** [comment]
It would be great to get some new blood into working on dask.dataframe @jsignell, so I'm all for making this happen :)

Do people have suggestions on what this would look like?  Presumably this would be an optional keyword argument to `dd.read_csv`?  If so, what name should it have?  Should the filenames be as a column or as an index, or is this something that the user should be able to toggle between by changing the value of the keyword argument?  Should filenames be relative or absolute?  etc..  Feedback from people watching this issue would be welcome.  I suspect that there are a few different approaches.

**Comment by twiecki** [comment]
My suggestion is to not add that many options as it's easy to go back and forth between them. I think reasonable defaults would be to add it as a multiindex level (tidy data) and do the relative path (does `dask.DataFrame` also supports multiple wildcards, e.g. `*/*.csv`? these should be included as well).

**Comment by martindurant** [comment]
I would not recommend using multi-indexing, which has it's own problems.
I would use either a straight column for the file-names (categorical type, I suppose) or as the sole index.
Yes, urls with multiple wildcards should be successfully resolved by the backend file-system, so the file basename may not be unique.

**Comment by twiecki** [comment]
> I would not recommend using multi-indexing, which has it's own problems.

Care to elaborate?

**Comment by martindurant** [comment]
Dask keeps track of "divisions" in order to know which partition to go to for which label, and managing these gets complicated. Multi-indexing is not totally supported in its catagorical-like nature (selecting sub-levels, etc), limiting its usefulness.

**Comment by jlstevens** [comment]
As a quick comment, I often find that people aren't interested in the filename itself but in some information/metadata that has been encoded into the filename. 

It might be nice to offer users the flexibility to (optionally) supply a function when calling `read_csv` in order to parse out this information into the appropriate columns right away. Then they can immediately get the dataframe in the format they actually want without having to perform additional data munging passes to process the filename afterwards.

**Comment by jsignell** [comment]
I think as a first approach adding a column with the filename is the simplest method. This would work nicely when concatenating on columns, but it seems like often we are trying to describe another dimension to the data, so that kind of concat doesn't quite make sense. Maybe rather than a `MultiIndex` we could optionally add the filename (or some derivative of the filename) as another axis and concat on that new axis. This might be separable from the filename issue. It seems like supporting different types of concat would be generally useful.

We could allow a `path_parser` as @jlstevens suggested which would be a function taking the relative path as the only argument and returning something.

**Comment by jsignell** [comment]
I will get started on just adding filenames as a col and we can see how that feels.

**Comment by jsignell** [comment]
I have been thinking more about the `path_parser` idea. Pandas already accepts a `converters` kwargs. So we could just do a minor tweak and check that `converters` dict for the path_col and if we find it do the transformation before returning the df. I think the value is in only needing to do the operation once for each path vs. lots of times. This is what it would look like:

<img width="810" alt="screen shot 2018-08-28 at 3 34 08 pm" src="https://user-images.githubusercontent.com/4806877/44746376-3265f280-aad8-11e8-890c-cb392c16fd80.png">

**Comment by mrocklin** [comment]
I like the idea of reusing the existing `converters` API.  

> I think the value is in only needing to do the operation once for each path vs. lots of times

If we wanted to get fancy then we might also consider converting the filenames into a categorical dtype.  This would make things slightly more complex, but would improve performance in the way that you suggest (and in other ways too).

**Comment by jsignell** [comment]
I think that isn't quite needed yet. I'll push my changes to the PR.

**Comment by fmfreeze** [comment]
Is an equivalent feature argument available for `dd.read_hdf`?

**Comment by jsignell** [comment]
@fmfreeze it doesn't look like this functionality exists for `dd.read_hdf` but I'm sure it would be a welcome addition if you want to open a PR. Otherwise you can always use `dd.from_map` (docs: https://docs.dask.org/en/latest/generated/dask.dataframe.from_map.html) to make a custom per-file reader.
