### ISSUE TITLE
da.linalg.svd_compressed promotes float32 to float64

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#2849]
Need to check if this is deliberate or not. `svd` will return arrays of float32s.

```python
In [10]: import numpy as np; import dask.array as da

In [11]: X = da.random.uniform(size=(100, 4), chunks=(50, 4)).astype('f4')

In [12]: u, s, v = da.linalg.svd(X)

In [13]: u.dtype, s.dtype, v.dtype
Out[13]: (dtype('float32'), dtype('float32'), dtype('float32'))

In [14]: u, s, v = da.linalg.svd_compressed(X, 2)

In [15]: u.dtype, s.dtype, v.dtype
Out[15]: (dtype('float64'), dtype('float64'), dtype('float64'))
```

**Comment by mrocklin** [comment]
cc @marianotepper .  Was this intentional for some numerical precision reason?

**Comment by RogerMoens** [comment]
Hi all,

This problem is not caused by the tsqr function, but the compression_matrix function in linalg. The original datatype is not applied on the random matrix "omega". The latter is automatically spawned in float64 as a standard. It is not required for the process for it to be float64 as you are randomly sampling the columns of your original matrix, and if that original matrix is float32 then multiplying it with a weight that is float64 doesn't make sense, nor improves accuracy.

It might improve numerical precision for the qr that is performed later on as it does for a standard svd as those are performed in higher accuracy. But it should be in my opinion a users preference, similar to numpy, when you input a float32 it will perform an svd or qr in float32 precision, etc.

So, the solution would be to change the dtype of omega. This also speeds up the other processes.


Cheers,


Roger

**Comment by RogerMoens** [comment]
Rereading my statement: since the implemented qr's are stable in float32 as well as float64, it never makes sense to promote to float64 instead of keeping it in float32 (if float32 is the datatype of the input matrix). It only adds a lot of extra need for memory/disk to store the intermediate matrices and it increases the gpu/cpu need.

**Comment by RogerMoens** [comment]
_This note is added for the records_.

As already mentioned in #6757, the power iteration is prone to errors due to numerical precision. Therefore, running in float32 deteriorates the performance of the power iteration more than float64 (see second test case in #6802). For some matrices, the influence might be more than for others, depending e.g. on the singular value landscape (e.g. steep decrease, ...).

Why is this important? Performing a subspace iteration with a QR or LU decomposition might be computationally more of a burden (I will do some testing after I have implemented those). One thought could be that Mariano Tepper kept the simple power iteration as a next best solution for extremely large matrices by keeping the promotion to float64. Such that he traded of memory vs. cpu, but also accuracy/stability during the iteration step. This would surprise me, however, because if matrices don't fit into memory, they get spilled to disk such that reading/writing becomes dominant in the performance of the compressed svd. Again, this doesn't make it the next best solution, as keeping it in float32 and performing the more accurate QR would be way faster. So the only case where float64 promotion is appropriate is when the input matrix is float64, which I think is more plausible why this was overseen.

**Comment by RogerMoens** [comment]
@TomAugspurger : this one is fixed, so it can be closed I guess.

**Comment by TomAugspurger** [comment]
Thanks!
