### ISSUE TITLE
Profiler, and CacheProfiler return empty lists

### ISSUE THREAD

**Issue by andersy005** [dask/dask#3089]
I am trying the profiling examples provided in the [documentation](http://dask.pydata.org/en/latest/diagnostics.html#profiling). The profiler and the cacheProfiler don't seem to work as expected though. They are returning empty lists. 

I am using 

Python | 3.6.4
-- | --
dask | 0.16.1

---

![screenshot-2018-1-21 04_arrays](https://user-images.githubusercontent.com/13301940/35203121-374bacec-feec-11e7-9a99-dfd56d240765.png)

**Comment by jcrist** [comment]
Are you sure you're using a local scheduler and not the distributed scheduler? If you ever create a `dask.distributed.Client`, the distributed scheduler becomes the default scheduler.

`dask.diagnostics` only is intended to work with the local scheduler (threading or multiprocessing). The `ResourceProfiler` happens just happens to work with both because it doesn't rely on scheduler callbacks that the others do. If you're intentionally using the distributed scheduler here, you should use the [distributed diagnostics](http://distributed.readthedocs.io/en/latest/web.html) instead.

The following example works fine for me when using a local scheduler:

```python
import dask.threaded
import dask.array as da
from dask.diagnostics import ResourceProfiler, Profiler, CacheProfiler

a = da.random.random(size=(10000, 1000), chunks=(1000, 1000))
q, r = da.linalg.qr(a)
a2 = q.dot(r)
with Profiler() as prof, ResourceProfiler(dt=0.25) as rprof, CacheProfiler() as cprof:
    # By default this should use the threaded scheduler, but if you
    # have a global default set you can override it locally by specifying
    # the scheduler directly. Here I specify to use the threaded scheduler.
    out = a2.compute(get=dask.threaded.get)
```

**Comment by andersy005** [comment]
Ok, got you. I didn't specify what scheduler to use for `compute()`.  Thanks @jcrist!
