### ISSUE TITLE
Add DataFrame.to_dask_array

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#3090]
We have `DataFrame.values`, but this results in chunks of unknown size. If we happen to know the size of each partition / chunk, then we could do `df.to_dask_array(chunk_lengths)`.

Basically,

```python
In [35]: df = dd.from_pandas(pd.DataFrame(np.random.uniform(size=(100, 5))), 10)

In [36]: lengths = df.map_partitions(len).compute().values  # user knows this somehow

In [37]: blocks = []

In [38]: for block, length in zip(df.to_delayed(), lengths):
    ...:     blocks.append(da.from_delayed(block.values, (length, len(df.columns)), 'f8'))
    ...:

In [39]: arr = da.vstack(blocks)

In [40]: arr
Out[40]: dask.array<concatenate, shape=(100, 5), dtype=float64, chunksize=(10, 5)>
```

**Comment by mrocklin** [comment]
This seems like a good idea to me.  Presumably it would also help with roundtripping arrays -> dataframes -> arrays.  We might consider accepting a `chunks=` keyword to maintain uniformity with other I/O functions.  The docstring should probably have a loud disclaimer that this doesn't mean that Dask will enforce this chunk sizing, but rather that you the user are promising that it is the case.

**Comment by jorisvandenbossche** [comment]
Could there be an option to specify that dask itself figures out the chunk sizes? Or should we require the user to pass it? 
It isn't difficult to do as shown above, the user should just be aware that it is materializing the full dataframe to get the lenghts, so it should probably not be the default (but in certain cases the user will otherwise to exactly this him/herself).

**Comment by cr458** [comment]
Could I have a go at this? Provided no one else has already started.

**Comment by mrocklin** [comment]
That would be quite welcome @cr458 .  I recommend leveraging `dd.map_partitions` with a function that produces a numpy array.  This will produce the appropriate dask.array without good chunk information.  You should then be able to modify `._chunks` explicitly with provided chunk information.  You may want to read more about chunks here: http://dask.pydata.org/en/latest/array-design.html#chunks

**Comment by cr458** [comment]
@mrocklin apologies for the delay. I have been thinking about how to approach this given my lack of familiarity with dask. 
From my understanding a function that produces a numpy array using `dd.map_partitions` would look something like `df.map_partitions(lambda x: x.values)` which would produce a dask.array. We would then explicitly set the `._chunks` attribute of the dask.array with a tuple of tuples which were passed by the user. Is there a reason that @TomAugspurger looped through the blocks rather than using `dd.map_partitions` and explicitly setting the chunks afterwards?

**Comment by TomAugspurger** [comment]
@cr458 has `map_partitions` always been able to return a dask array, or is that a new addition?

**Comment by cr458** [comment]
@TomAugspurger thanks for replying! I'm not sure actually, am fairly unfamiliar with dask. I only asked because @mrocklin suggested using `dd.map_partitions`, so wanted to check if there was a particular reason/preference for either method.

**Comment by TomAugspurger** [comment]
Indeed. If map_partitions works, then I'd go with that.

**Comment by mrocklin** [comment]
Map partitions is now smarter about creating a proper dask array than it was when this issue was created.  A simple implementation of this would be the following:

```python
def to_dask_array(self, lengths):
    x = self.values
    x.chunks = (tuple(lengths), (len(self.columns),))
    return x
```

Or the same but with `to_records` to create a record array.  Given the simplicity of this now I wonder if it might make sense to forego creating a new method here, and maybe just make it easier to define chunk sizes on arrays with unknown chunks.  This is somewhat related to #3293

**Comment by TomAugspurger** [comment]
I could imagine cases where the dask.dataframe user knows the sizes
(reading from a parquet file that has the sizes for example), so a compute
could be avoided.

**Comment by mrocklin** [comment]
Agreed.  I think that some of the conversation in that issue is about that
possibility as well.

**Comment by cr458** [comment]
Thank you for your replies, that clears things up considerably for me! 
From looking at #3293 it seems that there are two possible scenarios: one where the sizes are known beforehand, and one where the sizes are computed. 
For both cases we'd eventually set the sizes with something like `x.chunks = (tuple(lengths), (len(self.columns),))`, but I guess this will be addressed in the other PR and this one is no longer required?

**Comment by TomAugspurger** [comment]
@cr458, I'm not sure if #3239 has settled on a consensus, but IIUC it will provide two things

1. A helper for discovering the chunk sizes of unknown chunks
2. A public API for converting an array with unknown chunks to known chunks.

If we already know the chunk sizes, we can already achieve 2 by setting the private `x._chunks` value.

**Comment by cr458** [comment]
@TomAugspurger great, thanks for clearing things up. I will look for another PR to contribute to in the mean time as am keen to help out where I can.

**Comment by jakirkham** [comment]
So you may find [this comment]( https://github.com/dask/dask/issues/3293#issuecomment-376762949 ) interesting, @cr458. Expect calling `to_records` and employing that strategy to be reasonably effective.
