### ISSUE TITLE
Indexing a dask array with another dask array

### ISSUE THREAD

**Issue by mraspaud** [dask/dask#3096]
So, following the instructions in the documentation, I'm raising an issue :)

> It does not currently support the following:
> 
> * Slicing one dask.array with another x[x > 0]
> * Slicing with lists in multiple axes x[[1, 2, 3], [3, 2, 1]]
> 
> Both of these are straightforward to add though. If you have a use case then raise an issue.
> 

Our use case is a quite common one in our domain (weather satellite data processing), that is using lookup tables like this:

```python

import numpy as np
import dask.array as da

lut = np.random.rand(1024) * 100
dlut = da.from_array(lut, chunks=1024)
idx = np.random.randint(1024, size=(1000, 1000))
print(dlut[idx.ravel()])
# -> dask.array<getitem, shape=(1000000,), dtype=float64, chunksize=(1000000,)>

didx = da.from_array(idx, chunks=1000)
print(dlut[didx.ravel()])
```

I most cases, the lookup table is quite small (256 to 4096 values), but the index (the actual data to be converted) is large. 

The previous script crashes on the last line with this traceback

```
  File "test_dask_idx.py", line 13, in <module>
    print(dlut[didx.ravel()])
  File "/home/a001673/.local/lib/python2.7/site-packages/dask/array/core.py", line 1257, in __getitem__
    self, index2 = slice_with_dask_array(self, index2)
  File "/home/a001673/.local/lib/python2.7/site-packages/dask/array/slicing.py", line 844, in slice_with_dask_array
    y = elemwise(getitem, x, *index, dtype=x.dtype)
  File "/home/a001673/.local/lib/python2.7/site-packages/dask/array/core.py", line 2751, in elemwise
    out_ndim = len(broadcast_shapes(*shapes))   # Raises ValueError if dimensions mismatch
  File "/home/a001673/.local/lib/python2.7/site-packages/dask/array/core.py", line 2723, in broadcast_shapes
    "shapes {0}".format(' '.join(map(str, shapes))))
ValueError: operands could not be broadcast together with shapes (1024,) (1000000,)
```

The expected behaviour would be of course to have a dask Array returned.

As a bonus item, the `.ravel()` thing is a bit annoying, since all we do in the end is ravel and reshape (the data is most often 2D).

dask version is 0.16.0+37.g1fef002
numpy version is 1.13.3

Thanks for a great package !

**Comment by mrocklin** [comment]
I agree that in principle it would be nice if this worked.  

I wonder if, short term, you could use `map_blocks` to resolve your need

```python
>>> didx.map_blocks(lambda block, lut=None: lut[block], lut=lut)
dask.array<lambda, shape=(1000, 1000), dtype=float64, chunksize=(1000, 1000)>
```

**Comment by mraspaud** [comment]
@mrocklin yes, I can live with that for a short while. I might have a look at a PR for that, do you have some quick pointers to get me started on this ?

**Comment by mrocklin** [comment]
You would want to look at dask/array/slicing.py and the associated test
suite in dask/array/test_slicing.py .

We probably wouldn't want to solve just this particular case though.  This
might require looking at the problem a bit more holistically to see if
there is a chunk of functionality that we can implement that makes sense to
maintain.

**Comment by rzu512** [comment]
I was trying `B[da.argmin(A)]`. Even though `da.argmin(A)` is just one number, that didn't work because it needs indexing a Dask array with another Dask array. In the end, I reduce both A and B together ([https://github.com/dask/dask/issues/3092](url)). That solution is really not ideal because it breaks `B` into parts and then sends `B` to the tasks. But there shouldn't be a need to send `B` in the first place especially when `B` is large. Alternatively, it is possible to evaluate `da.argmin(A)` to a numpy array first, and then use that to index B. But I can't quite figure out how to make that a lazy evaluation.

After writing that, I think about an indexing that works for reduction. The indices `A` would have a chunks of ((np.nan, np.nan), (3,)) if we are indexing an array `B` with two block along the 0<sup>th</sup> axis and 1 block along the 1<sup>st</sup> axis. Both `A` and `B` have the same `numblocks` that are broadcastable with each other. When evaluating `B[A]`, the (i, j)<sup>th</sup> block of B is indexed by (i, j)<sup>th</sup> block of A if the `numblocks` of `A` and `B` are the same. If `B` and `A` don't have the same numblocks, the blocks of `A` is broadcasted to the blocks of `B`.

The down side is that the resulting array `B[A]` has `np.nan` in chunks, which represent unspecified size of some blocks along some dimension. Sometimes I am sure that the shape of `B[A]` is 5 along axis 0 because A is the top 5 element of another array. But I can't quite represent a Dask Array with known shape and known numblocks but unknown chunks along some dimension. Can't use a Dask array in chunks of another Dask array.

Another potential problem is that some blocks of `B[A]` would contain no elements but have more than 0 dimensions.

**Comment by jakirkham** [comment]
> > Slicing one dask.array with another x[x > 0]

So this line is out of date. Where did you see this @mraspaud?

**Comment by jakirkham** [comment]
Would point out something subtle, but very important about fancy indexing. Namely...

```python
x[[1, 2, 3], [3, 2, 1]] != x[np.array([[1, 2, 3], [3, 2, 1]])]          # Partial index array
x[[1, 2, 3], [3, 2, 1]] == x[np.array([1, 2, 3]), np.array([3, 2, 1])]  # Full index array
```

So if we support this with Dask Arrays, we need to distinguish these two cases.

**Comment by jakirkham** [comment]
@shoyer, may have more thoughts on this as well.

**Comment by jakirkham** [comment]
Wrote up a rough attempt at how one might do this in [this gist]( https://gist.github.com/jakirkham/362ec5316922c19543bec84c7b7b7072 ). Would be curious to hear thoughts on this and whether and/or how we might want to include it in Dask.

**Comment by mraspaud** [comment]
@jakirkham this was on the slicing page, and can still be seen on the stable version of the documentation.
http://dask.pydata.org/en/stable/array-slicing.html

I suppose that has changed since I raised this issue.

**Comment by jakirkham** [comment]
Thanks @mraspaud. It has been fixed in the `latest` docs. It won't show up in the `stable` docs until the next release. That said, `x[x > 0]` does indeed work and has worked for some time.

**Comment by shoyer** [comment]
I agree, slicing with multiple lists is quite subtle. It would be better to point users towards the `.vindex` attribute for this use-case.

**Comment by jakirkham** [comment]
Interesting. Was not aware of `vindex` being in Dask Array. That is very useful. Have since read up on issue ( https://github.com/dask/dask/issues/433 ) and PR ( https://github.com/dask/dask/pull/439 ) where it was implemented. Would it be ok to extend `vindex` to handle Dask Arrays of potentially unknown length?

**Comment by jakirkham** [comment]
Adding a note to the docs in PR ( https://github.com/dask/dask/pull/3199 ) mentioning `vindex` next to the `Slicing with lists in multiple axes...` bullet point. Hopefully that helps other users looking for this functionality. Suggestions on how to improve the wording welcome.

**Comment by mraspaud** [comment]
`dlut.vindex[didx]` is a good solution indeed (works in my example), but making it use Dask Arrays would be great !

**Comment by jakirkham** [comment]
Yeah I agree.

Have gotten something along these lines working in PR ( https://github.com/dask/dask/pull/3210 ). Would be great if some people could take a look and offer feedback.

**Comment by maxkazmsft** [comment]
Would this workaround also work for numpy index arrays? In our case the index and returned matrices are small (can fit on a single machine), but the lookup matrix is large. 

More specifically, for each row in distributed matrix C, we need to select a fixed number of different columns specified with dense k by 3 index matrix (numpy array), i.e. 
`C[:,index_array]`, where index_array can look something like `[[100, 300, 0], [123, 532, 1], …, [6, 7, 1003023]]`; this is accomplished with `C[np.arange(k)][[:,None], index_array]` in numpy. Since double array indexing is not yet supported in Dask and k is large, is there a workaround which can be implemented?

**Comment by akloster** [comment]
My use case would be to transform a 3D volume (CT, Micro-CT, MRI...) by a matrix. I can generate the coordinates first with meshgrid, then transform them, and use them to get the data. The only way I see right now is to go "straight to the source", and use chunks of the coordinates to vindex the zarr/hdf5 etc file directly. Disadvantage is that I can only transform data accessible to all workers.

**Comment by mrocklin** [comment]
This seems to work today

```python
import numpy as np
import dask.array as da

lut = np.random.rand(1024) * 100
dlut = da.from_array(lut, chunks=1024)
idx = np.random.randint(1024, size=(1000, 1000))
print(dlut[idx.ravel()])
# -> dask.array<getitem, shape=(1000000,), dtype=float64, chunksize=(1000000,)>

didx = da.from_array(idx, chunks=1000)
print(dlut[didx.ravel()])
```

**Comment by mrocklin** [comment]
```
dask.array<getitem, shape=(1000000,), dtype=float64, chunksize=(1000000,)>
dask.array<slice_with_int_dask_array_aggregate, shape=(1000000,), dtype=float64, chunksize=(1000000,)>
```

**Comment by jakirkham** [comment]
Right, this got solved by PR ( https://github.com/dask/dask/pull/3407 ).
