### ISSUE TITLE
dask_dev twitter account permissions

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3112]
There is a [@dask_dev](https://twitter.com/dask_dev/) account on twitter.  I believe that it is currently managed by @jcrist and myself.  Do any other core contributors want access to this account?  Do we want to set expectations about what we tweet?

**Comment by jcrist** [comment]
To expand this a bit, we have a `daskdevelopers` gmail account that I've been using to sign up for project wide services that shouldn't really be owned by a single person. A few people have the login information for this account. Currently this is just for appveyor and twitter. I'm not sure if there's a better system we could have, but at least it's not a single point of failure since multiple people have access.
