### ISSUE TITLE
Problems with Community Discussion Policy

### ISSUE THREAD

**Issue by Shellcat-Zero** [dask/dask#3134]
There is currently an issue with the Dask Community Discussion Policy (http://dask.pydata.org/en/latest/support.html) where Dask users are strongly discouraged from asking questions about Dask usage in any place other than Stack Overflow (such as Gitter or IRC).  

The general use cases for chats like IRC or Gitter are when you need to discuss the answer or you are not sure how to even formulate the question, which also means you don't fully understand the problem. In that case it's better to talk it out and get immediate feedback. This is the process that I typically go through before posting anything to Stack Overflow, or to Github if I determine my issue is actually a bug.

Dask is still young enough that many of the test cases have not yet been explored, and limiting the discussion to Stack Overflow can create barriers to new users who don't know if their issues are specific to Dask, Linux, cluster configurations, Python configurations, etc.  Open source projects like Dask should benefit from generating community discussion and contribution wherever it will be openly supported.  Dask users and maintainers answering questions on Gitter, IRC, Stack Overflow, or wherever they choose to chat should also be better suited to updating their documentation (or blog) accordingly to be more clear in their explanations.  I would encourage usage of Stack Overflow, but I would not create a single point of failure around Stack Overflow for community discussion.

**Comment by mrocklin** [comment]
I'll try to separate my personal thoughts on this as a person who asks and answers questions, and as someone with some responsibility to maintain a community around this project.

### As an individual who asks and answers questions

I strongly prefer stack overflow for both roles.  As an asker I *often* refer back to previous questions that I've asked.  Having them in a publicly visible place is super valuable for me.  I also appreciate and depend on other people who have asked well-posed questions in the past.  I find the wealth of good quality questions on Stack Overflow to be an invaluable resource, and I feel a responsibility to contribute back to that resource.

As a question answerer I used to answer many questions on gitter, but I kept getting the same questions over and over again, which eventually made me frustrated enough that I stopped.  When I stopped answering questions, people became upset.  The compromise was to ask people to ask questions on stack overflow and to answer them in a timely manner (many of the dask devs subscribe to e-mail updates on the stack overflow dask tag).  Stack overflow handles repeats well and there is a good sense that the question asker needs to put in time to make a good question.  See [mcve](https://stackoverflow.com/help/mcve).

Due both to the value provided to other future question askers, and due to the increased expectation of effort from current question askers I personally will probably only ever answer user questions on Stack Overflow, unless I'm actively engaged in a collaboration with someone.  More on my thoughts here: http://matthewrocklin.com/blog/work/2016/08/25/supporting-users

### As a community maintainer

However, those are only my preferences, and while I think there is value to strongly pushing people towards stack overflow we probably shouldn't stop people from asking and answering questions in any medium if they so choose. I apologize if I was overly harsh [earlier](https://gitter.im/dask/dask?at=5a74dae4ce68c3bc743a243f).

I suggest that we maintain the current language in the docs, which is more about strong preferences rather than rules, particularly when they provide explanations for the logic:

> In particular we strongly prefer the use of StackOverflow and Github issues over Gitter chat.  Github and StackOverflow are more easily searchable by future users and so is more efficient for everyone’s time

I also suggest that we should allow questions and answers in https://gitter.im/dask/dask but ban them in https://gitter.im/dask/dev .

Thoughts from other maintainers would be especially welcome.  I suspect that I am in a more extreme position than most people on this topic.
