### ISSUE TITLE
Integrating dask in vaex, some questions

### ISSUE THREAD

**Issue by maartenbreddels** [dask/dask#3148]
I'm interested to see if I can use dask as backend for vaex, to see if this is possible, I have some questions. I asked @TomAugspurger a bit at a meeting in Paris, but we concluded a code example would clarify some of it.

 * Is it possible to have a per process or per thread variables? The reason is that in vaex I do statistics on Ndimensional grids, each thread has it's own grid (not each task/job), and in the final phase these grids are combined together. Having a per task/job grid would be too memory consuming and a waste of resources.

The best I could come up with is this:
```python
import vaex
import dask
import numpy as np
import multiprocessing
import threading

lock = threading.Lock()
local = threading.local()
thread_indices = iter(range(1000000))  # enough threads until 2100?

# generate some random data
N_chunks = 16*4
size_chunk = 1024**2
N = size_chunk * N_chunks
x = np.random.normal(0, 1, N)

# split into chunks
chunks = [x[i*N:(i+1)*N] for i in range(N_chunks)]

# we do a histogram per thread
N_bins = 64
N_threads = multiprocessing.cpu_count()
counts_thread = np.zeros((N_threads, N_bins), dtype='f8')


@dask.delayed
def bin_subset(x):
    # make sure we write to a unique piece of memory for each thread
    # so we get a thread local thread index
    with lock:
        if not hasattr(local, 'thread_index'):
            local.thread_index = next(thread_indices)
    # compute (add) to a 'thread local' grid
    vaex.vaexfast.histogram1d(x, None, counts_thread[local.thread_index], -3, 3)
    # this would be the slow non-vaex way
    #counts, __ = np.histogram(x, bins=N_bins, range=(-3, 3))
    #counts_thread[local.thread_index] += counts
@dask.delayed
def reduce(*tasks):
    return counts_thread.sum(axis=0)
tasks = [bin_subset(chunk) for chunk in chunks]
# although bin_subset does not return anything, we make sure reduce waits for all the tasks
result = reduce(*tasks)
counts = result.compute()
```

The issue with this is that it won't work with other schedulers, since thread local storage cannot be pickled. Maybe there is also a better way to do, it doesn't seem very 'dasky'.

* Can a computation be cancelled, and it's progress be monitored? 

In vaex, you can have a visualization, zoom in, and if you zoom or pan before the computation is done, the current calculations is cancelled. Also, is the API for the progress documented and/or stable?

**Comment by mrocklin** [comment]
Generally dask workflows avoid the use of thread-locals and don't modify data in-place.  This results in performance degredation, but we generally accept that loss for some of the other benefits, like being able to scale, being resilient to worker loss, etc..  There is a trade-off here.  Dask will never be as fast as something hand-tuned for a particular machine.

So in this situation I would probably suggest the "slow non-vaex way" and see how far one could get.

> Can a computation be cancelled, and it's progress be monitored?

Yes, you probably want to look at these docs: http://dask.pydata.org/en/latest/futures.html

> Also, is the API for the progress documented and/or stable?

I recommend looking at these docs for the two different task schedulers:

-  http://dask.pydata.org/en/latest/diagnostics.html
- http://distributed.readthedocs.io/en/latest/plugins.html

If you're just looking for visual feedback then you probably want the dashboard: http://distributed.readthedocs.io/en/latest/web.html

**Comment by maartenbreddels** [comment]
Thanks. Ok, I can live with this 'hack', since it will only run using a threaded scheduler, for the distributed part I need to probably take a different code path. However, it is possible to use the distributed schedular with threads only, so no pickling is happening? I'd like to use the dashboard indeed.

**Comment by TomAugspurger** [comment]
You can create a local cluster using only threads with

```python
client = Client(processes=False)
```

**Comment by maartenbreddels** [comment]
That still seems to pickle, also, it seems that compared to the non-distributed scheduler it will copy the data as well. I see memory usage doubling when using the distributed scheduler, is this expected?

**Comment by mrocklin** [comment]
Some things get serialized.  Some don't.  I would expect functions to be
serialized.  I would not expect data to be serialized.

**Comment by mrocklin** [comment]
Any further questions here or should we close?

**Comment by jakirkham** [comment]
Haven't seen these points come up in the discussion already so going to add them, but maybe they are not appropriate for some reason.

First have you looked at using Dask Arrays? Since you are mostly working with arrays it seems like this is a good option and should avoid rewriting many things with `dask.delayed`. In many cases the functions in `dask.array` are much better optimized than the equivalent hand rolled function. Expect that will improve the utility of the following suggestions as well.

Second have you looked at using [`persist`]( http://distributed.readthedocs.io/en/latest/api.html#distributed.client.Client.persist ) (possibly with [`replicate`]( http://distributed.readthedocs.io/en/latest/api.html#distributed.client.Client.replicate ))? This is a pretty good option if you want to compute and hold on to a result across many workers. Would only use `replicate` if you are fairly confident the data will fit in memory across all workers. Otherwise simply using `persist` would be fine.

Third if memory is a big problem and you still want to share the result across processes, instead of using `persist` you might want to try [`store(..., compute=True, return_stored=True)`]( http://dask.pydata.org/en/latest/array-api.html#dask.array.Array.store ), which is the equivalent of a spill to disk version of `persist`. Instead of keeping the array chunks in memory, it writes them to some store that provides a NumPy-like interface (e.g. [Zarr]( http://zarr.readthedocs.io/en/stable/ )). With the options provided above, computation and storage will occur immediately and a new Dask Array will be passed back with the information necessary to load the results from this store.

**Comment by mrocklin** [comment]
I think that this conversation has ended.  Closing.

**Comment by maartenbreddels** [comment]
That's ok, thanks for the feedback @mrocklin and @jakirkham !
