### ISSUE TITLE
Subsetting 2x throws error

### ISSUE THREAD

**Issue by joshua-gould** [dask/dask#3347]
I am unable to subset a 2-d array 2x (I realize I could re-code this to only subset 1x, but I don't understand why this doesn't work. I have real use cases where I need to do this). Thanks.
```
import dask.array as da
x = da.random.normal(10, 0.1, size=(200, 200), chunks=(10, 10))
indices = x.sum(axis=1) > 2000 
x = x[:, indices]
indices = x.std(axis=1) > 1040 
x = x[:, indices]
x.compute()
```
ValueError: ('Arrays chunk sizes are unknown: %s', {(nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan), (10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10)})

**Comment by mrocklin** [comment]
Arrays that have unknown chunk sizes do not support slicing.
http://dask.pydata.org/en/latest/array-creation.html#unknown-chunks

After your first slicing operation dask doesn't actually know how large
each chunk is, because this would depend on the values of the array, which
it hasn't touched yet.  Now that the chunk sizes are unknown, the second
operation fails.

However, in this particular case it should be possible because the arrays
have identical chunking.  If anyone has some time it would be nice to fix
this.

**Comment by jakirkham** [comment]
Have you considered using "logical and" to combine the two masks together before slicing or is that problematic for some reason?

**Comment by joshua-gould** [comment]
I can in this simple example, but I have other use cases where it's not so
straightforward. Thanks.
