### ISSUE TITLE
Add RandomState shuffle/permute

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#3409]
Would be great to have `RandomState`'s [`permutation`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.permutation.html#numpy.random.RandomState.permutation ) and [`shuffle`]( https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.RandomState.shuffle.html#numpy.random.RandomState.shuffle ) for Dask Arrays.

**Comment by mrocklin** [comment]
I agree that this might be useful.  It might also be hard to do well?

**Comment by jakirkham** [comment]
Definitely.

My naive thinking was we could randomize a range of numbers instead (should fit in memory) and use these to select out parts of the Dask object, which can be followed by concatenation. Though there are still weaknesses with this approach.

Any thoughts on this or other approaches?

**Comment by mrocklin** [comment]
The shuffle mechanism in dask.dataframe may be relevant.  It hierarchically
moves rows through different partitions in a few passes.  There are also
sorting networks like https://github.com/dask/dask/issues/3173

**Comment by jakirkham** [comment]
Starting with the Dask DataFrame approach is probably reasonable. Mainly interested in shuffling along one dimension of a multidimensional object. So that's probably close to the right behavior. It's pretty important that things within a chunk can be shuffled with things outside of the chunk (possibly even far away), which probably results in it being slow, but this constraint is unavoidable ATM.

**Comment by jakirkham** [comment]
So I've skimmed the Dask DataFrame shuffle code and have to admit there is a fair bit to digest. Ideally we would reuse this code for DataFrames and Arrays, but porting it seems to be a fairly large task. Any suggestions on where to begin (or if that is even the right approach)? Would it be possible to do this in pieces?

**Comment by jakirkham** [comment]
For now we have been using a randomized list of indices to shuffle the data. This seems to work ok, but it is not the best approach; especially, if this starts to behave poorly ( https://github.com/dask/dask/pull/3648 ). Suggestions on how to hook into the existing Dask DataFrame code to use with Dask Array with minimal effort would be very helpful.

**Comment by mrocklin** [comment]
> For now we have been using a randomized list of indices to shuffle the data

Just verifying that you're aware that this makes a single-chunked dask array.

> especially, if this starts to behave poorly ( #3648 )

They probably both work poorly, just in different ways.

> Suggestions on how to hook into the existing Dask DataFrame code to use with Dask Array with minimal effort would be very helpful

Agreed that this would be nice, but in general I think that the dask.array solution will probably look a bit different.  If you don't care about having reasonable chunk sizes then you could convert to dask.dataframe, set_index with a random value, and then convert back.

Otherwise I don't think that there is an easy way.  I think that someone would have to dive into this problem in order to do it well.

**Comment by jakirkham** [comment]
> > For now we have been using a randomized list of indices to shuffle the data
>
> Just verifying that you're aware that this makes a single-chunked dask array.

Yep, it's not great, but shuffling is not optional.

> > especially, if this starts to behave poorly ( #3648 )
>
> They probably both work poorly, just in different ways.

That's probably a fair assessment.

> > Suggestions on how to hook into the existing Dask DataFrame code to use with Dask Array with minimal effort would be very helpful
>
> Agreed that this would be nice, but in general I think that the dask.array solution will probably look a bit different. If you don't care about having reasonable chunk sizes then you could convert to dask.dataframe, set_index with a random value, and then convert back.

This sounds reasonable in the short term and probably better than what we are doing now. Will look into it.

> Otherwise I don't think that there is an easy way. I think that someone would have to dive into this problem in order to do it well.

Ok, that's fair. Then outlining your thoughts on the best way forward in this issue would be good. That way, I or someone else can pick this up if/when they have time and interest.

**Comment by mrocklin** [comment]
> Then outlining your thoughts on the best way forward in this issue would be good.

I'm not sure I'm able to outline things here.  This is a hard topic and one needs to understand it well to proceed.  I would look at what other systems do, both within dask and outside of it, and then lock yourself in a room with a pad of paper for a day.  That's how I tend to solve problems like this.

There are also sorting networks, and the term butterfly comes to mind, but I don't know mucha about these.  Whoever does this should start by learning a lot about the topic.

**Comment by jakirkham** [comment]
> For now we have been using a randomized list of indices to shuffle the data
> > Just verifying that you're aware that this makes a single-chunked dask array.

Should have added that we rechunk and select portions of indices from this list of indices. It's still suboptimal and needs work, but maybe not as badly as other things surprisingly.

**Comment by mrocklin** [comment]
@lmcinnes was interested in this for parallelizing nearest neighbor descent, a building block for umap and dbscan.  cc'ing him here just so that he is pinged when this issue is closed.

**Comment by mrocklin** [comment]
OK, so here is a simple-ish example of the problem, and I think a set of steps for someone to solve it.

Lets say that I have a dask array with some data.  It doesn't really matter what data is in it, but we'll use arange here just so we can get a sense of the results later if we want.

```python
import dask.array as da
x = da.arange(8, chunks=4)
```

And lets say that the user presents us with an index that, when it slices into this dask array, would produce a very heavily chunked result.

```python
index = np.array([6, 0, 4, 2, 7, 1, 5, 3])
x[index].chunks
# ((1, 1, 1, 1, 1, 1, 1, 1),)
```

Here for this small dataset this is alright, but in practice this will generate roughly as many chunks as there are rows in our data, which is likely far too large.

In code this happens here:

https://github.com/dask/dask/blob/master/dask/array/slicing.py#L566

If this occurs then I believe that we're better off block-sorting our index a bit.  Here we chunk our index into two pieces (the number of chunks in our original array) and then sort them independently.

```python
index2 = np.array([0, 2, 4, 6, 1, 3, 5, 7])
x[index2].chunks
# ((2, 2, 2, 2),)
```

This is more polite to the slicing code, but now we need to reorder our data again to get back to the original ordering.  

```python
index3 = np.array([3, 0, 2, 1, 7, 4, 6, 5])  # The location of the values of index in index2.  E.g. the first value of index, 6, is in location 3 in index2
index2[index3] == index
# array([ True,  True,  True,  True,  True,  True,  True,  True])

x[index2].rechunk(((4, 4),))[index3].chunks
# ((4, 4),)

(x[index] == x[index2].rechunk(((4, 4),))[index3]).all().compute()
True
```

We can measure the effectiveness of this transformation by looking at the number of tasks

```python
len(x[index].dask)
# 10
```

In this case they're actually the same, but my hope would be that this would improve significantly for larger chunks.  

I would implement this in the following way:

1.   In `slicing_plan` stop the normal plan if we end up producing more than, say, 4x the number of chunks of the input
2.  If that happens, then construct an `index2` and `index3` objects as above.  This may be tricky and require some thinking.  I did it manually above but hopefully there is some nice numpy trick to solve this problem.  Otherwise we'll have to use some sort of for loop or hash table.
3.  Call the index/rechunk/index computation appropriately

@jakirkham or @stsievert  you may find this problem interesting

**Comment by mrocklin** [comment]
This will still generate n-squared tasks if the index is entirely unaligned, but at least it isn't the full number of rows, which is an improvement.  Additionally, I suspect that this same approach will be useful for staged shuffling.

**Comment by mrocklin** [comment]
@jrbourbeau you might also find this task interesting.  It's moderately tricky and requires some looking at performance of the result.

**Comment by ahartikainen** [comment]
Sorting order

    arr = np...
    index = np.argsort(arr)
    index2 = np.argsort(index)

Not sure if there are faster way.
