### ISSUE TITLE
Issues running parallel computations in Jupyter Qtconsole?

### ISSUE THREAD

**Issue by demba** [dask/dask#3577]
Hi,

I use the Jupyter Qtconsole quite a bit for prototyping. It seems as though daskified code will not run in parallel in the Qtconsole but will in the IPython shell. Here's a simple example

```
import time
import dask.bag as db
from dask import compute

n = 2000

xlist = [i for i in range(n)]
xbag = db.from_sequence(xlist)

start_time = time.time()
results = xbag.map(lambda y: y**2).compute()
dur = time.time()-start_time
print(dur)
```
On my machine, the code runs roughly 4 times faster in the IPython shell. This is consistent with the fact that I have 4 cores on my laptop.

I used the `Profiler` from `dask.diagnostics` to verify that the code ran in he IPython shell does indeed use all 4 cores. The `Profiler' does not seem to work in the Qtconsole.

Python version: 3.6.2
dask version: 0.17.2

Thanks in advance for any pointers!

Demba.

**Comment by mrocklin** [comment]
Thanks for the issue @demba .   In principle the user interface of the IPython console or the QTConsole shouldn't affect the actual execution of Python code.  In the end they're just executing Python commands.  Most often when we see issues like this arise it's because people have different user environments that are pointed to different versions of Python.  

Can you verify that `sys.executable` is the same in each case?  Or is it possible that your IPython console is pointed to a different set of libraries than your QTConsole?

Also, for your example I would expect sequential operation to be faster than parallelism in any case.  Squaring 2000 numbers should be pretty trivial for Python to do.  The extra infrastructure of parallelism is more likely to cause more pain than benefit here.

**Comment by demba** [comment]
@mrocklin, thanks for the prompt response. `sys.executable` is the same in both cases.

You are right, sequential execution is faster in this simple case. The point of the example was to demonstrate a simple case for which I see a difference.

**Comment by mrocklin** [comment]
Well, I guess my general response is that if you do see an issue then it has more to do with QTConsole or IPython console.  Dask doesn't do anything special with either of them.  

I would be more concerned if the example where you saw a difference was on something larger.  The computation you provide would be more dominated by noise of other things going on, like the cost to fork a process, than Dask's actual execution.

**Comment by demba** [comment]
The example that prompted me to ask this question is a bigger one, where instead of the square function above, I am running some custom code. The sequential version of said example  takes 1 min to run, the daskified version take 1 min to run in the Qtconsole and 25 s in the IPython shell.

Just to be clear as to your response: you are suggesting that any overhead I am seeing comes from the Qtconsole, even in the larger example I mention above, yes? I am happy to share the code for that here but do not think it will add much to the discussion.

**Comment by mrocklin** [comment]
> Just to be clear as to your response: you are suggesting that any overhead I am seeing comes from the Qtconsole, even in the larger example I mention above, yes?

I do not know what causes the difference.  I suggest more experimentation.  

I am saying that neither Dask nor Python should behave any differently based on what program you use to interact with it.  QTConsole and the IPython console are just ways of interacting with Python.  In either case it's just Python underneath.  You might consider raising your issue on some other issue tracker, perhaps for qtconsole?

In your case I would try a few simple computations to try to isolate when the behavior changes.  You might, for example, try running some sleep computations instead.
