### ISSUE TITLE
Release Requirements for 0.18.0

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3592]
I would like to release 0.18.0 soonish.  This is a biggish release with several changes that will cause friction both for users and for downstream packages.  Here are a few that come to mind:

-  Deprecation of `get=` for `scheduler=`
-  Creation of the dask.config module and centralization of all downstream packages to use that module
-  ...

This will probably force a timed release for some downstream packages.  It would be good to get to a point where we can happily release a few things at the same time.

What blocking issues exist either in Dask or related packages that we need to prioritize to allow for this release?

**Comment by jakirkham** [comment]
Think we should start deprecating the `name` argument in `map_blocks` and warning users that `token` will be renamed to `name` in the future (1.0.0).

xref: https://github.com/dask/dask/issues/3226#issuecomment-396419864

**Comment by mrocklin** [comment]
That seems like a reasonable way to back us out of a jam.  Do you have any interest in submitting this?  I can probably find some time tomorrow if not.  My hope is that it won't take too long.

**Comment by mrocklin** [comment]
OK, looking at this now, I actually don't know the right way to gracefully perform this warning and degredation.  My first inclination was to warn for either keyword, but now there is no way for a user to get decent behavior and avoid the warning.  Thoughts?

I'm inclined to switch behavior for `name=` immediately, and warn on use of `token=`.

**Comment by jakirkham** [comment]
Sorry to be slow here today. Yeah, would be willing to help here.

Generally your proposal sounds fine. Treating `name` as a prefix for the name shouldn't break any existing use cases that assume it is used as the key/token. Warning that `token` will be dropped (when set) should be fine for obvious reasons.

FWIW looked through the xarray and hyperspy projects (as example downstream projects) to see where this might affect people. Interestingly did not see any uses of either (though plenty of usages of `map_blocks`). Of course this is only a sampling of users, but this does support making a breaking change should be ok.

**Comment by jakirkham** [comment]
Would it be possible to get this bug fix PR ( https://github.com/dask/dask/pull/3607 ) for `to_zarr` in? Given `to_zarr` hasn't yet shown up in a release, would be good to make sure we are happy with its behavior.

Ideally would like to get PR ( https://github.com/dask/dask/pull/3561 ) in as well as that seems generally agreed upon. Though if this PR doesn't make it, that would be ok.

**Comment by mrocklin** [comment]
OK.  If there are no objections then I plan to do a release tomorrow.

**Comment by jakirkham** [comment]
Copied from [Gitter]( https://gitter.im/dask/dev?at=5b219d7f8864a936cc8639e9 ):

Breaking changes

1. Replaced the get=dask.threaded.get keyword with scheduler='threading'
2. Centralized configuration, replaced
3. dask.set_options with dask.config.set
4. Dropped dask.array.learn
5. name= in map_blocks
6. worker_client automatically rejoins
7. dask.distributed protocol now interprets msgpack arrays as tuples rather than lists

Fun Changes

1. Orc Support
2. `__array_ufunc__` support for dask dataframe and series
3. einsum
4. Pandas 0.23.0 support
5. gufuncs
6. rechunk('auto')
7. QR decomposition improvements
8. Joblib
    1. simpler startup and global access
    2. keywords
    3. reference cycle
    4. Automatic scattering
13. Improved web presence, consistent styling on rtd
14. Serialization families, starting to make client secure to pickle

**Comment by jakirkham** [comment]
This looks like a pretty complete list.

Of the things since the 0.17.5 release, would add `to_zarr`/`from_zarr`.

**Comment by martindurant** [comment]
Also to/from_json, in that case?

**Comment by mrocklin** [comment]
Perhaps I should cut the orc section, and make a small section that lists
all of the new data ingestion formats supported.

**Comment by jakirkham** [comment]
The last blog post was for 0.17.2. Here are some things that would be good to add to a new blogpost since then (up to you of course). Does not including anything after 0.17.5.

* Dask Dataframe gets an `isna` method.
* Dask Array gets a `piecewise` function.
* Addition of `einsum` (know it's already there)
* Many improvements to `topk`/`argtopk`.
* Dask Array gets a `gradient` function.
* Significant performance improvements in Dask Array's slicing.
* Various bug fixes for `map_overlap`.

**Comment by mrocklin** [comment]
Typically I highlight a few changes that I think most dask users will find
interesting.  I link to our changelog for a more comprehensive list.  I
definitely don't plan on mentioning all of these.  Even the list I posted
before is a set of ideas that will eventually be culled into a few (3-5)
topics.

**Comment by mrocklin** [comment]
That being said, if someone wants to really dive into the changelog and
provide a lot of context on each change uniformly across changes then I
suspect that people would find that interesting to read.

**Comment by jakirkham** [comment]
So basically I just went through the changelog and if it something stuck out at me I listed it above. It's probably not worth diving into detail for all of them. Though I thought the blogs use to contain a list of miscellaneous other things that were notable. Many of these might fit there.

**Comment by jakirkham** [comment]
Thanks for getting this out, @mrocklin. 🎉 Good to close?
