### ISSUE TITLE
topk vs argtopk Performance

### ISSUE THREAD

**Issue by piercefreeman** [dask/dask#3596]
I've run some tests comparing the performance of `topk` vs `argtopk` and it seems like there's a significant difference despite a similar underlying codebase.

Sample script -
```
a = da.random.normal(size=(100000,100),chunks=(1000,100))
b = da.random.normal(size=(100,100000),chunks=(100,10000))

c = a.dot(b)

#top = c.topk(5, axis=-1)
top = c.argtopk(5, axis=-1)

with ProgressBar():
    da.compute(top)
```

When the above is executed with `topk` it completes in 1min 40sec.  When it runs with argtopk, it gets to 4% in 3min 40sec.  I interrupted this test early because a similar experiment took nearly 2 hours to complete - if growth is anywhere near linear, this one would complete in over an hour.

Is this a known issue with argtopk or anything we can do to optimize execution?

**Comment by mrocklin** [comment]
I don't know anything offhand without going back and reviewing the implementations (which is something you might consider as well).  Alternatively you might want to use the diagnostics to investigate what is taking up time.  The [diagnostics documentation](http://dask.pydata.org/en/latest/understanding-performance.html) might be helpful here.

**Comment by mrocklin** [comment]
Also @crusaderky might have thoughts on the performance here.

**Comment by crusaderky** [comment]
Ouch. The issue is caused by ``numpy.recarray`` creation and slice-by-label not releasing the GIL.
I did not notice in my production problem because I'm using argtopk at the end of a long series of other tasks that release the GIL - so that it's rare to get two of the problematic tasks together.

I'll tinker with it to see if I can find an alternative implementation.
