### ISSUE TITLE
Indexing error with boolean array

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3706]
This was reported to me in a side channel

```python
In [1]: import numpy as np

In [2]: import dask.array as da

In [3]: da.asarray(np.ones(1))[np.array([True], dtype=bool)]
   ...: 
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-486aaf80dd68> in <module>()
----> 1 da.asarray(np.ones(1))[np.array([True], dtype=bool)]

~/workspace/dask/dask/array/core.py in __getitem__(self, index)
   1326 
   1327         from .slicing import normalize_index, slice_with_dask_array
-> 1328         index2 = normalize_index(index, self.shape)
   1329 
   1330         if any(isinstance(i, Array) for i in index2):

~/workspace/dask/dask/array/slicing.py in normalize_index(idx, shape)
    781     for i, d in zip(idx, none_shape):
    782         if d is not None:
--> 783             check_index(i, d)
    784     idx = tuple(map(sanitize_index, idx))
    785     idx = tuple(map(normalize_slice, idx, none_shape))

~/workspace/dask/dask/array/slicing.py in check_index(ind, dimension)
    824         x = np.asanyarray(ind)
    825         if (x >= dimension).any() or (x < -dimension).any():
--> 826             raise IndexError("Index out of bounds %s" % dimension)
    827     elif isinstance(ind, slice):
    828         return

IndexError: Index out of bounds 1

In [4]: np.asarray(np.ones(1))[np.array([True], dtype=bool)]
   ...: 
   ...: 
Out[4]: array([1.])
```

**Comment by ZiyaoWei** [comment]
So I looked into this a bit and it seems fairly easy and the cause is actually in the stacktrace - the `check_index` function compares `x` which is the boolean array with the dimension which is a number, so the `x` array is treated as a 0/1 array. This caused the error above since `True` has integer value 1 which equals to the length of the array.

This bug also has another manifestation. Since dask just compares the elements to the array length it missed the constraint that the boolean indexing array should have length `dimension` (see ["Boolean arrays must be of the same shape as the initial dimensions of the array being indexed"](https://docs.scipy.org/doc/numpy/user/basics.indexing.html#boolean-or-mask-index-arrays). E.g.,

    >>> da.asarray(np.arange(5))[np.array([True, True], dtype=bool)].compute()
    array([0, 1])
    >>> np.asarray(np.arange(5))[np.array([True, True], dtype=bool)]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 2

This should be pretty easy to fix - I can send out a pull request this week if the above sounds reasonable.

**Comment by mrocklin** [comment]
A fix would be welcome

**Comment by ZiyaoWei** [comment]
This issue seems to be an exact duplicate of #3290 and any fix should resolve these at the same time.
