### ISSUE TITLE
argtopk broken with uneven chunks

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#3719]
```
>>> a = da.ones(9, chunks=((4, 5), ))
>>> a.argtopk(2)
ValueError: Shapes do not align {0: {2, 3}}
```

The cause of the error is trivial; just need to change https://github.com/dask/dask/blob/669cde6b1a02e5fc7f0bcb924489c6ae8e697323/dask/array/reductions.py#L904 
to ``chunks=(a.chunks[axis], )``.

What baffles me however is the underlying reason why this went undetected so far. Can anybody tell me if there is any good use case for why this should not raise ValueError?!?
```
>>> normalize_chunks((4, 5), shape=(9, ))
((4, 4, 1),)
```

**Comment by mrocklin** [comment]
I'm not sure if you're genuinely asking for a possible use case, or if you are instead asking what we should do.  

If you're genuinely asking for a use case, then I can imagine a novice user doing the following:

    x = da.ones(9, chunks=(4, 5))

and meaning to ask for an array of ones of size 9 with uneven chunks of size 4, and 5.   Answering your literal question, this seems like a good use case.  I can definitely imagine a novice user doing this and it might be nice to support them.

However, it looks like we currently don't support them in this, and instead just silently drop the second value, which clearly is incorrect.

It seems like we have at least two options here when encountering a tuple-of-ints of a different length than the shape:

1.  Check to see if the dimension is 1 and if the sum of the tuple is the same as the dimension, if so wrap it in an extra tuple, otherwise err
2.  Always err with an informative message pointing them to correct behavior

I don't have strong confidence on which is best.  My inclination is to go with 1 *if* no one can find cases where it's likely to cause trouble, and 2 otherwise.

**Comment by crusaderky** [comment]
@mrocklin I had your same thoughts. My adversity to the function trying to be too smart is that you would then need to decide an arbitrary, non obvious behaviour in case of ambiguity. For example, should ``normalize_chunks((4, 5), shape=(9, 9))`` return ((4, 5), (4, 5)) or ((4, 4, 1), (5, 4))?

**Comment by mrocklin** [comment]
Currently our policy when finding a chunks tuple-of-ints that is the same length as the shape is to broadcast the chunk value within each dimension, so `((4, 4, 1), (5, 4))`.  I think that this policy remains a good one and should not change.

I think that the currently undefined behavior we're seeing in this issue is limited to the case when the following hold:

1.  Chunks is a tuple-of-ints
2.  The length of chunks is greater than the length of shape
3.  The length of shape is 1
4.  The sum of chunks is equal to shape[0]

**Comment by crusaderky** [comment]
@mrocklin I implemented the algorithm you suggested in normalize_chunks
