### ISSUE TITLE
Should dask.delayed cull for optimization?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3735]
Currently `dask.Delayed.__dask_optimize__` is `dont_optimize`.  Do we want to add something simple, like `cull`?

**Comment by mrocklin** [comment]
I had to work around this here: https://github.com/dask/distributed/pull/2100

**Comment by mrocklin** [comment]
It looks like the local scheduler culls by default and the distributed scheduler doesn't.

**Comment by jakirkham** [comment]
Had the impression this was expensive hence why it was not optimized.

Interesting to hear the Distributed scheduler doesn't cull. Though not surprising in retrospect.

**Comment by mrocklin** [comment]
Yes, it is a bit of a cost.  Typically we suffer this cost in the
collection's optimizations.  That's not the case for delayed though, which
is the only collection that doesn't cull by default

**Comment by jakirkham** [comment]
If you have a chance to comment @jcrist, it would be good to hear your thoughts on optimizing delayed collections.

**Comment by jcrist** [comment]
Apologies for the delay here (I'm on vacation this week). If other collections cull, I don't see a reason why delayed shouldn't. However, since the local scheduler culls as well, this leads to work being done twice - it might be good to either remove the culling in the local scheduler (may break/slow down people using custom graphs), or add it to the distributed scheduler and remove it from the collections.

**Comment by mrocklin** [comment]
It's useful to cull before doing other optimizations, so keeping it in the
standard optimization suite for array/dataframe/bag is definitely a win.

I'm somewhat inclined to remove culling from the local scheduler

**Comment by jakirkham** [comment]
Agreed. For people using custom graphs, they know enough that they can add `cull`. We should just make sure to put this in the changelog so that people are aware they need to take this action.

**Comment by jcrist** [comment]
A PR to fix this is at #3856.
