### ISSUE TITLE
Restructure documentation using the Django four quadrant documentation style

### ISSUE THREAD

**Issue by itamarst** [dask/dask#3760]
Django documentation is deliberately structured into four kinds of documentation. For detailed explanations see https://www.divio.com/en/blog/documentation/ (well worth watching, or the PyCon talk: https://www.youtube.com/watch?v=azf6yzuJt54), but TL;DR version is:

1. Tutorial, learning-oriented. Get a complete beginner from zero to doing a small thing.
2. How-to, goal-oriented. Help a user achieve a goal.
3. Explanation, understanding-oriented. Explains how things work.
4. Reference, information-oriented. Things you look up.

All four are necessary, all four should be clearly separated because they're for different people at different times.

Current documentation:

1. Has no tutorial.
2. "Use cases" is combination of explanation and how-to.
3. Explanation and reference seem somewhat intermixed. This is problematic in that explanation is usually a thing people read upfront, and reference people want to use on the fly while coding.

**Comment by quasiben** [comment]
Thanks @itamarst !

since this was filed dask now has:
- https://examples.dask.org/ (with quick access to binder)
- http://stories.dask.org/en/latest/
- https://github.com/dask/dask-tutorial

Snapshot from https://docs.dask.org/en/latest/
<img width="206" alt="Screen Shot 2019-04-30 at 1 37 43 PM" src="https://user-images.githubusercontent.com/1403768/56981602-41141600-6b4d-11e9-936e-d4a8a5434b1a.png">
