### ISSUE TITLE
wrong dataframe size when using map partitions

### ISSUE THREAD

**Issue by dma092** [dask/dask#3834]
I have a dask dataframe that is on only one partition.
My problem is when I use map with the tou function, I don't find the shape of my original dataframe.
 I know this isn't the intended use of dataframes , but still I think it is worth to mention this issue.

```
from sklearn.datasets import load_iris
data=dd.from_pandas(pd.DataFrame(load_iris().target[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]]),npartitions=1)
out=data.map_partitions(f)


def f(x):
    print(x.shape)
    return x


```
I am using the 0.17.5 version .

**Comment by TomAugspurger** [comment]
When you don't specify a `meta` argument to `map_partitions`, the function is applied on a small bit of fake data. See http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions.

FYI, you might want to skim http://dask.pydata.org/en/latest/dataframe.html#design. As written, `f` would never print the full shape of your dataframe, since it's applied to each partition, not the entire dask dataframe.
