### ISSUE TITLE
Misbehaving reductions over arrays with empty chunks

### ISSUE THREAD

**Issue by dionhaefner** [dask/dask#3906]
Consider the following example:

```python
import numpy as np
import dask.array as da

a = da.from_array(np.array([0, 1, 2, 3]), chunks=1)
b = a[a != 0]
b.min().compute()
```

This raises

```
ValueError: zero-size array to reduction operation minimum which has no identity
```

because the first chunk of `b` is empty (due to the slicing operation). However, `min()` is obviously well-defined for this array.

Is there a way around this, e.g. by filtering empty chunks?

### Other ufuncs with similar behavior that I found

- `max` (same error)
- `std` (returns `nan`)

### Platform

- `dask==0.18.2`
- Python 3.6
- Windows 10 64-bit

**Comment by jakirkham** [comment]
Thanks for the report. This is a known issue.

xref: https://github.com/dask/dask/issues/2794

**Comment by dionhaefner** [comment]
In case anyone comes across this, one workaround is to use a masked array instead:

```python
import numpy as np
import dask.array as da

a = da.from_array(np.array([0, 1, 2, 3]), chunks=1)
b = da.ma.masked_equal(a, 0)
b.min().compute()
```

**Comment by mrocklin** [comment]
Thanks for the excellent bug report @dionhaefner 

So what are some ways to resolve this problem?

1.  We might include an identity value when we provide call `reduction` as in 

    ```python
        return reduction(a, chunk.min, chunk.min, axis=axis, keepdims=keepdims,
                     dtype=a.dtype, split_every=split_every, out=out,
                     identity=-math.inf)  # <<--- new
    ```
2.  This value might be included in the `chunk.min` definition itself
3.  If we notice empty chunks then we might call rechunk in order to remove them

In all cases we need to be sure that we raise properly if *all* chunks are empty.

@dionhaefner if you have any interest in diving into this problem that would be welcome.

**Comment by dionhaefner** [comment]
> @dionhaefner if you have any interest in diving into this problem that would be welcome.

I don't have the bandwidth at the moment, but if this is still an issue in a couple of months I might give it a shot.

**Comment by jakirkham** [comment]
As of NumPy 1.15.0, functions like [`amin`]( https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.amin.html ) support an `initial` value. Maybe adding support for this option would provide users one way of solving this problem.
