### ISSUE TITLE
Suggestion : Reading avro files

### ISSUE THREAD

**Issue by lijose** [dask/dask#3916]
I have avro files in S3 and I want to know is there any to read directly these files
 and create dask dataframe ??

**Comment by martindurant** [comment]
I would recommend https://github.com/ContinuumIO/intake-avro . You may not need the plugin or cataloguing capabilities of [Intake](https://intake.readthedocs.io/), but it does show how to load both very tabular data fast into dataframes (using uavro) or nested data (using fastavro) into bags. You could choose to use [uavro](https://github.com/martindurant/uavro/blob/master/uavro/core.py#L250) directly. These methods do accept S3 uris.

**Comment by martindurant** [comment]
@lijose , does either solution prove useful to you? Were you looking for something else?

**Comment by lijose** [comment]
I was looking for avro feature as default in dask  along with parquet or orc, that why raised a suggestion.
Sorry I did not use any of the suggested !!

**Comment by martindurant** [comment]
To be sure, parquet and orc also need additional packages to be installed for the functions within dask to work. The only difference for avro would be, that you need to call functions that are not in the dask namespace. They *could* be, but there has not been much impetus for that.

**Comment by ian-whitestone** [comment]
@martindurant would you be able to point me to some examples of using intake-avro to load a bunch of avro files into bags?

I've been playing with [dask_avro](https://github.com/rmax/dask-avro/blob/master/src/dask_avro/__init__.py) but there are some bugs when reading from S3 (will be opening an issue shortly), and I am finding it pretty slow because it has to read some metadata from each file. Would like to compare with other options if possible.

**Comment by ian-whitestone** [comment]
Disregard question above, for those interested, please see [here](https://github.com/ContinuumIO/intake-avro/issues/8), thanks @martindurant

**Comment by sandys** [comment]
hi @martindurant 
sorry to be pinging on a very old bug, but i wanted to check if dask is going to not support native reading of avro ?

the problem is that Google is now supporting only Avro in multiple usecases - for example bigquery export is CSV, json and avro. 

Given that dask has native support for reading GCS, it made a lot of sense for native support of google's supported export format (without a parquet alternative).

just checking.

**Comment by martindurant** [comment]
Perhaps you mean https://github.com/dask/dask/blob/master/dask/bag/avro.py#L68 ? This function appears to not have been correctly included in the auto-generated documentation.

A long-running issue exists to add avro reading to the dataframe too, which would essentially be the same code as referenced above, or you could look into [intake-avro](https://intake-avro.readthedocs.io/en/latest/?badge=latest)

**Comment by sandys** [comment]
Oh brilliant. I did not know read_avro was present !

Having this part of the default Dask infra is much more amazing than having
to do this via plugins.

Because we will be using this via the gcsfs system (especially for reading
bigquery dumps)
