### ISSUE TITLE
Replace examples in docs with dask-examples

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#3927]
Currently the [examples doc page](http://dask.pydata.org/en/latest/examples-tutorials.html) has links to old blogposts and gists.  We should consider replacing this with links to notebooks in dask-examples, possibly with binder links. 

@TomAugspurger you have some experience doing this for dask-ml.  Any suggestions?

**Comment by TomAugspurger** [comment]
I also opened https://github.com/dask/dask/issues/3921

I can get dask's doc build setup with something similar to dask-ml's.

**Comment by mrocklin** [comment]
@ceball was good enough to run [nbsite](https://github.com/pyviz/nbsite/) on dask-examples.  The results are hosted here: https://ceball.github.io/dask-examples/ .  Personally I like the styling.  

In a side-conversation he brought up the following small issues and comments.  The rest of this comment is a copy-paste of an e-mail from Chris.

### E-mail from Chris

You can see the result of trying nbsite at
https://ceball.github.io/dask-examples/. That's automatically
generated by travis when there's a commit to my fork of dask-examples.

The generated site might be enough to decide whether or not you want
to pursue using nbsite (no obligation just because I tried it out!).

There are a few issues.

One of the problems is that not all notebooks ran successfully. That's
not related to nbsite, but to me getting the dask examples environment
set up correctly. It didn't work for me out of the box (I think some
pip installing failed), so I modified the environment a bit, but still
a couple of notebooks didn't run. I didn't want to spend long on that
for now, so please just ignore any missing notebooks, or tracebacks in
notebooks, for the moment.

Other issues come about because of assumptions we made about projects
using nbsite. Basically, we made a number of decisions so that we
could handle multiple large collections of notebooks without going too
crazy. So to get a reasonable website, I made a couple of changes to
dask-examples:

* Titles. I renamed the notebooks, and removed the titles from the
start of notebooks. nbsite expects the notebook filename to specify
the notebook's title. E.g. My_Notebook.ipynb is given the title "My
Notebook" - and there's no title in the notebook itself. Part of the
reason for that is because - at least in the classic notebook - the
notebook's title is its filename. (But if you definitely want to have
a title in the notebook itself, make sure it's in the first cell on
its own, and pass --offset=1 to nbsite generate-rst. You can also
override the title nbsite generates from the filename by editing the
generated rst stub and then committing it.)

* Ordering. If a collection of notebooks should be ordered in a way
other than by python sort(), they should be named like
01_My_Notebook.ipynb, 02_Some_Other_Notebook.ipynb. I made an example
of that for the 'dataframes' section.

Apart from a couple of modifications to the dask-examples environment
so that I could install it on my laptop and travis (unrelated to
nbsite, mentioned above), that's all I changed about dask-examples.

There are some other things that would make for a nicer website:

* using bokeh instead of matplotlib

* going through the site and making it coherent (e.g. homepage
content, adding links between notebooks, etc).

* adding a logo (currently the default nbsite logo)

* modifying the theme to match dask

* removing redundant elements from theme (e.g. could remove footer)


Anyway, I could make one or more PRs on dask-examples for using
nbsite, if you think it's worthwhile. Also happy to receive feedback
about what should change in nbsite.

(In case you're interested, the diff showing what I did is here:
https://github.com/dask/dask-examples/compare/master...ceball:nbsite?expand=1.)

**Comment by mrocklin** [comment]
Also cc @jbednar

**Comment by mrocklin** [comment]
My personal thoughts:

1.  In general I really like having a static and executed view of the notebooks
2.  I like the code styling, and the fact that the finished result doesn't look like a notebook
3.  I would probably want to swap in our sphinx theme, `dask_sphinx_theme`, and see how things looked (and whether or not there are things we should steal for our sphinx theme generally :))
4.  I would want to include "Run Live" or "Try Now" buttons somewhere that point to Binder (our current use for this repository)
5.  It would be good to compare against other "execute my notebooks and generate static HTML" frameworks.  @TomAugspurger probably has thoughts here.  My (completely uneducated) guess is that they won't look as nice, but will be more stable.

@TomAugspurger I'd be curious to hear your thoughts on all of this

**Comment by jbednar** [comment]
> Personally I like the styling.

 You are much more generous than we are!  None of us actually like the default styling, but we haven't yet set it up to have something we'd be happier with as a default.  https://hvplot.pyviz.org/  is a better example of something close to the look and feel that we like these sites to have, which doesn't take much customization -- just put in the logo, pick a theme color and an accent color (usually something matching the logo), and then use the resulting customized CSS file instead of the default.  So when evaluating this option, please think of the overall styling as more like the hvplot site than like the current draft of this dask material.

> It would be good to compare against other "execute my notebooks and generate static HTML" frameworks. @TomAugspurger probably has thoughts here. My (completely uneducated) guess is that they won't look as nice, but will be more stable.

I think that's a fair summary.  nbsite and the affiliated projects will definitely see a lot of churn before they settle down, but what will churn is the process of maintaining the site and how it's automated; the actual content you create in notebooks won't need to be updated as that happens.  So, you can use the current version, tweak the styling as suggested above, then as the remaining pieces fall painfully into place, what happens is that your experience as site maintainer changes.  What's kept me sane through this far-too-extended process is just to focus on the content of the notebooks, which I maintain entirely independently of the management of the site.  So, I think that's what you can expect here -- we'll tighten up how everything works, but the fundamental basis of the site is and will continue to be just a collection of notebooks.

For what it's worth, I didn't find any other framework where the notebooks were treated as the archival reference; instead sites like scikit-image looked great, but underlying it it was .rst that was the master, and notebooks were only generated from that, which was not how I wanted to manage things.  Other sites render notebooks, but not by treating them as source code for a website as nbsite does, so those approaches set up a tension between "notebook" material and true docs.  So we wished we could have not had to write any of this, but I really wanted to maintain notebooks as the one true source for examples, docs, and output tests, so here we are...

**Comment by ceball** [comment]
> > I would want to include "Run Live" or "Try Now" buttons somewhere that point to Binder (our current use for this repository)
>
> I agree this would be nice. The two easiest ways I see are including that link in the notebook itself (which isn't great). Or a bit of javascript.

nbsite currently (optionally) inserts a link to download the notebook from github:

<img width="741" alt="screen shot 2018-09-10 at 4 04 22 pm" src="https://user-images.githubusercontent.com/1929/45306009-79f67080-b513-11e8-83d5-cd0210d29fc1.png">

The plan is for nbsite to also optionally insert a link to run the notebook (e.g.
https://mybinder.org/v2/gh/dask/dask-examples/master?filepath=machine-learning%2Fincremental.ipynb )...it's just that - despite being very enthusiastic about mybinder - we haven't quite managed to get our own things running smoothly enough on mybinder yet (or we found mybinder not quite reliable enough when we last tried).

**Comment by ceball** [comment]
> Without having looked too closely at nbsite, it seems like nbsite is indented to be standalone, while nbsphinx is intended to be part of a larger documentation build, is that correct?

I think there's no reason it couldn't work as part of a larger sphinx documentation build. Once the rst is generated, it's just a sphinx-build command to run the notebooks and get html. However, yes, we use nbsite as a standalone tool, and to do otherwise would require us to integrate of a couple of small commands with sphinx.

**Comment by mrocklin** [comment]
I ended up going with nbsphinx.  Results are at https://examples.dask.org , which is now integrated in with our documentation generally.  Closing.
