### ISSUE TITLE
Realtime profile visualization

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#395]
@jcrist 's [recent work on profiling](https://github.com/ContinuumIO/dask/pull/363) is nice because it allows us to inspect a completed computation of very may tasks after the fact.

For long running graphs it might be pleasant to view this graph *during computation*, using the Bokeh server to update the graph as tasks complete.

Once we have realtime plots we might also consider progress bars for frequently occurring task keys.  E.g. if we have many tasks that follow our tuple conventions like `('load-data', 0), ('load-data', 1), ...` then we might create a progress bar for `load-data` to show the progress of classes of tasks.

cc @ogrisel

**Comment by jcrist** [comment]
"Realtime" profiling has turned out to be mildly problematic, in that we can't get the worker that ran the task until after the task completes (limitation of the thread/process pools). It could be plotted in a lagged version, but for long running tasks this would look odd. I'm also not sure how much value this brings.

The per-task-type progress bars could easily be done though.

**Comment by mrocklin** [comment]
Lagging sounds good to me.  The real objective here is to give insight to people with long-running computations.  Perhaps we should find one of those people first.  The project that @cowlicks is working on right now might be a good example.  Also @shoyer might have some long running computations; we could ask him what he would like to see.

**Comment by shoyer** [comment]
I'll give this a try today along with the progress bar. I have a long running task I'm running for which some transparency would be helpful.

**Comment by mrocklin** [comment]
This has been done in the distributed scheduler.  Closing.
