### ISSUE TITLE
`dask.config.set(num_workers=n)` context doesn't seem to work anymore

### ISSUE THREAD

**Issue by david-hoffman** [dask/dask#4082]
I don't know how to make a self contained example, but suffice to say that if I try something like

```python
with dask.config.set(num_workers=2):
    # code the does something
```

All cores start firing, not just 2.

```
%watermark -v -m -p dask
CPython 3.6.6
IPython 7.0.1

dask 0.19.3

compiler   : MSC v.1900 64 bit (AMD64)
system     : Windows
release    : 10
machine    : AMD64
processor  : Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
CPU cores  : 48
interpreter: 64bit
```

**Comment by jrbourbeau** [comment]
Thanks for the issue report @david-hoffman. I think I am able to reproduce this using

```python
import dask
import dask.array as da
from dask.diagnostics import visualize, Profiler

a = da.random.randint(0, 100, size=100_000, chunks=1_000)

with dask.config.set(num_workers=2) as _, Profiler() as prof:
    a.compute()
    visualize([prof])
```

The visualizing the `Profiler` yields

<img width="825" alt="screen shot 2018-10-11 at 6 26 48 pm" src="https://user-images.githubusercontent.com/11656932/46839426-7577de80-cd83-11e8-9785-91e34f715c53.png">

So it looks like the `compute()` call is being executed with 4 workers instead of 2. 

cc @mrocklin
