### ISSUE TITLE
TypeError: split() got an unexpected keyword argument 'expand' | string split function doesn't work [TypeError] | dask 0.20

### ISSUE THREAD

**Issue by ZiyadMoraished** [dask/dask#4179]
Hi,

I'm trying to split a column by space as follows:
` df.CUSTOMER.str.split(expand=True)`

here is the error I get:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-07645d325084> in <module>()
----> 1 df.CUSTOMER.str.split(expand=True).head()

TypeError: split() got an unexpected keyword argument 'expand'
```

when I perform it on the top 5 records, it works perfectly.
` df.head().CUSTOMER.str.split(expand=True)`

i'm using python 3.6 and dask 0.20

**Comment by mrocklin** [comment]
Perhaps your pandas version is too old?  Otherwise I don't know what might
be wrong.  I recommend providing a minimal failing example.

**Comment by ZiyadMoraished** [comment]
pandas version is 0.23.4

here is a quick failing example:

```
dask_df = dd.from_pandas(pd.DataFrame({'name' :['Ziyad Moraished']*1000000 }), npartitions= 10000)

dask_df['name'].str.split(' ', exapnd=True)

TypeError                                 Traceback (most recent call last)
<ipython-input-22-2833952eac0a> in <module>()
----> 1 dask_df['name'].str.split(' ', exapnd=True)

TypeError: split() got an unexpected keyword argument 'exapnd'
```

**Comment by mrocklin** [comment]
Reproduced.  Thank you @ZiyadMoraished .  

At first it looked like we could just pass through the `expand=` keyword from our version to Pandas' (though we would want to verify that this works well on previous pandas versions as well).  However when I tried this it looked like we weren't getting the metadata correct.  Presumably we don't correctly infer that this produces a dataframe rather than a series.  

If you start diving in from here:

https://github.com/dask/dask/blob/113457b692034d8a15f521a33be88a1183bcfae0/dask/dataframe/accessor.py#L119-L120

You'll eventually get to here:

https://github.com/dask/dask/blob/113457b692034d8a15f521a33be88a1183bcfae0/dask/dataframe/accessor.py#L61-L62

Which should be a dataframe with a few text columns, but seems not to be.

If anyone wants to investigate this further that would be welcome.

**Comment by nixphix** [comment]
@mrocklin after adding `expand` arg to split function it failed meta data check here
https://github.com/dask/dask/blob/113457b692034d8a15f521a33be88a1183bcfae0/dask/dataframe/core.py#L3691-L3694

**Comment by mrocklin** [comment]
What are the differences between `meta.columns` and `df.columns` (arguably this should also be in the exception).  I wonder if that information would direct you to the fix.

**Comment by nixphix** [comment]
**meta.column** is `RangeIndex(start=0, stop=1, step=1)` where as **df.column**  is `RangeIndex(start=0, stop=2, step=1)`

**Comment by nixphix** [comment]
@mrocklin we could make num splits parameter mandatory if expansion is required, that way we can be sure. Let me know what your thinking.

**Comment by jakirkham** [comment]
@TomAugspurger, do you have thoughts on this issue?

**Comment by mrocklin** [comment]
Fixed in https://github.com/dask/dask/pull/4744
