### ISSUE TITLE
Should we pin distributed in the dask conda package?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4257]
We currently have a few `dask` related conda packages.  There is `dask-core` which includes the main dask codebase, `distributed` which includes the distributed scheduler, and `dask`, which is a metapackage that includes `dask-core`, `distributed`, and also a variety of dependencies for commonly desired functionality like `numpy`, `pandas`, and `bokeh` for dask array, dask dataframe, and the dashboard respectively.   

In https://github.com/conda-forge/dask-feedstock/pull/56 @jakirkham and I had a conversation about which versions of these libraries we should pin.  We're in agreement that `dask=1.2.3` should pin `dask-core=1.2.3` but we're unsure if we should also pin the `distributed` library to the version co-released with dask, or if we should allow `distributed` to float to any known compatible version.

-  Reasons to support pinning: the goal of the metapackage is to provide a smooth experience for dask users.  We should be able to tell them to just `conda install dask` and get the most recent least-buggy software.  Otherwise we'll need to tell novice users to `conda install dask distributed ...`, which can be confusing for them.  We used to have several bug reports for already-fixed-bugs before we started doing this.
-  Reasons to avoid pinning: we should stay consistent to the information in the dask package's `setup.py` file, which currently only lists strict version requirements.  Having a mismatch between these two sets of informations may be confusing for users.  It may also provide a different install experience depending on if you're using pip or conda, which may also be confusing.

(@jakirkham please let me know if I've missed anything above)

So the operational question is "should we require recent versions of the `distributed` package in the `dask` conda metapackage?"

**Comment by jcrist** [comment]
I think we should set a minimum distributed version in the dask conda metapackage, mirroring that in dask's setup.py (no change in what we're currently doing). This argument:

> Having a mismatch between these two sets of informations may be confusing for users. It may also provide a different install experience depending on if you're using pip or conda, which may also be confusing.

seems strong to me, and I don't think having users manually upgrade distributed to fix bugs is too much to ask.

**Comment by mrocklin** [comment]
So I've interacted with many people that have said "I know that this was
fixed recently, so I conda installed dask but the problem persists".

I've never interacted with someone who said "wait, why is the version in
the dask metapackage different from the version in setup.py?"

If we're optimizing for minimizing user issues then I think that keeping
distributed recent in the dask metapackage is better.

**Comment by mrocklin** [comment]
> In this case, we should only update the dask metapackage when we release dask

Well, we could increment the build number, but you're right that in practice we don't.

> Perhaps we should bump the version of distributed to distributed>=current_distributed_release when we release dask

Sorry, I should have been clear, this is what we do currently (at least whenever I do the release).

> I'm wary of exact pinnings, but minimal pinnings seem probably fine.

I agree with this.

**Comment by jcrist** [comment]
I'm suggesting that we don't change anything from our current practice. My main fear here is overspecifying users environments.

Say we release dask 10 and pin it to most recent distributed version 11 (imaginary versions for sake of argument). If there's a bug in distributed 11, *and* a bug in dask 9, then a user affected by both of these has no options for a satisfiable environment - they can't downgrade to distributed 10, because that would force them to downgrade to dask 9. With bugfix releases, etc... I could certainly see this becoming an issue for users if we're pinning in our setup.py.

The metapackage doesn't prevent users from individually specifying dask-core/distributed versions, but I'm not sure if we should have conda and pypi diverge in requirements (although they already have, since `dask` and `dask[all]` aren't exactly the same.

Instead, I think we should continue with our current practice, but *maybe* be more proactive about bumping the minimum viable version of distributed (if we're not already doing so). I know Matt said he already does this, but I'm not sure how far back we go for compatibility. Preventing user environment flexibility in the case of bugs in different versions seems too much of a price to pay just to minimize already resolved bug reports.

**Comment by jrbourbeau** [comment]
We started pinning `dask` and `distributed` releases more tightly starting with the `2021.05.0` release (see https://github.com/dask/community/issues/150 and https://github.com/dask/community/issues/155 for context around this decision). Over the past three months there haven't been any complaints about this (that I'm aware of) and the number of new version incompatibility issues reported in the `dask` and `distributed` issue trackers have dropped to zero. Because of this, I'm going to close this issue. We can always reopen if others would like to continue this conversation.
