### ISSUE TITLE
Autosummary links missing in array API page

### ISSUE THREAD

**Issue by djhoese** [dask/dask#4259]
This is in reference to #4258. There are some dask array methods/functions that aren't properly linked in the array api page via the autosummary section. I was able to fix a few in #4258, but I there are some other ones that I couldn't figure out. This could possibly be a bug in autosummary and I don't see any warning messages for this when building the docs (there are a lot of other indentation and similar errors for various docstrings).

- [ ] random.choice: Even though this is not included for versions of numpy<1.7, it still isn't linked with numpy 1.15
- [ ] linalg.sfqr
- [ ] overlap.trim_internal
- [ ] overlap.trim_overlap

**Comment by jrbourbeau** [comment]
Thanks for opening up this issue @djhoese! I think the issues with these methods/functions not being properly linked is because they are present in in `autosummary` section of `array-api.rst`

https://github.com/dask/dask/blame/master/docs/source/array-api.rst#L321-L325

but don't have a corresponding `autofunction` later in `array-api.rst`

https://github.com/dask/dask/blame/master/docs/source/array-api.rst#L590-L591

**Comment by jrbourbeau** [comment]
Fixed in #4282
