### ISSUE TITLE
visualize not working on dict items

### ISSUE THREAD

**Issue by Ariel-Lieberman** [dask/dask#4288]
The following outputs graph where nodes (boxes) are with no labels.  (Version 1.0.0)  
no method name in operations (circles)

```
  dskx = {'a': 1, 'b': 2, 'c': (add, 'a', 'b')}
  dask.visualize(dskx, filename='graph2.png')
```

![graph2](https://user-images.githubusercontent.com/1833400/49809022-8c788400-fd66-11e8-9def-8669aa6a4415.png)

**Comment by jcrist** [comment]
In dask 1.0.0 we redid how graph visualization is done (https://github.com/dask/dask/issues/4146).

Since:
- Most graphs use descriptive key names (e.g. dask collections create dask's with informative key names by default)
- Many tasks have nested functions (e.g. `(add, (mul, 'x', 1), 'y')`), especially after graph optimization - displaying only the top-level function name was misleading
- Often the task and key names were redundant, making for a busier visualization
- By reducing the amount of text, graphviz can make smaller nodes, allowing for a more condensed representation of the graph

That said, if you have a better idea for how things should be visualized, we'd welcome your input.

**Comment by trankmichael** [comment]
Ah I see I see. Thank you for the response.

**Comment by Ariel-Lieberman** [comment]
OK. Are there any instructions/examples how to build more informative key names? tasks?   (For us who build custom graphs.)   

BTW, the examples in the documentation would need fixing.

**Comment by Juanlu001** [comment]
I think the optimization example in the docs got outdated after https://github.com/dask/dask/pull/4160:

https://docs.dask.org/en/latest/optimize.html#example

**Comment by TomAugspurger** [comment]
@Juanlu001 that sounds correct. We can fix this somewhat but including the literal values in the keynames,

```python
from __future__ import print_function
dsk = {'words': 'apple orange apple pear orange pear pear',
       'nwords': (len, (str.split, 'words')),
       ('val', 'orange'): 'orange',
       ('val', 'apple'): 'apple',
       ('val', 'pear'): 'pear',
       'count1': (str.count, 'words', ('val', 'orange')),
       'count2': (str.count, 'words', ('val', 'apple')),
       'count3': (str.count, 'words', ('val', 'pear')),
       'out1': (format_str, 'count1', ('val', 'orange'), 'nwords'),
       'out2': (format_str, 'count2', ('val', 'apple'), 'nwords'),
       'out3': (format_str, 'count3', ('val', 'pear'), 'nwords'),
       'print1': (print_and_return, 'out1'),
       'print2': (print_and_return, 'out2'),
       'print3': (print_and_return, 'out3')}

dask.visualize(dsk)
``` 
which produces

![mydask](https://user-images.githubusercontent.com/1312546/70919562-adf9f480-1fe6-11ea-8f0f-76581bb3ab38.png)

Could probably do a bit more, though I worry about making the dask graph too complicated. What do you think?

**Comment by Juanlu001** [comment]
Thanks @TomAugspurger - it's the empty rectangles for custom graphs what bothers me, but it's not a big deal and I only was going through an old notebook and updating it. It's probably more valuable to show real world graphs.
