### ISSUE TITLE
Feature Request: add observed- keyword to groupby

### ISSUE THREAD

**Issue by jmunar** [dask/dask#4371]
Hi, dask developers! Thank you for this very nice package, I have been using extensively for a while.

I am missing Pandas keyword observed for groupby with categorical variables. Without it, the memory used by my processes is huge, as groupby by default creates all possible tuples of categories, no matter whether they are found in the dataset.

Minimal example of the expected behavior:

```
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame({
    'c1': pd.Categorical(['v11', 'v12', 'v11'], ['v11', 'v12', 'v13']),
    'c2': pd.Categorical(['v21', 'v22', 'v23']),
    'c3': [1, 4, 7]})

ddf = dd.from_pandas(df, npartitions=1)
ddf.groupby(['c1', 'c2'], observed=True).sum().compute()
```

Desired output:

c1 | c2 | c3
-- | -- | --
v11 | v21 | 1
v11 | v23 | 7
v12 | v22 | 4

**Comment by jmunar** [comment]
I am working on implementing it, will keep you posted

**Comment by jmunar** [comment]
Implemented in #4383

**Comment by OliverHofkens** [comment]
I recently tried to implement `observed` support in my Dask branch here: https://github.com/OliverHofkens/dask/tree/feature/groupby-observed-categoricals 

This wasn't too much work, just storing `observed` and passing it as argument to the `GroupBy._aca_agg` functions got a lot of it working. However, some test cases in this parametrized test case failed: https://github.com/OliverHofkens/dask/blob/b9feeb254e18c88ca9d5ab34143049d4a53e6d85/dask/dataframe/tests/test_groupby.py#L2291-L2323

Not because of Dask, but because of a wide variety of categorical/groupby related bugs in the underlying Pandas code. Mainly:
- Cases where Pandas coerces categoricals to object when setting it as an index.
- Cases where Pandas drops categorical columns when aggregating with `observed=False`. (Here, Dask actually does the right thing, but the test fails because we compare with Pandas behavior)

Once those issues are fixed in Pandas, I will gladly submit a PR with `observed` support.

**Comment by MatteoSchiavinato** [comment]
Any news on the development of `observed`?

**Comment by TomAugspurger** [comment]
Doesn't look like it. All the discussion happens here on github.

Are you interested in working on this @MatteoSchiavinato?

**Comment by TomAugspurger** [comment]
Perhaps @OliverHofkens can share if any of the underlying issues in pandas have been fixed.

**Comment by MatteoSchiavinato** [comment]
@TomAugspurger I don't think I have the necessary knowledge! I solved my error with a workaround so for now I don't need it.

**Comment by OliverHofkens** [comment]
Hey, thanks for reminding me about this! I fast-forwarded my branch and the test still fail, but on something different than before. 
Once I find some time I'll see if we can finish this feature!

**Comment by maximz** [comment]
Just wanted to bump this thread and express further interest in support for `observed=True`. The current behavior — expansion of my groupby index to the Cartesian product of all possible categorical values — causes RAM issues and poor performance for me. Thanks!

**Comment by melvinev** [comment]
Bumping also, thank you!

**Comment by lorenh516** [comment]
Bumping as well, this would be an extremely helpful feature.

**Comment by TomAugspurger** [comment]
Just an FYI, the pandas behavior is potentially changing, which would make this more important to implement: https://github.com/pandas-dev/pandas/pull/35967

In the future pandas will require this keyword when grouping by one or more categoricals.

**Comment by jsignell** [comment]
I can take on wrapping up the work that @OliverHofkens started. I'll open a PR shortly.
