### ISSUE TITLE
No error when calling dask.visualise

### ISSUE THREAD

**Issue by CMCDragonkai** [dask/dask#4435]
I have `graphviz` and python `graphviz`. When calling `z.visualise(filename='test.svg')`, nothing happens. No error, no exceptions and no file.

```
from time import sleep

def inc(x):
    sleep(1)
    return x + 1

def add(x, y):
    sleep(1)
    return x + y

from dask import delayed

x = delayed(inc)(1)
y = delayed(inc)(2)
z = delayed(add)(x, y)

z.visualise(filename='test.svg')
```

How are you meant to debug this?

**Comment by TomAugspurger** [comment]
That's an unfortunate side-effect of the dask developers being primarily biased Americans :) It should be `visualize` with a `z`.

I'm not sure whether we should alias `visualise` to `visualize`. Thoughts @jcrist?

**Comment by sadielbartholomew** [comment]
Hi Dask team, I realise this issue is marked as closed, but having read through the brief conversation here I was wondering if you would indeed consider aliasing `visualise` to `visualize` as @TomAugspurger asked above?

I raise this because as well as the original poster, I (also a British English speaker) too ran into this when following along with the official tutorial (in `01_dask.delayed.ipynb`) and spent ~15 minutes trying to work out why I was getting a `delayed` object rather than the graph. I suspect yet more people could end up being unnecessarily confused on this for the same reason, especially when the result of some spelling variant or typo on the method returning a valid object and not an error making one such as I suspect and try to fix some environment issue (e.g. not having graphviz or some facet of the notebook set up correctly to show the image, etc.) initially, rather than realise the, ultimately obvious, cause!

Having checked through your Issue Tracker for similar requests, I see that in #5944 you specify you aren't keen on method name aliases in general, and that's understandable, but think `visualise` could be a good exception due to the motivation of the very common spelling variant? I guess it could be the only spelling-variant alias required for `delayed` at least as e.g. `delayed(lambda a: a + 1)(1).__dir__()` only gives four other non-internal methods ('compute', 'dask', 'key', 'persist'), all with the one spelling.

Alternatively, for us Brit English users, could you perhaps create a log warning or similar for when `visualise` is called, e.g. 'Did you mean visualize?' or consider adding a a 'tip' or 'note' to the documentation and/or tutorial to point out that only the American spelling will work, else we'll be setting up deferred attribute access, possibly inadvertently?

Thanks for (re-)considering this!

**Comment by TomAugspurger** [comment]
I'm fine with aliasing visualise if other maintainers are on board. I think I'd prefer that to emitting a warning.

**Comment by jrbourbeau** [comment]
Thanks for poking this issue @sadielbartholomew! I think today we should raise an informative warning

https://github.com/dask/dask/blob/95fb60a31a87c6b94b01ed75ab6533fa04d51f19/dask/delayed.py#L544-L552

What version of `dask` are you using?

**Comment by jrbourbeau** [comment]
For example, this is what I see on the current `main` branch 

```python
In [1]: from dask import delayed

In [2]: @delayed
   ...: def foo():
   ...:     return "bar"
   ...:

In [3]: result = foo()

In [4]: result.visualize()
Out[4]: <IPython.core.display.Image object>

In [5]: result.visualise()
/Users/james/projects/dask/dask/dask/delayed.py:547: UserWarning: dask.delayed objects have no `visualise` method. Perhaps you meant `visualize`?
  warnings.warn(
Out[5]: Delayed('visualise-64663e0d-7fa9-4049-88bb-f10d9c1b0e81')
```

**Comment by sadielbartholomew** [comment]
Thanks Tom and James for the extremely quick replies.

Ah, so there already is a warning, that's really useful! Sorry for not checking the current `main` branch which I should probably have done before commenting. I was using the environment that is provided for binder for the tutorial from the `dask-tutorial` repo, which is `'2.20.0'` (from `dask.__version__`) as backed up by [the environment file](https://github.com/dask/dask-tutorial/blob/114084c323665d1faadc23979beb7451fe1edd64/binder/environment.yml#L13). I assumed that would be pretty up-to-date.

I think the warning demonstrated is definitely sufficient, so I guess the alias isn't strictly necessary given it, though certainly if the alias was added it would be helpful in that some of us wouldn't need to go in and change the `s` to `z` a lot of the time from typing intuitively :smiley: We could always define that alias simply in our scripts locally etc., I guess.

Thanks again, I'm sure I'll catch the warning in the wild when the next release is out and I update!

**Comment by sadielbartholomew** [comment]
Oh wait, just re-reading and seeing that you are probably proposing that for `main`, not that it is already there as I assumed? Either way, that exact warning looks great to me.

**Comment by jrbourbeau** [comment]
https://github.com/dask/dask/pull/6216 is where the `visualise` warning was added, which should be included in the `dask==2.17.0` release. When I launch a binder session from the Dask tutorial I see the warning when I use `visualise` instead of `visualize`:

<img width="1552" alt="Screen Shot 2021-08-16 at 4 08 43 PM" src="https://user-images.githubusercontent.com/11656932/129629919-cc8f78fe-4efc-4b3f-aca4-81d53793d854.png">

Do you see something different? Could you confirm that `visualise` is spelled correctly?

**Comment by sadielbartholomew** [comment]
Interesting, I didn't see that (or any) warning before, no. I was using the binder environment but not actually on Binder, just running the Jupyter Notebooks of the tutorial repo locally.

Strangely, I have just re-run the original Notebook I was working with and still had open, and this warning did indeed pop up, much to my surprise! So it is implemented as you indicated and does emerge, however if I re-run the cell any number of times, it doesn't seem to be shown again, only the once on first run. So I suspect in my case, in coding up some lines as part of the tutorial the warning got hidden by the cell having been run before with different code, or maybe it did show and I missed it completely (given it is marked strikingly in red the former is most likely I think).

So, it looks like the warning is indeed already there and working fine - my bad, sorry about that! As for the warning disappearing in the Notebook, I guess that's a Jupyter and not a Dask issue and there's probably a good reason for warnings behaving that way. Assuming people re-run their Notebook afresh they should see the warning about `visualise` should they try it :)

Thanks @jrbourbeau, case (already) closed I think!

**Comment by jrbourbeau** [comment]
Good to know. Thank you for following up. The warning is disappearing because, by default, Python will not repeat the same warning multiple times if it's coming from the same source location. From the [`warning` module docs](https://docs.python.org/3/library/warnings.html):

>  Repetitions of a particular warning for the same source location are typically suppressed.

I'm going to close this issue, but thank you for engaging here. I had forgotten that we raised this warning, so it was good to be reminded.
