### ISSUE TITLE
ORC Reader and Writer API

### ISSUE THREAD

**Issue by kkraus14** [dask/dask#4468]
cc @mrocklin 

Currently it looks like the ORC reader directly talks to PyArrow and converts the resulting PyArrow table into a Pandas dataframe. I've opened a discussion on pandas about defining what the ORC reader / writer APIs would like like for Pandas: https://github.com/pandas-dev/pandas/issues/25229. Unsure if dask.dataframe would want to continue using PyArrow directly or would rather consume a Pandas provided function, but figured it would be in the best interest to start a discussion and make this visible.

**Comment by martindurant** [comment]
cc @jcrist (who did the ORC work)

**Comment by mrocklin** [comment]
I think that it would be preferable to consume the Pandas API directly, if it does everything that we need.  I suspect that we may need slightly more than is exposed through the Pandas API.  For example for Parquet we need to inspect the metadata files a bit, gather row group statistics, and more in order to get a sense for which partitions to keep, which columns are sorted, and so on.

**Comment by mrocklin** [comment]
Any further comments here?

**Comment by martindurant** [comment]
Given that the pandas issue has gone stale, I am closing this until such a time that pandas implements the proposed API, so we can use it directly.
