### ISSUE TITLE
A future version of pandas will default to `skipna=True`

### ISSUE THREAD

**Issue by jimfulton** [dask/dask#4527]
When calling to_parquet, I get this warning:

```
/home/INTERNAL/c97346/.conda/envs/dask/lib/python3.5/site-packages/fastparquet/util.py:221: FutureWarning: A future version of pandas will default to `skipna=True`. To silence this warning, pass `skipna=True|False` explicitly.
  inferred_dtype = infer_dtype(column)
```

But I can't pass skipna to to_parquet.  

It looks like dask should pass False or let me pass a value.

**Comment by TomAugspurger** [comment]
I believe this is fixed in fastparquet master, https://github.com/dask/fastparquet/pull/396/files. Not sure when a release is planned (cc @martindurant)

**Comment by martindurant** [comment]
Whenever I get around to it? :)

**Comment by MichaelSchroter** [comment]
Hi @jimfulton,  @TomAugspurger, @mrocklin 

I got the same with `fastparquet` in a new minimal virtual enviroment (only `dask,` `dask[complete]` and `dask-ml` installed). You could install pyarrow `(pip install pyarrow)` instead of `fastparquet` (uninstall fastparquet, since if both are installed it will use `fastparquet`) and convert to parquet. 

It worked for me in a new virtual environment with `dask` (along with `dask[complete]` and `dask-ml`) only installed. 

I tried with a virtual environment tensorflow installed and it gave me an error (however, there I used pyarrow) you could see it [here](https://stackoverflow.com/questions/55012950/convert-csv-file-to-parquet-using-dask-jupyter-kernel-crashes). @TomAugspurger, @mrocklin would you be able to see the query on [stackoverflow](https://stackoverflow.com/questions/55012950/convert-csv-file-to-parquet-using-dask-jupyter-kernel-crashes).

Hope this helps

Thanks

Michael
