### ISSUE TITLE
map_blocks to receive xarray

### ISSUE THREAD

**Issue by ttung** [dask/dask#4582]
Can the callable in `map_blocks` receive an xarray if the source array is an xarray?

I can think of some crazy ways to achieve this, but none of them are particularly elegant.  Hoping the community has a better solution for this.

**Comment by mrocklin** [comment]
Generally dask arrays contain numpy-like arrays.  Usually xarray datasets
contain dask arrays, so the arrangement here is somewhat reversed.

The Xarray equivalent of dask array's map_blocks function is apply_ufunc.
I wonder if that would solve your problem. cc @shoyer

**Comment by shoyer** [comment]
+1 to everything @mrocklin said

**Comment by ttung** [comment]
There are intrinsic advantages to knowing your dimension names, and it's certainly plausible there are computations where knowing your labels are helpful.  In many ways, it's like typing your variables in code.  It's not strictly required, but it is a boon for the long-term maintainability of code.  xarray as the fundamental building block of scipy (rather than numpy) would be a huge improvement.

**Comment by mrocklin** [comment]
I agree that Xarray is generally great.  

I'm not sure what your last comment is intended to convey though.  If you're trying to encourage Dask array to support xarrays internally then I disagree.  There is no reason for Dask Array to support Xarrays internally.  The relationship between the two projects is that Xarray wraps around Dask Arrays.  If you like the Xarray interface then I encourage you to use Xarrays rather than using Dask arrays directly.  You'll still get all of the parallelism and out-of-core operation that Dask offers while also getting all of the virtues of Xarray that you list above.

**Comment by ttung** [comment]
The callables in for `map_blocks` and `apply_ufunc` are not able to received "typed" arrays.  That's what I perceive is missing in the current arrangement.  Of course, it's quite likely I'm completely wrong, as I don't know the internals as well as either of you. :)

**Comment by mrocklin** [comment]
I'll defer to @shoyer on that.  I'm not super-familiar with the Xarray API.
 Alternatively you might want to raise this question on the Xarray issue
tracker, where more Xarray folks will be able to help.

**Comment by ttung** [comment]
Cool, I'll try that.  I wasn't sure where to raise this issue as it's the intersection between the two projects. :)

**Comment by mrocklin** [comment]
No worries

**Comment by ttung** [comment]
Filed as https://github.com/pydata/xarray/issues/2807
