### ISSUE TITLE
Type checking or duck typing inside dask.array.Array.__array_function__

### ISSUE THREAD

**Issue by pentschev** [dask/dask#4583]
A broad discussion on how handling `__array_function__` mixin should work started in #4567. I suggest this continues here.

Some highlights:

@shoyer said:

> The `__array_function__` protocol guarantees that it will only get called if `dask.array.Array` is in types. So if that's all you wanted to check, you could drop this entirely.
> 
> The problem is that you want to support operations involving some but not all other array types. For example, `xarray.DataArray` wraps dask arrays, not the other way around. So `dask.Array.__array_function__` should return `NotImplemented` in that case, leaving it up `xarray.DataArray.__array_function__` to define the operation.
> 
> We basically need some protocol or registration system to mark arrays as "can be coerced into dask array", e.g., either
> 
> ```
> sparse.Array.__dask_chunk_compatibile__ = True
> ```
> or
> 
> ```
> dask.array.register_chunk_type(sparse.Array)
> ```

@hameerabbasi said:

> > I guess Dask could safely coerce anything that implements `InMemory` and `NumpyDuckArray` mixins?
> 
> I was thinking of three classes of (NumPy-Specific) mixins, aimed at implementing what I see as the three major protocols:
> 
> * `NumPyUfuncMixin`
> * `NumPyIndexingMixin` (for NumPy-like indexing, so `XArray` and `pandas` would skip this).
> * `NumPyArrayFunctionMixin` (for implementing array methods via `__array_function__`, such as `sum` and `mean`).
> 
> I see the use of your `InMemory` mixin, but I would rename it to `InCore`, as GPU computations don't take place in main memory. :)
> 
> For now, these would be provisional, just like `__array_function__`. The hope is that these would be adopted and specific checking code would go away.

Another @hameerabbasi comment:

> Then how about a "numpy/pydata community repo" containing these mixins? I would be happy to maintain one. (Not in the main NumPy codebase)? The reason I like the idea of mixins is it allows "duck-array" like objects to easily implement NumPy-like functionality without too much effort.
> 
> We can also have protocols:
> 
> ```
> class DuckArray:
>     __array_indexing__ = True
>     __array_in_core__ = True
> ```

@mrocklin

**Comment by shoyer** [comment]
With the implementation merged in #4567, dask doesn't do *any* checks on argument types -- it simply asserts that it's at the top of the type casting hierarchy for all types.

This [isn't a safe assumption](https://www.numpy.org/neps/nep-0013-ufunc-overrides.html#type-casting-hierarchy), and is quite likely to result in bugs, e.g., `xarray.DataArray` should take precedence over dask arrays to define operations involving dask and xarray objects.

I continue to think that *some* sort of explicit registration or protocol for dask is the right way to do this for now. I agree that it's awkward, short of having access to a true multiple dispatch system, to figure out where to do this registration, e.g,. should it be in dask or cupy

My suggestion is that for types dask knows it should handle, for now should register them itself by using guarded imports, e.g.,
```python
try:
     import cupy
     register_chunk_type(cupy.NDArray)
except ImportError:
    pass
```

In the future, we might push this on other libraries like cupy that want to be usable in dask, but for now there's an advantage to keeping our experimental protocol/registration system only in one codebase.

**Comment by hameerabbasi** [comment]
I think a protocol without an optional dependency is fine. It doesn't have to be a NEP, just something agreed upon by the PyData community.

**Comment by jthielen** [comment]
Are there any updates with respect to Dask Arrays checking argument types and not assuming it is at the top of the type casting hierarchy? I have been working on tests integrating Pint with Dask (xref https://github.com/hgrecco/pint/issues/845), and have been running into numerous issues with non-commutativity since Dask declares it can handle Pint Quantities (when it should instead be returning `NotImplemented`).

**Comment by mrocklin** [comment]
> Are there any updates with respect to Dask Arrays checking argument types and not assuming it is at the top of the type casting hierarchy? 

There have been no updates that I can see here.  If there is something you'd like to suggest then please do.

**Comment by jthielen** [comment]
> There have been no updates that I can see here. If there is something you'd like to suggest then please do.

I unfortunately don't have any suggestions beyond what has already been discussed, but if @shoyer's `register_chunk_type` idea seems like a good way forward and nobody else has been working on it, I'd be glad to try helping move it along. Progress may be slow since I'm not well-acquainted with Dask's internals, and I have a number of other ongoing projects, but I can still try!

Two questions I would want to ask up front: 

- should there be any particular concern for backwards compatibility, given the current behavior of attempting to handle all array-like types?
- [based on the outline here](https://github.com/hgrecco/pint/issues/845#issuecomment-525842581), should Dask register the following types by default, or are there others?
  - cupy
  - sparse
  - masked arrays

**Comment by shoyer** [comment]
> * should there be any particular concern for backwards compatibility, given the current behavior of attempting to handle all array-like types?

I don't think we need to worry _too much_ about this. It should be straightforward to add `register_chunk_type` as necessary.

> * [based on the outline here](https://github.com/hgrecco/pint/issues/845#issuecomment-525842581), should Dask register the following types by default, or are there others?
>   
>   * cupy
>   * sparse
>   * masked arrays

This covers the cases I'm familiar with.
