### ISSUE TITLE
Dask dataframe cannot do any group_by sum

### ISSUE THREAD

**Issue by KathyGCY** [dask/dask#4611]
Hi All,
I have a dask dataframe with 5 columns 
Categorical: Priority_Of_Inc
Categorical: Type_Of_Inc
Categorical: YEAR
Categorical: MONTH
Integer: r c(constant 1)

> for col in ['Priority_Of_Inc', 'Type_Of_Inc', 'YEAR', 'MONTH']:
>     df[col] = df[col].astype('category')
> 
> print(df.groupby(['Priority_Of_Inc'])["r"].sum())

And NOPE, doesn't work. And yes I have tried 

> df.compute()

, but it keep hitting errors. So I had to convert back to pandas, so that I can to groupby-sum.

How should I do groupby-sum in dask dataframe?

FYI, crosstab also fales with dask dataframe

Thanks!
All the best,
Kathy

**Comment by mrocklin** [comment]
Hi Kathy, 

Thanks for the issue.  If possible, would you be able to produce a minimal reproducible example with the error that you've run into?  It's somewhat difficult to help otherwise. 

Groupby-sums do generally work, here is one such example

```python
In [1]: import dask.dataframe as dd, pandas as pd

In [2]: df = pd.DataFrame({'x': [1, 2, 1, 2], 'y': [1, 2, 3, 4]})

In [3]: ddf = dd.from_pandas(df, npartitions=2)

In [4]: ddf.groupby('x').y.sum().compute()
Out[4]:
x
1    4
2    6
Name: y, dtype: int64
```

If you have the time to construct a similar example that fails that would be very helpful.

See also: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by mrocklin** [comment]
Hi @KathyGCY , any further information here?

**Comment by jrbourbeau** [comment]
Closing as additional information is needed to reproduce the original issue. @KathyGCY please feel free to re-open this issue if you would like to continue the discussion.
