### ISSUE TITLE
shape API inconsistency between dask.array and dask.dataframe

### ISSUE THREAD

**Issue by gijzelaerr** [dask/dask#4616]
Hi! I noticed there is an inconsistency between the shape property of a dataframe and an array (dask 1.1.1). `dataframe.shape` gives a tuple with a delayed value while `array.shape` just gives the length:
```
In [2]: dataframe = dd.from_array(np.rec.array([(1,2.),(2,3.)], dtype=[('foo', 'i4'),('bar', 'f4')]))

In [3]: array = da.from_array(np.array([(1, 2.), (2, 3.)]), chunks=-1)

In [4]: dataframe.shape
Out[4]: (Delayed('int-d66df0db-2cd0-413c-aaf0-6c2754cf57c2'), 2)

In [5]: array.shape
Out[5]: (2, 2)
```

Maybe the reason is that delayed computation is different, but I'm still able to access these properties without calling a `.compute()`:

```
In [6]: len(dataframe), len(dataframe.count())
Out[6]: (2, 2)

In [7]: dataframe.shape[0].compute()
Out[7]: 2
```

So not sure why the behavior/API would be different?

**Comment by martindurant** [comment]
Arrays and dataframes are implemented in completely different ways.

Arrays always know the total shape and the size of all the chunks beforehand, and nearly all slicing/selecting that you do will also end up with arrays where you know the total shape and sizes. This is important for matrix-like operations and linear algebra in general.

Dataframes, on the other hand, usually only contain metadata about the columnwise dimension, and don't know the number of rows in each partition. They might have additional information about the ranges of index values found in each partition (known as "divisions"). The reflects most work on dataframes being row-wise or operations on or creating the index (like groupby). Furtehrmore, dataframe storage formats such as csv will not readily yield the row count per chunk. Thus, it takes work to find the number of rows in a division, and so this work is not carried out unless the user specifically asks for it with compute.

The only exception for dataframes is `len()`, and this is because the python spec says that this should return a real number every time - so Dask makes a special case and performs the work without requiring a call to compute.

**Comment by gijzelaerr** [comment]
ok thanks, that explains. I think I shall just close this issue then.
