### ISSUE TITLE
Try np.concatenate() for unregistered backends.

### ISSUE THREAD

**Issue by skrah** [dask/dask#4662]
As discussed in https://github.com/plures/gumath/issues/22, unregistered backends work if `np.concatenate()` is tried.  This is a an example that deliberately does not touch the code path for registered backends but works for `xnd.array`:

```
diff --git a/dask/array/core.py b/dask/array/core.py
index f04ff0c..dd968a6 100644
--- a/dask/array/core.py
+++ b/dask/array/core.py
@@ -3505,6 +3505,13 @@ def concatenate3(arrays):
         x = unpack_singleton(arrays)
         return _concatenate2(arrays, axes=list(range(x.ndim)))
 
+    if hasattr(advanced, '__array_function__'):
+        try:
+            x = unpack_singleton(arrays)
+            return _concatenate2(arrays, axes=list(range(x.ndim)))
+        except TypeError:
+            pass # np.concatenate not implemented.
+
     ndim = ndimlist(arrays)
     if not ndim:
         return arrays
```

**Comment by hameerabbasi** [comment]
cc @mrocklin @pentschev I believe this is the right way forward, since it was the point of `__array_function__`. 😄

**Comment by mrocklin** [comment]
This function is a little bit hacky (my apologies).  Ideally arrays use the logic at the bottom of this function, which allocates an array and then assigns into it.  The `_concatenate2` solution is slower and involves a new copy for every dimension.  

The proposed solution is sub-ideal because it slows down the common numpy case.  Probably short term we want to do something like ...

```python
if the arrays are all numpy arrays:
    do the assignment solution
else:
    try the concatenate2 solution
```

In the future presumably other fully featured implementations like cupy could also make use of the assignment solution at the bottom, if we used something like `np.empty_like(..., shape=)` (cc @pentschev)

**Comment by pentschev** [comment]
I agree with what @mrocklin is saying, we should try to avoid slowing the current implementation down. Seems like his suggestion wouldn't be too difficult to get working, so if we have a PR that covers his concerns, that's +1 from me.

**Comment by mrocklin** [comment]
This conversation appears to have gone stale.  Closing.

**Comment by skrah** [comment]
Ah yes, it appears to be superseded by #4669.

**Comment by hameerabbasi** [comment]
Re-open? I revitalised #4669

**Comment by skrah** [comment]
Since I opened this, I'm fine with moving the conversation to #4669.
