### ISSUE TITLE
__array_function__ protocol does not  work for SVD

### ISSUE THREAD

**Issue by andersy005** [dask/dask#4690]
According to https://blog.dask.org/2019/03/18/dask-nep18, #4567, https://github.com/dask/dask/issues/4563 , calling `np.linalg.svd()` on a dask array should return a dask array. However, I am noticing inconsistent behavior: when I call `np.linalg.svd(d)` where d is a dask array, the computation of results is not deferred until its consumption (see example below). In contrast, when I call `np.sin(d)`, I get consistent behavior guaranteed by ` __array_function__ ` protocol. 

Am I missing anything? Does `__array_function__ ` protocol work on a subset of functions for the time being?

```python
In [1]: import numpy as np

In [2]: import dask.array as da

In [3]: import dask

In [4]: np.__version__
Out[4]: '1.16.1'

In [5]: dask.__version__
Out[5]: '1.1.5'

In [6]: x = np.random.random((5000, 1000))

In [7]: d = da.from_array(x, chunks=(1000, 1000))

In [8]: %time u, s, v = np.linalg.svd(x)
CPU times: user 18.3 s, sys: 583 ms, total: 18.9 s
Wall time: 5.01 s

In [9]: %time u, s, v = np.linalg.svd(d)
CPU times: user 18 s, sys: 593 ms, total: 18.6 s
Wall time: 4.99 s

In [10]: %time u, s, v = da.linalg.svd(d)
CPU times: user 794 µs, sys: 13.4 ms, total: 14.2 ms
Wall time: 13.9 ms

In [11]: %time np.sin(x)
CPU times: user 53.1 ms, sys: 3.87 ms, total: 57 ms
Wall time: 56 ms
Out[11]:
array([[0.44740612, 0.58931101, 0.34309384, ..., 0.7955435 , 0.16937846,
        0.33826967],
       [0.62432792, 0.43999021, 0.83840337, ..., 0.21214213, 0.33224555,
        0.50296018],
       [0.03496391, 0.38251129, 0.78760437, ..., 0.82258898, 0.74761496,
        0.69566021],
       ...,
       [0.37794326, 0.48107401, 0.100952  , ..., 0.30811849, 0.73944186,
        0.53358238],
       [0.62488639, 0.65372414, 0.660924  , ..., 0.64636005, 0.63637919,
        0.01250593],
       [0.63777377, 0.52750805, 0.68272464, ..., 0.29993424, 0.53909875,
        0.57363216]])

In [12]: %time np.sin(d)
CPU times: user 705 µs, sys: 379 µs, total: 1.08 ms
Wall time: 6.49 ms
Out[12]: dask.array<sin, shape=(5000, 1000), dtype=float64, chunksize=(1000, 1000)>
```

**Comment by jrbourbeau** [comment]
Thank you for the inquiry and very nice example @andersy005! The `__array_function__` protocol is currently an experimental feature that is turned off by default. To enable the protocol you need to set the environment variable `NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1` (for reference see https://www.numpy.org/neps/nep-0018-array-function-protocol.html#implementation). In your example, was the `NUMPY_EXPERIMENTAL_ARRAY_FUNCTION` variable set? 


> when I call np.sin(d), I get consistent behavior guaranteed by __array_function__ protocol


Dask arrays implement the [`__array_ufunc__` protocol](https://docs.scipy.org/doc/numpy/reference/arrays.classes.html#numpy.class.__array_ufunc__) (which is enabled by default)

https://github.com/dask/dask/blob/926ef7098f8148e0312a0dfd1d8c911f3df814ee/dask/array/core.py#L918

which is why `np.sin(d)` returns a Dask array in your example.

**Comment by jrbourbeau** [comment]
cc @pentschev

**Comment by andersy005** [comment]
Thank you, @jrbourbeau! I assumed that the behavior was enabled by default for numpy version >= 1.16. Setting `NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1` environment variable fixes the issue. Feel free to close the issue

**Comment by jrbourbeau** [comment]
Awesome, glad to hear things are working now : )
