### ISSUE TITLE
http://localhost/dask/clusters 404 (Not Found)

### ISSUE THREAD

**Issue by Bidek56** [dask/dask#4711]
When running Dask using [Dask Chart](https://github.com/helm/charts/tree/master/stable/dask) in [Azure AKS](https://azure.microsoft.com/en-us/services/kubernetes-service/)
`helm install --namespace=dask --name dask ./dask` 

Starting Dask 1.1.5, I am seeing a lot of these errors in the Chrome console (Ctrl+Shift+J):
**GET http://10.10.0.50/dask/clusters?1555537293299 404 (Not Found)**

but I do NOT see them in 1.1.1

In addition, JupyterLab is using development build of React. Is this a Dask or JupyterLab issue?

**Comment by jcrist** [comment]
@mrocklin, @ian-r-rose - any changes to the docker images/jupyterlab extension that may lead to this?

**Comment by mrocklin** [comment]
Dask labextension currently polls to see if there is a dashboard available.  It's not a great solution for exactly the reason listed here.  I think that there is some improvement in master, but I'm not sure that it resolves this problem completely.  @ian-r-rose would know more.

**Comment by ian-r-rose** [comment]
I suspect that the problem here is actually that it is not installed correctly. We do poll the server for active clusters (indeed, JupyterLab and the classic notebook poll for kernel info as well). If the `dask_labextension` server extension is not installed or activated, it will result in 404s.

I couldn't see any reference to installing `dask-labextension` in the linked helm chart. Can anyone point me in the right direction? It may be as simple as the python package not being installed.

There has been some work recently on the client side to use exponential backoff for the case that the server is missing or unresponsive, but that should mostly reduce 404s rather than remove them.

**Comment by mrocklin** [comment]
Probably here:
https://github.com/dask/dask-docker/blob/master/notebook/Dockerfile

**Comment by ian-r-rose** [comment]
Ah, yep, looks like the server side component is missing (which was added as of 0.3)

**Comment by mrocklin** [comment]
I'll put up a PR and ping you

**Comment by mrocklin** [comment]
https://github.com/dask/dask-docker/pull/44

**Comment by Bidek56** [comment]
How about the development build of React issue?

**Comment by ian-r-rose** [comment]
@Bidek56 Currently the ability to do a prod (that is, minified) build of the application via the CLI is broken (see https://github.com/jupyterlab/jupyterlab/issues/5661), which should be fixed in the upcoming release. Once that happens, this image should be able to do that.

**Comment by Bidek56** [comment]
Commit [3b0c6e6](https://github.com/jupyterlab/jupyterlab/commit/3b0c6e622b25b8fee11fc11fff3da0436fbc2756) was merged into master, and [5661](https://github.com/jupyterlab/jupyterlab/issues/5661) was closed, what do we need to do to bring this fix into Dask and get a prod build of the hub? Thx

**Comment by ian-r-rose** [comment]
You should be able to install from JupyterLab master, with all the caveats that come with a potentially unstable version. Otherwise, we can wait until the release.

**Comment by ian-r-rose** [comment]
Can this be closed now?

**Comment by mrocklin** [comment]
Thanks @ian-r-rose !  Closing.

**Comment by Bidek56** [comment]
Can I expect the fix be included in the latest image on Docker Hub or next release? Thx
