### ISSUE TITLE
vindex with 2D int array fails to schedule or does not chunk

### ISSUE THREAD

**Issue by smartass101** [dask/dask#4847]
I'm trying to achieve the create a temporary array from shape `(f, t)` to ` f1, f2, t)` by vectorized integer broadcasting along these lines

```python
ind1 = np.arange(nf1)
ind2 = np.arange(nf2)
indx = np.abs(np.subtract.outer(ind1, ind2))
da.vindex[indx]
```

. Because it does not fit into memory, I tried using dask. Unfortunately, that also doesn't work, either it gets stuck  while creating the dask graph if chunking over `t` or does the full broadcast even when chunking over `f1, f2`.

I also tried `dask.array.take`, but that doesn't seem to support 2D index arrays.

Here is an [example as a Jupyter notebook](https://gist.github.com/smartass101/86add0935d871e1800386b6ff358755b), including stack traces and warnings.

Perhaps I'm missing some possible way to do this, but this seemed the most obvious way and yet does not work.

**Comment by shoyer** [comment]
`vindex` in dask is not terribly efficient. Due to the way dask.array works (building a full computation graph before doing computation), it has to check indexing operations over all pairs of possibly matching chunks.

If the structure of your data allows doing this operation in another way, I would recommend that. Based on your toy example, it looks like combining `dask.array.roll()` and `dask.array.stack()` might help?

**Comment by smartass101** [comment]
Thank you for the pointer, combining `roll` and `stakj` could work indeed in this case. I suppose in xarray jargon that would be `shift` and `concat`.

**Comment by shoyer** [comment]
In xarray it would be roll/concat.

**Comment by smartass101** [comment]
Thank you for the pointer, last time I checked, `roll` in `xarray` didn't have `roll_coords`, great to see it being added.

**Comment by jakirkham** [comment]
Did Stephan's suggestion work for you, @smartass101? Is there anything else to do here?

**Comment by mrocklin** [comment]
Closing due to lack of response.
