### ISSUE TITLE
Dask does not detect pyarrow

### ISSUE THREAD

**Issue by philippegr** [dask/dask#4864]
From a docker image python:3.7
```
pip install dask[complete]
pip install pyarrow
```
In Python 
```
Python 3.7.3 (default, May  8 2019, 05:28:42) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask.dataframe as ddf
>>> ddf.read_parquet()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: read_parquet() missing 1 required positional argument: 'path'
>>> ddf.read_parquet("")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet.py", line 1170, in read_parquet
    read = get_engine(engine)['read']
  File "/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet.py", line 1050, in get_engine
    raise RuntimeError("Please install either fastparquet or pyarrow")
RuntimeError: Please install either fastparquet or pyarrow
```

Importing pyarrow is fine and if fastparquet is installed, the code complains that "/" is a directory and not a .parquet file as expected.

**Comment by philippegr** [comment]
This has to do with pyarrow==0.13.0 not being supported by Dask as one can see by doing
```
ddf.read_parquet("", engine='pyarrow')
```

This issue is more around the error message in the read_parquet() with pyarrow 0.13.0 then

**Comment by TomAugspurger** [comment]
@martindurant do you know if pyarrow 0.13.1 will fix things without changes to dask?

**Comment by jakirkham** [comment]
@martindurant, would you be able to take a look at this?

**Comment by martindurant** [comment]
Yes indeed, the error which shows for `engine='pyarrow'` is being swallowed up by the general error when using `engine='auto'` (the default) and neither being successfully found.

Indeed, pyarrow 0.13.0 does not work with distributed, due to serialisation issues. It maybe works with pure dask following some fixes on our end. The current issues should be solved in version 0.13.1, but since that is not yet available, we will have to wait to be sure.

#4336 is also waiting on version 0.13.1, but for new features rather than fixes. Eventually we hope to have a much more streamlined parquet codebase.

**Comment by martindurant** [comment]
To reiterate: the correct workaround for now is to *downgrade* pyarrow

**Comment by martindurant** [comment]
@philippegr , ok to close this?

**Comment by philippegr** [comment]
Yes!
I see this is as a temporary problem from an external depency.

Thank you very much everybody
