### ISSUE TITLE
[Bug report]when the calculation finished,bokeh's graph tab disappeared

### ISSUE THREAD

**Issue by tarjintor** [dask/dask#4964]
I'm using bokeh to watch the graph tab
I'm following the turtorial here: http://distributed.dask.org/en/latest/web.html
I want to see the DAG of all tasks, and it works fine when the tasks are running
![1](https://user-images.githubusercontent.com/12421352/59745738-00608f80-92a8-11e9-8c05-6c248369e2f4.PNG)

But the graph is disappeared when the task is finished
![2](https://user-images.githubusercontent.com/12421352/59745798-20904e80-92a8-11e9-8540-3cbb345a6184.PNG)

I don't whether it's a feature or a bug?

my libs are 
tornado (6.0.2)
dask (1.2.2)
bokeh (1.1.0)

**Comment by martindurant** [comment]
This is expected - the scheduler is designed to "forget" graphs that are complete, to free up memory and resources. Otherwise, the graph display would grow forever as you submitted new work. You can have some control over this by deciding when you let the futures referring to results go out of scope or get `del`ed.

**Comment by tarjintor** [comment]
> 
> 
> This is expected - the scheduler is designed to "forget" graphs that are complete, to free up memory and resources. Otherwise, the graph display would grow forever as you submitted new work. You can have some control over this by deciding when you let the futures referring to results go out of scope or get `del`ed.

OK,Thank you
