### ISSUE TITLE
Expose metadata_nthreads in dataframe.read_parquet

### ISSUE THREAD

**Issue by gsakkis** [dask/dask#5055]
Pyarrow's [ParquetDataset](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetDataset.html) accepts a `metadata_nthreads` parameter to allow reading the dataset metadata concurrently using a thread pool. It would be helpful to expose this on the dask side, mainly to set it to >1 for large partitioned datasets but also to set it to 0 to disable the thread pool (currently it has a bug in that errors that happen in a thread pass silently; I'll open an issue for it on pyarrow's tracker).

**Comment by quasiben** [comment]
perhaps @martindurant or @rjzamora may have thoughts here ?

**Comment by martindurant** [comment]
Sounds like a reasonable thing to want. I think in @rjzamora 's new implementation, you can pass lots of arguments through to the reader engine, I'm sure he can say the correct way to write it. However, the [PR](https://github.com/dask/dask/pull/4995) is not quite in yet. I would not bother making a change to the pyarrow branch of the current reader code, since it will be shortly replaced.

**Comment by rjzamora** [comment]
Thanks for raising this @gsakkis!

Your comment is motivating me to further simplify/expand the process of passing kwargs from Dask's `to_parquet` and `read_parquet` calls to the underlying `pyarrow` and `fastparquet` routines.  I will push some proposed changes to [PR#4995](https://github.com/dask/dask/pull/4995) soonish (including a test for passing `metadata_nthreads` to `pyarrow`'s `ParquetDataset`)

**Comment by jrbourbeau** [comment]
Great, thanks for handling this @rjzamora!

**Comment by jrbourbeau** [comment]
Closing as it looks like support for passing `metadata_nthreads` was added in #4995. Thanks @rjzamora!
