### ISSUE TITLE
Release dask 2.1

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#5063]
I plan to release Dask 2.1 this Friday if there are no objections

**Comment by jrbourbeau** [comment]
No objection from me. Happy to manage the release if you'd like

**Comment by TomAugspurger** [comment]
+1

**Comment by mrocklin** [comment]
> No objection from me. Happy to manage the release if you'd like

You're welcome to it if you'd like to.  From my perspective we're good to go on both dask/dask and dask/distributed.

**Comment by jrbourbeau** [comment]
Then I'll do a 2.1 release for both dask/dask and dask/distributed later this afternoon

**Comment by mrocklin** [comment]
Hooray!

**Comment by jrbourbeau** [comment]
I held off on pushing a new release Friday because we had a failing test in `master` (#5073). It's not an issue with Dask, but with a test that used a new feature of pandas that was added in version 0.24.0. There's a PR (#5075) to fix the issue. Once the test is fixed in `master` I'll push the 2.1 release.
