### ISSUE TITLE
Upload exported conda env to WORKERS

### ISSUE THREAD

**Issue by hamroune** [dask/dask#5142]
Hi everyone,
I exported conda env using conda pack, as Zipped file, when I try uploading this zip env to workers (installed on other aws VMs) in order to use some extra package, cassandra in my case, through calling
 ` client.upload_environment(name, zipFile)`
 it breaks, the exception is curious : 
`TypeError: _upload_environment() takes 2 positional arguments but 3 were given` 
and then when we use the private fct directly
 `_upload_environment` 
it seems not taking a count of the zipped file, the error is the classical package not found `Exception: ModuleNotFoundError("No module named 'cassandra'")
`

my code is so simple juste inside map I just call:
````
  def insert_to_cassandra(entry):
        from cassandra.cluster import Cluster
        cluster_cassandra = Cluster([CASSANDRA_HOST])
        session = cluster_cassandra.connect(CASSANDRA_SCHEMA)
  
````

any solution or recommendation?
thanks in advance

**Comment by jcrist** [comment]
I recommend transporting your environment separate from dask's mechanisms, as it's bound to be more efficient and reliable. The `upload_environment` method is undocumented, and looks to no longer work (there's no way to restart the worker in the specified environment, so the library won't be properly found).

---

*Aside: @mrocklin, would you be opposed to deleting this method rather than fixing it? It's not resilient to worker additions/removals, inefficient as it requires an existing dask installation, which is supplanted by a new dask installation, and can be better handled by external deployment methods.*

---

If you do need to install package on all nodes, you can shell out to `pip`:

```
import os
client.run(lambda: os.system("pip install cassandra"))
```

Or upload a zipped version of your package (requires the package be zip safe):

```
client.upload_file("cassandra.zip")  # could also use an .egg file here, as they're the same
```

**Comment by mrocklin** [comment]
No objection to removing it from me

**Comment by jcrist** [comment]
https://github.com/dask/distributed/pull/2877
