### ISSUE TITLE
ValueError: Metadata mismatch found in `from_delayed`.

### ISSUE THREAD

**Issue by CJ-Wright** [dask/dask#5435]
It seems that merging multiple delayed dataframes does not work when the dataframes are series of category type.

It seems that the error is coming from the equality of categorical dtypes includes the categories used, which makes this approach to concatenation not work. This came up in the context of intake.

```python
from pandas import DataFrame, Series
from dask.delayed import delayed
from dask.dataframe import from_delayed

a = Series(['a', 'b', 'a'], dtype='category')
b = Series(['a', 'c', 'a'], dtype='category')
da = delayed(lambda x: x)(a)
db = delayed(lambda x: x)(b)

c = from_delayed([da, db])
c.compute()
```
Error msg
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-02c1dd8d067d> in <module>
----> 1 c.compute()

~/mc/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    173         dask.base.compute
    174         """
--> 175         (result,) = compute(self, traverse=False, **kwargs)
    176         return result
    177 

~/mc/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    444     keys = [x.__dask_keys__() for x in collections]
    445     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 446     results = schedule(dsk, keys, **kwargs)
    447     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    448 

~/mc/lib/python3.7/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     80         get_id=_thread_get_id,
     81         pack_exception=pack_exception,
---> 82         **kwargs
     83     )
     84 

~/mc/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    489                         _execute_task(task, data)  # Re-execute locally
    490                     else:
--> 491                         raise_exception(exc, tb)
    492                 res, worker_id = loads(res_info)
    493                 state["cache"][key] = res

~/mc/lib/python3.7/site-packages/dask/compatibility.py in reraise(exc, tb)
    128         if exc.__traceback__ is not tb:
    129             raise exc.with_traceback(tb)
--> 130         raise exc
    131 
    132     import pickle as cPickle

~/mc/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    231     try:
    232         task, data = loads(task_info)
--> 233         result = _execute_task(task, data)
    234         id = get_id()
    235         result = dumps((result, id))

~/mc/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/mc/lib/python3.7/site-packages/dask/dataframe/utils.py in check_meta(x, meta, funcname, numeric_equal)
    650     raise ValueError(
    651         "Metadata mismatch found%s.\n\n"
--> 652         "%s" % ((" in `%s`" % funcname if funcname else ""), errmsg)
    653     )
    654 

ValueError: Metadata mismatch found in `from_delayed`.

Partition type: `pandas.core.series.Series`
+----------+----------+
|          | dtype    |
+----------+----------+
| Found    | category |
| Expected | category |
+----------+----------+
```

**Comment by mrocklin** [comment]
Thank you for the excellent issue @CJ-Wright .  

Looking into the code a bit it looks like this strictness in `check_meta` was intentional at some point:

https://github.com/dask/dask/blob/8001ee2e258f3f27d40e78990c5b98d44edc138e/dask/dataframe/utils.py#L593-L602

And it looks like we enforce the metadata check in `from_delayed` here:

https://github.com/dask/dask/blob/8001ee2e258f3f27d40e78990c5b98d44edc138e/dask/dataframe/io/io.py#L565-L570

So one answer to this issue is "make sure that all of your dataframes are consistent with each other".  

However, many Dask Dataframe algorithms *are* robust to mismatched categoricals.  Probably in this case you would want to tell Dask dataframe that you're not sure what the categories of your dataframe are. The `dd.from_delayed` function takes a `meta=` keyword, where you can provide metadata for your full dataframe.  If you don't provide something then it computes the first partition and uses that.  You might provide metadata, but with explicitly unknown categories.  It looks like there is a function in `dd.utils.clear_known_categories` that might be helpful?  (I actually don't know this part of the code at all, so I'm just guessing).

Hopefully some of that provides context here.  If you have suggestions on how this can be fixed/improved generally, that would also be welcome.

**Comment by CJ-Wright** [comment]
Hmm ok. Would it be possible to have a boolean flag on `from_delayed` which says don't check the meta? I tried using the `clear_known_categories` function, but that got rid of my categories all together.

**Comment by mrocklin** [comment]
Yes, that seems reasonable

**Comment by CJ-Wright** [comment]
Would you like a PR to that effect?

**Comment by mrocklin** [comment]
Sure

**Comment by diegoxfx** [comment]
I'm getting that same error when trying to read a json file with `include_path_column` flag

```python-traceback
ValueError: Metadata mismatch found in `from_delayed`.

Partition type: `pandas.core.frame.DataFrame`
+--------+----------+----------+
| Column | Found    | Expected |
+--------+----------+----------+
| 'path' | category | category |
+--------+----------+----------+
```

**Comment by jsignell** [comment]
Have you tried setting `verify_meta=False`?

**Comment by diegoxfx** [comment]
> Have you tried setting `verify_meta=False`?

I tried but then i got this new error: `TypeError: read_json() got an unexpected keyword argument 'verify_meta'`. My dask version is 2022.02.1

I checked the read_json and i found this:

```
        parts = [
            delayed(read_json_file)(
                f,
                orient,
                lines,
                engine,
                include_path_column,
                path_converter(f.path),
                path_dtype,
                kwargs,
            )
            for f in files
        ]

    return from_delayed(parts, meta=meta)
```

The `from_delayed` function at the end does not receive any additional argument, I think that's why I'm getting the `ValueError`

**Comment by jsignell** [comment]
ah yeah that makes sense. Feel free to open a pull request if you like!
