### ISSUE TITLE
scatter dataframe

### ISSUE THREAD

**Issue by kwunlyou** [dask/dask#5585]
when I run the following code

```python
_ = ddf['col_name'].map_partitions(foo, meta=tuple()).compute()
```

I received a warning message

```
/usr/local/lib/python3.6/dist-packages/distributed/worker.py:3254: UserWarning: Large object of size 153.89 MB detected in task graph: 
  ('getitem-145f763f7858c68f69577c5b88cbb259',       ... ], 'col_name')
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and 
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
```

- Is there an easy way to scatter dataframe before runing `map_partitions`?
- should I use a larger `npartitions` for the dataframe?

**Comment by mrocklin** [comment]
The warning doesn't necessarily relate to your map_partitions call.  It
could be due to anything in your computation up until that point.

I don't know exactly wher your problem is, but in dataframe computations
this is a common issue:
https://docs.dask.org/en/latest/best-practices.html#load-data-with-dask

**Comment by mrocklin** [comment]
Closing this for now.  If there is more information here then let us know and we'll reopen.
