### ISSUE TITLE
Interface for getting futures from a persisted array

### ISSUE THREAD

**Issue by djhoese** [dask/dask#5658]
This is based on [this tweet](https://twitter.com/TobiasAdeJong/status/1200928293291274240) by @TAdeJong and the [associated gist](https://gist.github.com/tadejong/abc70b33f54c4230e3da1119c7a20609). The code involves getting the Futures behind a dask array that has been persisted on the cluster. I'm wondering if there is a defined interface to make this easier or if the current solution is the best option.

Here is what is in the code right now:

```
def persist_and_visualize(dA):
    A = dA.persist()
    res = np.full(A.shape, np.nan)
    chunksize= np.array(A.chunksize)
    futures = next(iter(A.__dask_graph__().layers.values())).values()
    fig, ax = plt.subplots()
    for batch in as_completed(futures, with_results=True).batches():
        for future, result in batch:
            index = np.array(future.key[1:])*chunksize
            res[tuple(slice(i,j) for i,j in zip(tuple(index), tuple(index+chunksize)))] = result
        ax.imshow(res)
        display(fig)
        clear_output(wait=True)
        plt.pause(0.01)
    return res
```

The two "ugliest" parts of this are the `__dask_graph__` usage and the calculation of the indexes. Do either of these have better ways of doing them in dask's advertised interfaces? If not, should they?

**Comment by jacobtomlinson** [comment]
As this is a question about using Dask and understanding its API rather than reporting a bug or an issue perhaps this is more suitable for a question on Stack Overflow with the 'dask' tag.

**Comment by mrocklin** [comment]
You might be looking for the `dask.distributed.futures_of` call.  

 +1 on SO

**Comment by djhoese** [comment]
> more suitable for a question on Stack Overflow with the 'dask' tag.

Yeah, my one excuse is that I thought if this wasn't implemented and could be that this could turn in to an actionable issue. Also wanted to be able to mention Tobias to easily get their attention on this.

**Comment by TAdeJong** [comment]
Chiming in on this, as I spend quite some time on roaming around the documentation, I think I can confirm there is no better way of doing is using Dask's _advertised_ interfaces, as in documented interfaces. 
Most information is either from https://docs.dask.org/en/latest/futures.html#waiting-on-futures and https://distributed.dask.org/en/latest/manage-computation.html#client-persist

Note that the last documentation is actually out-of-date as this situation changed since the introduction of `HighLevelGraph`'s, which necessitates the need for the `next(iter()).values()`.

So maybe we can use this issue as a reminder to improve documentation, as the `dask.distributed.futures_of` seems rather hard to find.

Or we just close this.

@djhoese: the calculation of the indices is actually rather more forward than it seems here, during to a brain fart of mine:
`res[tuple(slice(i,i+di) for i, di in zip(tuple(index), tuple(chunksize)))]`

**Comment by mrocklin** [comment]
Futures_of is rarely used by people, so it's not surprising that it's hard
to find.  I suspect that it's in API docs, but I agree that that's not
super helpful for discovery.

In general I'm at a loss for how to arrange the documentation to suit
everyone's needs.  People come to this project with very different
objectives and skillsets, and it's a continuous challenge to figure out how
to arrange the documentation accordingly

**Comment by mrocklin** [comment]
Conversation here has stalled.  Closing.  If anyone has a specific suggestion on how to improve things please speak up and we'll reopen.
