### ISSUE TITLE
Consider implementing .array and .to_numpy

### ISSUE THREAD

**Issue by jamescasbon** [dask/dask#5705]
Series and dataframe implement .values:

https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.Series.values

But this api is warned against in pandas docs...

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.values.html

**Comment by TomAugspurger** [comment]
Duplicate for https://github.com/dask/dask/issues/5001 for `.array`. Chime in there if you have thoughts on what the return type would be (I suspect we'll need another Dask collection to implement this).

I'm not sure about a `to_numpy()`, since we wouldn't be creating a numpy array, we'd be creating a Dask array. And we already have `to_dask_array`. Thoughts on that?

**Comment by TomAugspurger** [comment]
Any thoughts here @jamescasbon? Is `.array` useful to you, useful enough to implement a new Dask collection? Is having `.to_numpy()` return a Dask array too confusing?

**Comment by jamescasbon** [comment]
Hi, sorry for not responding sooner.   I think I was probably misusing dask when I wanted this.  Things are clearer to me now so I don't really need this.  Previously I was getting a mix of dask and real dataframes.  But now I realize how to keep my types consistent :+1:

**Comment by mrocklin** [comment]
Thanks for circling back James
