### ISSUE TITLE
Function np.average fails on Dask data frame with categorical field

### ISSUE THREAD

**Issue by BodonFerenc** [dask/dask#5712]
Hi All

this works like a charm:
```python
import dask.dataframe as dd
import pandas as pd
import numpy as np
import random
import string

N = 1000
t = pd.DataFrame({
        'bucket': [''.join(random.choices(string.ascii_lowercase, k=2)) for _ in range(N)],
        'weight': np.random.uniform(0, 2, N),
        'qty': np.random.randint(100, size=N)})
d = dd.from_pandas(t, 16)

d.groupby('bucket').apply(lambda g: np.average(g.qty, weights=g.weight), meta=('x', 'f8')).to_frame('W_AVG_QTY').compute()
```

but if I change the type of field _bucket_ to _category_ then I get error 

```python
t['bucket'] = t['bucket'].astype('category')
d = dd.from_pandas(t, 16)

d.groupby('bucket').apply(lambda g: np.average(g.qty, weights=g.weight), meta=('x', 'f8')).to_frame('W_AVG_QTY').compute()

...
ZeroDivisionError: Weights sum to zero, can't be normalized
```

Any idea for a simple workaround?

**Comment by TomAugspurger** [comment]
I'm not entirely sure why, but an empty DataFrame is being passed to the `lambda`. It shouldn't be needed for `meta` since you provide it. So perhaps a bug, or an empty partition?

I'd recommend defining a function that caches the ZeroDivisionError and does the correct thing. With categorical data, zero-length groups are a possibility.

**Comment by TomAugspurger** [comment]
> I'm not entirely sure why, but an empty DataFrame is being passed to the lambda

Ah, since you're grouping by a Categorical and doing a `.apply` you almost surely have empty groups within a partition. The docstring for groupby.apply has a warning about this.

```python
In [14]: d.groupby("bucket").apply(len).min().compute()
/Users/taugspurger/.virtualenvs/dask-dev/bin/ipython:1: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  #!/Users/taugspurger/Envs/dask-dev/bin/python
Out[14]: 0
```

You probably want to write a custom `dd.Aggregation` function and pass it to `.agg`. That might help with the empty groups in this specific case, though you'll want to consider it unless you know that it's impossible for your dataset.

Let us know if you think there's any additional issues, but I think we've discovered the root cause.
