### ISSUE TITLE
std function returns NaN for long floats

### ISSUE THREAD

**Issue by tjperr** [dask/dask#5725]
Calling `.groupby().std()` on a dataframe with long floating point numbers returns NaNs and a warning. This occurs because internally the variance is calculated as a (small) negative number.

Seems to be a resurfacing of https://github.com/dask/dask/issues/4233

```
import pandas as pd
import dask.dataframe as dd

values = [-0.00179999999 for _ in range(10)]
ids = [1 for _ in range(5)] + [2 for _ in range(5)]

# Returns 0s as expected
df = pd.DataFrame({'ids': ids, 'values':values})
df.groupby("ids").values.std()

# Returns NaNs and a warning
ddf = dd.from_pandas(df, npartitions=2)
ddf.groupby("ids").values.std().compute()
```
The following is returned:

```
/Users/tom/anaconda3/envs/example/lib/python3.7/site-packages/pandas/core/series.py:856: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)
ids
1   NaN
2   NaN
Name: values, dtype: float64
```

Not totally sure if this is a bug or just the limits of floating point numbers, but would be interested to hear your thoughts.

**Comment by mrocklin** [comment]
Thank you for the excellent bug report @tjperr and especially for the minimal reproducible example.

My guess is that this is due to numeric instability.  Done naively, the calculation of std is prone to small errors rounding errors.  We have a much more advanced algorithm in dask.array that we also use for full series objects, which is more robust, but never did the work to extend this to dask dataframe in the groupby case (which complicates things).  I can see a couple of paths forward here:

1.  Someone could implement the full stable calculation of moments for groupby aggregations.  My guess is that this would take someone with some mathematical ability a couple of weeks.
2.  We could accept the numeric instability, but add a quick rounding to zero if the variance is zero.

I've implemented option 2 in https://github.com/dask/dask/pull/5728
