### ISSUE TITLE
Support for Dask executor in Apache Airflow

### ISSUE THREAD

**Issue by potiuk** [dask/dask#5803]
I am creating an issue on behalf of Apache Airflow community and it's about Apache Airflow integration with Dask.

We are working on Apache Airflow 2.0 (still at least 3-4 months to release it) but we are doing various cleanup tasks. One of the things we noticed is that we have a DaskExecutor https://github.com/apache/airflow/blob/master/airflow/executors/dask_executor.py . It uses Dask to run the tasks. The executor is very little used. It's used so little that we even have all the Dask Executor tests failing for months - without anyone noticing. We understand that Dask is important for a number of people, but also in order to keep it in Airflow we need someone who actually uses Dask (and Dask Executor in Airflow) to keep it in a healthy state. We are querying at our devlist and checking if someone is willing to maintain it but we also think it might be a good idea to ask here. 

We are happy as Apache Airflow committers to review and accept all the related code but we would love someone more familiar and using Dask to maintain it :).

Note that the executor is rather simple and the tests https://github.com/apache/airflow/blob/master/tests/executors/test_dask_executor.py are just a few and not very complex.

It's literally 200 lines of code in total. We could fix it ourselves, but maybe having someone who actually uses Dask being just a bit more active in the Apache Airflow community is a good idea :)

**Comment by TomAugspurger** [comment]
Thanks for opening the issue. I'm not sure any of the Dask maintainers actively use airflow, but if you have links to failing test logs we'd happily glance through them.

Otherwise, we can try to coordinate a fix. cc @jlowin who I think implemented the DaskExecutor in the first place. @mrocklin thoughts on using the dask_dev Twitter account to promote awareness of issue?

**Comment by potiuk** [comment]
Sure (and again - I think it is simple to fix - it's more about how we aproach it also from now on :) 

Here you can see the failing tests:

- https://travis-ci.org/apache/airflow/jobs/639137045#L1695

They are all marked as "xfail" (expected to fail) so they do not fail the build but they are still executed. 

Here are detailed names about those tests failing:

- https://travis-ci.org/apache/airflow/jobs/639137045#L2475

We also have very easy to use test environment to reproduce what happens on CI:

https://github.com/apache/airflow/blob/master/BREEZE.rst  - you literally check out the repo, run `./breeze` and you should be dropped in docker container where you should be able to run 

```
pytest tests/executors/test_dask_executor.py
```

and see the tests failing.

**Comment by mrocklin** [comment]
>  @mrocklin thoughts on using the dask_dev Twitter account to promote awareness of this issue?

No need to ask me for permission.  I encourage you to just use it as you see fit.

> it's more about how we aproach it also from now on :)

Agreed.  I think that if the question is "Is the Dask maintainer community willing and able to take on responsibility for the Dask-Airflow connection" then my answer for myself personally is "I probably don't have bandwidth, but maybe we can mutually help to find someone?"

If there are particular tracebacks I'm more than happy to take a look and offer advice to anyone.  I'm on a machine and don't yet have docker set up (it's not part of my normal workflow).  I tried for a bit to install things manually, but that ended up taking a while.  

We can also just abandon it.  If no one is speaking up about it being an issue then that might be the answer.

**Comment by mrocklin** [comment]
cc also @mariusvniekerk who might have been active on this historically.

**Comment by mrocklin** [comment]
One approach that might work and be cleaner long term, is that the two projects might agree on a protocol, perhaps concurrent.futures, that would work well on both sides.  Dask already implements the concurrent.futures API.  I wonder if Airflow could be made to run on top of that?

**Comment by mik-laj** [comment]
@dazza-codes  started working on the new DaskExecutor. @mrocklin  Does It use the mentioned API?
https://github.com/apache/airflow/pull/6984/files

**Comment by dazza-codes** [comment]
I recently looked into gRPC and asyncio, where I bumped into an interesting pattern to use concurrent.futures with an asyncio event loop, i.e.
- https://gist.github.com/seglberg/0b4487b57b4fd425c56ad72aba9971be
- when I get cycles to pick up the thread of the airflow-dask async/await option (PR 6984), I'll look a little closer at that pattern, because something has to manage an event loop to submit dask jobs and collect the future results (or handle exceptions).
- My full-time position has primary demands on my time and I've had a little time to understand and fix some Airflow behavior that's related to our workflows on AWS.  I only recently started to consider asyncio to scale Airflow tasks, with the hope that it might work well with async features in dask-distributed.  I don't know exactly when I'll get back to it, but our group is invested in using Airflow and Dask, but not usually together (yet).
- Anyway, when I get back to it, I'll be looking at the unit tests for sure and appreciate this linked issue here for support in the Dask dev-community.  IMO, it would be a pity to remove the dask option from Airflow.
- The online forums and github are working well, but also please LMK if there is any way to find grant funds to sponsor this community collaboration, perhaps via PyCon travel support and a hack workshop.

**Comment by mrocklin** [comment]
> @dazza-codes started working on the new DaskExecutor. @mrocklin Does It use the mentioned API?

The concurrent.futures API I'm referring to is the standard library `concurrent.futures` module: https://docs.python.org/3/library/concurrent.futures.html 

It looks like you all might need to go more deep than that though with security and things.

**Comment by mrocklin** [comment]
@dazza-codes yes, if your goal is to scale Airflow on AWS then combining Airflow-on-Dask and Dask-on-AWS seems like a reasonable approach.  There are a number of efforts to make it easy to use Dask on the cloud today, both in OSS and commerical activities. 

> please LMK if there is any way to find grant funds to sponsor this community collaboration, perhaps via PyCon travel support and a hack workshop.

Most of the Dask maintainers are paid properly by a variety of companies.  If your company is looking to hire out someone to build or maintain this let me know and I can recommend a couple of groups.  My guess is that the usual pizza money donations won't turn as many heads as it used to though :)

**Comment by dazza-codes** [comment]
For some context:
- Airflow
  - I started using Airflow in late 2018 for various projects that run AWS batch or ECS jobs
  - I recently contributed some bug fixes and a small feature for Airflow AWS batch
  - While working on that, I collected some ideas for using asyncio in
    - https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-28%3A+Add+AsyncExecutor+option
    - some low hanging fruit for that might be an Airflow asyncio pattern that can submit jobs using the dask-async features in https://distributed.dask.org/en/latest/asynchronous.html
- I started using dask in early 2019
  - almost all use so far is on a localhost (or EC2/batch), not cluster deployments
  - dask is used with other common scipy/numpy/pandas libs
  - I've never looked at dask source code to understand the internals of the dask DAG engine etc. (not sure I need to yet and not sure what prerequisites I need to get started, e.g. I don't know twisted yet).
  - I might want to quickly get a grasp on how dask unit test setup works to either use a localhost or a set of mock dask tasks, but dask is a big project and I'm not entirely clear yet where to focus.

**Comment by mrocklin** [comment]
Some relevant docs for context

-   Setting up Dask for actual use: https://docs.dask.org/en/latest/setup.html
-  Testing infrastructure to quickly set up and tear down Dask clusters: https://distributed.dask.org/en/latest/develop.html#writing-tests

(no expectations though, you already mentioned that you're busy right now)

**Comment by dazza-codes** [comment]
First steps were added into a collection of WIP on Airflow executors, more to come as time allows:
- https://github.com/apache/airflow/pull/6984/files#diff-37a6af8d668dbac0912fd469ca123dcdR58

**Comment by jcrist** [comment]
cc @seibert, @esc, @siu - I believe y'all are currently using the existing dask airflow backend and may be interested in following/supporting this issue.

**Comment by seibert** [comment]
Yes, thanks for the heads up.  We have been using the Dask Executor for some months successfully, so I didn't realize it was failing in Airflow's own testing.  I'll see if we have someone who can get more involved in supporting the airflow side of things.

**Comment by mrocklin** [comment]
Just checking in here @seibert , did you end up finding anyone who can help with this?

**Comment by tooptoop4** [comment]
gentle ping @seibert

**Comment by TomAugspurger** [comment]
I looked into this today. Locally, the only one failing was `test_tls`, at https://github.com/apache/airflow/blob/bfce7e9862da15be1955dcb3215ec3491271fe9a/tests/executors/test_dask_executor.py#L128.

That's because the scheduler was being created with the default `tcp://` protocol, and we attempted to connect to it with a Client requiring tls

```
    def _check_encryption(self, address, connection_args):
        if not self.encrypted and connection_args.get("require_encryption"):
            # XXX Should we have a dedicated SecurityError class?
            raise RuntimeError(
                "encryption required by Dask configuration, "
>               "refusing communication from/to %r" % (self.prefix + address,)
            )
E           RuntimeError: encryption required by Dask configuration, refusing communication from/to 'tcp://127.0.0.1:57241'
```

The fix is to specify `protocl=tls` when creating the scheduler and workers

```python
diff --git a/tests/airflow/test_dask_executor.py b/tests/airflow/test_dask_executor.py
index 7564a82ea..79a742f7a 100644
--- a/tests/airflow/test_dask_executor.py
+++ b/tests/airflow/test_dask_executor.py
@@ -125,8 +125,8 @@ class TestDaskExecutorTLS(TestBaseDask):
 
     def test_tls(self):
         with dask_testing_cluster(
-                worker_kwargs={'security': tls_security()},
-                scheduler_kwargs={'security': tls_security()}) as (cluster, _):
+                worker_kwargs={'security': tls_security(), "protocol": "tls"},
+                scheduler_kwargs={'security': tls_security(), "protocol": "tls"}) as (cluster, _):
 
             # These use test certs that ship with dask/distributed and should not be
             #  used in production
```

Is anyone willing / able to apply that diff (along with removing the skip) to apache/airflow?

---

@mrocklin aside from updating the test in airflow, do you think the presence of a `security` kwarg in the scheduler / worker kwargs`distributed.utils_test.cluster` should implicitly set `protocol=tls` in https://github.com/dask/distributed/blob/e928cc0090015a7e07c18d2d64255d33a849224a/distributed/utils_test.py#L462-L464? 

Or maybe, a bit further down in `address_from_user_args`, though perhaps requiring this is a bit better? I haven't used this before.

**Comment by potiuk** [comment]
I am happy to help - but maybe you can just open a PR with that :) I can review and merge it and we will get one more contributor to Airflow :)

**Comment by TomAugspurger** [comment]
This has been fixed in airflow master: https://github.com/apache/airflow/pull/7786

@potiuk if there are issues in the future feel free to ping me or open another issue here.

**Comment by potiuk** [comment]
Thanks @TomAugspurger !!! Great to have support from Dask community on that one :)

**Comment by mrocklin** [comment]
Thanks everyone!

**Comment by mrocklin** [comment]
It's great to see the inter-project bonds between Dask and Airflow
strengthen a bit.  Thanks Jarek for reporting this and Tom for resolving it.

**Comment by semihsezer** [comment]
Hi @dazza-codes and everyone,
I am new to dask and have a few questions around DaskExecutor in Airflow.

What is the main benefit of using DaskExecutor in Airflow? It seems to me that airflow scheduler issues an `airflow run dag_id...` command to Dask scheduler and dask scheduler just assigns it to a worker. This command still needs to do all the airflow database connections, listing/verifying dags, and bringing up a python runtime.

This seems to me not very different than spinning up a new pod using the Kubernetes Executor (which probably takes a few seconds longer). I would guess the real advantage would come from knowing that your runtime environment is a Dask cluster and implicitly leveraging its power, but from the little I know about Dask, it seems to me you still need to create an explicit client connection to dask-scheduler (`client = Client('...:8786')`, which could be done from an Airflow operator/python callable without using the DaskExecutor.

Thanks in advance for any pointers to gaps in my understanding.
