### ISSUE TITLE
Idea: Alias `.compute()` to e.g. `.c`

### ISSUE THREAD

**Issue by asmith26** [dask/dask#5944]
When prototyping code in a Jupyter notebook, I'm often finding myself using `.compute()` to check output.

**Inspired by [numpy transpose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html) which uses the attribute `.T` for `.transpose()`, is it worth adding such an attribute for `.compute()`?**

Of course to stay Pythonic I wouldn't want this to confuse matters. `.c` seems like a possible attribute (I realise if _A_ is a matrix than _A^T_ is the mathematical notation for _A_ transpose, but I don't think there is a meaning for the mathematical notation _A^c_?)

**Comment by quasiben** [comment]
@asmith26 I appreciate the thoughts here but I'm inclined not to add an alias -- at least not at the moment. As you say `.T` is an alias due to historic mathematical notation and while I can see writing `.compute` many many times would be annoying, I think it's good to be explicit in dask about `compute`.   Others may disagree.  Again, thank you for taking the time to write up your thoughts

**Comment by jrbourbeau** [comment]
Thanks @asmith26 for raising this discussion point and your reasoning behind the proposal! I agree with @quasiben that explicit is better in this case though

**Comment by asmith26** [comment]
Thanks for the feedback. I understand the explanations for not doing this for now, hence closing.
