### ISSUE TITLE
Feature Request: Support for deltalake

### ISSUE THREAD

**Issue by ksranga** [dask/dask#6001]
Do you plan to support read (higher priority) and write of deltalake (https://delta.io/) file format? The format is built on top of parquet but supports versions that is useful for data scientist when testing their models as it allows them to use a static version of the data without copying it all over the place

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @ksranga. I'm not familiar with deltalake. Where were you thinking it would fit into the existing API? For dask.dataframe we try to follow the pandas API as closely as possible. So if pandas had something like `pd.read_deltalake(...)` function, then it would be in scope for dask too.

**Comment by mrocklin** [comment]
(FYI @jrbourbeau Deltalake is a Databricks product.  There is some nominal OSS offering, but I don't think I've ever seen it used outside of Databricks).  

@ksranga most solutions like this end up living slightly outside of the Dask project.  If you or someone around you is interested in creating a dask-deltalake OSS project I think that that would be great, and would certainly go a long way to ensuring that data stored in Deltalake can be ready by a variety of systems, rather than just Databricks.

**Comment by ksranga** [comment]
@jrbourbeau - pandas does not support deltalake either.

Deltalake is gaining wider adoption on Azure as well as the spark community especially with the up coming release of Spark 3. So they do have a substantial and feature complete oss offering that you can find here https://github.com/delta-io/delta

I will touch base with a couple of engineers from Databricks regarding your suggestion to create a new project.

**Comment by jrbourbeau** [comment]
Thanks for the additional context @ksranga. I agree with @mrocklin that a seperate `dask-deltalake` (or some other name) package makes sense in this case and would be a valuable contribution to the OSS community. I'm going to close this issue for the time being, but do let us know if you, or anyone else, develops such a package. Thanks again for raising the issue!
