### ISSUE TITLE
Understanding the logic behind the dask graph 

### ISSUE THREAD

**Issue by GTimothee** [dask/dask#6015]
I am trying to find the getitems tasks from any dask graph. 

But I don't understand how dask graph work I cannot find any logic in it. Every time I figured out a way to find the getitem tasks from a dask graph, another case arises where it does not work. 

For example I created a dask array which is a subarray of another dask array and then I add some value to the subarray. It gives me this kind of dependencies in the high level graph: 

```python
>>> graph.dependencies
{'add-73acc6fa036316f013ef6dd6d183981c': {'getitem-e6c984dbea0a737e1d7806e6edec3280'},
 'getitem-e6c984dbea0a737e1d7806e6edec3280': {'array-67c15f6a82a6804f1a55818b002069d2'},
 'array-67c15f6a82a6804f1a55818b002069d2': set()}
```

But then in a task where I am storing data into a file, the dask graph states that there is no dependency at all: 

```python
>>> graph.dependencies
{140567086140704: set(),
 140567034393376: set(),
 140566571770496: set(),
 140567086152032: set(),
 140566571772256: set()}
```
So maybe there is no dependency between the store keys but at least there should be some dependency between the store task and the getitem task which requires the data.

Some help would be greatly appreciated.

**Comment by jrbourbeau** [comment]
@GTimothee could you provide a minimal example (https://blog.dask.org/2018/02/28/minimal-bug-reports) where you generate those graphs?

**Comment by GTimothee** [comment]
Sorry for the time before I answered. I was creating the code snippet because I am implementing a library so I have a lot of high level functions. 

Please find below the link to a jupyter notebook with the sample code: 

https://github.com/GTimothee/dask_io_experiments/blob/master/notebooks/Simple%20working%20example.ipynb

**Comment by TomAugspurger** [comment]
@GTimothee see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for writing a minimal example.

HighLevelGraphs (which is your `graph` object) are documented at https://docs.dask.org/en/latest/high-level-graphs.html

**Comment by GTimothee** [comment]
Hi @TomAugspurger, can you be more clear about what you want me to do, please.
As you can see, @jrbourbeau already gave me the link to the minimal bug reports post. Also I already read the page about high level graph. 

So I don't see why you give me those links again. Can you tell me what you want me to do instead? Do you want me to put the code directly here instead of providing a link? I thought it was simpler to download it directly to test it. I did not provide any data and I provided the minimal code to reproduce exactly the problem I was speaking about so I don't see what more I can do.

**Comment by TomAugspurger** [comment]
Posting code in the issue is better than linking to an external gist or repository. You might delete that repository, and future readers won't be able to follow the issue anymore (I thought that blog post linked to it, but apparently not).

I didn't see where you said you read the docs specifically about HLGs.

**Comment by GTimothee** [comment]
So here is the code:

```python
import dask
import dask.array as da
import h5py

PATH = 'myfirstpath.hdf5'
DATASET_KEY = "/data"

def get_array():
    with h5py.File(PATH, 'r') as f:
        dataset = f[DATASET_KEY]
        return da.from_array(dataset, chunks=(100, 100, 100))

def create_array():
    random_array = da.random.random(size=(500, 500, 500))
    da.to_hdf5(PATH, DATASET_KEY, random_array, chunks=None, compression=None)

create_array()

# case 1:
arr = get_array()
arr = arr[slice(0, 400), slice(0, 200), slice(0, 100)]
arr = arr + 21
graph = arr.__dask_graph__()
print(graph.dependencies)

# case 2:
PATH2 = 'mysecondpath.hdf5'
arr = get_array()
arr_list = [arr[0:100, 0:100, :100], arr[100:200, 0:100, :100], arr[200:300, 0:100, :100]]

datasets = list()
with h5py.File(PATH2, 'a') as f:
    for i, a in enumerate(arr_list):
        key = '/data' + str(i)
        datasets.append(f.create_dataset(key, shape=a.shape))

arr = da.store(arr_list, datasets, compute=False)
graph = arr.__dask_graph__()
print(graph.dependencies)
```

**Comment by mrocklin** [comment]
I'm not sure what's up with the HLG graph structure of the store operation in particular (cc @jakirkham , who wrote most of that code). 

@GTimothee I get the sense that mostly you're frustrated.  I'm sorry to hear that you've been having a hard time.  You've raised a number of specific questions here like "how do I find getitem tasks", "how do I remove unused tasks", as well as some general questions "please help me do the thing that I want to do".  

I'm happy to help answer the specific ones:

1.  There is no absolute standard on getitem tasks today, but generally looking for `key.startswith("getitem")` should be a good start.  I can't give you a more comprehensive solution unfortunately.
2.  For removing unused tasks we use the `cull` optimization (see docs).  

In general, it sounds like you're getting tripped up on high level graphs.  If you're making a custom optimization then you might not want to deal with high level graphs, but instead with lower level graphs.  These tend to be created about halfway through the optimization pipeline (again, see docs).  If you want to play around with things though, you can call `dict` on a high level graph.

```python
dsk = dict(x.__dask_graph__())
```

I'm not sure how else to help you with your general problem.  Instead of raising an issue that says "I don't get how things work, they don't make sense" I recommend instead raising an issue explaining your overall goal 

> "I'm trying to query data as efficiently as possible from this particular data storage solution, but I find that things are slow.  Here is a minimal example." 

This helps us to understand why your query is important, and why maintainers should devote time to it, which should help you to get time from a volunteer workforce.

**Comment by jakirkham** [comment]
Looking at the code above, I wouldn't expect this to work. The `h5py.File` object will be invalid by the time Dask uses it. We could probably walk through how to improve the code, but there are quite a few people that have already done this work and packaged it.

So would actually look to their solutions just to avoid further hang-ups. One option might be [h5pickle]( https://github.com/exteris/h5pickle ), which gives you an object that should compose nicely with Dask and Dask Array. Another would be [xarray]( https://github.com/pydata/xarray ), which actually is a full library that leverages Dask under-the-hood. Which choice would be reasonable is up to you.

**Comment by GTimothee** [comment]
Thank you for your answers, I will see what I can do with this information and I will come back with more precise questions, if any.
