### ISSUE TITLE
Question/Feature Request/PR offer - passing **kwargs to compute() within to_parquet()

### ISSUE THREAD

**Issue by KrishanBhasin** [dask/dask#6026]
In the final steps of dataframe's `to_parquet()` method, `.compute()` is called to trigger the write action:
https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet/core.py#L455-L457

Is there a reason that there are no **kwargs passed in to the `.compute()` method?

**Context:**
I am doing some work on the delayed dataframe to apply resource constraints to certain tasks, and would like to ensure those tasks hang around after I call `to_parquet()`.

I am aware that I could pass in `compute=False`, and then manually call `.compute(optimize_graph=False)` on the returned object, but I think it would be neater if we could pass the kwargs straight through to the `to_parquet()` function.

If there are no objections, I can make a PR to this effect :)

**Comment by mrocklin** [comment]
It looks like that function also passes `kwargs` to the underlying Parquet engine (pyarrow, fastparquet, cudf).  So it might get a bit complicated to pass some kwargs there and the others to compute.  

In hindsight, it probably would have been better to add an explicit `compute_kwargs=...` keyword rather than depend on `**kwargs`.

> If there are no objections, I can make a PR to this effect :)

I think that this change would be good if there is good precedent that other dask dataframe operations, like `to_csv` or `to_hdf` do this.  Otherwise, I would suggest something like a `compute_kwargs`.  Whatever choice we make it should be consistent for all of the saving methods.

(also, thank you for offering to help, regardless)

**Comment by KrishanBhasin** [comment]
I'm happy to contribute the `compute_kwargs=...` changes to the different dataframe `to_...` methods in one larger PR,  or many smaller ones (guidance wanted on this).

I wonder if trying to pass the kwargs around everywhere would be a more complicated change to make.

**Comment by mrocklin** [comment]
The first step to this is to look at the other methods like to_csv and
to_hdf and see what they do.  That will inform what we should do here.

**Comment by KrishanBhasin** [comment]
It looks like it would be relatively simple to pass `compute_kwargs=...` to `to_csv()`, `to_parquet()`, and `to_json()`, as they all end in a `.compute()` call.

`to_hdf()` does some stuff with `compute_as_if_collection()`; after dropping down the chain I can't see it call `.compute()` directly.

`compute_as_if_collection()` looks like it does something to pick up a scheduler, optimise the graph, and then return the computed object? I'm not really sure what happens here, or what this compute kwargs change might look like for it.


```python
def compute_as_if_collection(cls, dsk, keys, scheduler=None, get=None, **kwargs):
    """Compute a graph as if it were of type cls.

    Allows for applying the same optimizations and default scheduler."""
    schedule = get_scheduler(scheduler=scheduler, cls=cls, get=get)
    dsk2 = optimization_function(cls)(ensure_dict(dsk), keys, **kwargs)
    return schedule(dsk2, keys, **kwargs)
```
