### ISSUE TITLE
Specify a set of Dask workers to use for a specific process.

### ISSUE THREAD

**Issue by chinmaychandak** [dask/dask#6095]
Let's say I have a Dask scheduler with 3 Dask workers (each worker is a process) set up.

I have 3 streaming jobs, each needing 1 Dask worker each. If I use the same Dask cluster to share all the 3 streams, the jobs switch between the Dask workers across batches, which I don't want.

Is there a way I can specify the number of workers/the name of workers for each stream, so that each stream gets its own dedicated set of worker(s)? 

Creating 3 different schedulers, and attaching one worker to each works well, but I was thinking if there is a more convenient way to achieve sharing a cluster among jobs.

FYI: I am using [streamz](https://github.com/python-streamz/streamz) to write streaming jobs.

**Comment by jcrist** [comment]
I'm not sure about `streamz`, but tasks can be bound to workers (or sets of workers) by passing a list of workers to methods like `Client.submit` or `Client.compute` (docs [here](https://distributed.dask.org/en/latest/locality.html#user-control)).

**Comment by mrocklin** [comment]
In principle we should be able to trust that Dask is running tasks in the
best place for them to run.  It takes into account things like the cost of
moving data, and the backlog on every worker.  If it is making bad choices
here then it's probably a good idea to figure out why, rather than
explicitly pinning workers (which is often bad in the long run).  A common
cause to investigate is whether or not the dask.sizeof.sizeof
function returns the right size for your objects.  If that is wrong (too
low) then Dask may move things around when it shouldn't.

**Comment by mrocklin** [comment]
Also, it's worth noting that most Dask maintainers don't know anything
about streamz.  If you can reduce your situation to a Dask-only problem my
guess is that you'll get better feedback from folks here.

**Comment by chinmaychandak** [comment]
Thanks @jcrist, @mrocklin! I'll try both options — pinning workers using the docs provided above, and allowing Dask to handle the jobs by itself and see how it performs.

**Comment by chinmaychandak** [comment]
I also have a use case where one of the jobs needs a higher worker memory limit like 8GB, while the other two jobs need around 4GB. Maybe that's why I thought it was best to pin workers.

**Comment by TomAugspurger** [comment]
I think the original questions have been answered, so closing this.
