### ISSUE TITLE
dask.pad does not work with cupy arrays

### ISSUE THREAD

**Issue by izaid** [dask/dask#6117]
The following throws an exception with `cupy`, but works fine with `numpy`.

```
import numpy as np
import cupy as cp

import dask.array as da

x = cp.random.randn(128, 128, 128)

da.pad(x, tuple((0, x.shape[dim]) for dim in range(x.ndim)), mode = 'constant')
```

Note that `cupy` supports the pad function.

**Comment by mrocklin** [comment]
@izaid thanks for raising.  cc @pentschev and @quasiben from NVIDIA in case they have time to test this out.

**Comment by pentschev** [comment]
`da.pad` is currently not supported for the lack of ability of creating temporary CuPy arrays with `__array_function__`.

**Comment by mrocklin** [comment]
Ah, that makes sense.  Thanks @pentschev .  Is there a related issue either on cupy or numpy that you can link here in case @izaid wants to keep track?  (I should probably know where this conversation is happening, but unfortunately I've lost track myself)

**Comment by pentschev** [comment]
The only one I'm aware is https://github.com/dask/dask/issues/4731, but it has been stalled for quite some time, mostly due to the inability to create arrays with `__array_function__`. Since that's a limitation of NumPy, there's not much that can be done for the next few months at least. There are proposals to address that and the community is discussing that lately:

- https://numpy.org/neps/nep-0035-array-creation-dispatch-with-array-function.html
- https://numpy.org/neps/nep-0037-array-module.html

**Comment by pentschev** [comment]
FYI, this is resolved in https://github.com/dask/dask/pull/6738 , hopefully that will be merged soon.

**Comment by jsignell** [comment]
Thanks @pentschev! Seems like this can be closed :)
