### ISSUE TITLE
roll operation changes chunksize

### ISSUE THREAD

**Issue by MaximilianHoffmann** [dask/dask#6209]
Is this a bug?

When applying  rolling operation the chunksize changes.
I would expect it to stay constant.

Example:
```
import dask.array as da
from dask.array import roll
import numpy as np
chunks=(64,64,64)
data=da.from_array(np.random.randn(125, 194, 125).astype('single'),chunks=chunks)
print(data.chunksize)
data_r=roll(data,[-2,-2,-2],axis=[0,1,2])
print(data_r.chunksize)
```
Output:
```
(64, 64, 64)
(62, 64, 62)
```

Possibly related to [this](https://github.com/pydata/xarray/issues/3277)

Dask version is 2.16.0

**Comment by jcrist** [comment]
This is not a bug. The `.chunksize` attribute can be a bit misleading, since dask arrays can be composed of multiple arrays, each with different chunks. I recommend looking at the `chunks` attribute instead:

```python
In [10]: data.chunks
Out[10]: ((64, 61), (64, 64, 64, 2), (64, 61))

In [11]: data_r.chunks
Out[11]: ((62, 61, 2), (62, 64, 64, 2, 2), (62, 61, 2))
```

Each tuple is the chunking along one axis. Here we can see that the roll operation took a chunk of `2` off the beginning of each axis (`64` -> `62`), and appended it to the end of each axis (the new `2` on the end).

We don't want to rechunk so that things are aligned automatically, as that would require moving all of the data around (which could be expensive!). For most uses this is fine - dask array should be agnostic to chunking. If you do need the output to be chunked explicitly, you can use `array.rechunk` to do so yourself.

Does that make sense?

**Comment by MaximilianHoffmann** [comment]
That makes sense. So chunksize is displayed as max(chunks) ? And can I therefore fully fragment the array by repeated calls to roll?

**Comment by jcrist** [comment]
The `chunksize` attribute is defined as:

```python
    @property
    def chunksize(self):
        return tuple(max(c) for c in self.chunks)
```

> And can I therefore fully fragment the array by repeated calls to roll?

Meaning break an array that was chunked in large chunks into many smaller chunks by repeatedly calling roll? Yeah. Since that would be application specific, we'd leave it up to you to periodically `rechunk` to avoid having many many small chunks. Dask works with small chunks, but ideally you want each task to take at least a 1 ms (so the overhead of dask is low in comparison), and small array tasks generally run much faster than that.

**Comment by MaximilianHoffmann** [comment]
Alright, thanks taking the time to explain this.
I'll close the issue.
