### ISSUE TITLE
dd.to_parquet() duplicates graph execution

### ISSUE THREAD

**Issue by noreentry** [dask/dask#6232]
Writing 2 dataframes in parallel using `.to_parquet()` runs excessive execution of source tasks:
``` python
import dask
import dask.dataframe as dd
import numpy as np
import pandas as pd

calls = 0
def get_2df():
    global calls
    calls += 1
    return pd.DataFrame(np.zeros((100, 1), dtype=np.uint8), columns=['a']), \
           pd.DataFrame(np.zeros((100, 1), dtype=np.uint8), columns=['a'])

calls = 0
dfs = dask.delayed(get_2df)()
df1 = dd.from_delayed(dfs[0], meta=pd.DataFrame({'a': [1]}, dtype='uint8'))
df2 = dd.from_delayed(dfs[1], meta=pd.DataFrame({'a': [1]}, dtype='uint8'))
df3 = dd.concat([df1, df2])
f1 = df3.to_parquet('foo1', write_index=True, engine='fastparquet', compute=False)
dask.compute([f1])
assert calls == 1  # that's ok

calls = 0
dfs = dask.delayed(get_2df)()
df1 = dd.from_delayed(dfs[0], meta=pd.DataFrame({'a': [1]}, dtype='uint8'))
df2 = dd.from_delayed(dfs[1], meta=pd.DataFrame({'a': [1]}, dtype='uint8'))
f1 = df1.to_parquet('foo1', write_index=True, engine='fastparquet', compute=False)
f2 = df2.to_parquet('foo2', write_index=True, engine='fastparquet', compute=False)
dask.compute([f1, f2])
assert calls == 1  # NO! calls == 2
```

**Comment by jsignell** [comment]
Thanks for writing this up! I agree it isn't intuitive, but I'm not sure that this is a bug. In the second case the task graphs for f1 and f2 are entirely separate so they can't know to share the output of dfs unless you do some persistence. If you instead do: `dfs = dask.delayed(get_2df)().persist()` then you will see that `get_2df` is only called once.

**Comment by mrocklin** [comment]
> so they can't know to share the output of dfs unless you do some persistence.

Actually, I think that this is a genuine issue.  Dask schedulers merge graphs before running, so ideally we would recognize that `dfs` is shared here and run it only once.  In general Dask tries to identify common tasks in complex computations and run them only once.

I suspect that the issue here is that `to_parquet` converts a dataframe computation into a delayed computation, which triggers an optimization pass, which ends up fusing the `dfs` task with the getitem tasks.  This fusion makes it harder for the later call of `dask.compute` to properly identify that these tasks are related.

One way to check this would be to turn off fusion and try again.  I suspect that it will operate as desired.

```python
dask.config.set({"optimization.fusion.active": False})
```

If my guess here is correct, then the long term fix for this is probably to only optimize when we call compute, rather than during intermediate stages like `to_parquet`.  That can get complicated though.

**Comment by jsignell** [comment]
Oh cool! Thanks for the explanation. I didn't know that the scheduler did that. 

You are correct that turning off optimization in the config results in the expected behavior (although the key to set to false is "optimization.fuse.active"). I wonder if there could be a way that `to_parquet` could suggest optimization for particular tasks and return that as metadata that can either be used or not used based on ta kwarg in `compute`. Or perhaps a better approach would be to include an `optimize_graph` kwarg in `to_parquet`.

**Comment by mrocklin** [comment]
The challenge here is that we currently call an optimize method based on the class of the thing that we are computing.  If the thing that we're computing is a dask.delayed object (like what to_parquet(compute=False) returns) then we call the delayed optimization function.  Unfortunately, that optimization function doesn't know anything about dataframes.  Things like operator fusion or column selection in read_parquet.  

Ideally we would only optimize at the end when we call compute/persist, and we would optimize every layer in the graph based on where that layer came from (was it a dataframe or an array or a delayed layer).  Unfortunately we don't currently store this data on each layer of the graph, and so the best that we can do is optimize whenever we transition from one kind of collection to another, which in this case has the unfortunate consequence of fusing early.

cc @TomAugspurger and @gforsyth who are thinking about high level query optimization.

**Comment by dhirschfeld** [comment]
> Unfortunately we don't currently store this data on each layer of the graph

Maybe annotations could help with this? (https://github.com/dask/dask/pull/6217)

**Comment by mrocklin** [comment]
This is something that we would want to handle higher up I think on the HighLevelGraph layer.

**Comment by jsignell** [comment]
I am wondering whether #6222 is related to this or will exacerbate this kind of issue.

**Comment by ian-r-rose** [comment]
`dd.to_parquet()` has been rewritten to use blockwise in #8487, and no longer goes through `Delayed`. The original reproducer now works as as expected. Thanks all!
