### ISSUE TITLE
Latest Dask 2.21: ImportError:  LZ4 must be installed everywhere or nowhere

### ISSUE THREAD

**Issue by vinhdiesal** [dask/dask#6455]
The latest `pip install -U dask` which is 2.21 results in the following error when trying to establish a client.
Also `pip install -U distributed` requires you to downgrade `pyqt5<5.13` and `pyqtwebenginer>5.13`.

```
Latest Dask 2.21: ImportError:  LZ4 must be installed everywhere or nowhere
```
When I install `pip install -U dask` last week, this error didn't occur. 

Thanks, 

vinhdiesal

**Comment by gforsyth** [comment]
@vinhdiesal -- it looks like you are trying to upgrade dependencies on the client without also upgrading those same dependencies on your workers.  That's the error you are getting, that you have `LZ4` installed on some combination of workers + client but not on all of them.

These sorts of usage questions are probably better posed over on Stack Overflow.  If you have a bug you would like to report, please put together a minimum reproducible example so that the maintainers can more easily find the bug.

You can read https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports for more info.
