### ISSUE TITLE
COMPAT: expand `parse_dates` keyword in `dataframe.read_csv`

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#661]
I had a need for this today,

```python
In [6]: !cat tst.csv
date,a
2015-01-01,1
2015-01-02,2

In [7]: pd.read_csv('tst.csv', index_col='date', parse_dates=True).index.dtype
Out[7]: dtype('<M8[ns]')

In [8]: pd.read_csv('tst.csv', index_col='date', parse_dates=['date']).index.dtype
Out[8]: dtype('<M8[ns]')

In [9]: dd.read_csv('tst.csv', index_col='date', parse_dates=['date']).index.dtype
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-c65944acae21> in <module>()
----> 1 dd.read_csv('tst.csv', index_col='date', parse_dates=['date']).index.dtype

...

ValueError: 'date' is not in list
```

FWIW, I've never been a fan of the `parse_dates=True` option in `In [7]`, especially when working with MultiIndexes where only one level is datetime (my actual case).

I *might* be able to carve out some time for it today or early next week.

**Comment by mrocklin** [comment]
The problem here might not be `parse_dates`, but rather `index_col`.  At the moment there is no way to tell dask.dataframe that a particular column within the csv file is the index or is a sorted index.

To do this *well* we would want to read a little bit of the csv file at all of the lines where we break on partitions to get the index value at that point.  This is important because we can use these values to populate `.divisions` which helps us with a lot of parallel logic.

If we're dumb and willing to accept a full read and shuffle then the following would work, but would incur startup time.

```python
In [1]: import dask.dataframe as dd

In [2]: df = dd.read_csv('tst.csv', parse_dates=['date']).set_index('date')

In [3]: df.compute()
Out[3]: 
            a
date         
2015-01-01  1
2015-01-02  2

In [4]: df.index.compute().dtype
Out[4]: dtype('<M8[ns]')
```

**Comment by mrocklin** [comment]
Parse_dates works well, index_col doesn't on CSV (this is hard).  This issue occurs in other places.  Closing this for now.

**Comment by 3ggaurav** [comment]
Hey Tom, 

Just checked in your dataframe , there is a column having name 'date' or not. You have to pass column name list in parse_dates attribute to parse the values of that column in datetime format. Thanks.
