### ISSUE TITLE
`in` operator for char arrays not working with master branch anymore

### ISSUE THREAD

**Issue by mraspaud** [dask/dask#6611]
**What happened**:

Using the latest (and greatest) master branch, checking if a char element is in a dask array seems to always return False.
With ints it works correctly.

**What you expected to happen**:

I was expecting the check to tell me the truth about the requested char being in the array.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da
'R' in da.array(['R', 'G', 'B'])
# evaluates to False
```

**Anything else we need to know?**:
This was working in 2.9.2, and works with ints at least.

**Environment**:

- Dask version: Master branch
- Python version: 3.8.5
- Operating System: RHEL8
- Install method (conda, pip, source): pip from github

**Comment by TomAugspurger** [comment]
Thanks for the report. 0ca1607aa14cb81520ca9526f871b631fe6706fa looks to be the culprit (cc @jthielen if you have time to look)

**Comment by TomAugspurger** [comment]
If I had to guess...

1. dask.array.Array doesn't implement `__contains__`, so Python falls back to `__getitem__` and `__eq__`
2. This looks fishy

```python
In [2]: import dask.array as da
   ...: a = da.array(['R', 'G', 'B'])

In [3]: 'R' == a[0]
Out[3]: False
```

Previously that returned

```python
In [2]: 'R' == a[0]
Out[2]: dask.array<eq, shape=(), dtype=bool, chunksize=(), chunktype=numpy.ndarray>
```

which evaluated to True.

**Comment by jthielen** [comment]
Interesting!

In https://github.com/dask/dask/pull/6393 I only considered numeric scalars, so non-numeric scalars like strings were ignored. The "easy" fix for this particular issue would be to add `str` to the check here:

https://github.com/dask/dask/blob/0ca1607aa14cb81520ca9526f871b631fe6706fa/dask/array/core.py#L170-L188

But, I'm not sure if there needs to also be more careful handling of any other non-numeric scalars or not?

For what it's worth, I think `'R' == a[0]` being `False` comes from them both returning `NotImplemented`, which seems to be interpreted as `False` instead of raising the usual error.

**Comment by mraspaud** [comment]
> And IIUC, a' in dask.array.Array is going to be extremely inefficient, since you'll be recomputing a bunch of stuff for each element :) You may be better off avoiding it for good.

Noted. Thanks for looking into this!

**Comment by ravwojdyla** [comment]
I run into this as well on the Dask version that was released yesterday. I haven't noticed this issue, so I have opened #6631 and debugged it there. As I point out in #6631, #6393 has much larger consequences to non-scalars than just `in`/`eq` operator. afaiu essentially "all" dunder/operator methods on Dask array and non-scalar won't delegate to Dask anymore.
