### ISSUE TITLE
Concatenating then rechunking zarr files uses lots of memory

### ISSUE THREAD

**Issue by tomwhite** [dask/dask#6745]
**What happened**:

The following example produces four 10GB zarr files on disk, chunked into 20 chunks along two axes. The goal is to combine them into a single zarr file, along the first axis. This can be done by concatenating the arrays, then rechunking them before saving as a zarr file.

In each of the four input files, the final chunk on the first axis is smaller than the chunk size, so concatenating them produces non-uniform chunks, which is why the rechunk step is needed, as zarr requires uniform chunk sizes. This diagram gives an idea of what is happening:

![concat and rechunk](https://user-images.githubusercontent.com/85085/96447587-0652e180-120a-11eb-9647-9df9cfcc4675.png)

The code to do this works in some cases, but uses a lot of memory, and in other cases does not complete since the system memory is overwhelmed.

**What you expected to happen**:

I would like a way of running this computation with modest memory requirements - e.g. a small multiple of the chunk size.

**Minimal Complete Verifiable Example**:

```python
import dask
import dask.array as da
from dask.diagnostics import ProgressBar
import zarr

# create data on disk
x = da.zeros((20 * 500_000 + 100_000, 20 * 50), chunks=(500_000, 50))
da.to_zarr(x, "data/x1.zarr", overwrite=True)
da.to_zarr(x, "data/x2.zarr", overwrite=True)
da.to_zarr(x, "data/x3.zarr", overwrite=True)
da.to_zarr(x, "data/x4.zarr", overwrite=True)

# read
x1 = da.from_zarr("data/x1.zarr")
x2 = da.from_zarr("data/x2.zarr")
x3 = da.from_zarr("data/x3.zarr")
x4 = da.from_zarr("data/x4.zarr")

# concatenate
x = da.concatenate([x1, x2, x3, x4], axis=0)

# rechunk uniformly (so we can save as zarr)
x = x.rechunk(x.chunksize)

# create empty store to save as zarr
store = zarr.DirectoryStore("store/out_big")
root = zarr.group(store, overwrite=True)
dest = root.empty_like(name="dest", data=x, chunks=x.chunksize, overwrite=True)

# inline roots of graph, see https://github.com/dask/dask/issues/6668
def custom_optimize(dsk, keys):
    print("running custom optimize")
    dsk = dask.optimization.inline(dsk, inline_constants=True)
    return dask.array.optimization.optimize(dsk, keys)


with dask.config.set(array_optimize=custom_optimize):
    d = x.store(dest, lock=False, compute=False)
    with ProgressBar():
        d.compute()
```

This example uses well over 40GB of memory (on 4 cores), even though the chunks are 200MB in size. The following shows a portion of the task graph:

![min-example-order](https://user-images.githubusercontent.com/85085/96448385-351d8780-120b-11eb-8156-2363484907e7.png)

Produced with this code:
```python
with dask.config.set(array_optimize=custom_optimize):
    x = x[-3*500_000:,:2*50]
    d = x.store(dest, lock=False, compute=False)
    dask.visualize(d, filename=f"min-example-order", optimize_graph=True, verbose=True, color="order", cmap="autumn", node_attr={"penwidth": "4"})
```

The numbers in circles are the order the tasks run in (red = earlier, yellow = later). It's clear that the lack of alignment in the chunking causes chains of tasks. So `x[n][0]` are all linked to each other in one chain, `x[n][1]` are in another, etc. These chains are processed concurrently (and with the example above there are 20 of them), and each chain will keep a (presumably small) number of zarr chunks in memory. The problem is that some chunking schemes can easily overwhelm memory.

**Anything else we need to know?**:

I came up with a workaround that uses a "pull" scheme, where the target array is filled in by pulling data from the relevant source chunks. The downside is that each zarr chunk has to be read twice (although it's no slower overall on local disks), but the main advantage is that everything is very parallelizable, and runs with modest memory requirements (<2GB for this example).

![min-workaround-order](https://user-images.githubusercontent.com/85085/96450448-2389af00-120e-11eb-92f1-d64b67ed2490.png)

```python
z1 = zarr.open("data/x1.zarr")
z2 = zarr.open("data/x2.zarr")
z3 = zarr.open("data/x3.zarr")
z4 = zarr.open("data/x4.zarr")

# concatenate and rechunk uniformly (so we can save as zarr)
x = concatenate_and_rechunk([z1, z2, z3, z4])
```

The code for `concatenate_and_rechunk` is [here](https://github.com/tomwhite/sgkit/commit/9ff4004dea705f9a9ef2e2f68a6987472f13a09c), however it works at the level of zarr files, making it hard to use with xarray for example (I'd like to be able to concatenate and rechunk whole datasets).

Is there a better way of doing this with Dask?

**Environment**:

- Dask version: 2.30.0
- Python version: 3.7
- Operating System: OS X
- Install method (conda, pip, source): pip

**Comment by TomAugspurger** [comment]
Thanks for writing the issue up. I'm hoping to give it some thought today.

**Comment by TomAugspurger** [comment]
This is an interesting one! (cc @eriknw if you want to follow along for fun). The task graph generated by `da.store` contains a curious element: `store-<token>`, which depends on the *list* of `('store-<token>', i, j)` tasks. Here's a slightly simpler (smaller) problem that I think illustrates the issue:

```
import numpy as np
import dask.array as da
import zarr
import dask

arrays = [da.from_array(np.ones((110, 4)), chunks=(100, 2)) for i in range(4)]
x = da.concatenate(arrays, axis=0).rechunk((100, 2))

store = zarr.DirectoryStore("store/out_big")
root = zarr.group(store, overwrite=True)
dest = root.empty_like(name="dest", data=x, chunks=x.chunksize, overwrite=True)
d = x.store(dest, lock=False, compute=False)

dsk = dict(d.dask)
dask.visualize(dsk, filename="bad", optimize_graph=True, verbose=True, color="order", cmap="autumn", node_attr={"penwidth": "4"})
```

![bad](https://user-images.githubusercontent.com/1312546/97053674-fbb98480-1548-11eb-8888-7e236e7519bc.png)

So we jump from the left side (`11`) to the right half (`14`)

Here's that dependency that's a list of keys

```python
>>> dsk[d.key]
[('store-d726c9c8-1572-11eb-aa4a-82170c0955c0', 0, 0),
 ('store-d726c9c8-1572-11eb-aa4a-82170c0955c0', 0, 1),
 ('store-d726c9c8-1572-11eb-aa4a-82170c0955c0', 1, 0),
 ('store-d726c9c8-1572-11eb-aa4a-82170c0955c0', 1, 1),
 ('store-d726c9c8-1572-11eb-aa4a-82170c0955c0', 2, 0),
 ('store-d726c9c8-1572-11eb-aa4a-82170c0955c0', 2, 1),
 ('store-d726c9c8-1572-11eb-aa4a-82170c0955c0', 3, 0),
 ('store-d726c9c8-1572-11eb-aa4a-82170c0955c0', 3, 1),
 ('store-d726c9c8-1572-11eb-aa4a-82170c0955c0', 4, 0),
 ('store-d726c9c8-1572-11eb-aa4a-82170c0955c0', 4, 1)]
```

If we change that to a tuple, what do we get?


```python
dsk[d.key] = tuple(dsk[d.key])
dask.visualize(dsk, filename="good", optimize_graph=True, verbose=True, color="order", cmap="autumn", node_attr={"penwidth": "4"})
```

![good](https://user-images.githubusercontent.com/1312546/97053759-260b4200-1549-11eb-82a0-64735845ad1e.png)

Now all the tasks on the left half finish first. I'll see why things are like that, and if changing it fixes things.

**Comment by eriknw** [comment]
Oh, so weird that one weakly connected graph isn't traversed in entirety before the next one.  That shouldn't be happening.  I'm curious what you'll find @TomAugspurger, and let me know if you'd like me to take a look.

**Comment by TomAugspurger** [comment]
Here's the basic summary of where things go wrong for this task graph


![mydask](https://user-images.githubusercontent.com/1312546/97118119-3bfa3d80-16d6-11eb-9ee3-2028e91637ff.png)



We process through `('store',
0, 0)` and then see that we have a single remaining dep: `'store'`, so we want
to finish that immediately. We discover that `store` has four dependencies.

```
(Pdb) pp item, dependencies[item]
('store', {('store', 0, 1), ('store', 1, 0), ('store', 1, 1), ('store', 0, 0)})
```

We've finished `('store', 0, 0)`. Ideally `('store', 1, 0)` would be next, since
we already have some of it's dependents in memory `('c', 3, 0)`, the root of
`(store, 0, 0)` and `(store, 1, 0)`. When considering the remaining three
stores, we unfortunately tie and fall back to the key as a tie-breaker:

```
(Pdb) deps
{('store', 0, 1), ('store', 1, 0), ('store', 1, 1)}
(Pdb) pp list(map(dependencies_key, deps))
[(-21, 2, 21, 2, -5, 1, 1, 2, <dask.order.StrComparable object at 0x11291d9d0>),
 (-21, 2, 21, 2, -5, 1, 1, 2, <dask.order.StrComparable object at 0x1120671f0>),
 (-21, 2, 21, 2, -5, 1, 1, 2, <dask.order.StrComparable object at 0x1120675b0>)]
```

Which gives this order:

```
(Pdb) sorted(deps, key=dependencies_key, reverse=True)
[('store', 1, 1), ('store', 1, 0), ('store', 0, 1)]
```

Again, we'd like to take `('store', 1, 0)`, but it's in the middle (thanks to
the name being the tiebreaker).

How to resolve this? I'm not really sure yet. We do have the start of the
chain in the `min_pool`, so perhaps that could be considered?
```
(Pdb) pp min_pool
[('b', 48), ('b', 41)]
```

Though seeing that `('store', 1, 0)` is eventually a dependency of `(b', 41)`
isn't exactly obvious.

Here's a test

```python
def test_list_final():
    # https://github.com/dask/dask/issues/6745
    # da.store(...) generated a task graph with several
    # (store, i, j) tasks and the result is a final
    # "store-<token>: ([("store", 0, 0), ("store", 0, 1), ...]"
    # The presence of this final key negatively affected the
    # ordering
    dsk = {
        ("store", 0, 0): (f, ("a", 0, 0)),
        ("a", 0, 0): (f, ('b', 40), ('b', 41)),
        ("b", 40): (f,),
        ("b", 41): (f, ("c", 3, 0)),
        ("c", 3, 0): (f, ),

        ("store", 1, 0): (f, ("a", 1, 0)),
        ("a", 1, 0): (f, ('b', 4, 0), ('b', 48)),
        ("b", 4, 0): (f,),
        ("b", 48): (f, ("c", 3, 0)),

        # right half
        ("store", 0, 1): (f, ("a", 0, 1)),
        ("a", 0, 1): (f, ('b', 42), ('b', 43)),
        ("b", 42): (f,),
        ("b", 43): (f, ("c", 3, 1)),
        ("c", 3, 1): (f, ),
        ("store", 1, 1): (f, ("a", 1, 1)),
        ("a", 1, 1): (f, ('b', 4, 1), ('b', 50)),
        ("b", 4, 1): (f,),
        ("b", 50): (f, ("c", 3, 1)),
    }
    assert dsk
    o = order(dsk)
    dsk2 = dict(dsk)
    stores = [x for x in dsk if x[0] == "store"]
    dsk2["store"] = stores
    o2 = order(dsk2)

    final = o2.pop("store")
    assert final == 18
    assert o == o2
```

**Comment by tomwhite** [comment]
Thank you for investigating this @TomAugspurger!

When you change the store key from a list to a tuple the visualization shows the desired ordering, but I couldn't see a way of getting `compute` to use this ordering. (I was wondering if there was a workaround that could involve mutating the task graph in the way you suggested.) Or is the problem that even if the store uses a tuple, when running the computation the ordering is not honoured due to the way ties are broken?

**Comment by TomAugspurger** [comment]
> When you change the store key from a list to a tuple the visualization shows the desired ordering, but I couldn't see a way of getting compute to use this ordering.

A quick fix is something like this I think:

```diff
diff --git a/dask/array/core.py b/dask/array/core.py
index 75ce9d5a0..363c35fdc 100644
--- a/dask/array/core.py
+++ b/dask/array/core.py
@@ -986,9 +986,8 @@ def store(
         return result
     else:
         name = "store-" + str(uuid.uuid1())
-        dsk = HighLevelGraph.merge({name: store_keys}, store_dsk)
+        dsk = HighLevelGraph.merge({name: (_store_finalize, tuple(store_keys))}, store_dsk)
         result = Delayed(name, dsk)
-
         if compute:
             result.compute(**kwargs)
             return None
@@ -996,6 +995,10 @@ def store(
             return result
 
 
+def _store_finalize(*store_keys):
+    return list(store_keys)
+
+
 def blockdims_from_blockshape(shape, chunks):
     """
 
```


That avoids the taking the "Fast path" in https://github.com/dask/dask/blob/81c24bf05ed59394424527900ae60662c3bb8fa1/dask/order.py#L335-L344 when we get to the `store` key, which isn't actually fast in this case, since there are now many `deps` to finish it.

Perhaps we proceed with the quick fix for now, and consider whether we need bigger changes to `order` as a followup (e.g. traversing lists of `deps`?). I'll make sure that change doesn't break anything at the least.

**Comment by TomAugspurger** [comment]
Hmm, apparently that quick fix doesn't quite do it. I'll continue to investigate.

**Comment by TomAugspurger** [comment]
I'm not really seeing an easy way to solve this ordering problem. I briefly considered messing with the keys of the `store` task to ensure that they broke ties correctly, but we don't really know the relationship between the original `from_zarr` tasks and the `store` keys.

**Comment by TomAugspurger** [comment]
@tomwhite one other config that may be worth investigating is the `optimization.fuse.ave-width` setting. On a smaller version of your problem (chunksize of 50,000 instead of 500,000)

```python
cfg = {"array_optimize": custom_optimize, "delayed_optimize": custom_optimize,
       "optimization.fuse.ave-width": 12}
with dask.config.set(cfg):
    y = x[-3*50_000:,:2*50]
    d = y.store(dest, lock=False, compute=False)
    display(dask.visualize(d, filename=f"min-example-order", optimize_graph=True, verbose=True, color="order", cmap="autumn", node_attr={"penwidth": "4"}))
```

![min-example-order](https://user-images.githubusercontent.com/1312546/97359874-73e6b980-186b-11eb-9764-c66a069facfe.png)

That fuses all the `from_zarr - rechunk - store` tasks into one big task, and so dask never has the chance to make the "wrong" choice on which store task to handle next.

The downsides are that

1. You need to fit all of that chain in memory at once, which might not be possible for too large of source chunks
2. You need to correctly choose the ave-width, which is problem-specific

**Comment by tomwhite** [comment]
Thanks for the additional comments @TomAugspurger - it's a shame that there doesn't seem to be an easy fix.

I did try playing with `optimization.fuse.ave-width` at the beginning, but didn't manage to get it to produce any improvement.

Why did you pick 12 in this case? I can't see where that comes from. Would this work when rechunking multiple arrays at once (the xarray case) - or would they have different values for ave-width?

**Comment by TomAugspurger** [comment]
> I did try playing with optimization.fuse.ave-width at the beginning, but didn't manage to get it to produce any improvement.

Guess and check :) I thought 4 would do it, but apparently not.

I did have a probably awful idea. Dask does perfectly fine when there's no root node that's a common dependent of everything (`'store-<token>'` in this case). What if we... just ignored it? I'll put up a PR :)

**Comment by alimanfoo** [comment]
Thanks everyone for following this up. I'm following this at a distance and not fully grokking all aspects, so apologies if my comments are off. 

If there is a straightforward change that can be made to the ordering algorithm that resolves this issue then that would seem great and worth pursuing. 

I wondered if it might be worth also considering another point, which is that in general it might be a better solution to somehow mark the tasks which read from the input zarr as recomputable. I.e., provide a general way (if one does not already exist) to tell dask that it is relatively cheap to recompute those tasks, and so should prefer to do so rather than caching the results in memory and attempting to reuse them. I am wondering if this may be particularly true when executing on a distributed cluster, because even if the ordering of tasks is improved, there is no (?) guarantee that tasks with a shared input will get scheduled on the same cluster node, meaning that data will have to be moved between worker nodes. I have no sense of how good dask is at scheduling tasks intelligently to worker nodes to minimise data movement. But if you do start moving data between worker nodes, you might as well have each node reread the data from the source zarr instead. I.e., the cost of moving data between workers is probably (?) similar to the cost of reading it directly from object storage.

I.e., would it make sense to provide a dask way of achieving what @tomwhite implemented manually in his [concatenate_and_rechunk](https://github.com/tomwhite/sgkit/commit/9ff4004dea705f9a9ef2e2f68a6987472f13a09c) function.

There of course could be some situations where this might be a bad idea, e.g., where each zarr chunk ends up being read >>2 times. But just wondering if this is worth considering.

**Comment by mrocklin** [comment]
> which is that in general it might be a better solution to somehow mark the tasks which read from the input zarr as recomputable

The easiest way to do this is to include opening the Zarr array in every task.  Then every task opens a zarr file, reads some data, and then closes it down.

There are two potential challenges:

1.  The Zarr array may be non-trivial to serialize and send (I'm not too concerned about this though)
2.  Opening the Zarr array every time can be expensive, particularly when metadata is non-trivial.  Xarray gets around this by caching these things (this mostly occurs with NetCDF).  We could consider caching as well, *or* maybe Zarr could cache things somehow?
