### ISSUE TITLE
Migrate CI away from TravisCI.org

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#6781]
https://github.com/jupyterhub/team-compass/issues/348 for some background. travisci.org is going away in favor of travsci.com. It seems that the queue on .org is quite long.

We should migrate from travisci.org to travisci.com or to GitHub actions. I don't really have a preference, but travisci.com will be less effort I think: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by jakirkham** [comment]
Yeah this is a good idea.

In conda-forge we went about this ourselves. This is was in part because the queue time on `.org` was getting to be too painful and with so many repos we couldn't really depend on when Travis CI would migrate some subset of repos over.

With Zarr, we just did this by hand and it wasn't too difficult. Though there are only a couple repos to consider.

Took a look to see what the situation is here. It seems we have some mix of [things on `.org`]( https://www.travis-ci.org/github/dask ) and [some on `.com`]( https://www.travis-ci.com/github/dask ). Not sure if this is because some were migrated or newer repos just showed up on the newer service or what. Anyways figured that was worth being aware of.

**Comment by jakirkham** [comment]
Huh this is new? Maybe it just requires going through and clicking the button for each of these? If we decide to do that, maybe before the weekend to minimize disruption would be good (though could see arguments for other dates/times as well).

<img width="1792" alt="Screen Shot 2020-10-29 at 7 59 22 PM" src="https://user-images.githubusercontent.com/3019665/97654995-54918d00-1a21-11eb-91a1-a75a53e4f9a9.png">

**Comment by jsignell** [comment]
Closing this in favor of #6787 which was discussed in https://github.com/dask/community/issues/107
