### ISSUE TITLE
Setting a sorted index drops rows

### ISSUE THREAD

**Issue by FilippoBovo** [dask/dask#6973]
**What happened**:

Setting a sorted column with `object` dtype as index with argument `sorted=True` drops some rows from the data.

**What you expected to happen**:

I expect that setting an index does not drop rows.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd


data = pd.DataFrame(index=pd.Index(["A", "A", "A", "A", "A", "A", "A", "A", "A", "B", "B", "B", "C"]))
data = dd.from_pandas(data, npartitions=2)
data = data.reset_index().repartition(8).set_index('index', sorted=True)
# The index becomes [A, A, A, A, A, B, B, C]
```

**Anything else we need to know?**:

Using `sorted=False` works correctly, that is, no rows are dropped from the data.

```python
data = data.reset_index().repartition(8).set_index('index', sorted=False)
# The index remains the same: [A, A, A, A, A, A, A, A, A, B, B, B, C]
```

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.5
- Operating System: MacOS Big Sur (14.0.1)
- Install method (conda, pip, source): Pip

**Comment by rjzamora** [comment]
Thanks for raising this @FilippoBovo !  I can definitely reproduce the problem.  I'll try to figure out the cause soon.

**Comment by rjzamora** [comment]
I have been thinking through this, and the fix is proving to be a bit tricky.

In Dask-Dataframe, partitions are expected to be "non-overlapping."  For your example, a "correctly" partitioned result should have only three non-empty partitions (the result you get with `sorted=False`).  When you specify `sorted=True`, we are trying to get non-overlapping partitions, without shuffling the data, by moving data between adjacent partitions only.  The problem is that the `compute_and_set_divisions`/`fix_overlap` code is not designed to handle initial overlap that expands beyond "nearest neighbors."

**Comment by FilippoBovo** [comment]
Thank you for your quick reply, @rjzamora.

What do you mean with non-overlapping partitions?

**Comment by FilippoBovo** [comment]
Also, would this work “correctly” if the index had a category dtype, rather than object dtype?

**Comment by rjzamora** [comment]
> What do you mean with non-overlapping partitions?

Partitions `i` and `i+1` are overlapping if the maximum value in the index of `i` is not less than the minimum value in the index of `i+1`.  Therefore, if two adjacent partitions contain the same value in the index, those partitions are "overlapping."

> Also, would this work “correctly” if the index had a category dtype, rather than object dtype?

Yes, it should - I will check and update this answer if I'm wrong :)

**Comment by FilippoBovo** [comment]
Great. Thanks for the explanation, @rjzamora.
