### ISSUE TITLE
Why is the mode automatically 'w' for dask.dataframe.read_hdf()?

### ISSUE THREAD

**Issue by rs9w33** [dask/dask#7022]
Very sorry if it doesn't belong in Bug Report, it is also my first issue, let me know if this belongs somewhere else. I'm wondering why the read_hdf function has a default 'w' mode? When I read data, I would assume the default mode is 'r' (read, not append or overwrite), when I want to alter the data then I should explicitly mention it is open for writing or appending. pandas.read_hdf() takes 'r' as the default mode, so I had assumed dask would do the same. Was there a strong community preference for default writing mode? Thanks!

**Comment by jsignell** [comment]
First - welcome to dask, and sorry it took a while to get to this. Probably the right place for a question like this would be in the [Discussions area](https://github.com/dask/dask/discussions/categories/q-a). I did a little digging back in the codebase and this piece does not seem to have changed in a long time, which leads me to suspect that it was just an oversight and not intentional. I imagine the project would welcome a PR to change the mode from `"a"` to `"r"`. Are you interested in opening that Pull Request? It should be changing the mode here: https://github.com/dask/dask/blob/76a4f536237a5e65e03ba471f004226056646b65/dask/dataframe/io/hdf.py#L422 and updating the docstring accordingly.
