### ISSUE TITLE
Policy for minimum versions on dependencies

### ISSUE THREAD

**Issue by jsignell** [dask/dask#7378]
This came up in the maintenance meeting and then again in https://github.com/dask/dask/pull/7345#pullrequestreview-610010122 so I thought we can finish the conversation here. 

@crusaderky mentioned how xarray handles this:

> At xarray and pint we use a rolling policy based on NEP-29:
https://xarray.pydata.org/en/stable/installing.html#minimum-dependency-versions
The number of months listed is arbitrary and subject to negotiation. The key benefit of such a policy is that it allows developer to bump up minimum dependencies as needed, without initiating a discussion every time.

@pentschev suggested that we use only packages released in the last 18 months to match NEP-29. 

Ping @jakirkham @jrbourbeau @dask/maintenance

**Comment by crusaderky** [comment]
The 12 months policy of xarray has been found to be a bit too tight for people's comfort. 18 months sounds more reasonable.

**Comment by jakirkham** [comment]
NumPy 1.17 was released at the end of July 2019, which would fit the 18 month requirement. This is handy as we can drop a bunch of compat code if we bump the minimum requirement to NumPy 1.17.

I think everything else is already meeting this requirement.

**Comment by jrbourbeau** [comment]
FYI I opened up an issue in the community issue tracker informing folks who may not watch the `dask/dask` tracker about this issue

**Comment by crusaderky** [comment]
We just discussed the issue at the maintainers' meeting. The general consensus is:
- People are generally happy to have *some* rolling policy instead of having to discuss version bumps every time
- If we're going with NEP-29, it should be implemented lazily, that is minimum versions should not be bumped up until they become an actual nuisance. In other words, we shouldn't aggressively pursue cleaning up compatibility code that is not onerous to just keep there until it actively gets in the way.
- The impacted people are typically large corporate or institutional users which are rarely involved in this kind of discussion. However, in most cases those users will have the whole ecosystem frozen in time 2-3 years ago and should typically not cherry-pick a bleeding edge version of dask while keeping everything else obsolete.

**Comment by hmaarrfk** [comment]
> If we're going with NEP-29, it should be implemented lazily, that is minimum versions should not be bumped up until they become an actual nuisance. In other words, we shouldn't aggressively pursue cleaning up compatibility code that is not onerous to just keep there until it actively gets in the way.

I somewhat disagree with this. I feel like versions should be bumped when:
* They become too old as per the established policy.
* Any contributor, core or not, has an interest in making the contribution.

The ability of non-core contributors to make the PR is critical since asking new contributors to ensure compatibility with old versions of libraries can be quite onerous.

I agree that they shouldn't be blockers, but I would consider it a PR that contributors shouldn't have to ask permission to submit.

I'm all for nep-29. [(Shameless plug for the tool I developed for it)](https://pypi.org/project/nep29/).

However, I'm curious to know the policy for how people that depend on dask should interpret the results:

```
$ nep29 dask
|  version  |    date    |
|-----------|------------|
|  2021.3.0 | 2021-03-05 |
|  2021.2.0 | 2021-02-05 |
|  2021.1.0 | 2021-01-15 |
| 2020.12.0 | 2020-12-11 |
|   2.30.0  | 2020-10-06 |
|   2.29.0  | 2020-10-02 |
|   2.28.0  | 2020-09-26 |
|   2.27.0  | 2020-09-19 |
|   2.26.0  | 2020-09-11 |
|   2.25.0  | 2020-08-28 |
|   2.24.0  | 2020-08-22 |
|   2.23.0  | 2020-08-14 |
|   2.22.0  | 2020-07-31 |
|   2.21.0  | 2020-07-17 |
|   2.20.0  | 2020-07-03 |
|   2.19.0  | 2020-06-19 |
|   2.18.0  | 2020-06-06 |
|   2.17.0  | 2020-05-27 |
|   2.16.0  | 2020-05-08 |
|   2.15.0  | 2020-04-25 |
|   2.14.0  | 2020-04-03 |
|   2.13.0  | 2020-03-25 |
|   2.12.0  | 2020-03-06 |
|   2.11.0  | 2020-02-19 |
|   2.10.0  | 2020-01-28 |
|   2.9.0   | 2019-12-06 |
|   2.8.0   | 2019-11-14 |
|   2.7.0   | 2019-11-08 |
|   2.6.0   | 2019-10-16 |
|   2.5.0   | 2019-09-27 |
|   2.4.0   | 2019-09-13 |
|   2.3.0   | 2019-08-16 |
|   2.2.0   | 2019-07-31 |
|   2.1.0   | 2019-07-08 |
|   2.0.0   | 2019-06-25 |
|   1.2.0   | 2019-04-12 |
```

**Comment by crusaderky** [comment]
> * They become too old as per the established policy.
> * Any contributor, core or not, has an interest **and need** in making the contribution.

With my addition in bold, what you and I said would become perfectly aligned

> However, I'm curious to know the policy for how people that depend on dask should interpret the results:

Support in downstream libraries for old versions of dask is something that each downstream library should be free to decide by themselves. Here we were strictly discussing the dependencies of dask itself...

**Comment by hmaarrfk** [comment]
I think the requirement for "need" adds unnecessary complexity for minimum version bump.

I'm trying to find the numpy/scipy thread that discussed this. In the end, it is about having clear guidelines on what to support and what not to support.

Looking at the highlights from the [1.17.0 numpy release](https://numpy.org/devdocs/release/1.17.0-notes.html#highlights), ever single one of these could be justified as either a necessary requirement for a new dask feature, or, a contributor might be asked to go the extra mile and ensure their contribution is also valid for numpy 1.16.

Removing the word "need" from `Any contributor, core or not, has an interest and need in making the contribution.` makes it so much easier to decide between the two.

**Comment by jakirkham** [comment]
FYI NumPy 1.17 will be deprecated July 26. Details in [this table]( https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table ).

Additionally conda-forge is dropping it for the same reason ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1696 ).

If we want to make one last release supporting it, that seems ok, but would recommend dropping NumPy 1.17 in the subsequent release.

**Comment by jsignell** [comment]
I think we should probably do one last release with numpy 1.17 and pandas 0.25 and then update the requirement on both of them.

**Comment by jakirkham** [comment]
cc @TomAugspurger (in case you have thoughts on bumping the Pandas version)

**Comment by TomAugspurger** [comment]
No preference.

**Comment by jrbourbeau** [comment]
Yeah, no strong preference from me about dropping NumPy 1.17 and pandas 0.25 after the next release

**Comment by hmaarrfk** [comment]
I'm all for moving minimum dependencies forward. I feel like it reduces maintenance burden at a minimum

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/dask/dask/pull/7939 ) to bump NumPy & Pandas

**Comment by ian-r-rose** [comment]
It seems like the consensus here is to lazily follow NEP-29 (which I believe we have been doing). Closing as resolved
