### ISSUE TITLE
Upstream failures: extra kwargs in gufunc

### ISSUE THREAD

**Issue by jsignell** [dask/dask#7493]
Seen on main in [Upstream CI tests](https://github.com/dask/dask/runs/2233244711). It seems like kwargs are no longer being handled properly.

```python-traceback
=================================== FAILURES ===================================
________________ test_Array_numpy_gufunc_call__array_ufunc__01 _________________

    def test_Array_numpy_gufunc_call__array_ufunc__01():
        x = da.random.normal(size=(3, 10, 10), chunks=(2, 10, 10))
        nx = x.compute()
        ny = np.linalg._umath_linalg.inv(nx)
>       y = np.linalg._umath_linalg.inv(x, output_dtypes=float)
E       TypeError: inv() got an unexpected keyword argument 'output_dtypes'

dask/array/tests/test_array_core.py:300: TypeError
________________ test_Array_numpy_gufunc_call__array_ufunc__02 _________________

    def test_Array_numpy_gufunc_call__array_ufunc__02():
        x = da.random.normal(size=(3, 10, 10), chunks=(2, 10, 10))
        nx = x.compute()
        nw, nv = np.linalg._umath_linalg.eig(nx)
>       w, v = np.linalg._umath_linalg.eig(x, output_dtypes=(float, float))
E       TypeError: eig() got an unexpected keyword argument 'output_dtypes'

dask/array/tests/test_array_core.py:309: TypeError
________________________ test_apply_gufunc_via_numba_02 ________________________

    def test_apply_gufunc_via_numba_02():
        numba = pytest.importorskip("numba")
    
        @numba.guvectorize([(numba.float64[:], numba.float64[:])], "(n)->()")
        def mysum(x, res):
            res[0] = 0.0
            for i in range(x.shape[0]):
                res[0] += x[i]
    
        a = da.random.normal(size=(20, 30), chunks=5)
    
        x = a.sum(axis=0, keepdims=True)
>       y = mysum(a, axis=0, keepdims=True, allow_rechunk=True)

dask/array/tests/test_gufunc.py:592: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <numba._GUFunc 'mysum'>
args = (dask.array<normal, shape=(20, 30), dtype=float64, chunksize=(5, 5), chunktype=numpy.ndarray>,)
kwargs = {'allow_rechunk': True, 'axis': 0, 'keepdims': True}

    def __call__(self, *args, **kwargs):
        # If compilation is disabled OR it is NOT a dynamic gufunc
        # call the underlying gufunc
        if self._frozen or not self.is_dynamic:
>           return self.ufunc(*args, **kwargs)
E           TypeError: mysum() got an unexpected keyword argument 'allow_rechunk'

/usr/share/miniconda3/envs/test-environment/lib/python3.8/site-packages/numba/np/ufunc/gufunc.py:151: TypeError
```

**Comment by jsignell** [comment]
I stuck a breakpoint in `__array_ufunc__` https://github.com/dask/dask/blob/a31c0fc72e1cc59b8b0254965824abb0718c5f56/dask/array/core.py#L1317 and in my upstream env it doesn't hit. So I think something is messed up with the dispatching.

**Comment by quasiben** [comment]
@seberg Does NumPy 1.21 have breaking changes ?  I confirmed this is valid for NumPy 1.20

**Comment by seberg** [comment]
So you do pass additional keyword arguments after all :/... I thought I had seen `output_dtypes` but then missed that it was still related to NumPy (and was unaware of the others)

The change is that previously NumPy checked for `__array_ufunc__` up-front, which duplicated quite a bit of stuff for no good reason, as far as I could tell that was never intentional but that doesn't mean it can't be useful.
Now, I cleaned out there and NumPy does some argument parsing (only the unpacking, not the content validation) happens first.  That will catch "invalid arguments" though, such as `allow_rechunk` and `output_dtypes` (none of these are valid if there was no Dask array involved!)

The question is, do we consider these tests as weird (why would you pass non-NumPy arguments to NumPy functions), or just expand the `__array_ufunc__` protocol to accept arguments that are invalid in NumPy if someone else will handle them?

**Comment by jsignell** [comment]
> The question is, do we consider these tests as weird (why would you pass non-NumPy arguments to NumPy functions), or just expand the `__array_ufunc__` protocol to accept arguments that are invalid in NumPy if someone else will handle them?

I agree that this pattern is slightly odd, so I am happy to change these tests if this is an intentional change in numpy. But, from my reading of NEP13 it seemed like any additional arguments would be passed through.

**Comment by seberg** [comment]
I doubt that it was ever intentional so to speak, I was going partially of this discussion: https://github.com/numpy/numpy/issues/8892

But, that doesn't matter much. Even if I am convinced that normalizing arguments up-front is better (e.g. `__array_function__` is very clear that additional arguments are invalid and enforces this.). The question would still be if there is any impact beyond fixing these tests.

My plan would be to look into whatever `dask` decides, because I am pretty convinced that `dask` is the only likely project running into this.  So if you think `dask` users will run into it and/or the workaround is not super easy then this is too big a change.

Beyond "what is the right behaviour", to support this the `out` keyword argument needs to be extracted twice.  Although, at least if we go with a deprecation, that could be nicely tucked away behind a `try/except` block, I guess.

**Comment by jsignell** [comment]
Ok I think the workaround these aren't the only kwargs and I think the workaround is pretty straightforward. So probably dask should move on this one. 

@dask/maintenance for visibility

**Comment by quasiben** [comment]
Thank you @seberg for you thoughts and time! And thank you @jsignell for tracking and the fix!
