### ISSUE TITLE
Regression: poor memory management in threads and sync schedulers

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#7583]
Reopen after triage from https://github.com/pydata/xarray/issues/5165

```python
import dask.array as da
d = da.random.random((15000, 250000), chunks=(1, -1)).sum()
d.compute(optimize_graph=False)
```
Peak RAM usage:
Before #6322 (2021.3.1): 200 MiB
After #6322 (2021.4.0): 28 GiB

This regression impacts the ``threads`` and ``sync`` schedulers. ``processes`` and ``distributed`` are unaffected.

CC @jakirkham

**Comment by crusaderky** [comment]
Also cc @mrocklin @jrbourbeau . IMHO this should be treated as very high priority as it is something that is very likely to hit in the face a newbie user when he plays around with dask.array or dask.dataframe for the very first time.

**Comment by parashardhapola** [comment]
Hi,

I'm also experiencing increased memory usage since ad0e5d140dfc934d94583f8ce50d6b00a04cea38
Is there a workaround for this other than using <=2021.03.1

I'm surprised to see the lack of discussion about this so far. Is there some other thread where this is being tracked?

Best regards,
Parashar

**Comment by jrbourbeau** [comment]
Sorry to hear about the increased memory usage @parashardhapola. If you're able to look into where this might be coming from, that would be welcome. 

Gentle ping for @jakirkham in case you have any thoughts about this issue

**Comment by jsignell** [comment]
@jakirkham in case you have some time to look into this.

**Comment by CptOrange16** [comment]
I'm also having this issue. Something that would use about 3.70 gb ram now just uses so much memory it crashes.
I'm not using dask directly but I'm using xArray.
If you need any info to help diagnose the issue just let me know.

**Comment by sjperkins** [comment]
I'm also running into this issue here https://github.com/paoloserra/crystalball/issues/45. Whereas previously memory usage was stable for long periods of time, https://github.com/dask/dask/commit/ad0e5d140dfc934d94583f8ce50d6b00a04cea38 results in a quick OOM.

I wonder if the removal of the reverse keyword when traversing sorted dependencies might be causing the issue?

https://github.com/dask/dask/commit/ad0e5d140dfc934d94583f8ce50d6b00a04cea38#diff-fec9e4eca8d9878b2808d90c5875a3f5f347f88073e51f06a006841eeb3c0cfdR266

/cc @JSKenyon @o-smirnov

**Comment by mraspaud** [comment]
This also affect our satellite processing in https://github.com/pytroll/satpy/issues/1791 
Feel free to ping me if we can be of any help testing/trying things.

**Comment by mrocklin** [comment]
Thanks all for bumping this issue.

@quasiben can you poke @jakirkham about this when he gets back?  This seems to be a priority issue that arose from his work on swapping in concurrent.futures.

Also cc @eriknw in case he is interested (although this may not be ordering related)

**Comment by djhoese** [comment]
I wanted to see if @sjperkins was on to something with the `reverse` changes so I made this script:

```python
$ cat test_dask_memory_regression.py
from dask.diagnostics import ResourceProfiler, Profiler, CacheProfiler, visualize
import dask.array as da
from datetime import datetime

if __name__ == "__main__":
    with Profiler() as prof, ResourceProfiler(dt=0.5) as rprof, CacheProfiler() as cprof:
        d = da.random.random((5000, 250000), chunks=(1, -1)).sum()
        d.compute(optimize_graph=False)
    visualize(
            [rprof, prof, cprof],
            file_path=f'/tmp/profile_{datetime.utcnow():%Y%m%d_%H%M%S}.html',
            show=False
            )
```

Note I used a smaller number of rows to make the computation go faster for easier testing. Ran it locally and here's a screenshot of the results (github doesn't let me attach HTML files, I can put them somewhere if desired).

### Version 2021.3.1 - profile_20210813_132924.html

![image](https://user-images.githubusercontent.com/1828519/129364723-7b42c49f-6d8c-4ed9-bc96-3fba60997d8c.png)

Peak: ~220MB

### Version 2021.6.2 - profile_20210813_131334.html

![image](https://user-images.githubusercontent.com/1828519/129364880-f69882f9-79e9-4472-b257-ec98c6ff412c.png)

Peak: ~10GB

I then hacked my 2021.6.2 install to undo the `reverse` changes (without knowing why the changes were made or what purpose they serve) and did *NOT* see any differences in the profile.

**Comment by mrocklin** [comment]
If you revert the concurrent.futures commit (is this possible?) do things
improve?

**Comment by slevang** [comment]
`git revert ad0e5d1` leaves a pile of conflicts since this change was ~10 releases ago. The problem was clearly introduced with the `concurrent.futures` change in this commit though. Performance is as expected on the previous commit ([fba94e65](https://github.com/dask/dask/commit/fba94e65e6053163fd1b1ed3c1803ab4f4aa541f)).

**Comment by eriknw** [comment]
Stopping by to share that ordering hasn't changed and, indeed, probably isn't the issue.  Using https://github.com/dask/dask/pull/7992, this plot shows the number of dependencies in memory based on `dask.order` for the example in the original post:

![bokeh_plot (3)](https://user-images.githubusercontent.com/2058401/129389761-213f5f52-0ad8-4b00-87a3-fe0d0960816c.png)

This looks similar to the "Cache Size (count)" profile plot from https://github.com/dask/dask/issues/7583#issuecomment-898462342.  It may be interesting to create this profile plot for the original example too.

**Comment by djhoese** [comment]
> If you revert the concurrent.futures commit (is this possible?) do things improve?

I was hoping to be able to walk through the commits (eventually git blame) of the PR and find the exact issue. Unfortunately the PR was squashed and @jakirkham deleted the branch (totally expected behavior and is the same thing I would do, just too bad in this case). There may be an option to recover the deleted branch but unlikely, especially to us non-jakirkham people.

I can confirm @slevang's finding that before the concurrent futures PR it is fine and after that squashed commit it jumps up to the high memory usage.

Here's the profile for the original 15000 row example case @eriknw:

![image](https://user-images.githubusercontent.com/1828519/129408056-e8e3f4d4-7a58-4d17-9200-85f7a50874a1.png)

**Comment by djhoese** [comment]
I was able to run git bisect on the individual commits from the pull request and unless I'm doing something wrong it all worked fine until the second to last commit which was a merge of `main` into the PR branch. Not the easiest to decipher after that.

**Comment by djhoese** [comment]
Ok so the first problem commit is https://github.com/dask/dask/pull/6322/commits/9d0aaa29d6b439ba9164d55c98a857f8907b165a

I updated my script for quick memory checking by replacing the visualize call with `print(max(x.mem for x in rprof.results))` which let me easily see if the memory usage was in the ~200s or ~10000s.

I took that problem commit, ran my script and noted the high memory usage, then I manually reverted the changes from that commit, ran my script and noted low memory usage.

This is difficult to go any further for me (I'm making it up as I go along but it's friday so I'm avoiding real work). It is at least semi-simple to understand these if statements in this commit, but @jakirkham goes on in this pull request to re-add `num_workers` which he removed in this commit and then refactor the `get_async` function to the point that I'm not sure where the conditions that these if statement changes were checking are (or should be) in the current code. This may be an overall logic bug in the refactor that is causing this.

**Comment by slevang** [comment]
Adding a diagnostic to main [here](https://github.com/dask/dask/blob/main/dask/local.py#L501):
```python
            while state["waiting"] or state["ready"] or state["running"]:
                print(len(state["waiting"]), len(state["ready"]), len(state["running"]))
```
reveals that all 5000 (or whatever number of) tasks are simultaneously in `state["running"]`, whereas in the last working commit ([e52bbbd](https://github.com/jakirkham/dask/blob/e52bbbd786c57c7aa44ccfde4d2f2f670d16d38c/dask/local.py#L479)) there are never more than `n_workers` tasks in `state["running"]`, which is 8 on my local machine. 

In that commit, tasks are explicitly not fired unless `len(state["running"]) < num_workers`, but `get_async` was refactored significantly by the end of this PR so I'm not sure exactly what needs to change.

**Comment by djhoese** [comment]
Thanks for pointing that out. That helps the understanding a lot more. I think I'm actually starting to understand the code, but don't know enough apparently to fix any memory issue. The running tasks are definitely not good and you can fix it by changing the code right under your print statement to say:

```diff
-                fire_tasks(chunksize)
+                print(len(state["waiting"]), len(state["ready"]), len(state["running"]))
+                if len(state["running"]) < num_workers:
+                    fire_tasks(chunksize)
```

But you also need to update the code a little higher so that when tasks are fired only available workers are used:

```diff
-                    ntasks = min(nready, chunksize * num_workers)
+                    avail_workers = max(num_workers - len(state["running"]), 0)
+                    ntasks = min(nready, chunksize * avail_workers)
```

But this doesn't help with the memory. Oh wait...`state['running']` is per-task, not per worker. One sec...

**Comment by djhoese** [comment]
Got it! See my edits above for the path to debugging, here's the current diff:

```diff
diff --git a/dask/local.py b/dask/local.py
index 9f035ef2..913a4706 100644
--- a/dask/local.py
+++ b/dask/local.py
@@ -463,11 +463,14 @@ def get_async(
                     ntasks = nready
                     chunksize = -(ntasks // -num_workers)
                 else:
-                    ntasks = min(nready, chunksize * num_workers)
+                    used_workers = -(len(state["running"]) // -chunksize)
+                    avail_workers = max(num_workers - used_workers, 0)
+                    ntasks = min(nready, chunksize * avail_workers)
+                    print(nready, ntasks, num_workers, len(state["running"]), avail_workers, chunksize)

                 # Prep all ready tasks for submission
                 args = []
-                for i, key in zip(range(ntasks), state["ready"]):
+                for key in state["ready"][nready-ntasks:nready]:
                     # Notify task is running
                     state["running"].add(key)
                     for f in pretask_cbs:
@@ -487,7 +490,7 @@ def get_async(
                             pack_exception,
                         )
                     )
-                del state["ready"][:ntasks]
+                del state["ready"][nready-ntasks:nready]

                 # Batch submit
                 for i in range(-(len(args) // -chunksize)):
@@ -499,7 +502,11 @@ def get_async(

             # Main loop, wait on tasks to finish, insert new ones
             while state["waiting"] or state["ready"] or state["running"]:
+                print(len(state["waiting"]), len(state["ready"]), len(state["running"]))
                 fire_tasks(chunksize)
+                if not len(state["running"]):
+                    print("Nothing is running")
+                    continue
                 for key, res_info, failed in queue_get(queue).result():
                     if failed:
                         exc, tb = loads(res_info)
```

I can make a pull request later today if this seems reasonable and we can discuss pros/cons of this approach (and see what tests fail). Here's the profile as proof:

![image](https://user-images.githubusercontent.com/1828519/129446945-85714179-568d-410c-addd-f87c47a12bb4.png)

So in summary:

1. The batch logic was submitting all tasks regardless of how many workers there were.
2. The reverse ordering of the ready tasks is needed otherwise we run into the situation in my last comment where all the data generation tasks are executed before the reduction/dependent tasks which fills up the memory. This is likely similar to the distributed memory back pressure discussions that have been going on elsewhere on this repository.

**Comment by djhoese** [comment]
PR #8040

**Comment by mrocklin** [comment]
Thank you for stepping up here David

**Comment by djhoese** [comment]
FYI to anyone following this and not the #8040 PR, my reversing of the order of tasks which had a huge impact on the memory usage actually breaks the order setup by [`dask.order`](https://github.com/dask/dask/blob/main/dask/order.py) so it can't be included as part of a fix. However, the original example code doesn't optimize the graph. I found that by letting it get optimized reduces the memory usage **a lot** (~10GB to ~197MB versus ~179MB for reversed order with optimizing).

I think if "we" (users effected by changes to dask.order) want better performance beyond this we'll need to submit improvements to `dask.order`.

**Comment by mrocklin** [comment]
I'll be surprised if dask.order is what is misbehaving here.  Finding valid bugs/rooms for improvement in that code are rare.  

I suspect that it's more likely that the changes of dask.local to use concurrent.futures messed with things a bit.  In theory a single-threaded dask.local execution should follow the dask.order ordering _exactly_.  I would encourage us to verify this with a test before going to improve dask.order.

**Comment by djhoese** [comment]
There is this test:

https://github.com/dask/dask/blob/4a59a6827578fdf8e105d1fb7e9d50d428c9d5fa/dask/tests/test_local.py#L160-L172

Were you thinking something more complex?

I see what you're saying though. Current `main` with my available workers fix and 2021.3.1 are producing major unoptimized memory usage. There must be something else going on. I will try applying my fixes to 2021.4.0 and see how what profiling shows.

**Comment by mrocklin** [comment]
Something more complex.  Let's get a larger computation (maybe something like `x.dot(x.T) - x.mean(axis=0)` for example) and then make a [custom callback](https://docs.dask.org/en/latest/diagnostics-local.html#custom-callbacks) that, whenever a task finishes, checks the order value of the key of that task, and ensures that the order value is continuously increasing, that in a single-threaded situation we never run something out of order.

**Comment by mrocklin** [comment]
> Something more complex. Let's get a larger computation (maybe something like x.dot(x.T) - x.mean(axis=0) for example) and then make a custom callback that, whenever a task finishes, checks the order value of the key of that task, and ensures that the order value is continuously increasing, that in a single-threaded situation we never run something out of order.

If this is confusing then speak up and I'll try to provide more guidance / an example.
