### ISSUE TITLE
Dask needs a logo

### ISSUE THREAD

**Issue by shoyer** [dask/dask#761]
Dask is starting to get lots of buzz, which is great, but without a logo there's no consistent memorable graphic someone can plot on a slide or webpage to indicate that they use the tool. I've resorted to using @mrocklin's collections/tasks/schedulers graphic on slides, but it's really not ideal:

![image](https://cloud.githubusercontent.com/assets/1217238/10147003/79d3664c-65e0-11e5-919e-45c7953e6d32.png)

Is someone creative interested in putting together a dask logo? At one point, @mrocklin suggested something like a matchup of the task graph above with the cubes from the xray logo (see [here](https://github.com/xray/xray/blob/master/doc/_static/dataset-diagram-logo.tex) for the source code):

![image](https://cloud.githubusercontent.com/assets/1217238/10147194/59e621a2-65e1-11e5-8a67-af8e99b80012.png)

In general, something like a mix of task graphs with objects representing dask collections (dataframes or arrays) seems like a good idea.

**Comment by mrocklin** [comment]
I would love for this to happen.  My own attempts at creating a logo have been less-than-aesthetically-pleasing.  It would be great to have people toss out a few ideas.

**Comment by bryevdv** [comment]
In the past we have used sites like 99designs, but that's only because there was no-one in-house to help out. I think you could ping Sara about this.

**Comment by VictoriaODell** [comment]
Hey everyone! Met with @mrocklin today about moving this issue forward. It would be great if we could get something before late March since we have a conference coming up and a dask cheatsheet in the works. 

Below are some takeaways I got when talking to Matt. Keep in mind I don't have a ton of technical knowledge but am trying to translate everything in a way the helps me(or other designers)come up with a proper solution: 
- Dask is a library for parallel computation that coordinates many parts to work together. 
- Dask is high-performance and speedy. It distributes work and coordinates it in a clever way. 
- Dask does complex task in parallel. 

**Some key words for Dask that I've gathered thus far are:**
parallel, intertwined, coordination, distribution, speed, high-performance. 

**Moving forward my design process should go as follows:**
- [ ] Phase 1: Research
- [ ] Phase 2: Sketching/low-fi comps & ideas
- [ ] Phase 3: Digital Comps- Refining the best ideas
- [ ] Phse 5: Final logo- Picking the best solution and cleaning it up so the files can be distributed.  

Feel free to comment or correct the assumptions thus far. Any feedback or suggestions are encouraged at this point. For those unfamilar with logo design I suggest [checking out this pdf](http://www.crestwoodschools.org/userfiles/805/Logo-presentation-1.pdf). There are tons of other opinions and thoughts about logo design out there of course. :wink:

**Comment by shoyer** [comment]
[directed graphs](https://www.google.com/search?q=directed+graph&biw=1055&bih=915&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjWsNjrp-HKAhUH5WMKHTB5AlsQ_AUIBigB&dpr=2) (especially) and [multi-dimensional arrays](https://www.google.com/search?q=multi-dimensional+arrays&espv=2&biw=1175&bih=951&source=lnms&tbm=isch&sa=X&ved=0ahUKEwilxrTqqOHKAhUUSGMKHZCaB7EQ_AUIBigB#tbm=isch&q=multidimensional+array) are also relevant concepts for dask.

**Comment by tonyfast** [comment]
Just chiming in,  When I saw this issue pop up, ``bag`` popped up in my mind as an interesting piece of iconography for Dask.

**Comment by VictoriaODell** [comment]
Nice/helpful links @shoyer!
@tonyfast What is bag?

**Comment by tonyfast** [comment]
[``dask.bag``](http://dask.pydata.org/en/latest/bag.html) is  a powerful part of ``dask``.  There are not as many tools that work with **bags**; they are a thing in mathematics.

**Comment by mrocklin** [comment]
Victoria and I had a nice chat.  There was a strong emphasis on how simple a logo needs to be to be effective and how it should focus on what the project accomplishes, rather than how it accomplishes it.  I generally agree with this sentiment.

So rather than try to convey "that dask accelerates python code through dynamic task scheduling and blocked algorithms in high level collections" we might just try to convey that "dask coordinates parallel computation to make things go fast."  

Also, for what it's worth, I don't think that they logo needs to convey much technical merit at all.  The hard part here is probably about design rather than agreeing on a message.

**Comment by FirecatSue** [comment]
Meeting in 2 weeks to review low-fidelity sketches.

**Comment by mrocklin** [comment]
If anyone has some visual ideas or images that they think might inform the development of a dask logo, please include them in this issue.

**Comment by springcoil** [comment]
Guys any chance I can see this logo for my keynote at PyData Amsterdam?

**Comment by eriknw** [comment]
You know, "dask" is short enough that it may be worth exploring logos that contain--and are designed around--the word "dask".  Perhaps square-ish or blocky fonts would look good, and maybe each letter could be surrounded by a box or oval to get the feel of a DAG.

**Comment by VictoriaODell** [comment]
Hey @springcoil if the logo is done by then I'm sure you'll be able to. I just set up a meeting with @mrocklin to review some initial sketches to help nail down a direction. 

Thanks for the feedback @eriknw. I'll be exploring different approaches and keep this in mind. 

In the meantime, ya'll can view my WIP [Pinterest ](https://www.pinterest.com/Victoria_ODell/dask-parallel-computing/)inspiration board. Again, feel free to add imagery and the like here.

**Comment by VictoriaODell** [comment]
Hello everyone. After a lot of spinning I've created 2 high fidelity comps for the Dask logo.
I presented to @mrocklin this morning. 

These aren't the final versions but are a very close iterations. A and B can be viewed as sets. I've shown how the logos would lock up both stacked and horizontal and made slight adjustments for when the images are made smaller for icons. 

Happy to answer andy Q's and feedback is also welcome. Hoping to get this wrapped up soon and I hope that ya'll are liking where this is going. 

<img width="829" alt="screen shot 2016-05-09 at 10 21 29 am" src="https://cloud.githubusercontent.com/assets/10767430/15117991/d61f65a0-15cf-11e6-9a45-f5ccd03bbab2.png">

View the PDF in the link below: 
[logo_dask_v5.pdf](https://github.com/dask/dask/files/255263/logo_dask_v5.pdf)

**Comment by springcoil** [comment]
I vote for B :+1:

**Comment by mrocklin** [comment]
@VictoriaODell can you say a bit about what ideas back each design?  

@springcoil can you say a bit about why you like B over A?

**Comment by springcoil** [comment]
I like the fluidity of it, which indicates that Dask is an evolving tool.

**Comment by springcoil** [comment]
But this is a design n00b commenting :)

**Comment by VictoriaODell** [comment]
Sure thing @mrocklin ! Though I do encourage some feedback prior to reading my descriptions. A lot is up to the viewers interpretation rather than my intentions.

Both of the ideas illustrated above focus on the idea of "working in parallel" and are metaphorical or abstract. 

**A:** Focuses on what Dask does. It converges to complete a task, shown by the abstract shapes. The point is at the top to denote it moving forward. The shape has a few references in it. 2 planes of fields meeting, 2 ship sails moving together to move forward, and also calls back a bit to the "D" from Dask. The curvature is meant to show the flexibility. The thinner lines of this imagery again suggest flexibility.

The color gradient red/orange was chosen to mean both action and power. A flame was some inspiration for the color. I had initially thought of using a yellow to reference lightning and speed but yellow can be a hard color to work with on lighter background. Here though, the "hotter"/lighter part of the color is more towards the top. Kind of like a comet. 
 
**B:**Is similar but represented differently. The image inspiration for B was a snake kind of turning on itself. It is abstract but shows 2 shapes coming together to form that abstraction. Again coming back to the idea of completing a task by converging and kind of meeting to form that shape. 

The color gradient here was green/blue to again reference the initial inspiration, a snake. But also shows flexibility and energy.  

**For both,** the font [Exo](http://ndiscovered.com/exo-2/) was chosen which is free and open. Its shape is kind of techy because of the blockiness but also slightly fluid or organic, which can be seen a little better in the S and the slight curves found in the k. 

Both iterations include icons or imagery separate from the text to make them more scalable and allow the mark to live on it's own if needed. Ideally, as Dask gains more popularity people may start using the symbol alone to represent it.

**Comment by VictoriaODell** [comment]
Also, should be noted that @tonyfast played a role in getting iteration A to where it is now.

**Comment by eriknw** [comment]
Both are very slick.  Nicely done.

I prefer A.  It is unique and has good contrast on light and dark backgrounds.  I like its interplay of curves and sharp edges, and the layering effect works well for me.  Combining two relatively simple shapes to create a deep and complex--bot not too complicated--ftw!  My initial 1-second reaction favored A as well.

@mcg1969 and @jim22k (and his wife) all prefer A as well (not influenced by each other).  mcg1969 points out that B is kind of like the Nike swoosh, which isn't exactly desirable.

**Comment by shoyer** [comment]
I think both are very nice. I would lean towards A because it looks a
little more distinctive to me.

**Comment by jcrist** [comment]
I also like A. Nice work Victoria!

**Comment by koverholt** [comment]
Looking good! +1 for version A.

**Comment by bryevdv** [comment]
I like A better, but I'd also wish I liked it *more*. The shape says "pinched together" and "drooping, hanging" rather than "coming together" and "moving forward" to me. I definitely don't get ship sails from it with the sharp junction point in that relative position. It needs a counterclockwise rotation to evoke sails filled with wind. I do personally like the font (including the caps) alot.

**Comment by sinhrks** [comment]
+1 for B because I feel green is more associated to dask functionality (this is only my impression, I can't explain the exact reason). Though not strong because both designs are really good:)

**Comment by VictoriaODell** [comment]
Hey ya'll! As far as typography goes, small caps were chosen intentionally. Using small caps saves some vertical height when stacked with the icon. The letterforms keep their intergrity a little better when scaled down or far away. The small 'a' and 's' can get a little muddled together when small. 
<img width="780" alt="screen shot 2016-05-12 at 10 43 12 am" src="https://cloud.githubusercontent.com/assets/10767430/15221054/7895d77c-182f-11e6-8bf9-685a079e9ee7.png">

Seems like A is a winner though. 
I'm working on making the lines of A a little thicker to help with scalability. I'll post some slight varients.

**Comment by mrocklin** [comment]
I like @bryevdv 's comments.  @VictoriaODell does changing the tilt or slightly separating the glyphs at the top have any affect?

**Comment by VictoriaODell** [comment]
Hello ya'll, sorry for the delay to reply.
Know that I designed the mark with a few refrences but ultimately it is a simplified abstraction. When making this mark I also considered scalability, height, and looked at how it would perform when placed with other marks, etc.

So yes, when exploring the suggestions of changing the direction and seperating the glyphs, it effected the mark in an undersirable way.

**Comment by mrocklin** [comment]
I decided to see what a bit of rotation would look like.  Here is 11 degrees:

<img width="135" alt="dask-logo-11d-rotation" src="https://cloud.githubusercontent.com/assets/306380/15367126/8152ac6c-1cdc-11e6-9748-c07692583c83.png">

**Comment by VictoriaODell** [comment]
<img width="702" alt="screen shot 2016-05-18 at 11 57 06 am" src="https://cloud.githubusercontent.com/assets/10767430/15367736/f57b1ba2-1cef-11e6-8ef4-335e2ff4b94d.png">


Here is:
**A** Initial 
**B** adjusted line weight plus adjusted icon and text relation
**C** rotation

I have preference to B because it's lines move upward and to the right and it saves a tad more on height compared to C when stacked. However, this also makes it a little wider when horizontal with text.

**Comment by mrocklin** [comment]
Thanks for sharing these.  I hadn't thought about trying to save vertical space. @bryevdv does C look significantly less "droopy" to you to warrant the excess height?

@VictoriaODell do you happen to have similar mockups separating the two points at the top slightly, perhaps by moving the glyph in the background slightly to the left?

Regarding lines moving up and to the right I suspect that, with the sails analogy the direction is changed somewhat and seems to be somewhat defined by bow of the curve rather than the lines.  At the moment it appears to be sailing to the right and slightly downwards.

**Comment by mcg1969** [comment]
I share Victoria's preference for B, but I think they all look good. The vertical stack for C looks like it's not quite centered, though.

**Comment by tonyfast** [comment]
`B` is more standout to me; the text and icon complement each other nicely.  The icon has horizontal motion that  flows nicely into the bolder text.  Relative to `B`, `C` has less balance between the logo and the text.  In `B`, the angles of the icon play better with the angles on the `K` in `dask`.

**Comment by VictoriaODell** [comment]
Kinda spinning ya'll. I have a lot of sketches + digital sketches but chose these 2 as the strongest after consulting other designers + OS community members. I was hoping that by moving here we could pick one of the 2 and maybe look into slight tweaks. I also fear the sail analogy got a little over emphasised.

With what is currently presented there seems to be a majority support and it works vertical, horizontal, in black in white, as its own mark, and to scale.

**Comment by mcAnalytics** [comment]
Hi Everyone -

It seems to be that B is the choice based on your feedback. @mrocklin are you good with that? If so, let's go with it! We've got lots of new content that's being held up awaiting this logo. Let's make a final decision by noon tomorrow and close the issue.

**Comment by mrocklin** [comment]
B is fine by me.  I'm also probably not the decision maker for this particular issue (not my expertise) so I'm quite happy to defer to others' judgment.

**Comment by mcAnalytics** [comment]
Thanks @mrocklin!

I can decide. Let's go with B. It will work better when we need to scale it down in size. Can you close out the issue so that we show the decision has been made and we're going to finalize and make the assets available.

**Comment by mrocklin** [comment]
Closing in 24 hours if no further comments.
