### ISSUE TITLE
High memory usage for reductions.median but not reductions.mean

### ISSUE THREAD

**Issue by cmccully** [dask/dask#7780]
I'm attempting to median stack 200 x 4k x 4k images. I've been having trouble with the memory allocation so I tried to simplify my problem by going to 2d and was surprised to see that doing a median reduction can take 50 GB of memory and crash python.

This code works as expected in ipython. Almost no memory is used and this completes in less than a minute.
```python
import dask.array as da
x = da.random.normal(10, 0.1, size=(100000, 100000), chunks=(10, 100000))
y = da.reductions.mean(x, axis=1)
%time z = y.compute()
```
`CPU times: user 6min 38s, sys: 2.36 s, total: 6min 41s
Wall time: 56.3 s`

Running the following code causes python to crash after activity monitor showing it using more than 50 GB of RAM.

```python
import dask.array as da
x = da.random.normal(10, 0.1, size=(100000, 100000), chunks=(10, 100000))
y = da.reductions.median(x, axis=1)
%time z = y.compute()
```
![Screen Shot 2021-06-09 at 4 32 29 PM](https://user-images.githubusercontent.com/5331996/121426745-c66f7480-c928-11eb-8f5e-17bdf4c69a48.png)

![Screen Shot 2021-06-09 at 4 47 17 PM](https://user-images.githubusercontent.com/5331996/121427191-45fd4380-c929-11eb-8bdc-5ed0985ec02d.png)

**Anything else we need to know?**:
I did also try this in regular python (as opposed to ipython) and got the same crash. The odd chunk size is an attempt to make sure each chunk has the full array necessary to compute the median in one chunk.

**Environment**:

- Dask version: 2021.05.1
- Python version: 3.8.10
- IPython version: 7.22.0
- Operating System: MacOS 11.3.1
- Install method (conda, pip, source): conda

**Comment by mrocklin** [comment]
Mean works because the data creation and initial data reduction steps are
fused, so we create and destroy data at the same pace.

In the median case there is an intervening step, where we rechunk the array
along the axis to be reduced over to ensure that we can do the median (we
don't have a parallel median algorithm).  This creates a bit of a
disconnect in the graph, and so the worker creates some data and then
doesn't immediately consume that data with the first pass of the
reduction.  Instead it asks the scheduler what's next (in the distributed
case) or waits for neighboring data creation chunks to be done as well for
the eventual rechunk.  The workers are eating themselves to death :)

The solution to this problem is probably to rechunk less aggressively. In
your case we don't even need to rechunk at all.  We can fix this by
changing line 1586 here:

https://github.com/dask/dask/blob/eed298b2335401d2cb8e85ebb44888eb59937cf8/dask/array/reductions.py#L1569-L1588

Probably we should

   1. Only call rechunk if any(x.numblocks[ax] > 1 for ax in axis)
   2. Be careful about using "auto" on all other dimensions, and instead
   make sure that we only reduce the size of chunks, rather than increase them
   / glom them together (which can cause scheduling artifacts)

The first task is the easiest and would solve your problem immediately.
It's a decent task for anyone with mild experience with dask array.  The
second task would be good too, but is not necessary.

**Comment by jsignell** [comment]
For part 2 I am wondering if a different "special" string could be introduced. Something like "auto-downsample", which would behave like "auto" but only if output chunk size is smaller. I can't tell if that is too wierd.

**Comment by mrocklin** [comment]
> For part 2 I am wondering if a different "special" string could be introduced. Something like "auto-downsample", which would behave like "auto" but only if output chunk size is smaller. I can't tell if that is too wierd.

I would wait until there are more requirements for that.  The auto-chunking code is pretty core.  I wouldn't want to add more complexity there for just this use case.  

Instead, we might look at the memory of the current maximum size block (`np.prod(map(max, self.chunks))) * self.dtype.itemsize`) and then use that size instead of "auto".  That way we'll avoid unnecessarily glomming things together.

**Comment by cmccully** [comment]
Thanks for fixing this so quickly!
