### ISSUE TITLE
Support sorting Dask DataFrames with multiple columns

### ISSUE THREAD

**Issue by ChrisJar** [dask/dask#7938]
In pandas it's possible to pass multiple columns to `sort_values` when sorting a DataFrame. For example:
```
import pandas as pd
import numpy as np

df = pd.DataFrame({"a": np.random.randint(0,2,10), "b": np.random.randint(0,2,10), "c": np.random.randint(0,2,10)})
df.sort_values(["a", "b", "c"])
```
returns:
```
   a  b  c
3  0  0  0
8  0  0  1
0  0  1  1
4  0  1  1
1  1  0  0
2  1  0  0
5  1  0  0
6  1  0  1
7  1  0  1
9  1  1  0
```

However, with a Dask DataFrame this raises:
```
NotImplementedError: Dataframe only supports sorting by a single column which must be passed as a string or a list of a single string.
```

**Comment by jsignell** [comment]
Thanks for opening this issue! Sorting is an especially difficult operation for dask because it requires moving data around from one partition to another. You can read about this [here](https://docs.dask.org/en/latest/dataframe-best-practices.html#avoid-full-data-shuffling)

There is an open issue requesting full support for `sort_values` https://github.com/dask/dask/issues/958 so I'm going to close this, but if you are interested in implementing multiple column you should feel free to open a pull request!

**Comment by ChrisJar** [comment]
Good to know. Thanks for pointing me in the right direction!
