### ISSUE TITLE
Parquet filepath parsing error

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#8028]
I attempted to load a large Parquet dataset on S3 with

```python
import dask.dataframe as dd

df = dd.read_parquet("s3://oss-shared-scratch/timeseries.parquet", storage_options=storage_options)
```

but encountered the following error from `pyarrow` (full traceback down below):

```python
OSError: Passed non-file path: oss-shared-scratch/timeseries.parquet
```

I'm not sure if the underlying issue is with `pyarrow` or `dask` or `fsspec`. I'll attempt to create a minimal reproducer, but thought the traceback might be useful by itself. 

cc @jorisvandenbossche @rjzamora 

<details>
<summary>Full traceback:</summary>

```python
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<timed exec> in <module>

~/projects/dask/dask/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, split_row_groups, read_from_paths, chunksize, aggregate_files, **kwargs)
    314         gather_statistics = True
    315 
--> 316     read_metadata_result = engine.read_metadata(
    317         fs,
    318         paths,

~/projects/dask/dask/dask/dataframe/io/parquet/arrow.py in read_metadata(cls, fs, paths, categories, index, gather_statistics, filters, split_row_groups, read_from_paths, chunksize, aggregate_files, **kwargs)
    540             split_row_groups,
    541             gather_statistics,
--> 542         ) = cls._gather_metadata(
    543             paths,
    544             fs,

~/projects/dask/dask/dask/dataframe/io/parquet/arrow.py in _gather_metadata(cls, paths, fs, split_row_groups, gather_statistics, filters, index, dataset_kwargs)
   1786 
   1787         # Step 1: Create a ParquetDataset object
-> 1788         dataset, base, fns = _get_dataset_object(paths, fs, filters, dataset_kwargs)
   1789         if fns == [None]:
   1790             # This is a single file. No danger in gathering statistics

~/projects/dask/dask/dask/dataframe/io/parquet/arrow.py in _get_dataset_object(paths, fs, filters, dataset_kwargs)
   1754         base = paths[0]
   1755         fns = [None]
-> 1756         dataset = pq.ParquetDataset(paths[0], filesystem=fs, **kwargs)
   1757 
   1758     return dataset, base, fns

~/mambaforge/envs/coiled/lib/python3.9/site-packages/pyarrow/parquet.py in __init__(self, path_or_paths, filesystem, schema, metadata, split_row_groups, validate_schema, filters, metadata_nthreads, read_dictionary, memory_map, buffer_size, partitioning, use_legacy_dataset, pre_buffer, coerce_int96_timestamp_unit)
   1330          self._partitions,
   1331          self.common_metadata_path,
-> 1332          self.metadata_path) = _make_manifest(
   1333              path_or_paths, self._fs, metadata_nthreads=metadata_nthreads,
   1334              open_file_func=partial(_open_dataset_file, self._metadata)

~/mambaforge/envs/coiled/lib/python3.9/site-packages/pyarrow/parquet.py in _make_manifest(path_or_paths, fs, pathsep, metadata_nthreads, open_file_func)
   1577         for path in path_or_paths:
   1578             if not fs.isfile(path):
-> 1579                 raise OSError('Passed non-file path: {}'
   1580                               .format(path))
   1581             piece = ParquetDatasetPiece._create(

OSError: Passed non-file path: oss-shared-scratch/timeseries.parquet
```

</details>

**Comment by jorisvandenbossche** [comment]
From the traceback, it seems this is a problem with `fs` (an fsspec / s3fs filesystem) not recognizing it correctly as a file or directory (not sure which of the two would be correct?)

Is the file publicly accessible? (or do you see something similar with a publicly accessible bucket?)

**Comment by jorisvandenbossche** [comment]
Also, which version of dask are you using? If not latest main branch, can you check with `engine=pyarrow-dataset`?

**Comment by mrocklin** [comment]
Ping @jrbourbeau to put this on his inbox in the morning.

**Comment by jcrist** [comment]
Summarizing the state of this issue, it looks like there are 2 suggested solutions:

- Automatically set use_listings_cache=False in Dask's storage_options (if not already specified by the user)
- Call `fs.invalidate_cache()` in non-read operations. (wouldn't this still not work if files were written by an external process before a `read_parquet` call?)

AFAICT the former should always work but may lead to performance issues, while the latter *may* work but would fail if something was modified external to the process doing the listing. Is that accurate?

A third option would be to:
- Never use the cache when listing/globbing/... files when building the graph for a high-level (e.g. `read_parquet`) call on the client. This ensures all files are always found when setting up a graph for a read.
- Invalidate the cache after any write operation on the workers
- Continue to use the default cache behavior on read 

I _think_ this would be sufficient - the generated graph would always contain all files, and it would let caching on the workers still work during reads for any performance benefits that may have (are there any for read calls?).

If this more complicated third option doesn't get us anything, I'd opt for the first option, as it's simple to implement. @martindurant can you add some color into the performance impacts we might see from disabling caching using the strategies above? Should we worry about such a change?

**Comment by jcrist** [comment]
> @martindurant can you add some color into the performance impacts we might see from disabling caching using the strategies above? Should we worry about such a change?

@martindurant , if you have a moment I'd appreciate some fsspec advice here ^^

**Comment by martindurant** [comment]
Listing files on s3 can be slow, because a limited number of files are returned in each call (with a surprising amount of bytes, due to XML encoding and lots of details), and you need to paginate through serially. Since we are explicitly moving towards a no _metadata and many datafiles in many directories model, this cost will be bigger in the future. You would notice not caching particularly if you had reason to `dd.read_parquet` multiple times on the same dataset, perhaps because you want to try different options.

(If there were a _metadata, there would be no need to list at all. Of course, my intuition might be out of date by now...)

> Call fs.invalidate_cache() in non-read operations. (wouldn't this still not work if files were written by an external process before a read_parquet call?)

Correct, you can always have stale info when files are modified in another process. *If* all you want to do is open a file with known path, that's probably always fine, so this only matters on the client. Which argues that it doesn't matter much whether you have it on the workers.

One note: sharing FS instances is good for cutting the cost of establishing connections/credentials; if the uses has one they are using to list files and find their data, with the default listings cache, and we choose to make a another one without, then it will be a separate instance and session. This point argues (weakly) towards invalidating the cache rather than disabling it.

**Comment by jcrist** [comment]
Based on your comment above, I think the 2nd option (call `fs.invalidate_cache()` in non-read operations) might make the most sense then? We'd have `to_parquet` invalidate the local (client side) cache before returning. This gets a bit weird if `compute=False`, but I think it's still what we want to do. This would solve the specific issue here, and shouldn't be too costly in the normal case. I also think we wouldn't need to call `invalidate_cache` ever on the workers, since the real issue here is with listings and those never happen on the workers?

**Comment by martindurant** [comment]
The workers should invalidate their cache for the specific directory they are writing into anyway. So yes, agreed.

**Comment by jcrist** [comment]
#8994.
