### ISSUE TITLE
Investigate support for MultiIndex in dask.dataframe.

### ISSUE THREAD

**Issue by cowlicks** [dask/dask#811]
@jreback expected this to work. I expect other people would too.

**Comment by mrocklin** [comment]
Probably it would be both quite useful and also quite a bit of trouble.  This is the sort of thing that would probably require a fair amount of forethought and a solid amount of effort.

**Comment by jreback** [comment]
my 2c.

you actually have 2 issue here:

- a syntax issue for supporting  a multi-index where you are actually only chunking on a single column

e.g. ``ddf.groupby(level='second')``, so from ``dask`` POV it is exactly the same as a ``dd.from_pandas(df.reset_index())``, and interpreting ``second`` as a column. Conceptually this is very easy.

- a more involved method of actually chunking on a multi-index (e.g. groupings of columns), where your chunks are logical. I am not sure if you actually support this ATM (IOW you are singly indexed). 

All that said a ``MultiIndex`` is really just a mapping of values, so conceptually its not any different (just store tuples instead of single values).

**Comment by mrocklin** [comment]
I'm going to go ahead and close this for now.  It's stale and not generating any new discussion.  MultiIndices would be nice, but at the moment they're also quite expensive.

**Comment by jseabold** [comment]
I looked into a bit. At a high-level what would this require to support the bare minimum (no indexing, no level groupby)? Adding a MultiIndex to `dask.DataFrame` and adding support to `partd` for this? It looked to me like the serialization and index-handling was the hairiest part given the handling of indices there.

The minimal use case I have is for setting partitions and then doing GroupBy on multiple columns. My workaround for now is to set the largest partition and then use `map_partitions` to achieve what I need. What I'm worried about is when the outer partition might be too big to fit in memory. 

For example, something like sensor data collected over many years (or something like this). It's natural to set the partition by year, but you might want to group by, say, year, month, region and get some aggregations, but even the single year partition won't fit in memory, so I'd have to figure out where my partitions should be and proceed, but IIUC even this is inefficient because the partitioning doesn't know anything about the sortedness of the columns.

**Comment by jcrist** [comment]
It should be noted that multiple-column groupby does work, but operations after the initial groupby may or may not:

```python
In [1]: import dask.dataframe as dd

In [2]: import pandas as pd

In [3]: df = pd.DataFrame({'a': range(10), 'b': list('abcde')*2, 'c': list('ab')*5})

In [4]: ddf = dd.from_pandas(df, npartitions=3)

In [5]: ddf.groupby(['b', 'c']).a.sum()
Out[5]: dd.Series<series-..., npartitions=1>

In [6]: ddf.groupby(['b', 'c']).a.sum().compute()
Out[6]:
b  c
a  a    0
   b    5
b  a    6
   b    1
c  a    2
   b    7
d  a    8
   b    3
e  a    4
   b    9
Name: a, dtype: int64
```

**Comment by jseabold** [comment]
Yeah, that's what lead me to look into what it would take. I added some rudimentary support but stopped short when I saw what was going on with the index naming and the serialization.

**Comment by TomAugspurger** [comment]
Closing in favor of https://github.com/dask/dask/issues/1493
