### ISSUE TITLE
Distributed LocalCluster's `memory_limit` keyword argument needs documentation 

### ISSUE THREAD

**Issue by pavithraes** [dask/dask#8224]
**Minimal Complete Verifiable Example**:

```python
from dask.distributed import Client, LocalCluster
cluster = LocalCluster(n_workers=2,
                       threads_per_worker=4,
                       memory_target_fraction=0.95,
                       memory_limit='32GB')
client = Client(cluster)
client
```

**What happened**:
Looks like the `memory_limit` keyword argument used here sets the limit ~~for the entire cluster (see screenshot below)~~. If that's the case, it'll be helpful to add it to the [LocalCluster documentation here](https://docs.dask.org/en/latest/setup/single-distributed.html#localcluster).

Edit: It sets the limit per worker. My example is a special case because my computer has a maximum of 16GB, hence we can't go beyond that (see `@jcrist`'s comments below for more details). It'll still be useful to document the behavior.

**Anything else we need to know?**:

Possible causes of confusion:

- Based on [distributed.deploy.local.py](https://github.com/dask/distributed/blob/7bf884b941363242c3884b598205c75373287190/distributed/deploy/local.py#L76-L78), it sounds like it should be set for each worker?
- [dask-worker has a CLI option to set memory limit](https://docs.dask.org/en/latest/setup/cli.html?highlight=memory_limit#cmdoption-dask-worker-memory-limit), which was the only other mention of the keyword I could find in the docs

StackOverflow question that surfaced this issue is [here](https://stackoverflow.com/questions/69429950/dask-what-does-memory-limit-control).

**Screenshot**:

![Screenshot 2021-10-06 at 2 02 45 PM](https://user-images.githubusercontent.com/33131404/136168970-02c73fd7-fb5d-4b41-8b37-d518f92077fe.png)

**Environment**:

- Dask version: 2021.09.1
- Python version: 3.9.7
- Operating System: macOS
- Install method (conda, pip, source): conda

**Comment by pavithraes** [comment]
cc'ing @jcrist who helped confirm the behaviour

**Comment by jcrist** [comment]
From looking at the code, it looks like passing `memory_limit` to `LocalCluster` sets the memory limit per worker (it's forwarded directly), not total cluster. This also matches the observed behavior:

```python
In [1]: from dask.distributed import Client

In [2]: client = Client(memory_limit="1 GiB")

In [3]: client  # 4 * 1 GiB == 4 GiB
Out[3]: <Client: 'tcp://127.0.0.1:36517' processes=4 threads=8, memory=4.00 GiB>
```

I personally think this is a bit confusing, as I'd expect this to be split per worker with a kwarg named this way, but I think it's too late to change this.

To improve the documentation, should we split out a few common kwargs that are forwarded like `memory_limit` specifically in the docstring, rather than relying on the `**worker_kwargs` parameter docs?

https://github.com/dask/distributed/blob/a13321dbb2d8ed7ac5487f4df90864baa0f1e1b3/distributed/deploy/local.py#L76-L78

Something like

```python
"""
...
    memory_limit: int, float, string
        Number of bytes of memory that each worker should use.
        Set to zero for no limit. Default is based on system memory limit.
    **worker_kwargs:
        Extra worker arguments. Any additional keyword arguments will be passed
        to the ``Worker`` class constructor.
...
"""
```

If so, are there any other worker parameters that would be worth splitting out? This wouldn't change the behavior at all, just improve the docstrings.

**Comment by keflavich** [comment]
I'm quite confused; are the examples shown by @pavithraes and @jcrist contradictory?  @pavithraes showed:
```python
LocalCluster(n_workers=2, memory_limit='32GB')
```
which resulted in two workers with 16 GB each, 32 GB total but @jcrist showed
```python
Client(memory_limit='1 GiB')
```
which resulted in 4 workers with 1 GB each, 4 GB total.

Is this a difference between `Client` and `LocalCluster`?  Or some different behavior if you don't specify `n_workers` directly?

**Comment by jcrist** [comment]
I noticed that too. This is because we take `min` of the user input and the total available system memory. So if your machine has 16 GiB of RAM, no workers are limited to 16 GiB of RAM even if `memory_limit="32 GiB". This is what happened in @pavithraes case above, and I think is the correct behavior (but could also be called out in the docstring).

**Comment by keflavich** [comment]
@jcrist how is the total available system memory determined?  I suspect this is the root cause of myriad problems I've been experiencing: I'm operating on slurm-managed machines that have ~0.5 TB memory available per node, but only ~few GB free to a given process.

**Comment by jcrist** [comment]
The code can be found here: https://github.com/dask/distributed/blob/main/distributed/system.py. It should take into account cgroups limits and RSS rlimit settings, but maybe slurm doesn't set those? Dask's memory accounting also isn't perfect, so slurm may kill the job before dask notices the memory limit has been exceeded.

Note that if you instead use [dask-jobqueue](http://jobqueue.dask.org/en/latest/) to span a cluster out across multiple jobs, the memory limits are automatically forwarded to each worker.

**Comment by ncclementi** [comment]
@pavithraes and @jcrist, I'm checking in here. What is the final status on this issue? It is not quite clear to me from the conversation if we are having the right behavior but is missing documentation or if there is something else going on? 

Since this issue has the tag of "good first issue". Is it possible to set up clear action items on what needs to happen/what is expected so if someone were to pick it up would know how to go about it?

**Comment by pavithraes** [comment]
@crislanarafael Thanks for your interest in contributing! Here are Dask's [development guidelines](https://docs.dask.org/en/stable/develop.html) and the main task to do is described in [my previous comment here](https://github.com/dask/dask/issues/8224#issuecomment-1008733987).

**Comment by pavithraes** [comment]
Closing as completed. Thanks, @crislanarafael!
