### ISSUE TITLE
ReadTheDocs PR builds are failing

### ISSUE THREAD

**Issue by charlesbluca** [dask/dask#8227]
Looks like we're getting timeout errors on RTD builds for PRs:

- https://readthedocs.org/projects/dask/builds/14922250/

Truncating the output, here is the failure message:

```
$ /home/docs/checkouts/readthedocs.org/user_builds/dask/envs/8225/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
...
writing output... [ 84%] generated/dask.dataframe.groupby.DataFrameGroupBy.count
writing output... [ 85%] generated/dask.dataframe.groupby.DataFrameGroupBy.cov
writing output... [ 85%] generated/dask.dataframe.groupby.DataFrameGroupBy.cumcount
writing output... [ 85%] generated/dask.dataframe.groupby.DataFrameGroupBy.cumprod
writing output... [ 85%] generated/dask.dataframe.groupby.DataFrameGroupBy.cumsum
writing output... [ 85%] generated/dask.dataframe.groupby.DataFrameGroupBy.first
writing output... [ 85%] generated/dask.dataframe.groupby.DataFrameGroupBy.get_group


Command killed due to excessive memory consumption
```

Has a recent PR significantly increased the docs size?

**Comment by charlesbluca** [comment]
Not sure if it's a consistent failure, just noticed it on the past handful of PRs:

- https://github.com/dask/dask/pull/8225
- https://github.com/dask/dask/pull/8223
- https://github.com/dask/dask/pull/8222

**Comment by jakirkham** [comment]
It also [fails on `main`]( https://readthedocs.org/projects/dask/builds/14911955/ )

**Comment by jakirkham** [comment]
Thanks Juan! 😄

**Comment by jacobtomlinson** [comment]
@jsignell and I have been doing a bunch of work on the docs lately.

In version 2 of the dask sphinx theme we now use the executable book theme instead of the read the docs theme as a base. Most of the other Dask projects have already rebuilt docs with the new theme.

I'm not surprised that it takes longer to build, the new theme is more complex and has more features. It's disappointing that this is long enough to hit a timeout though. Pinning to the old theme, for now, is a fine bandaid but we should get this resolved properly.

@choldgraf do you have any suggestions on improving performance here?

**Comment by jsignell** [comment]
Seems like https://github.com/readthedocs/readthedocs.org/issues/8545 would be a good start :)

**Comment by jacobtomlinson** [comment]
> does Dask have any really big API docs pages

Yeah it does.

**Comment by astrojuanlu** [comment]
> We can increase build limits on a per-project basis. Send an email to support@readthedocs.org providing a good reason why your documentation needs more resources.

No need to throw money at it :)

**Comment by choldgraf** [comment]
I looked into this today and it was more complicated than I was hoping haha. I think that there are still improvements we could make, but there seems to be some fundamental reality that include a *ton* of API docs on every single page will slow things down considerably.

However, there was a new feature we implemented in the pydata theme to try and help with this, which is to optionally limit the depth of the navigation bar so that items N levels deep aren't included at all. If your API documentation is nested enough levels deep, then this should be a way that you can prevent them from slowing down your builds. I've got a PR to document and add support for this in the book theme, wanna try it out from there and see if this could fix things?

https://github.com/executablebooks/sphinx-book-theme/pull/409

**Comment by choldgraf** [comment]
Ah one more idea which I think would make a much _bigger_ difference. The `autosummary` directives currently are being used with a `toctree` argument:

https://github.com/dask/dask/blob/843c37554dc65e532d70c38b2cd1f337fcc874a0/docs/source/array-api.rst#L6-L14

This means that a toctree entry is being generated for every single API entry. If you remove `:toctree:` from the directive, I believe that the stub pages are still generated, and you can click through to them from the main API landing page, but they just aren't inserted into the left `toctree` anymore.

Can somebody try this and see if this works?

**Comment by jrbourbeau** [comment]
Closing as this issue has been resolved -- thanks all!

**Comment by choldgraf** [comment]
I saw this pop up in my notifications and was like oh god what have we broken now?! 😆
