### ISSUE TITLE
Update Talks & Presentation page of docs

### ISSUE THREAD

**Issue by ncclementi** [dask/dask#8344]
Currently, the Talks and Tutorials page of the docs is outdated (see https://docs.dask.org/en/stable/presentations.html)
We only have links up to 2019.
 
I'm opening this issue to start tracking some talks and tutorials that we want to include. Comment here with talks or tutorials that should be added to this page.

**Comment by jrbourbeau** [comment]
@jsignell and I gave a "Hacking Dask: Diving Into Dask’s Internals" tutorial at PyCon 2021 and the Dask Summit 2021, which I think was well received ([materials presented](https://github.com/jrbourbeau/hacking-dask) and [Dask Summit recording](https://www.youtube.com/watch?v=KZkkVYRZcDA))

I'm not sure how many repeats we want to list, but the standard Dask tutorial was also given at SciPy 2020 / PyCon 2020. There were also a ton of great presentations at the Dask Summit this year. Instead of linking to individual presentations, we might link to the five related [playlists on Dask's YouTube channel](https://www.youtube.com/c/Dask-dev/playlists)

cc @jsignell @jacobtomlinson @quasiben who regularly give Dask talks too

**Comment by jacobtomlinson** [comment]
I keep a [similar page](https://jacobtomlinson.dev/talks/) roughly up to date on my blog with talks I've given. If you grep through there for Dask there may be some of interest.

One of particular note to add to the Dask page might be [Intro to distributed computing on GPUs with Dask in Python ](https://jacobtomlinson.dev/talks/2021-03-31-dask-and-rapids-blazing-webinar/) as it is a GPU flavoured intro to Dask.

**Comment by jsignell** [comment]
I gave kind of a talk version of the hacking dask tutorial at the pydata dc meetup: https://github.com/jsignell/inside-dask
