### ISSUE TITLE
read_csv throws BlockSizeError

### ISSUE THREAD

**Issue by cheginit** [dask/dask#8402]
**What happened**:
Throws an exception when reading a `csv` file from a URL even when `blocksize` is set to `None`.

**What you expected to happen**:
Successfully return a dataframe from a URL.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
df = dd.read_csv("https://www.sciencebase.gov/catalog/file/get/60c92503d34e86b9389df1c9?f=__disk__4a%2Ff7%2F3e%2F4af73ee0ec6d2be1221e3dde541c6fe3c195e1bf", blocksize=None)
```
which throws (with or without `blocksize=None`):
```python
BlockSizeError: Got more bytes so far (>328353508) than requested (5498880)
```

**Anything else we need to know?**:
`pandas` works just fine.

```python
import pandas as pd
df = pd.read_csv("https://www.sciencebase.gov/catalog/file/get/60c92503d34e86b9389df1c9?f=__disk__4a%2Ff7%2F3e%2F4af73ee0ec6d2be1221e3dde541c6fe3c195e1bf")
```

**Environment**:

- Dask version: 2021.11.1
- Python version: 3.9.7
- Operating System: OSX
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Thanks for writing this up @cheginit I am able to reproduce. I think the issue is not with `blocksize` but with `sample`.

I tried setting the sample to very large. For the record I also tried setting `sample` to `False` and to `0` but neither of those got me as far as setting it to very large.

```python
import dask.dataframe as dd
ddf = dd.read_csv("https://www.sciencebase.gov/catalog/file/get/60c92503d34e86b9389df1c9?f=__disk__4a%2Ff7%2F3e%2F4af73ee0ec6d2be1221e3dde541c6fe3c195e1bf", assume_missing=True, sample=3_000_000_000)
```

and it was able to finish, but the dataframe was not usable, because anytime I try to actually load the data I get the original error. @martindurant I am having trouble figuring out if this is an fsspec issue or a dask issue.

**Comment by martindurant** [comment]
~We don't really have a good answer if the server doesn't respect RANGE header specifications.~

I started writing the typical answer above, but actually I see no reason for the restriction, since the `sample` must come from the file header, and `blocksize=None` means we don't do any random access within the file (i.e., reading from an arbitrary offset). 

So I made https://github.com/fsspec/filesystem_spec/pull/830 - and it works. Note that I get a dtype mismatch, but that's easily dealt with
```
ValueError: Mismatched dtypes found in `pd.read_csv`/`pd.read_table`.

+----------+---------+----------+
| Column   | Found   | Expected |
+----------+---------+----------+
| frommeas | float64 | int64    |
+----------+---------+----------+
```

**Comment by jsignell** [comment]
Nice @martindurant! Yeah @cheginit you can get around the dtype mismatch by using `assume_missing=True`

**Comment by cheginit** [comment]
@martindurant and @jsignell Thanks for your quick response and addressing the issue. Your explanation makes sense. I'll give it a try once it gets merged.
