### ISSUE TITLE
Default for dtype not correct for array-like objects

### ISSUE THREAD

**Issue by aeisenbarth** [dask/dask#8461]
Functions which accept a numerical value and an optional `dtype` try to determine the dtype from the value if not explicitely provided. 
Specifically, `da.full(shape, fill_value)` works for a literal scalar, but not for a Dask array that later produces a scalar.
This worked in dask 2021.7 but broke in 2021.8

**What happened**:

The example raises NotImplementedError "Can not use auto rechunking with object dtype. We are unable to estimate the size in bytes of object data".

**What you expected to happen**:

I expected that dask treats arrays/scalars equal no matter whether they are literal or delayed objects.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da

a = da.from_array([[[0], [1]]])
da.full(a.shape, da.mean(a)).compute()
```

**Anything else we need to know?**:

This is caused by `dask/array/wrap.py:207` which should probably first try to get `dtype` from array-like objects before resorting to `type`.
```
    if "dtype" not in kwargs:
        kwargs["dtype"] = type(fill_value)
```

**Environment**:

- Dask version: 2021.11.2
- Python version: 3.8.10
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): pip

**Comment by scharlottej13** [comment]
After looking into this a bit more, it seems you're correct that the [following added lines](https://github.com/dask/dask/pull/7903), and specifically `type(fill_value)` are responsible:
```python
if "dtype" not in kwargs:
    kwargs["dtype"] = type(fill_value)
```
Before those lines were added, the Dask array was being interpreted by numpy as a numpy-compatible array, via [this protocol](https://numpy.org/neps/nep-0018-array-function-protocol.html). Now, though, the Dask array data type is being converted to a string, which numpy is unable to interpret. A fix would be to change `type(fill_value)` to `np.dtype(fill_value)`, which is more flexible and can interpret a larger range of values.

It's worth noting that passing a Dask array to `da.full` will trigger an immediate compute of `fill_value`, because of the aforementioned protocol, which is perhaps not what you are intending. It's interesting, because I don't think the function was written with the ability to pass in a Dask array in mind and this is probably a good point for a larger discussion.

**Comment by scharlottej13** [comment]
@aeisenbarth would you feel comfortable opening up a PR for this?

**Comment by aeisenbarth** [comment]
Yes, I can make a PR, if the suggested change is sufficient. I did not find any similar occurences in the code that would require changes in more locations or at a higher level.
