### ISSUE TITLE
Changelog links don't reference specific release version

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#8473]
I noticed our release version anchor links in the changelog don't actually reference a specific released version. If I go to the changelog and click on the `2021.12.0` link, I'm redirected to https://docs.dask.org/en/stable/changelog.html#id1 when, naively, I would have expected this link to look like https://docs.dask.org/en/stable/changelog.html#2021.12.0 (or something similar). As you move down the page, other releases point to <...>/changelog.html#id2, <...>/changelog.html#id3, etc. which is unfortunate because as new releases come out changelog links aren't consistent (e.g. https://docs.dask.org/en/stable/changelog.html#id1 points to 2021.12.0 today, but will eventually point to 2022.01.0 in the future).

We should update the Sphinx headers we use in `docs/source/changelog.rst` to ensure section anchors point to specific releases and are consistent as new releases are issued. 

<img width="1552" alt="Screen Shot 2021-12-10 at 2 03 10 PM" src="https://user-images.githubusercontent.com/11656932/145634634-e9c89d86-63d3-451e-a64f-8afa9c6b14e6.png">

**Comment by aneeshnema** [comment]
From sphinx-doc/sphinx#1449 the issue seems to be with docutils which requires id to begin with a letter.
See https://repo.or.cz/docutils.git/blob/HEAD:/docutils/docutils/nodes.py#l2241

The easiest way to solve this is to append "v" to all releases, i.e. `2021.12.0` to `v2021.12.0`. I tested this locally, and it generates links like `#v2021.12.0` and `#v2-30-0-2020-10-06` for older releases instead of `#id1`,  `#id2` ...

If that sounds good, I can open a PR for it.

**Comment by pavithraes** [comment]
@aneeshnema Thank you for looking into this! To confirm, we're appending "v" to the release numbers only in [changelog.rst](https://github.com/dask/dask/blob/main/docs/source/changelog.rst) right? If so, the fix sounds good to me, I'd encourage you to open a PR. :)

This same issue exists in the [Distributed Changelog](https://distributed.dask.org/en/stable/changelog.html) too, would you be interested in opening an issue+PR for that too?
