### ISSUE TITLE
PyPI sdist tarball is missing 'conftest.py'

### ISSUE THREAD

**Issue by mgorny** [dask/dask#8475]
**What happened**:
Some tests fail when run from the sdist tarball on PyPI (https://files.pythonhosted.org/packages/18/23/8dea146e14e884e7e0a72738c6bc4ed2ab6939fffbd3ffa32330459861ef/dask-2021.12.0.tar.gz) because of missing fixture, e.g.:

```pytb
____________________________________ ERROR at setup of test_dataframe_shuffle_on_arg[4-on3-False] _____________________________________
file /tmp/portage/dev-python/dask-2021.12.0/work/dask-2021.12.0/dask/dataframe/tests/test_shuffle.py, line 1090
  @pytest.mark.parametrize("ignore_index", [None, True, False])
  @pytest.mark.parametrize(
      "on", ["id", "name", ["id", "name"], pd.Series(["id", "name"])]
  )
  @pytest.mark.parametrize("max_branch", [None, 4])
  def test_dataframe_shuffle_on_arg(on, ignore_index, max_branch, shuffle_method):
E       fixture 'shuffle_method' not found
[...]
```

FWICS this is because the top-level `conftest.py` is not included in the tarball (while tests are).

**What you expected to happen**:

Passing tests ;-).

**Minimal Complete Verifiable Example**:

n/a

**Anything else we need to know?**:

Don't think so.

**Environment**:

- Dask version: 2021.12.0
- Python version: 3.10.0
- Operating System: Gentoo Linux
- Install method (conda, pip, source): source

**Comment by jrbourbeau** [comment]
Thanks for reporting @mgorny. This fixture was added in https://github.com/dask/dask/pull/8250 and included in the 2021.11.2 release. `conftest.py` not being included in the the `sdist` on PyPI is a long-standing oversight, but hadn't been noticed before since it was rather minimal (e.g. it didn't contain any fixtures previously). I think we should stop shipping tests in the `dask` `sdist` and instead encourage folks to check out the `dask` source from GitHub instead. This is what we started doing over in `distributed` recently (xref https://github.com/dask/distributed/pull/5054) to avoid this same type of problem there (xref https://github.com/dask/distributed/issues/4902).

**Comment by mgorny** [comment]
Sure, I've switched Gentoo builds to use GH archives already in order to fix. Just figured out you want to know about this inconsistency, especially that it have gotten me a while to figure out why some tests started failing.

**Comment by jrbourbeau** [comment]
I definitely appreciate you surfacing this! Apologies for the unexpected test failures. I'll push a PR up in a moment with updates to not ship tests

**Comment by jrbourbeau** [comment]
See https://github.com/dask/dask/pull/8478 -- thanks again @mgorny
