### ISSUE TITLE
Update DataFrameGroupBy.apply warning

### ISSUE THREAD

**Issue by scharlottej13** [dask/dask#8503]
This was brought up in a [SO post](https://stackoverflow.com/questions/70265639/best-way-to-perform-arbitrary-operations-on-groups-with-dask-dataframes), and in addition to answering the question, Sultan pointed out these notes are out of date, since shuffling is in fact used: https://github.com/dask/dask/blob/124ae53f9627ec51659398877ba9d2cc6652f28b/dask/dataframe/groupby.py#L36-L41

**Comment by jsignell** [comment]
I think those docs are confusingly worded but correct. Reductions (i.e. `mean`, `sum`, ...) do not shuffle and `apply` does.

**Comment by ian-r-rose** [comment]
I thought the thing that is out of date is the `Warning` note here: https://docs.dask.org/en/latest/generated/dask.dataframe.groupby.DataFrameGroupBy.apply.html#dask.dataframe.groupby.DataFrameGroupBy.apply

**Comment by scharlottej13** [comment]
> I think those docs are confusingly worded but correct. Reductions (i.e. `mean`, `sum`, ...) do not shuffle and `apply` does.

Ah that makes sense, thanks for clarifying!

**Comment by jsignell** [comment]
> I thought the thing that is out of date is the `Warning` note here: https://docs.dask.org/en/latest/generated/dask.dataframe.groupby.DataFrameGroupBy.apply.html#dask.dataframe.groupby.DataFrameGroupBy.apply

Ah! Yeah that one is wrong. We do a shuffle (if needed) and then each group is contained in one partition.

**Comment by scharlottej13** [comment]
Great, sorry for the confusion! I'll edit the title :)

**Comment by JacobHayes** [comment]
Hi! With the shuffle, Pandas and Dask should now always have the same results for `.groupby(...).apply(...)` (but `groupby.Aggregation` is more efficient), right? If so, I wonder if the phrasing is a bit confusing and implies there _is_ a difference (emphasis mine):

> Pandas' groupby-apply can be used to to apply arbitrary functions, including aggregations that **result in one row per
> group**. Dask's groupby-apply will apply ``func`` once on each group, doing a shuffle if needed, such that each group
> is contained in one partition. When ``func`` is a reduction, e.g., **you'll end up with one row per group**. To apply
> a custom aggregation with Dask, use :class:`dask.dataframe.groupby.Aggregation`.

Maybe the warning can be removed entirely and the [bullet point above it](https://github.com/dask/dask/blob/cccb9d8d8e33a891396b1275c2448c352ef40c27/dask/dataframe/groupby.py#L1672-L1673) changed:

> Dask’s GroupBy.apply is not ~appropriate~ efficient for aggregations. For custom aggregations, ~use~ prefer [dask.dataframe.groupby.Aggregation](https://docs.dask.org/en/latest/generated/dask.dataframe.groupby.Aggregation.html#dask.dataframe.groupby.Aggregation).

? I'm happy to make a quick PR if that makes sense to you all!

**Comment by jsignell** [comment]
Hi thanks for commenting! I am having trouble understanding what the issue with the warning is though. The difference between apply and aggregate is that apply only does the function once per partition (where each partition contains a group) whereas aggregate follows an apply-concat-apply reduction pattern. I guess in practice you should get the same output, but the warning does not seem confusing to me. It describes how the apply function is basically just a `map_partitions` after a groupby. So I guess my preference is to leave the warning in.

**Comment by JacobHayes** [comment]
That makes sense between `apply` and `aggregate`, but my confusion is in the comparison to pandas. The warning makes it sound like the output is different from pandas (as it said before https://github.com/dask/dask/pull/8507 and was before the shuffle was implemented). Since it starts with `Pandas' groupby-apply can be used to to apply arbitrary functions`, I took the rest of the warning to mean "in constrast, Dask's output will be different in x, y, z situations". In reality, the `result in one row per group` and `end up with one row per group` behavior is the same (I kept rereading to find the contrast 😅) and you _can_ use an `apply` for aggregation (but it will be less efficient than `aggregate`).

This came up for me in a case where I had a reduction driven by a clustering algorithm that I wanted to apply per group, which couldn't (easily?) be implemented as apply-concat-apply and I was unsure whether I could use groupby/apply at all or would have to use `dask.delayed`.
