### ISSUE TITLE
parallel optimization feedback

### ISSUE THREAD

**Issue by ajfriend** [dask/dask#855]
@mrocklin was helping me implement a parallel optimization algorithm in dask. Here's the resulting notebook of a first naive implementation, along with some notes and bugs I was having. @mrocklin mentioned it might be useful to others.

Right now, I'm wondering why I'm not seeing a performance gain with the threaded scheduler (I may just be missing something obvious). 

I was also getting many runtime errors as I was switching between schedulers and methods of setting the schedulers. I've left two of those tracebacks in the notebook.

https://gist.github.com/ajfriend/d6324d1e81ab04dbb0fd

**Comment by mrocklin** [comment]
cc @jcrist who might this interesting

**Comment by jcrist** [comment]
A few things on just the performance issue:

- Each iteration is only a few us - ms (at least on my computer). The only parallel portion of this code is the parallel map of `proj` for each iteration. As such, the overhead context switches, dask overhead, and gil release/regain for the small bit of numpy that releases the gil in this code may be mildly large compared to the cost of the actual computation. I upped it to 2000 rows, and the gap between threaded and synchronous was clearer. 

- One way to check the effect of the gil in your code is to try running a function using `map`, and comparing it to `ThreadPool.map`. On my computer:

```python
In [10]: %time pool.map(lambda d: proj(d, x), proj_data)
CPU times: user 345 ms, sys: 5.14 ms, total: 350 ms
Wall time: 68.3 ms

In [11]:%time map(lambda d: proj(d, x), proj_data)
CPU times: user 236 ms, sys: 5.07 ms, total: 241 ms
Wall time: 102 ms
```
Ideally this would be 400% slower synchronous, but it's only about 40% slower. So you should still get some speedup from dask, but not much.

- Dask itself has some overhead - both in the scheduler, and in graph creation (as you noted). For *large enough* chunks, this overhead is negligible. As stated above, the cost of `proj` (the only parallel computation) is very small, so the overhead of dask will be proportionally larger. Increasing the size of the data reduces this though. On my machine I saw 7.9 seconds parallel, and 10.7 seconds synchronous (for 2000 rows). This is close to the parallel limit from the gil shown above - the other costs may be due to the serial bits, as well as the overhead of the schedulers.

**Comment by jcrist** [comment]
Remarks on the errors:

- I'm unsure what caused the `RuntimeError` - it may be a delay in garbage collection on the `ThreadPool`s (passing in `num_workers` on each call causes a new pool to be created on each iteration, rather than using a constant pool), resulting in requesting more threads than your system has available. I'm unable to reproduce though. To get around this, if you want a threadpool with fewer/more workers than cores, you can create a pool, and set it globally (or contextually) with `set_options(pool=ThreadPool(2))`.

- The `TypeError` would be from a call to `get_sync` with `num_workers` set. I'll push a PR to fix that. Thanks for the bug report!

**Comment by mrocklin** [comment]
Hrm, the `num_workers` thing is interesting.  Maybe we should retain ThreadPool objects as some state here, keeping around a dictionary mapping `num_workers` to the appropriate `ThreadPool`

```python
thread_pools = dict()

def get_threadpool(num_workers):
    if num_workers not in thread_pools:
        thread_pools[num_workers] = ThreadPool(num_workers)
    return thread_pools[num_workers]
```

Or, if we wanted to be hip (and add a dependency that we shouldn't)

```python
threadpool = toolz.memoize(ThreadPool, cache=thread_pools)
```

**Comment by jcrist** [comment]
Remarks on your "random Dask thoughts":

> would be nice to be able to rename a Value and change the data that it points to.

I'm unsure what you mean by this. If I understand correctly, you'd like to be able to change the name of the value (change its key effectively), and/or change the data it points to. Note that the name can be set on creation (`name` kwarg). Changing it after creation is something I'm unsure about - dask has (optional) tools to cache computations, changing the data/name of a value could cause these to return incorrect answers. Also, all imperative objects are `Value`s, but only root `Value`s point directly to data, and only these can change the object they point to. Perhaps I misunderstood what you're asking for though, or there may be a cleaner way than I can think of to implement it. Please speak up if you have thoughts on this.

> at least for visualizing, I wanted more control over intermediate value names and the ability to enumerate those names with subscripts, which lead to my kludgy functions above.

This could definitely be cleaner. A few thoughts:

- Could add a keyword to `do` that takes a function with signature `funcname(func, args, kwargs)`. Default is current behavior (function name + tokenized args/kwargs). Could be overridden to get the nice key names you want.

- Could make functions wrapped with `do` accept a keyword `token_name` or something, which if provided names the output. I'd be worried about clobbering an actual keyword for the function being wrapped though.

> would be nice if dask.visualize also worked on Dask graph dictionaries, so I don't have to remember dask.dot.dot_graph

Will fix.

**Comment by mrocklin** [comment]
Regarding names it might be nice to support a `name=` kwarg on the result of `do`

```python
In [1]: from dask import do

In [2]: do(lambda x: x + 1)(5, name='foo')
Out[2]: Value('<lambda>-d8549f45-b818-4246-870f-d380c8a18269')
```

Ideally this would return

```python
Out[2]: Value('foo')
```

**Comment by jcrist** [comment]
That's what was suggested above as option 2 - my only issue with that is that it might shadow a kwarg already present in the function being wrapped. Perhaps we just need an obscure enough name that the chance of that happening is small.

**Comment by mrocklin** [comment]
Regarding performance @jcrist 's benchmark shows that you're likely memory bound here, not CPU bound.

```python
def proj(proj_data, x0):
    """Use cholesky factorization data to project onto Ax=b."""
    A, chol, c = (proj_data[k] for k in 'A chol c'.split())

    x = A.dot(x0)
    x = cho_solve(chol, x, overwrite_b=True)
    x = A.T.dot(x)
    x = x0 - x + c
    return x
```

So perhaps the FLOP/Byte ratio to this is not very high?  I wonder what the ninja-C solution to this would look like.

**Comment by ajfriend** [comment]
Thanks for looking at this!
On the performance issue, I'm getting similar results now that I'm just timing the `proj` function. While I'm not expecting a full 200% speedup on my 2-core machine, it'd be nice to better understand if there's anything I can do to improve it.

It could very well be memory bound, but I'm not sure. The actual task I have in mind involves solving sparse matrix equations, so the FLOP/Byte ratio may improve in that case.

Do you think there's any significant slowdown due to releasing/requiring the GIL for each line of python wrapping a linear algebra operation in `proj`? If that's the case, it'd be pretty easy to write in Cython and call blas directly.

Also, does it make any sense to be concerned as to whether I have a multithreaded blas which would be trying to operate on top of the multiple python threads?

I'll comment on Values and names next...

**Comment by mrocklin** [comment]
Yes, if you have a multithreaded blas (accelerate may be using MKL) then you might actually get a significant slowdown by using multiple threads with dask.  A cheap way to check this is to see if your CPU usage goes significantly above 100% when using the single-threaded scheduler.  Even if you are using MKL with multiple threads it's quite possible that they haven't parallelized these operations because they don't get much performance gain.  Usually only the Level 3 BLAS operations substantially gain from multi-threading.

If your actual computation is more expensive then hooray, we're in business again.

I doubt that the GIL holding between the different linear algebra calls will make much of a difference.  It wouldn't hurt though if you wanted to try.

One guess for how to improve performance at this stage would be to start looking into things like thread affinity.  This is a bit intense though.

**Comment by ajfriend** [comment]
# Multithreading performance
Hmm... I actually get something like 400% utilization on my 2 core/4 processor macbook air when running something that takes a while in serial like

```python
As, bs, x_true, x0 = make_data(4, 3000, seed=0)
proj_data = list(map(factor, As, bs))
```

So I guess it does use multithreading, at least when doing a cholesky factorization. Good thing to keep in mind. And I can always switch to a single-threaded blas, if I want to.

I think I've pushed this toy example as far as is useful in terms of optimizing things. I'll get the convex optimization code that I'd really like to parallelize running, and focus on that.

# Names
For names: These ideas came out of the various weird ways I was abusing Dask while I was figuring out how to map it to my problem, so I concede that these may not be common use cases.

## Changing the data that a `Value` points to
I was only thinking of changing the data for root values. My use case was for iterative algorithms like the one in the notebook. Suppose you have a dask that, given x^k, can compute x^{k+1}. Instead of creating a new, but effectively identical dask, I might want to reuse it by assigning x^k <- x^{k+1} and re-running it.

You can (and its what I do in the notebook) extract the dask dictionary and change the value of the appropriate key, but it might be nice to have an alternative imperative interface that lets you assign `x.value`, for instance, and then call the appropriate `.compute()` method. That would give you the same functionality as my dictionary solution, without requiring the user to manipulate a dask dictionary.

On the other hand, this type of mutation might conflict too much with how you guys cache computations...

## Supplying a name to `do`
I only wanted to change the name of a `Value` resulting from a `do` call to make my dask visualizations a little prettier.

I agree that adding a keyword argument like `do(f)(5, name='foo')` might be too likely to conflict with one of the wrapped functions arguments.

Another possibility would be to move the keyword argument to the `do` function itself:

```python
x = do(f, name='foo')(5)
```

That would work great for the types of things I wanted to do in the notebook, like in a list comprehension:

```python
[do(f, name='foo_%d'%i)(i) for i in range(5)]
```

but not at all if the user's going to re-use the function `f = do(f)`, so I'm not sure what the best option is.

## Changing the name of a `Value`
Alternatively, `do` outputs whatever name it outputs and the user can change it later.

I understand that changing a name may mess up caching, but what if you had something like 

```python
a = value(1, 'a')
b = a.rename('b')
```

where, instead of mutating the `a` object, the `rename` method returned an otherwise identical copy, but with the key changed to 'b'?

**Comment by ajfriend** [comment]
Another thought to fix the keyword argument to the result of do:

Let it default to something like `'name'`, but in the case that it clobbers an argument to the wrapped function, allow an argument to `do` so the user can change the keyword argument name.

If `do(make_player)(name='Ruth', score=11)` won't work because `make_player` is expecting a `name` argument, then something like

```python
p1 = do(make_player, name_key='dask_name')(name='Ruth', score=11, dask_name='Player 1')
```
should work, with `p1` resulting in `Value('Player 1')`.

I suppose that could just sit as a keyword argument to `do`, but you could also bubble it up to a context manager or a global setting, if that makes sense.

**Comment by mrocklin** [comment]
You can safely change the name of a value up until the point where you use it within another computation.  Changing the name of a value will not necessarily update its name within other dependent values.

### Changing names

If you've made your dask graph and you're happy with it and are willing to drop the `do/value` abstraction then what you want can be handled with a merge:

```python
dsk = value.dask
data = {'x': 1, 'y': 2}
dsk2 = toolz.merge(dsk, data)
```

But again you're now responsible for names.  Caching solutions won't work anymore, but this doesn't really affect you.

### Setting names

I'm in favor of a `key_name` kwarg when calling a `do`ed function.

### Threads

You can also switch MKL to use just one thread with an environment variable.  

    export MKL_NUM_THREADS = 1

But if its a large part of your computation then you may want multiple threads for the cholesky decomposition.

**Comment by ajfriend** [comment]
Just to be sure I'm on the same page: When you say that you can safely change the name of a value, do you mean that it's safe in principle, or that it's actually possible with the current `Value` interface? Because I get a type error if I try:

```python
a = value(1, 'a')
a.key = 'b'
```

I just thought it might be convenient to do this within the `do/value` abstraction, since if the user wants to change the name but still use the `Value` object, they have to change it in at least 2 places: the `.key` attribute and the underlying dask, as in:

```python
def rename(value, name):
    d = dict(value.dask)
    d[name] = d[value.key]
    del d[value.key]
    return Value(name, [d])
```

Since this is just a convenience, the potential complexity/confusion might outweigh the benefits, but I'm not sure. :/

For threads: Luckily, the actual code that I want to run (which isn't in the toy example in the notebook) uses a custom sparse solver which avoids BLAS altogether, and so is single-threaded. I played with calling the solver in multiple threads a bit and I'm seeing good speedups! :+1:

**Comment by mrocklin** [comment]
The intent of my statement was to say that you definitely can not safely change the name of a value after it has been used elsewhere.  Values don't have links back to their predecessors.

In principle I think that renaming values should be discouraged.  The best way to do this is probably to make naming values initially pleasant.

**Comment by mrocklin** [comment]
The raised issues here, I think, have been handled.

**Comment by ajfriend** [comment]
Yeah!
