### ISSUE TITLE
MD5 not supported without usedforsecurity=False in FIPS 140-2 environment

### ISSUE THREAD

**Issue by tuffacton** [dask/dask#8608]
**What happened**:
In a FIPS 140-2 enabled CentOS 7 VM I got an error much like the one described here: https://github.com/paramiko/paramiko/issues/396

I had to effectively perform this monkey patch: https://stackoverflow.com/a/70232502

Changed `.env/lib/python3.6/site-packages/dask/base.py`:

```855     return md5(str(tuple(map(normalize_token, args))).encode()).hexdigest()```

to

```855     return md5(str(tuple(map(normalize_token, args))).encode(), usedforsecurity=False).hexdigest()```

**Anything else we need to know?**:

Tried to reproduce on my M1 Macbook but unfortunately the Mac's OpenSSL md5 has a different hashlib implementation that doesn't support multiple arguments. https://stackoverflow.com/questions/54717862/how-do-i-know-if-the-usedforsecurity-flag-is-supported-by-hashlib-md5

**Environment**:

- Python version: 3.8.9
- Operating System: CentOS 7
- Install method (conda, pip, source): pip

**Comment by graingert** [comment]
currently dask uses `hashlib.md5` in `dask.base.tokenize` for [deterministic hashing 
](https://docs.dask.org/en/stable/custom-collections.html#implementing-deterministic-hashing) and therefore not obviously security critical (hashing passwords).

However, currently `dask.base.tokenize` is a public function that could potentially be used by any user code in a security critical way.

Perhaps it would be better to side-step the issue and pick a different hashing function eg https://docs.python.org/3/library/hashlib.html#hashlib.blake2b which is [faster than md5](https://github.com/Cyan4973/xxHash#benchmarks) and supported by openssl FIPS mode? This would be a difficult change to make because every client and worker will need to upgrade at the same time.

**Comment by bryanwweber** [comment]
It seems that #8632 could be resolved at the same time, since fixing that would potentially also change the `tokenize` method? Should we create an issue to consolidate discussion around this topic?

@jrbourbeau @jsignell Just putting this on your radar.

**Comment by graingert** [comment]
https://github.com/dask/dask/pull/6843
