### ISSUE TITLE
Dask seems to re-compute delayed calls after calculating divisions

### ISSUE THREAD

**Issue by gerrymanoim** [dask/dask#8709]
To prep data for below repro (but this is the same with any dataset):

```
from dask.datasets import timeseries
zz = timeseries()
zz.to_parquet("~/tmp/dask_tmp")
```

Consider the two code snippers below:

```python
# good behavior
p = Path("~/tmp/dask_tmp")
ddf = dd.read_parquet(p)
ddf = ddf.sort_values("name")  # not lazy
ddf["z"] = ddf["x"] + ddf["y"]
df = ddf.compute()
```

vs 

```python
# bad behavior
p = Path("~/tmp/dask_tmp")
ddf = dd.read_parquet(p)
delayeds = ddf.to_delayed()
ddf = dd.from_delayed(delayeds , meta=ddf._meta)
ddf = ddf.sort_values("name") # not lazy
ddf["z"] = ddf["x"] + ddf["y"]
df = ddf.compute()
```

In the good behavior case, dask performs some work (including reading the parquet files) to determine divisions for `sort_values`. Then it proceeds to the rest of the work it needs to do. 

In the `bad behavior` case, if you watch the task graph or run with `performance_report` you can see that reads (i.e. each `read_parquet` task) are actually executed twice. (I can upload the reports or dashboards when I get home). 

This is of course a bit contrived, in the real world `from_delayed` involves some custom data reading code, but I'm surprised that those computations are "thrown away" when proceeding past the sort. 

Using the distributed client if that matters. 

Dask version: 2022.01.0
Python Version: 3.9

**Comment by phobson** [comment]
@gerrymanoim 

Thanks for the clear explanation and reproducible example. I'm looking into this now.

For the sake of clarity I've uploaded performance reports for the Good and Bad case that you provided. If you have a moment, I'd be keen to take a look at similar reports generated on your system.

Feel free to ping me here with additional info or questions.

[Good-Bad-perf_reports.zip](https://github.com/dask/dask/files/8073407/Good-Bad-perf_reports.zip)

**Comment by phobson** [comment]
Hey @gerrymanoim. We're still tracking this down. I was able to reproduce the issue you're seeing. I'll likely need to pull in more resources to really get to the bottom of it.

**Comment by phobson** [comment]
The intermediate conclusion for this is that this is essentially "how dask works". 

In the good case, a call to `read_parquet` isn't showing up due to task fusion. In the bad case, it's not possible to "un-persist" via deleting futures since the task graph will always depend on them.

You can inspect a low-level graph in an interactive REPL to help illuminate some of the inner working of this. 

For example, consider a simple script:

```python
import pandas as pd
import dask
import dask.dataframe as dd
from dask.distributed import Client


DATAPATH = "simple.pqt"


def setup():
    pdf = pd.DataFrame({
        "a": [1, 2, 3, 4] * 3,
        "b": [10, 20, 30] * 4,
        "name": ["Alice", "Bertie"] * 6
    })

    _ddf = dd.from_pandas(pdf, npartitions=3)
    _ddf.to_parquet(DATAPATH, engine="pyarrow")


def good_case():
    with dask.config.set({"optimization.fuse.active": False}):
        ddf = dd.read_parquet(DATAPATH, engine="pyarrow")
        ddf = ddf.sort_values("name")  # not lazy

        ddf["c"] = ddf["a"] + ddf["b"]
        ddf = ddf.loc[lambda df: df["name"] == "Bertie"]
        ddf, = dask.optimize(ddf)
    return ddf


if __name__ == "__main__":
    with Client(n_workers=2, memory_limit='1GB'):
        setup()
        good = good_case()
```

From there, execute the script interactively in ipython:

```shell
$ ipython -i test_simple.py
```

Then in the ipython session, you have access to the `good` object. If you inspect it, you should see something like this:

```ipython
In [1]: good.dask
Out[1]: 
HighLevelGraph with 4 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x1281b63d0>
 0. assign-bfcea428e99fbf31dd1e960ea60cf3fa
 1. repartition-1-3f455c139b39ae718be905769236ddd8
 2. simple-shuffle-9620ced33430b908a4d38b669e737af4
 3. loc-series-646a003d118cb6ede85282b5312087e5
```

I think the hashes might differ on your machine, but I'm not 100% certain of that. Just like the task graph visualizations we created, it looks like `read_parquet` is missing from this graph. We can index into it like it's a dictionary. Note that we use a tuple of the string key and an integer for each time the operation is repeated across partitions. Inspect `list(good.dask.keys())` to illustrate that better.

```ipython
In [2]: good.dask[("loc-series-646a003d118cb6ede85282b5312087e5", 0)]
Out[2]: 
(subgraph_callable-3553e669-858b-43d0-b504-f707ed11460b,
 None,
 'assign-0822ecbd944c8f3a242ed6630eb07623',
 'eq-9f26c22431ba888b01fd610e1846a52c',
 'Bertie',
 'name',
 'c',
 'b',
 'a',
 'drop_by_shallow_copy-334e46bde3f1f9cdf92cb61c5f9fc44b',
 ('simple-shuffle-9620ced33430b908a4d38b669e737af4', 0),
 ['_partitions'],
 'simple-shuffle-9620ced33430b908a4d38b669e737af4')
```

That first element (the subgraph-callable) is what we're looking for. I'll spare you the long output of it, but you can access it like this:

```ipython
In [3]: good.dask[("assign-bfcea428e99fbf31dd1e960ea60cf3fa", 0)][0].dsk
```
<details>
<summary><pre>Out[3]:</pre></summary>

```
{'assign-bfcea428e99fbf31dd1e960ea60cf3fa': 'getitem-set_partitions_pre-assign-bfcea428e99fbf31dd1e960ea60cf3fa',
 'read-parquet-3e8c9b128e2f37b695bcaea6c5cddf24_.0': (<dask.dataframe.io.parquet.core.ParquetFunctionWrapper at 0x11d6bd490>,
  '__dask_blockwise__3'),
 'getitem-set_partitions_pre-assign-bfcea428e99fbf31dd1e960ea60cf3fa': (<function dask.dataframe.methods.assign(df, *pairs)>,
  'read-parquet-3e8c9b128e2f37b695bcaea6c5cddf24_.0',
  '__dask_blockwise__0',
  (<function dask.utils.apply(func, args, kwargs=None)>,
   <function dask.dataframe.core.apply_and_enforce(*args, **kwargs)>,
   [(<function _operator.getitem(a, b, /)>,
     'read-parquet-3e8c9b128e2f37b695bcaea6c5cddf24_.0',
     '__dask_blockwise__2')],
   (dict,
    [['_func',
      <function dask.dataframe.shuffle.set_partitions_pre(s, divisions, ascending=True, na_position='last')>],
     ['_meta', Series([], dtype: int64)],
     ['divisions',
      0     Alice
      2    Bertie
      dtype: object],
     ['ascending', True],
     ['na_position', 'last']])))}
```
</details>

**Comment by gerrymanoim** [comment]
Ah I see - thanks for the detailed response!

**Comment by gjoseph92** [comment]
Sounds like https://github.com/dask/dask/issues/8635 is contributing to the confusion? That is, the `read_parquet` operation actually runs twice in both cases, it's just that in the "good" case, it's fused into the `assign` task as @phobson showed, so you don't realize it's happening. If the task name on the dashboard were `read_parquet-assign` instead of just `assign`, it might be clearer what was happening.

**Comment by gerrymanoim** [comment]
I think for me it was a combination of the name and the coloring that was different, so without delving into the task graph it wasn't clear that the reading was occurring as part of a fused operation in one case.

**Comment by phobson** [comment]
@elaineejiang this is the issue I mentioned that discusses how to dive into task graphs
