### ISSUE TITLE
dask how to read AlibabaCloud oss parquet?

### ISSUE THREAD

**Issue by LeeMo2K10** [dask/dask#8766]
dask_function(...,
    storage_options={
        "key": ...,
        "secret": ...,
        "client_kwargs": {
            "endpoint_url": "http://some-region.some-s3-compatible.com",
        },
        # this dict goes to boto3 client's `config`
        #   `addressing_style` is required by AlibabaCloud, other services may not
        "config_kwargs": {"s3": {"addressing_style": "virtual"}},
    })

how to ?

**Comment by scharlottej13** [comment]
Hi @LeeMo2K10, thanks for opening this issue! It seems this is more of a usage question rather than a feature or bug report and we encourage people to ask such questions on the [Dask Discourse](https://dask.discourse.group/). Would you mind opening a discussion topic about this over there and sharing a [minimal reproducible example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)? I'm going to close this issue, but looking forward to continuing the conversation on discourse.
