### ISSUE TITLE
Dask drop(axis=1) hangs on large datasets

### ISSUE THREAD

**Issue by jlehrer1** [dask/dask#8798]
**What happened**:
After letting dask run for 18+ hours with 75gb memory and 35CPU's, it is unable to drop a column of a 650k x 50k purely numeric (float64) dataset.

**What you expected to happen**:
Column would drop in a reasonable amount of time.

**Minimal Complete Verifiable Example**:
Hard to provide complete example with a minimal dataset since the problem is one of scaling, but the code is:

```python
        data = (da.read_csv(
            os.path.join(data_path, 'interim', file),
            assume_missing=True,
            header=1, # need this since calculating transpose adds one extra row, still need to figure out why as it doesn't happen on synthetic data 
            sample=1000000, # May need to make this bigger
        ))

        for gene in data.columns:
            if gene not in unique:
                print(f'Dropping gene {gene}')
                data = data.drop(gene, axis=1)
                data = data.persist()

        data.to_csv(
            os.path.join(data_path, 'processed', f'{file[:-4]}.csv'),
            single_file=True,
            index=False,
        )
```

**Anything else we need to know?**:
This is running in a Docker container scheduled via Kubernetes to a compute node. If there is any info about the node you need, I can provide it. 

However, when working with a smaller (189kx19k purely numeric float64) dataset, dropping 3k columns took only 16 hours. 
**Environment**:
Hosted from PyTorch docker image with some packages installed on to.

- Dask version: 2022.2.0
- Python version: 3.7.11
- Operating System: Linux/amd64
- Install method (conda, pip, source): pip

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by scharlottej13** [comment]
Hi @jlehrer1, thanks for opening this issue! It seems this is more of a usage question rather than a feature or bug report and we encourage people to ask such questions on the [Dask Discourse](https://dask.discourse.group/). Would you mind opening a discussion topic about this over there? If so, feel free to close this issue and we will continue the conversation on discourse.

From a quick look at your snippet, part of the issue may be calling `persist` within the `for gene in data.columns` loop. You might find [these docs on best practices around using `persist`](https://docs.dask.org/en/stable/dataframe-best-practices.html#persist-intelligently) helpful as well.

**Comment by jlehrer1** [comment]
@scharlottej13 Sure, I will. To me, this does seem like a bug, since the `.persist()` being called on each instance works when the length of the list of columns to drop is actually longer, but the dataset itself is smaller. It seems to me that the code hangs on larger datasets. Should I be setting the number of partitions manually?

**Comment by pavithraes** [comment]
@jlehrer1 Thanks for the note. It's generally not recommended to call `persist` inside a for-loop. In fact, we try to minimize calling `persist` because it triggers some computations in the background, which goes against the "lazy-evaluation" paradigm of Dask, and hence leads to poor performance. Does this make sense?

I'll go ahead and close this, looking forward to seeing you on Discourse, we can continue this discussion there!
