### ISSUE TITLE
Confusing error from map_blocks if function returns scalar per block

### ISSUE THREAD

**Issue by dcherian** [dask/dask#8822]
**What happened**:

`map_blocks` raises a confusing error when the mapped function returns a scalar.

**What you expected to happen**:

Let the user know that the function should return a single element array.

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import dask.array as da

array = da.from_array([1,1,2,2,2,3,3,3,3,3], chunks=((2,3,5)))
nchunks = len(array.chunks[0])
output_chunks = ([1] * nchunks,)

array.map_blocks(np.mean, chunks=output_chunks).compute()
```

```
File ~/mambaforge/envs/dcpy/lib/python3.8/site-packages/dask/array/core.py:4994, in concatenate3(arrays)
   4992 if not ndim:
   4993     return arrays
-> 4994 chunks = chunks_from_arrays(arrays)
   4995 shape = tuple(map(sum, chunks))
   4997 def dtype(x):

File ~/mambaforge/envs/dcpy/lib/python3.8/site-packages/dask/array/core.py:4781, in chunks_from_arrays(arrays)
   4778         return (1,)
   4780 while isinstance(arrays, (list, tuple)):
-> 4781     result.append(tuple(shape(deepfirst(a))[dim] for a in arrays))
   4782     arrays = arrays[0]
   4783     dim += 1

File ~/mambaforge/envs/dcpy/lib/python3.8/site-packages/dask/array/core.py:4781, in <genexpr>(.0)
   4778         return (1,)
   4780 while isinstance(arrays, (list, tuple)):
-> 4781     result.append(tuple(shape(deepfirst(a))[dim] for a in arrays))
   4782     arrays = arrays[0]
   4783     dim += 1

IndexError: tuple index out of range
```

**Anything else we need to know?**:

If I amke the fuction return a single element array, it works

```
array.map_blocks(lambda x: np.mean(x, keepdims=True), chunks=output_chunks).compute()
```

**Environment**:

- Dask version: 2021.12.0
- Python version: 3.10
- Operating System: macOS
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment]
Thanks for writing this up @dcherian! I hadn't realized that we fail for this case on the array side. On the dataframe side we seem to handle this more gracefully, so we can probably mimic that on the array side.

```python
import dask.dataframe as dd

ddf = dd.from_array(array)
ddf.map_partitions(np.mean).compute()
```

**Comment by dcherian** [comment]
I guess the general version of this problem is that the mapped function returns a value that has dimensionality different from what is expected.

**Comment by ParticularMiner** [comment]
@jsignell 

I think I agree with you that `dask.array` ought to be able to handle this case more gracefully.  In particular, I think this case should be able to return the exact same result as:
```python
array.map_blocks(lambda x: np.mean(x, keepdims=True), chunks=output_chunks).compute()
```
simply because of `dask`'s ability to broadcast the return value of `np.mean` to the expected shape during `compute()`.

I mean, the following calls work without hiccups:
```python
array.map_blocks(lambda x: np.array([[1]]), chunks=output_chunks).compute()
array.map_blocks(lambda x: np.array([[[1]]]), chunks=output_chunks).compute()
```
so why not the former?

Somewhere along the call-chain of the above error tracelog of @dcherian's case there's a curious piece of source code:
https://github.com/dask/dask/blob/e1a19cbd80c462371eb50e7cf309a8fc47d9bb45/dask/array/core.py#L4855-L4860
which seems to allow scalars `x` to be interpreted as arrays of shape `(1,)`.  But `np.mean([1, 1])`, for example, returns an object `x` that has `x.shape = ()`, which I'm guessing was unexpected at the time this piece of code was written.  

I think changing it to:
```python =
 def shape(x): 
     try: 
         return x.shape if x.shape else (1,)
     except AttributeError: 
         return (1,) 
 ```
will allow @dcherian 's case to run through without raising an error.
