### ISSUE TITLE
Unwanted aggregation `map_blocks`

### ISSUE THREAD

**Issue by jsignell** [dask/dask#8830]
**What happened**:

While working on https://github.com/dask/dask/issues/8822 I tried to use `drop_axis=True` in `map_blocks` and ran into an issue where `map_blocks` aggregated the results from each block rather than concatenating them.

**What you expected to happen**:

The output should contain one output per block. 

```python
array([1., 2., 3.])
```

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import dask.array as da

array = da.from_array([1,1,2,2,2,3,3,3,3,3], chunks=((2,3,5)))
array.map_blocks(np.mean, drop_axis=[0]).compute()
# 2.3
```

Ping @rjzamora for blockwise insight.

**Comment by rjzamora** [comment]
I'm not as familiar with `dask.array` as I'd like to be, but doesn't passing `drop_axis=[0]` to `map_blocks` mean you want to concatenate along the only axis you have?

**Comment by jsignell** [comment]
Hmm I guess I thought it would mean "the output of my chunk-function will have a different dimensionality than the input" But I still expect one result per block.

**Comment by ParticularMiner** [comment]
@jsignell @rjzamora 

The [`blockwise()` documentation](https://docs.dask.org/en/latest/generated/dask.array.blockwise.html#dask.array.blockwise) states:

> Any index, like `i` missing from the output index is interpreted as a contraction ... the passed function should expect an iterable of blocks on any array that holds that index. To receive arrays concatenated along contracted dimensions instead pass concatenate=True.

So `map_blocks()` calls `blockwise()` without any output axis labels (due to `drop_axis=[0]`).  But `blockwise()` compares input and output axis labels and sees that the output  is missing the only axis label that the input has so it concatenates all chunks of the input into one large chunk which `np.mean` then reduces to a scalar.

As far as I can see, this behavior should be expected as this is the only way for the return value of `map_blocks()`/`blockwise()` to remain consistent with the expected output dimensionality, or meta data.  I mean, if the output dask array is expected to have a dimensionality of 0, then only a single value must be returned, therefore the dask array must have only one chunk containing that value.  The only way to enforce this is to concatenate all the input chunks into one chunk before passing it to the chunk-function.

**Comment by ian-r-rose** [comment]
I'm not sure I agree with the "expected result" of
```python
array([1., 2., 3.])
```
To me, the fundamental contract of `map_blocks` is that the function should transform an array-like into an array-like. There might be changes to the representation (like sparsity or cupy or whatever), or the shape, but it should always be an arraylike, and  returning a scalar violates that contract. Automatically concatenating the resulting scalars into a new array would have some pretty surprising and confusing results that, to me, should be avoided.

To most users, I think we should be striving to make chunks an implementation detail. Clearly, the performance characteristics of a computation will depend on chunking, but I don't think the answer should. If my code got different answers depending on how I chose my chunked, I'd be very puzzled, and it would be pretty easy to hit that scenario if I simply forgot to specify which concatenation axis I want for `np.mean`. So with your example above

```
array = dask.array.from_array([1,1,2,2,2,3,3,3,3,3], chunks=((2,3,5)))
array.map_blocks(np.mean, drop_axis=[0]).compute()  # [1, 2, 3]


array = dask.array.from_array([1,1,2,2,2,3,3,3,3,3], chunks=((5,5)))
array.map_blocks(np.mean, drop_axis=[0]).compute()  # [1.6, 3]  Weird! 
```

Now, users could still make cases that have that above behavior by ensuring that their reduction function keeps their axes (this gets your expected behavior):

```python
array = dask.array.from_array([1,1,2,2,2,3,3,3,3,3], chunks=((2,3,5)))
array.map_blocks(np.mean, keepdims=True).compute()  # [1, 2, 3]
```

But I guess I'd be in favor of *making* people opt-in to chunking-dependent behavior with array-forcing workarounds like the above. So I guess I agree with @dcherian's suggestion in #8822 that a better error message if a scalar is returned is the right behavior.

**Comment by jsignell** [comment]
Hmm yeah I can see how the behavior that I am describing in this issue might be unwanted and surprising. I guess I'm more familiar with the dataframe equivalent which _does_ always return at least one value per partition and wraps scalars in Series objects if needed. But it is entirely possible that they are different enough that it's not worth trying to make their behavior internally consistent. 

The name `map_blocks` to me implies a simple mapping, so the fact that it's possible to get a cross-block aggregation is what really confused me. I understand how it's possible given that `map_blocks` is backed by `blockwise` but I'm not sure it _should_ be possible. 

But this is probably orthogonal to @dcherian's original issue. I totally agree that an error message makes sense in that case. It can probably be raised at graph construction.

**Comment by ParticularMiner** [comment]
Here's an illustrative diagram that could be added to the docs to clarify the case of `drop_axis != None`:

![image](https://user-images.githubusercontent.com/78448465/160272226-965e8733-e958-4263-b70d-ae4f2c7722dd.png)
