### ISSUE TITLE
unmanaged old not released after notebook re-run

### ISSUE THREAD

**Issue by RexHuang** [dask/dask#8942]
**What happened**:
After run scrpit in notebook with some error, it has about 1G unmanaged old, then I re-run the script, 
but the unmanaged old is not released.

**What you expected to happen**:
I expect the unmanaged old should release.

**Minimal Complete Verifiable Example**:
The script is same in issues/8941

```python
# Put your MCVE code here
dtype_dic= {0: str, 1: str, 2: str, 3: str, 4: str, 5: str, 6: str, 7: str, 8: str, 9: str, 10: str,
11: str, 12: str, 13: str, 14: str, 15: str, 16: str, 17: str, 18: str, 19: str, 20: str}
%time df2=dd.read_csv('/mnt/output202202/output*.csv', encoding='GBK',dtype=dtype_dic)
df2.columns[0]=['smg_req']
%time df2.set_index('smg_req')

```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.3.0
- Python version: 3.8
- Operating System: Cento7
- Install method (conda, pip, source): k8s docker hub

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by RexHuang** [comment]
We got out of memory error, the k8s node is down.

**Comment by pavithraes** [comment]
@RexHuang Thanks for the issue! Perhaps some solutions in this blog post might be helpful: https://coiled.io/blog/tackling-unmanaged-memory-with-dask/

It'll also be great if you can share a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), using a toy dataset and local cluster is possible. Also, since this is a usage question, I'd encourage you to open an issue on [Discourse](https://dask.discourse.group/) (maybe as a reply [to your other question](https://dask.discourse.group/t/bad-performance-with-dask-in-k8s/604) in case it's related and we can continue this discussion there!

**Comment by pavithraes** [comment]
I'll go ahead and close this due to lack of activity, but please feel free to re-open it if needed!
