### ISSUE TITLE
New Collections protocol breaks xarray objects

### ISSUE THREAD

**Issue by dcherian** [dask/dask#9058]
The recent merge of the new Collections protocol (#8674) broke Xarray's tests (https://github.com/pydata/xarray/issues/6578)

Xarray objects [return None](https://github.com/pydata/xarray/blob/4b76831124f8cd11463c9e4ecfdc6842654cf810/xarray/core/dataset.py#L701-L714) from `__dask_graph__` if there no dask arrays being wrapped.

It seems like the current version of `is_dask_collection` only checks for the presence of `__dask_graph__`. Xarray objects are a case where this check is not sufficient (they look like dask collections in general, you can call `dask.visualize` and `dask.compute` on xarray objects).

It isn't clear to me that there is a good solution other than explicitly checking the return value in `is_dask_collection` but if there is something we could do on the Xarray side, please let us know!

**Comment by jrbourbeau** [comment]
Thanks for reporting @dcherian (and hooray for upstream CI testing 🎉 ). I've not had a chance to dig into this yet, but plan to do so tomorrow. cc'ing @douglasdavis @ian-r-rose in the meantime

**Comment by ian-r-rose** [comment]
Thanks for flagging this @dcherian! We had some discussion about exactly this change [here](https://github.com/dask/dask/pull/8674#discussion_r809357431), and were not aware of any downstream usages of returning `None`. At the time it seemed relatively safe since there are many places in dask's codebase that *don't* check for `None` and happily assume the result is a graph. But evidently not.

It's simple enough fix to roll back that change, though after we do it it might be nice if we could continue discussing how to tighten the protocol a bit.

**Comment by douglasdavis** [comment]
I agree with @ian-r-rose. I just created a PR (#9062) to revert the change to `is_dask_collection`.
