### ISSUE TITLE
Order of metadata matters despite metadata being accepted by dict

### ISSUE THREAD

**Issue by s-baumann** [dask/dask#9080]
The order of the metadata you supply does matter in some cases. There is an example here:

https://stackoverflow.com/questions/72171471/order-of-metadata-in-dask-groupby-apply

This seems like a bug as users supply the metadata in the form of a dict. While the latest version of python does remember ordering for dicts, it seems wierd that dask relies on this. If ordering is required it would probably make more sense for dask to require an ordered dict, pandas dataframe or something like that.

**Comment by pavithraes** [comment]
@s-baumann Welcome! Thanks for opening this. I believe the ordering is intentional, see: https://github.com/dask/dask/issues/2789

It's also documented in the [API docs](https://github.com/dask/dask/blob/137206dc04eb62424617a068405545b26db99a6f/dask/dataframe/utils.py#L133-L136):

> For ease of use, some alternative inputs are also available. Instead of a DataFrame, a dict of {name: dtype} or iterable of (name, dtype) can be provided (note that the order of the names should match the order of the columns).

**Comment by jrbourbeau** [comment]
Thanks for raising an issue @s-baumann. As @pavithraes pointed out, the ordering of the meta dict needs to match the order of the DataFrame columns as outlined here https://docs.dask.org/en/stable/dataframe-design.html#metadata. Otherwise, for example, position-based indexing like `df.iloc[:, [1, 0]]` can lead to unexpected results
