### ISSUE TITLE
array reductions across chunks -> huge memory footprint; solvable with shared memory?

### ISSUE THREAD

**Issue by bjudkewitz** [dask/dask#9083]
Array reductions (for example: sum) along chunked axes can lead to very high memory use (and crashes). I assume this has to do with the recursive aggregation, and that results from tasks have to wait in memory for results from other tasks. Especially when the duration of tasks is heterogeneous , this can lead to many such waiting results piling up in memory. For example, the following code will blow up RAM and won't complete on my machine (128 GB RAM):

```
import dask.array as da
a = da.ones((100,1e8), chunks = (1,-1))
a_sum = a.sum(axis=0).compute()
```

However, in the case of reductions such as sum, mean, min, max, prod it would be straightforward to perform the reduction by aggregating results into shared memory. For example:

```
from threading import Lock
from dask.graph_manipulation import bind
from dask.array.utils import meta_from_array

def reduce_shape(t, i, val=1):
    l = list(t)
    l[i] = val
    return tuple(l)

def accumulate_blocks(arr, combine_fcn, axis):

    store = np.empty(shape=reduce_shape(arr.blocks.shape, axis), dtype='object')
    lock = Lock()
    
    def init_fcn(block, block_id=None, block_info=None):
        with lock:
            store[block_id] =  0
        return block
    def apply_fcn(block, block_id=None, block_info=None):
        ix = (*block_id[:axis], 0, *block_id[axis+1:])
        with lock:
            store[ix] = combine_fcn(store[ix], block)
        return np.array(True).reshape((1,)*block.ndim)
    def retrieve_fcn(block, block_id=None, block_info=None):
        out = store[block_id]
        store[block_id] = np.array([])
        return out
    
    out = da.zeros(reduce_shape(arr.shape, axis), chunks=reduce_shape(arr.chunksize, axis), dtype=arr.dtype)
    init_da = out.map_blocks(init_fcn)
    after_block_fcn = bind(arr.map_blocks(apply_fcn, dtype='bool', meta=np.array(True), chunks=(1,)*arr.ndim), init_da)
    out = bind(out.map_blocks(retrieve_fcn, dtype=arr.dtype, chunks=reduce_shape(arr.chunksize, axis), meta=meta_from_array(arr)), after_block_fcn)
    return out


sum_acc = lambda x, axis: accumulate_blocks(x.map_blocks(np.sum, axis=axis, keepdims=True, chunks=reduce_shape(x.chunksize, axis)), np.add, axis)
mean_acc = lambda x, axis: sum_acc(x.astype('float32'), axis) / x.shape[axis]
max_acc = lambda x, axis: accumulate_blocks(x.map_blocks(np.max, axis=axis, keepdims=True, chunks=reduce_shape(x.chunksize, axis)), np.maximum, axis)
min_acc = lambda x, axis: accumulate_blocks(x.map_blocks(np.min, axis=axis, keepdims=True, chunks=reduce_shape(x.chunksize, axis)), np.minimum, axis)
prod_acc = lambda x, axis: accumulate_blocks(x.map_blocks(np.prod, axis=axis, keepdims=True, chunks=reduce_shape(x.chunksize, axis)), np.multiply, axis)
```

And the following code completes without problem and small memory footprint (at least on a local machine using threads):

```
import dask.array as da
a = da.ones((100,1e8), chunks = (1,-1))
a_sum = sum_acc(a, axis=0).compute()
```

Can this only work on the local scheduler or is it conceivable to implement an approach like this for the distributed scheduler as well?

**Comment by pavithraes** [comment]
@bjudkewitz Thanks for opening this!

I think choosing better chunks for the Dask Array would help, but I'm assuming you created this example with `chunks = (1,-1)` just to demonstrate. In any case, here's a good blog about chunk sizes: https://blog.dask.org/2021/11/02/choosing-dask-chunk-sizes :)

> Can this only work on the local scheduler or is it conceivable to implement an approach like this for the distributed scheduler as well?

I'd not expect this to work as in on the distributed scheduler, but maybe @gjoseph92 has more thoughts?

For folks who are curious, here are the task graphs generated by `sum` and `sum_acc` respectively for a small array: `a = da.ones((10,14), chunks = (2,2))`

`a.sum(axis=0).visualize()`:

![8596f09e-4684-47ed-aed2-a6da3f531cfc](https://user-images.githubusercontent.com/33131404/174070814-a2bd8211-8813-4853-8c6d-a36340613d6a.png)


`sum_acc(a, axis=0).visualize()`:

![b4cfb249-2a78-4c2b-bc7f-469f3bd1a488](https://user-images.githubusercontent.com/33131404/174070866-4309ec17-67da-4b3f-81b8-ce2d70c7bd6f.png)

**Comment by gjoseph92** [comment]
@bjudkewitz see https://github.com/dask/distributed/issues/6360#issuecomment-1129434333, https://github.com/dask/distributed/issues/5223, https://github.com/dask/distributed/issues/5555. This is a common issue to see with the distributed scheduler, and I suspect it's more due to a problem in the scheduling algorithm than a problem in the graph. Anecdotally, when I used to use the local threaded scheduler extensively in a production system, I saw the same problem as you where something like a `mean` or `sum` would use more memory than necessary.

I haven't read the [local scheduler code](https://github.com/dask/dask/blob/068eb7fe51aa4274e0b3f69714aec2f30567b39a/dask/local.py) thoroughly. It seems conceivable that it might suffer from a similar root-task-overproduction race condition (though I believe it makes more of an effort to avoid this).

I also haven't read your shared-memory workaround throughly, so I may be misunderstanding what's going on here.

**Comment by gjoseph92** [comment]
I threw together a quick hacky experiment to see how many root objects are hanging around in memory at once. **This confirms to me that root task overproduction is _not_ an issue with the local threaded scheduler.** I've been wanting to verify this for a bit, so thanks for the motivation to do so!

<details>

```python
"""
Run a `sum` workload of varying sizes. See how many root objects are in memory at once.
"""
from __future__ import annotations

from typing import ClassVar
import threading
import datetime

import dask.array as da
import pandas as pd
import matplotlib.pyplot as plt


class TrackMemoryCount:
    lock = threading.Lock()
    count: ClassVar[int] = 0
    counts: list[tuple[datetime.datetime, int]] = []

    def __init__(self, obj):
        with self.lock:
            type(self).count += 1
            self.counts.append((datetime.datetime.now(), type(self).count))
        self.obj = obj

    def __getattr__(self, attr):
        # Proxy things to the underlying object
        return getattr(self.obj, attr)

    def __del__(self):
        with self.lock:
            type(self).count -= 1
            self.counts.append((datetime.datetime.now(), type(self).count))
        del self.obj


NTHREADS = 4
records: dict[str, pd.DataFrame] = {}
for magnitude in range(1, 8):
    assert TrackMemoryCount.count == 0, TrackMemoryCount.count
    TrackMemoryCount.counts.clear()

    a = da.ones((100, 10 ** magnitude), chunks=(1, -1))
    a_tracked = a.map_blocks(TrackMemoryCount, meta=a)
    a_sum = a_tracked.sum(axis=0)
    print(f"Computing 1e{magnitude}")
    a_sum.compute(scheduler="threads", num_workers=NTHREADS)

    series = (
        pd.DataFrame.from_records(TrackMemoryCount.counts, columns=["time", "count"])
        .set_index("time")
        .pipe(
            # normalize timestamps
            lambda df: df.set_index(df.index - df.index[0])
        )["count"]
    )
    records[f"1e{magnitude}"] = series


df = pd.DataFrame(records).sort_index().bfill(inplace=False)
df.plot(title=f"Root objects in memory at once during sum() with {NTHREADS} threads")
plt.savefig("instace-counts.png")
```

</details>

![instace-counts](https://user-images.githubusercontent.com/3309802/174131089-074194f5-60aa-4917-a216-39029203b713.png)
![instace-counts](https://user-images.githubusercontent.com/3309802/174131180-fbad3cbe-6220-4a15-952e-d9cffccb9afb.png)
![instace-counts](https://user-images.githubusercontent.com/3309802/174131262-e649ba01-9dfa-499c-a2e0-78220fe70d23.png)

So we can see that up to NTHREADS root objects will be in memory at once, but never more, which is what we'd expect/want.

Of course, the usual caveat applies: the more you try to do at once, the more memory you'll use at once. If your machine has 128GB of ram, I suspect it has a lot of CPUs as well. How many (what does `dask.system.CPU_COUNT` say)? You may want to `dask.config.set(num_workers=4)` or `compute("threads", num_workers=4)` or something and reduce your parallelism, so that you can't use as much memory. I'm curious how much the lock in your custom code is also helping with this by limiting parallelism.

**Comment by gjoseph92** [comment]
I think what you're observing here is that for this specific aggregation, the fact that we're not doing the sum in-place (each recursive aggregation is written into a new array, as opposed to overwriting an existing "scratch" array in-place) means that we'll use more memory. Each recursive step will have its N inputs + 1 output in memory, for each thread. With your in-place version, the "for each thread" part is removed, because all threads share the one scratch array.

When your chunksizes are large, as yours are—close to a 1GB—the fact that we have an extra 1GB chunk around per intermediate task adds up to a lot.

Though it might be cool to have an inplace optimization, dask generally just doesn't do anything inplace—it's hard to get right and very hard to generalize to a distributed system.

That's part of why, as @pavithraes said, picking reasonable chunksizes is important. If set `chunks=(1, "200mb")` instead, the 1e8-length sum easily computes on my machine using < 3GB with NTHREADS=4.

**Comment by gjoseph92** [comment]
Another thing to be aware of is the [`split_every`](https://docs.dask.org/en/stable/generated/dask.array.reduction.html#dask.array.reduction) parameter. This controls how many input chunks are summed at once. [By default](https://github.com/dask/dask/blob/068eb7fe51aa4274e0b3f69714aec2f30567b39a/dask/array/reductions.py#L256), I think this is 4. You can see in the graph @pavithraes posted that each `sum-partial` task takes 4 `ones_like`s as inputs.

![graph](https://user-images.githubusercontent.com/33131404/174070814-a2bd8211-8813-4853-8c6d-a36340613d6a.png)

So that means each `sum-partial` is going to require 4 inputs chunks + 1 output chunk in memory at once.

So if the chunksize is ~1GB, that's 5GB per task. With 4 threads, you'd expect 20GB of memory used.

And in fact, if I run your `da.ones((100, 1e8), chunks=(1, -1)).sum(axis=0)` case with 4 threads, that's about what I see:

![memory](https://user-images.githubusercontent.com/3309802/174136579-98267303-20e8-405f-a87f-0c0f21522646.png)

**Comment by bjudkewitz** [comment]
Thank you both for investing your time and for these helpful explanations!

**Comment by pavithraes** [comment]
Thank you, Gabe!

@bjudkewitz I'll close this as resolved, please feel free to re-open if needed!
