### ISSUE TITLE
_iLocIndexer / _LocIndexer deterministic hashing

### ISSUE THREAD

**Issue by faulaire** [dask/dask#9092]
Hi,

dask.dataframe.indexing._iLocIndexer and _LocIndexer should implement dask deterministic hashing:
https://docs.dask.org/en/latest/custom-collections.html#deterministic-hashing

The current situation is that dask create new tokens even if loc/iloc instructions are exactly the same:

```python
import pandas as pd
from dask.base import tokenize
from dask.dataframe import from_pandas
import dask

df = pd.DataFrame([[1, 2]], columns=['foo', 'bar'])
dask_df = from_pandas(df, npartitions=1)

foo_df = dask_df.loc[:, ['foo']]
foo_df_2 = dask_df.loc[:, ['foo']]

assert tokenize(foo_df) == tokenize(foo_df_2)
```

Suggested implementation:

```python
@normalize_token.register(_LocIndexer)
def normalize_loc_indexer(x):
    return type(x).__name__, x.obj
```

If you are ok with this implementation, I can add this code to dask.base and raise a PR.

Thanks for you help,

**Environment**:

- Dask version: 2022.05.0
- Python version: 3.9.12
- Operating System: CentOS Linux release 7.6.1810 (Core)
- Install method pip (pypi)

**Comment by jrbourbeau** [comment]
Thanks for reporting @faulaire -- agreed that having identical slices produce the same token hash would be useful 

> Suggested implementation:

Since we control the `_iLocIndexer` / `_LocIndexer` classes, I'd prefer to just add a `__dask_tokenize__` method directly to that class as we do in other place (e.g. [here](https://github.com/dask/dask/blob/6b62cc1215ba05ba6f89b226db0fe8a01a792306/dask/array/ufunc.py#L42-L43) and [here](https://github.com/dask/dask/blob/137206dc04eb62424617a068405545b26db99a6f/dask/dataframe/io/parquet/core.py#L132-L142)). That will help keep tokenization logic co-located with the relevant class

**Comment by faulaire** [comment]
@jrbourbeau , @pavithraes , PR is ready!

Waiting for your comments.
