### ISSUE TITLE
map_partitions of both pivot_table and pivot fail

### ISSUE THREAD

**Issue by martinedgefocus** [dask/dask#9191]
Dask version 2022.05.2

```
df = pd.DataFrame({'as_of_date':["2022-06-01", "2022-06-01", "2022-06-01"], "position_id":[1,2,3], "fund":['a','a','b']})
p = df.pivot_table(index='position_id', columns='as_of_date', values="fund", aggfunc='first')
```
This works fine, but if I try to do it via dask:
```
ddf = dd.from_pandas(df, npartitions=1)
ddf.map_partitions(lambda df : df.pivot_table(index='position_id', columns='as_of_date', values="fund", aggfunc='first')).compute()
```
ValueError: The columns in the computed data do not match the columns in the provided metadata
  Extra:   ['2022-06-01']
  Missing: ['foo']
Why is it expecting "foo" here?

Straight pivot also fails in a strange way.

```
df = pd.DataFrame({'as_of_date':["2022-06-01", "2022-06-01", "2022-06-01"], "position_id":[1,2,3], "fund":['a','a','b']})
p = df.pivot(index='position_id', columns='as_of_date', values="fund")
```
that works fine.
```
ddf = dd.from_pandas(df, npartitions=1)
ddf.map_partitions(lambda df : df.pivot(index='position_id', columns='as_of_date', values="fund")).compute()
```
ValueError('Index contains duplicate entries, cannot reshape')

**Comment by jsignell** [comment]
Thanks for writing this up, that error message is definitely not intuitive. The issue has to do with how dask keeps track of what a particular dask.dataframe object looks like. Dask does that by storing a tiny dataframe that looks similar to the data. Then when you do a transformation on the data, dask tries to figure out what the output will look like by eagerly doing the transformation before you call compute. Normally the actual data in this tiny dataframe (it's called `_meta`) is not important, all that matters is that is has the same dtypes as your real data. In the case of pivot though, the data becomes the column names, so it _does_ matter. 

The workaround in this case is to either tell dask what the meta should be, or tell dask not to worry about the `_meta`. Which you decide to do depends on what you are doing next. If you are going to immediately call compute or write to a file, then it's fine to set `enforce_metadata=False`, if instead you want to leave it as a dask object and keep chaining operations then you'll want to set the meta explicitly.

```python
ddf.map_partitions(... enforce_metadata=False).compute()
``` 

or set the meta explicitly:

```python
ddf.map_partitions(..., meta=p).compute()
```

If

**Comment by martinedgefocus** [comment]
Thanks, that makes a bit more sense ... I'm curious about a couple of things:

1. Why does it use fake data instead of just a snippet of the real data? Seems like that might work better (and give more comprehensible errors)
2. Why does it need the metadata? It's difficult to provide as we're doing transforms on a somewhat fungible underlying schema, so the only way I could know it is to process a subsection of the file using pandas, assign that to the meta variable, and it seems like dask could do that itself.

**Comment by jsignell** [comment]
1. I think I oversimplified a bit too much. Most of the time the `meta` that dask stores is actually an empty dataframe with the correct column names and the correct dtypes for each of the columns. An empty dataframe works fine for emulating lots of operations. Sometimes though, the operations would fail on an empty dataframe so in those cases dask generates a little bit of data from the dtypes. That is what is happening in your case. I am not entirely sure why dask doesn't store a snippet of the data itself, but I bet it's because for a lot of storage types (parquet for instance) dask doesn't actually need to read any of the data to know the column names and dtypes.
2. It doesn't need the metadata as long as it's the last step in the chain. I probably didn't make this clear enough, but the best path for you is to just add `enforce_metadata=False` and then immediately compute or write to a file. Then you can read the file back in as a dask dataframe and carry on. This is the best path because the column names of a pivot table depend on all the data in the input.

**Comment by martinedgefocus** [comment]
Much appreciate all the feedback - thank you! 
What seems odd to me is it seemed to do this even if the input was parquet or a Pandas dataframe and it seems like it could have figured this out itself without asking the user ... if that's unexpected, I'll try to get a decent problem reproduction. If it's possible but just known to be not fixed yet, I'll leave it in peace ;)

**Comment by pavithraes** [comment]
@martinedgefocus I think `@jsignell`'s comments have helped answer your questions. I'm closing this as resolved, but please feel free to re-open it if needed. :)
