### ISSUE TITLE
Optimizer hook for Futures API

### ISSUE THREAD

**Issue by multimeric** [dask/dask#9228]
There are currently `X_optimize` config options [described here](https://docs.dask.org/en/stable/optimize.html#optimization) for the other main APIs (delayed, dataframe etc). But there doesn't seem to be the same thing for futures. 

I would like to request this feature because I'm trying to wire up the graphchain library with dask Futures. Currently graphchain [works using the `optimize_delayed` hook](https://github.com/radix-ai/graphchain#using-graphchain-with-daskdelayed), but without a similar thing for Futures it's not clear how I can proceed.

**Comment by pavithraes** [comment]
Thanks for opening this! I think @gjoseph92 and @crusaderky might find this interesting. :)

**Comment by crusaderky** [comment]
The key difference between dask collections and Futures is that when you compute a collection you send all of its keys at once to the scheduler, whereas with a Future you send one key at a time. 
Optimization is about taking multiple keys and manipulating the graph *before* they reach the scheduler. Hence, with futures, it is impossible.

Even without optimization, typically delayed objects offer better performance than futures because calling compute() on a collection with 100 keys is a lot faster than calling submit() on 100 futures (as the round-trip time and overhead in comms is 1/100th). May I ask what's missing in delayed that you need?

**Comment by multimeric** [comment]
Right, I thought that might be the case. My motivation is #9164. In that issue I was pointed to graphchain, which cleverly caches `delayed` results based on the DAG structure, but I was wondering if it were possible to gain the advantages of both caching (which is very important in my work) and also the flexibility of `Futures`. This isn't a pressing issue because I can and will just use `delayed` instead, but I'm asking out of curiosity.

**Comment by pavithraes** [comment]
@multimeric Based on `@crusaderky`'s comments, I think we can close this issue because this feature request can't be implemented. Please feel free to re-open it if needed. :)
