### ISSUE TITLE
Config widget broken?

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#9279]
![image](https://user-images.githubusercontent.com/306380/179264604-82d25c7b-f612-4a5c-8458-68993dc00229.png)

cc @jacobtomlinson @scharlottej13

**Comment by jrbourbeau** [comment]
Thanks @mrocklin, I'm able to reproduce by going to https://docs.dask.org/en/stable/configuration.html#conversion-utility and making any changes to the YAML section. 

Looking through the codebase it looks like [`jsyaml` is used here](https://github.com/dask/dask/blob/eeb876a822ffbeac22d44206de45f14ce9869da4/docs/source/_static/config_converter.js). Maybe this package used to be installed when we were using the old theme (just a guess)? @jacobtomlinson do you have any thoughts how we might either having `jsyaml` included in the environment where the docs are built, or drop our need to rely on `jsyaml`?

**Comment by jacobtomlinson** [comment]
Everything seems fine in terms of `js-yaml` being loaded in the page, so I don't think this is related to the theme. We vendor the file in due to the way Sphinx wants you to specify JS files, and looking at the console it seems to be throwing an error. 

I wonder if either browsers have moved on in the last two years, or possibly it is trying to pull in a dependency that has moved on. I'll look at updating the version and see if that fixes things.

**Comment by jacobtomlinson** [comment]
I can't seem to figure out why this library isn't being loaded. I wonder if a more sustainable way of handling this would be to use [pyscript](https://pyscript.net/). We would just need to make sure it is loaded with `defer` so that it doesn't slow the whole page down.

**Comment by jrbourbeau** [comment]
Thanks for looking into this. I'll defer to your judgement as what would be the best way to handle this moving forward
