### ISSUE TITLE
`dask_key_name`s with hyphens can get altered

### ISSUE THREAD

**Issue by andrewbarisser** [dask/dask#9333]
**What happened**: If one uses `bind` with `delayed(... dask_key_name)`, the result of `dask.distributed.get_worker().get_current_task()` will not necessarily be the `dask_key_name` provided by the user. I noticed the problem when using ISO 8601 formatted dates as part of the `dask_key_name`. 

**What you expected to happen**: I would expect `dask.distributed.get_worker().get_current_task()` to return the `dask_key_name` provided by the user.

**Minimal Complete Verifiable Example**:

I would have expected to see `child-2000-01-01` rather than `child-9431b3ddf5f3dcd214bf0d080e3c0dee`.

```python

$ cat unexpected_task_key.py 
import dask
import dask.distributed
import dask.graph_manipulation

def f():
    dask.distributed.print(dask.distributed.get_worker().get_current_task())

if __name__ == '__main__':
    cluster = dask.distributed.LocalCluster(n_workers=2, threads_per_worker=8)
    client = dask.distributed.Client(cluster)
    parent = dask.delayed(f)(dask_key_name="parent-1999-12-31")
    child = dask.delayed(f)(dask_key_name="child-2000-01-01")
    child = dask.graph_manipulation.bind(child, parents)
    result = child.compute()

$ venv/bin/python unexpected_task_key.py 
parent-1999-12-31
parent-1999-12-31
child-9431b3ddf5f3dcd214bf0d080e3c0dee
child-9431b3ddf5f3dcd214bf0d080e3c0dee

$ venv/bin/pip list | grep dask         
dask              2022.7.1

$ venv/bin/python --version    
Python 3.8.9

$ sw_vers
ProductName:	macOS
ProductVersion:	11.6.7
BuildVersion:	20G630
```

**Anything else we need to know?**: I suspect the problem is in either `dask.base.key_split` or `dask.base.clone_key`.

**Environment**:

- Dask version: `2022.7.1`
- Python version: `3.8.9`
- Operating System: macOS 11.6.7 
- Install method (conda, pip, source): `pip`

**Comment by andrewbarisser** [comment]
Thanks for pointing out the docstring. Are there rules for how one should expect keys to be regenerated? Based on https://github.com/dask/dask/issues/8783, I would think that at least `child-2000-01-01` would be part of the new key. It seems that hyphens play a special role in the key names but that isn't obvious from the documentation. 

Also (and this is probably a much bigger issue), it isn't clear why one would need to change the key in the first place. The documentation makes it sound like the point of `bind` is to add edges from the `parents` to the `children` in the underlying task graph -- it doesn't make sense that it would create vertices with new attributes.

**Comment by pavithraes** [comment]
@andrewbarisser Ah, I see what you mean.

I think you're absolutely right that the root cause is `key_split`. However, `key_split` seems to be intentionally trimming any numbers after hyphens. Maybe the solution here is to document this better.

https://github.com/dask/dask/blob/e61405cb5d345e73f1952ee3d50708566b5263d1/dask/utils.py#L1804-L1830

@crusaderky Do you have thoughts on this? Especially about the broader question around why `bind` needs to regenerate the keys of `children`?

**Comment by crusaderky** [comment]
`bind` needs to regenerate the keys because it's designed so that you can use the original and the bound keys together.
e.g.

x = cheap_computation_with_large_output()
y = expensive_and_long_computation(x)
z = wrap_up(clone(x), y)

clone(). is a one-line wrapper around bind().
In the above code, the chunks of x will be forgotten as soon as they are consumed by the computation of y, and then they'll be regenerated from scratch at the very end of the computation.

bind() itself is working as intended. The function must change the key into a new, unique one.
The fact that it's preserving a bit of the original key is just out of courtesy.
Currently, it's preserving everything until the first hypen, but this should be treated as an implementation detail.
This behaviour is convenient for auto-generated keys, which are typically (<prefix without hypens>-<hash without hypens>).
This is also coherent with the web GUI, which groups task by their prefix (cut on the first hypen) when visualizing them.

I do not think we should change the code to cut on the last hypen instead, and we should definitely not publicly start supporting such a feature.

If you want to preserve readability, you can change your keys so that they don't contain hypens, e.g. `parent-1999-12-31` to `parent_19991231`. The output of bind() will be something like `parent_19991231-07fae858a9174a398853b4b5927aec73`.
