### ISSUE TITLE
`ddf.set_index` with `sorted=True` drops rows

### ISSUE THREAD

**Issue by jsignell** [dask/dask#9339]
Hi. I see the same issue, but I don't have empty partitions. Can someone explain why I lost records after `set_index`?
```
df = pd.DataFrame({
    'ts': [1, 1, 2, 2, 3, 3, 3, 3],
    'value': 'abc'
})
ddf = dd.from_pandas(df, npartitions=3)
ddf = ddf.set_index('ts', sorted=True)
print(ddf.compute())
```
```
   value
ts      
1    abc
1    abc
2    abc
2    abc
3    abc
3    abc
```
Dask: 2022.5.0
Python: 3.10.4
OS: macOS Monterey 12.1
Install method: pip

_Originally posted by @vdytyniak-exos in https://github.com/dask/dask/issues/8735#issuecomment-1185587580_

**Comment by ian-r-rose** [comment]
Thanks for promoting this to an issue @jsignell. @pavithraes and I have seen issues with `sorted=True` before (cf. https://github.com/dask/dask/issues/8999#issuecomment-1150087728). I'm not 100% sure that is related, but linking so I don't forget later.

**Comment by jorloplaz** [comment]
Exploring a bit, this seems to be some issue with `fix_overlap`. The original `ddf` is:

```python
>>> ddf.divisions
(0, 3, 6, 7)
>>> for p in ddf.partitions:
...     print(p.compute())
...
   ts value
0   1   abc
1   1   abc
2   2   abc
   ts value
3   2   abc
4   3   abc
5   3   abc
   ts value
6   3   abc
7   3   abc
```

Because the index is sorted, we are calling `dd.shuffle.set_sorted_index()`, which in turn calls `M.set_index()`. The output from this is stored in `result`:

```python
>>> result = dd.core.map_partitions(M.set_index, ddf, 'ts', drop=True, align_dataframes=False, transform_divisions=False)
>>> for p in result.partitions:
...     print(result.compute())
...
   value
ts
1    abc
1    abc
2    abc
   value
ts
2    abc
3    abc
3    abc
   value
ts
3    abc
3    abc
```

So far, so good. Now, since `divisions=None` when calling `set_sorted_index`, the last call is `compute_and_set_divisions(result)`, which gives the following tuple of `(mins, maxes, lens)`:

```python
>>> mins, maxes, lens = dd.shuffle._compute_partition_stats(result.index, allow_overlap=True)
>>> mins, maxes, lens
([1, 2, 3], [2, 3, 3], [3, 3, 2])
```

Which is also correct, given the 3 above partitions. Now it's the `fix_overlap(result, mins, maxes, lens)` that ruins things:

```python
>>> dd.shuffle.fix_overlap(aux, mins, maxes, lens).compute()
   value
ts
1    abc
1    abc
2    abc
2    abc
3    abc
3    abc
```

Don't know what the exact problem is, but at least it's more located.

**Comment by jsignell** [comment]
That is very helpful! I think I can do a fix for just this issue.
