### ISSUE TITLE
read_sql() and to_sql()?

### ISSUE THREAD

**Issue by user32000** [dask/dask#943]
It would be wonderful to have both read_sql() and to_sql(), analogous to pandas for those times when you have to clean up inconveniently large datasets. I saw [http://stackoverflow.com/questions/33129839/choosing-a-framework-for-larger-than-memory-data-analysis-with-python](url) but it appears that no issue had been opened yet

**Comment by mrocklin** [comment]
Yup.  I agree that this would be great to have..  For read_sql we would have to include a mandatory order by column to the API in order to cleanly pull out partitions.  See http://www.dofactory.com/sql/order-by-offset-fetch 

This will only work efficiently if there is some indexed column and the user knows what it is.

**Comment by user32000** [comment]
Something more to keep in mind (not that I've tested any of these flavours - I'm stuck with MySQL): [http://blog.jooq.org/2014/06/09/stop-trying-to-emulate-sql-offset-pagination-with-your-in-house-db-framework/](url)

**Comment by user32000** [comment]
@mrocklin on 2nd thought: why would that be different from read_csv, or is your comment about the efficiency of a read_sql process?

**Comment by mrocklin** [comment]
We need to ensure that several separate queries properly partition the data into disjoint subsets that cover the entire table.  I think that the only way to do this is with order-by/limit-offset but would be happy to learn of alternatives.  Additionally, sorting the dataset on an index would align well with other dask.dataframe operations

**Comment by mrocklin** [comment]
It now occurs to me that we don't really want limit/offset, we want to find percentiles on a column and then filter with a where clause for each of the partitions.  This is more in line with the partition by index-value approach.

**Comment by mrocklin** [comment]
This should be fairly easy to implement with `pd.read_sql`, `dask.delayed` and `dask.dataframe.from_delayed`.

**Comment by mrocklin** [comment]
Pseudo code would be something like the following:

```python
def read_sql_table(table_name, con, schema=None, index_col=None, coerce_float=True, parse_dates=None, columns=None, chunksize=None):
    divisions = pd.read_sql_query('select index_col and something with ntile')
    parts = [pd.read_sql_query('select columns from table where index_col >= divisions[i] and index_col < divisions[i + 1]') for i in range(len(divisions) - 1)]
    head = pd.read_sql('select columns from table limit 5')
    return dd.from_delayed(parts, divisions, head)
```

We can probably test against sqlite.  We should probably have pretty loud text warning that the index_column should really be indexed.

**Comment by cdagnino** [comment]
Just in case, NTILE is not supported in sqlite (See [here](http://www2.sqlite.org/cvstrac/wiki?p=UnsupportedSqlAnalyticalFunctions)). Not sure what other function could be used.

**Comment by mrocklin** [comment]
@cdagnino @martindurant ran into this issue in #1181.  Your input on that PR would be appreciated.

**Comment by QCaudron** [comment]
Agreed that this would be an awesome feature. 

Would a good workaround for this be to use the `chunksize` argument to `pd.read_sql` and `pd.read_sql_table`, and use the resulting generator to build up a `dask.dataframe` ?

**Comment by martindurant** [comment]
@QCaudron : Doesn't the use of chunksize use `offset` to do the paging, which we are trying to avoid (see above)?

**Comment by QCaudron** [comment]
@martindurant : think you might be right. The workaround I suggested was to pull data from SQL now in a hacky manner, rather than properly, which I hope will still come shortly ;)

**Comment by gryBox** [comment]
Hi  - Here is how I get mysql into dask. 

My use case essentially involves loading a `list of tables` from `mysql` into a `dictionary {table_name : dask_df, ...}` for grouping -> merging -> factorizing -> 'new db'.  Very similar to the dataflows described in the dask documentation

 It is a bit convoluted but in term of speeds this method beats `odo(uri_conn + table, dd.DataFrame, dshape=ds)` substantially (IMO it is because`odo` uses `pandas` to read the `sql table`). 

```
# mysql to dask
to_dask(dbTbl_name_str):
    # Handles whether remote or local host
    try: # Fast way using inline
    # 1. mysql to_csv using odo
    odo_csv = odo(uri_conn + dbTbl_name_str, csvNm, 
                             dshape= mysql_ds, ...) 

	# 2. csv_to_dask using  (header does not work in mysql natively (google mysql outfile headers)
        # Settings very important (Windows stuff)
	dd_df = dd.read_csv(self.odo_csv.path, header=0, 
							names=tbl_clmNms_list, # From list of sql tbl names (using get column names from mysql
							quoting=csv.QUOTE_NONE,
							encoding='latin1',
							sample=self.odo_csv_numbytes,
							collection = True # This where more optimization could be put in
							)

			#dd_df.compute()
			#display(dd_df.head(1))

```
Notes:

- I have done some optimization using dask delayed (roughly 50% improvement) but not in production.
- The actual code has a `try: `csv method` except: using odo(mysql, dd.DataFrame, ..)`

I hope this strengthens the case for a `dask.read_sql` , maybe  'to_sql` :)

Cheers

**Comment by mrocklin** [comment]
Very cool @gryBox . 

If dask.dataframe adds a read_sql command (as is done in #1181) it would probably just use the `sqlalchemy/pandas.read_sql` function, which, as you say, can be fairly slow.  We probably don't have the manpower to robustly build out SQL->CSV->DataFrame pipelines for all databases.  We tend to lean on whatever Pandas does for most functionality and push performance considerations up to that project.

**Comment by martindurant** [comment]
I agree that the slowness is probably in pandas alone (I don't think pandas' read_sql uses sqlalchemy for more than creating the connection and passing through pre-prepared SQL). Looking in the code, odo converts to csv on the server, which is why its faster.

In any case, SQL data is usually sent down the line essentially as text. To get the very best performance, I remember seeing (but I can't now find) that you can specify an SQL query to return packed binary data, the sort of thing that could be read with `np.fromstring` if the dtype is exactly defined. Perhaps worth if for really critical applications.

**Comment by gryBox** [comment]
@mrocklin Thanks.  

> We probably don't have the manpower to robustly build out SQL->CSV->DataFrame pipelines for all databases.

Yes.  The task is very time consuming with too many flavors and variables.  Using `sqlalchemy/pandas.read_sql`  would suffice ... `sql alchemy` would handle the errors and is robust enough.

@martindurant 

> SQL query to return packed binary data

Going to investigate this.  I can see skipping the csv part, getting the `packed binary data -> np.fromstring -> ... -> dd.DataFrame` No messing around with `csvs` permissions and other sql to text junk.  

> if the dtype is exactly defined

Hoping that something like this will take care of that:
`	# create resource
	resc = resource(data_obj)

	# Dicover the resource
	odo_ds = discover(data_obj)`

Another path I learned about a couple of days ago was [Inline JSON Path Expressions in MySQL 5.7](http://mysqlserverteam.com/inline-json-path-expressions-in-mysql-5-7/).  Still needs to be tested

**Comment by morganics** [comment]
I'm looking at using Dask as an almost drop-in replacement for pandas, but require the to_sql functionality (purely in to a flat table format for sqllite) for working with a (non-Python) third party tool that streams its data from an SQL table. I've not used Dask at all at this point, so would be grateful for any suggestions on how to implement to_sql prior to this becoming part of the library. The only thing required is that it can write a single table with a unique row index (currently I'm using pandas.to_sql). Thanks.

**Comment by martindurant** [comment]
@morganics : I haven't tested this, but I believe calling `.to_sql()` on each pandas dataframe section is totally fine, if you include the `if_exists="append"` parameter. You will need to create the row index as a column beforehand.
