### ISSUE TITLE
Why does Dask load every chunk into memory when using `sel` on a `xarray` Dataset?

### ISSUE THREAD

**Issue by guidocioni** [dask/dask#9451]
I have the following `xarray` dataset not loaded into memory

<img width="731" alt="Screen Shot 2022-09-01 at 13 39 58" src="https://user-images.githubusercontent.com/12760310/187905426-5342cfbe-82c4-4fa7-8380-8cff946e28d5.png">

I wouldn't consider the dataset "huge": on the machine that I'm trying this on it may even fit into memory. 
Still, trying to do a simple operation like selecting 1 point from a pair of latitude, longitude coordinates proves to be a real problem.

```python
dset.sel(longitude=10, latitude=53.55, method='nearest').compute()
```

I've been trying with local clusters of 2 up to 6 workers (48 threads each) and different chunk sizes but every time Dask attempts to load into memory the entire dataset. Looking at the status page I can clearly see that the `in-memory` number is always increasing, together with the RAM usage on my system.
This kind of goes against the idea of using Dask in the first place because I want to avoid filling up the memory by doing parallel computations. 
If I even try to load the dataset into memory at the beginning it takes a really long time and doesn't even finish up. 

Am I hitting a corner case in performance?

**Comment by observingClouds** [comment]
Hi @guidocioni,
Your case works for my own datasets. Would you mind posting the results of `xr.show_versions()` and how you loaded the dataset e.g. with `xr.open_dataset`, `xr.open_zarr`, `xr.open_mfdataset`?

**Comment by guidocioni** [comment]
Hey @observingClouds , nice to 'see' you again 😉
Very simply I used `open_mfdataset` to merge 3 different files from the ECMWF ensemble; as I'm reading grib files the engine `cfgrib` is used .
Maybe that's where the issue lies?

**Comment by observingClouds** [comment]
Yes, nice to 'see' you!

I'm not a big fan of the GRIB format, so I try to avoid it as much as I can, but it could very well be that your issue comes from using GRIB/`cfgrib`. You might want to have a look at https://github.com/gribscan/gribscan

@d70-t and @lkluft can explain this probably much better. But the main issue, why the data is eagerly loaded here, is likely due to the way `cfgrib` presumably reads the GRIB files. 

**A little bit of background to GRIB**
A GRIB file is basically a container for a bunch of messages that holds the data. Each message contains a header and the actual data chunk. Their maximum dimensionality is 2 and therefore the lat-lon field is mostly written to a single message. For each height level and time step an extra message is added. As messages do not need to be sorted and can be of different lengths, all messages need to be read to find a datapoint of interest.

**The issue with GRIB**
The smallest entity in a GRIB file is a single message. Because you need to know the header to interpret the data in a message, I can imagine that the whole message is just loaded with `cfgrib` as it forms a closed entity.  What [gribscan](https://github.com/gribscan/gribscan) does, is to scan your GRIB file for all headers and then creates a reference filesystem that knows at which byte ranges a specific datapoint is stored, without the need to read all messages again to find the right one.

I hope this helps!

**Comment by guidocioni** [comment]
I also don't like grib files and, yep, that's what I thought as well yesterday and that's what explaining the behaviour. Still grib files occupy way less space than NC and usually that's what you find as primary data.
I was searching for a library that would let me 'query' the grib file without having to scan it entirely...thanks for the suggestion, I'll try gribscan!

**Comment by observingClouds** [comment]
Yeah, give it a try. You only have to scan the GRIB file ones. Also, you can write netCDF4 files that are as well compressed as GRIB, you just need to apply lossy compression to the netCDF4 data as well...but that's a different story.

I would raise this issue at cfgrib, but depending on the version that you are using, they might have [fixed it](https://github.com/fsspec/kerchunk/pull/198) already.

**Comment by guidocioni** [comment]
> Yeah, give it a try. You only have to scan the GRIB file ones. Also, you can write netCDF4 files that are as well compressed as GRIB, you just need to apply lossy compression to the netCDF4 data as well...but that's a different story.
> 
> I would raise this issue at cfgrib, but depending on the version that you are using, they might have [fixed it](https://github.com/fsspec/kerchunk/pull/198) already.

True but (1) you need additional time to process them (2) you need some additional time when loading them into `xarray` because at some point you need to apply de-compression. From what I remember last time that I tried the overhead of these 2 operations was not worth the try :)

**Comment by guidocioni** [comment]
@observingClouds since you're here, what you think would be the most efficient (fastest, less resources) way of extracting time series of all members for some grid points from grib files? Besides `gribscan` are there any pure Python approaches?
For the time being I've been using ptyhon CDO bindings with `remapnn` because I haven't yet found something as fast as that which is also not CPU or RAM intensive. 

Thanks again for the help.

**Comment by d70-t** [comment]
There are a couple of things going on here:

## GRIB 
* GRIB messages always represent a single horizontal surface in it's entirety (except of few very special cases).
* GRIB files are just a plain concatenation of GRIB messages. They can appear in any order, be each of variable size and there is no index which you can use to directly access individual messages.

Thus, without any additional tooling, it's just impossible to access data in GRIB files faster than by scanning through the entire file until you find what you want.
Selecting a single lat-lon point out of the file requires to read every single GRIB message entirely and to drop everything except one single data point. If that's your only task, the fastest way to do this may be to loop through the file and do just that. `cdo` internally uses this model (running though a sequence of messages).
Note that you can't really parallelize this task very much, because you can't know where the next message starts before handling the previous one. You'd need an index of these start positions to be able to fetch anything in parallel.

`gribscan` is one (relatively quick) way to build such an index, but the design of `gribscan` is intentionally not "plug and play". This is because GRIB doesn't encode any information across messages. Thus a lot of the structural information required to build a dataset out of these messages is missing. We've wanted the user of `gribscan` to use customization points to make the resulting dataset nice instead of building a generic solution (like e.g. `cfgrib` aims to be).

But all of these tools can't get you around the fact, that you still only need single values out of a large message and thus only about 2 ppm of your bytes to read are actually useful bytes.

## reading with dask

Dask can be used to parallelize some of the tasks required (e.g. one task per GRIB message as your screenshot shows). To do so in a general way, it doesn't run through the tasks in order. But as said before, you'll have to make use of an index telling where each message starts, because otherwise you wouldn't be able to fetch the message corresponding to a particular `number` and `step`.
Assuming this index exists somewhere (`cfgrib` should do something like this internally as well), there might also be some scheduling problems going on. I've previously seen cases where I **believe** dask figured that all the tasks which load data into memory are ready to execute (because they have no predecessors), but those tasks which cut out one single element of a .5M sized chunk are (initially) not ready (because they need the data to be loaded first). Unfortunately I couln't proceed in fixing these issues, because I wasn't able to build a reliably reproducible minimal example.

## netCDF

A main difference between GRIB and netCDF is that netCDF carries it's index with the file. This makes random access possible and thus picking individual pieces is much faster. netCDF also supports flexible chunking, which would be extremely helpful in your particular case (see e.g. [this blog post](https://www.unidata.ucar.edu/blogs/developer/entry/chunking_data_why_it_matters)). Essentially it says, if your chunk shape is moderate (in stead of extreme), the average access time will go down massively, because you don't have to read the entire file anymore. GRIB unfortunately forces you into about the most extreme chunk shape.

netCDF4 supports compression, but unfortunately the default algorithm `zlib` is super slow. Additional to compression, there's also the possibility to represent float values as (e.g. 16bit) integers by applying offsets and scaling factors. This is what GRIB also does internally, it's super fast, but of course it's lossy compression. So to do a fair compresseion with GRIB in terms of file size and compression speed, you'd have to do scaling to integer values and comression using `zstd` or `lz4` instead of the default options.

**Comment by guidocioni** [comment]
> There are a couple of things going on here:
> 
> ## GRIB
> * GRIB messages always represent a single horizontal surface in it's entirety (except of few very special cases).
> * GRIB files are just a plain concatenation of GRIB messages. They can appear in any order, be each of variable size and there is no index which you can use to directly access individual messages.
> 
> Thus, without any additional tooling, it's just impossible to access data in GRIB files faster than by scanning through the entire file until you find what you want. Selecting a single lat-lon point out of the file requires to read every single GRIB message entirely and to drop everything except one single data point. If that's your only task, the fastest way to do this may be to loop through the file and do just that. `cdo` internally uses this model (running though a sequence of messages). Note that you can't really parallelize this task very much, because you can't know where the next message starts before handling the previous one. You'd need an index of these start positions to be able to fetch anything in parallel.
> 
> `gribscan` is one (relatively quick) way to build such an index, but the design of `gribscan` is intentionally not "plug and play". This is because GRIB doesn't encode any information across messages. Thus a lot of the structural information required to build a dataset out of these messages is missing. We've wanted the user of `gribscan` to use customization points to make the resulting dataset nice instead of building a generic solution (like e.g. `cfgrib` aims to be).
> 
> But all of these tools can't get you around the fact, that you still only need single values out of a large message and thus only about 2 ppm of your bytes to read are actually useful bytes.
> 
> ## reading with dask
> Dask can be used to parallelize some of the tasks required (e.g. one task per GRIB message as your screenshot shows). To do so in a general way, it doesn't run through the tasks in order. But as said before, you'll have to make use of an index telling where each message starts, because otherwise you wouldn't be able to fetch the message corresponding to a particular `number` and `step`. Assuming this index exists somewhere (`cfgrib` should do something like this internally as well), there might also be some scheduling problems going on. I've previously seen cases where I **believe** dask figured that all the tasks which load data into memory are ready to execute (because they have no predecessors), but those tasks which cut out one single element of a .5M sized chunk are (initially) not ready (because they need the data to be loaded first). Unfortunately I couln't proceed in fixing these issues, because I wasn't able to build a reliably reproducible minimal example.
> 
> ## netCDF
> A main difference between GRIB and netCDF is that netCDF carries it's index with the file. This makes random access possible and thus picking individual pieces is much faster. netCDF also supports flexible chunking, which would be extremely helpful in your particular case (see e.g. [this blog post](https://www.unidata.ucar.edu/blogs/developer/entry/chunking_data_why_it_matters)). Essentially it says, if your chunk shape is moderate (in stead of extreme), the average access time will go down massively, because you don't have to read the entire file anymore. GRIB unfortunately forces you into about the most extreme chunk shape.
> 
> netCDF4 supports compression, but unfortunately the default algorithm `zlib` is super slow. Additional to compression, there's also the possibility to represent float values as (e.g. 16bit) integers by applying offsets and scaling factors. This is what GRIB also does internally, it's super fast, but of course it's lossy compression. So to do a fair compresseion with GRIB in terms of file size and compression speed, you'd have to do scaling to integer values and comression using `zstd` or `lz4` instead of the default options.

Thanks! That's super helpful. 
I suspected that GRIB files didn't allow for random access and everything that you said make sense. 

In my case it seems that the best options are

1. Converting the file to netcdf beforehand. However, this would increase the size footprint by a factor of 2 (at least) without compression. Using compression (as you said) would increase the processing time as well, thus defeating the purpose of optimizing the whole thing in the first place :) 
2. Letting `cdo` scan the entire file with `remapnn` and produce temporary file to be opened afterwards with `xarray` and `cfgrib` as engine (this is what I'm currently doing now). 
3. Somehow build an index of the grib file beforehand that allows me to find the correct message without having to scan the entire file. 

I think for now it makes sense sticking to solution 2.

**Comment by d70-t** [comment]
Yes. If all you ever want is to get a series at a single lat/lon point, starting from the GRIBs you have, then it's likely very hard to do anything better than what `cdo` does. In this particular case, an index won't help you much because you'll have to read everything anyways.

If you want to bring your data into a format once which enables quick retrieval of series at random points many times, then you'll have to go to other formats (like netCDF4 or zarr). Note that if compression is done properly, it will likely **reduce** retrieval time. It's just unfortunate that the netCDF4 defaults happen to be particular slow choices (but that's because history).

**Comment by guidocioni** [comment]
I'll close this for now. In case someone is interested I followed up with https://github.com/ecmwf/cfgrib/issues/311
