### ISSUE TITLE
expose the API as a section in main documentation

### ISSUE THREAD

**Issue by jreback** [dask/dask#953]
searching for a specific API function, e.g. ``.apply`` works great, but this would provide an ability to browse directly.

cc @electronwill

**Comment by mrocklin** [comment]
I believe that @jreback was particularly looking for the dask.dataframe API

**Comment by jreback** [comment]
related and not sure if this is more general, ``dask.dataframe.read_hdf`` does not appear to be exposed (even when searching)

**Comment by electronwill** [comment]
You mean have "API" as one of the top-level categories in the left sidebar at dask.pydata.org, right?

Geri Ochoa ( @gochoam ) is the one now handling the dask docs, and as long as he and Kerry ( @kerrywatson1 ) approve, that seems fine.

The docs don't seem to have any information about read_hdf. Running python and ``help(dask.dataframe.read_hdf)`` showed this:

```
Help on function read_hdf in module pandas.io.pytables:

read_hdf(path_or_buf, key=None, **kwargs)
    read from the store, close it if we opened it

    Retrieve pandas object stored in file, optionally based on where
    criteria

    Parameters
    ----------
    path_or_buf : path (string), or buffer to read from
    key : group identifier in the store. Can be omitted a HDF file contains
        a single pandas object.
    where : list of Term (or convertable) objects, optional
    start : optional, integer (defaults to None), row number to start
        selection
    stop  : optional, integer (defaults to None), row number to stop
        selection
    columns : optional, a list of columns that if not None, will limit the
        return columns
    iterator : optional, boolean, return an iterator, default False
    chunksize : optional, nrows to include in iteration, return an iterator

    Returns
    -------
    The selected object
```

Was this not included in the dataframe API at dask.pydata.org because it's actually part of pandas, and dask.dataframe just links to it? If so, how should we handle that? Maybe create a page listing the pandas functions that dask.dataframe links to, and make each item in the list a link to that function's documentation on the pandas site, such as http://pandas.pydata.org/pandas-docs/version/0.17.1/generated/pandas.read_hdf.html#pandas.read_hdf ?

**Comment by jreback** [comment]
@electronwill yep excatly w.r.t. the API as a top-section

**Comment by mrocklin** [comment]
Sphinx supports API docs.  I think that this should be handled by 

1.  Making the dask.dataframe api docs more prominent, as you suggest
2.  Ensuring that dd.read_hdf is listed in that page.

**Comment by mrocklin** [comment]
It would be good if this could be a separate PR from other documentation work

**Comment by electronwill** [comment]
Yes, making it a separate PR sounds wise.

What would we do differently to ensure that dd.read_hdf is listed with the other dataframe functions at http://dask.pydata.org/en/latest/dataframe-api.html ?

**Comment by mrocklin** [comment]
We would add it to `docs/source/dataframe-api.rst`, probably next to read_csv

**Comment by mrocklin** [comment]
http://dask.readthedocs.org/en/latest/dataframe-api.html

This is complete.
