### ISSUE TITLE
.columns incorrect after merge

### ISSUE THREAD

**Issue by jreback** [dask/dask#959]
dask 0.7.6
```
In [42]: df1 = pd.DataFrame({'A' : [1,2,3], 'B' : list('abc'), 'C' : 'foo', 'D' : 1.0},columns=list('DCBA'))

In [43]: df1
Out[43]: 
   D    C  B  A
0  1  foo  a  1
1  1  foo  b  2
2  1  foo  c  3

In [44]: df2 = pd.DataFrame({'G' : [4,5], 'H' : 6.0, 'I' : 'bar', 'B' : list('ab')},columns=list('GHIB'))

In [45]: df2
Out[45]: 
   G  H    I  B
0  4  6  bar  a
1  5  6  bar  b

In [46]: pd.merge(df1,df2,on='B')
Out[46]: 
   D    C  B  A  G  H    I
0  1  foo  a  1  4  6  bar
1  1  foo  b  2  5  6  bar

In [47]: ddf = dd.from_pandas(df1,npartitions=3)

In [48]: dd.merge(ddf,df2,on='B').compute()
Out[48]: 
   D    C  B  A  G  H    I
0  1  foo  a  1  4  6  bar
1  1  foo  b  2  5  6  bar
```

```
# this is out of order w.r.t. the actual merged output
# and can affect future operations
In [49]: dd.merge(ddf,df2,on='B').columns  
Out[49]: ('D', 'C', 'A', 'G', 'H', 'I', 'B')
```

This might be because setting .columns doesn't have any effect
```
In [53]: df1 = pd.DataFrame({'A' : [1,2,3], 'B' : list('abc'), 'C' : 'foo', 'D' : 1.0},columns=list('DCBA'))

In [54]: ddf = dd.from_pandas(df1,npartitions=3)

In [55]: ddf
Out[55]: dd.DataFrame<from_pandas-668e7ccb027a1a83b01d197ba0395de9, divisions=(0, 1, 2, 2)>

In [56]: ddf.compute()
Out[56]: 
   D    C  B  A
0  1  foo  a  1
1  1  foo  b  2
2  1  foo  c  3

In [57]: ddf.columns = list('ABCD')

In [58]: ddf.compute()
Out[58]: 
   D    C  B  A
0  1  foo  a  1
1  1  foo  b  2
2  1  foo  c  3
```

**Comment by jcrist** [comment]
A few things:

- Previously you couldn't set columns using `df.columns = ...`, as this would mutate the `dd.DataFrame`, but not the underlying computational graph. This was fixed in #961.

- The actual computation result is correct, but the order of the columns on our proxy aren't consistent with the order in the actual result. Unfortunately inferring this is proving difficult, as pandas has inconsistent behavior. We use an empty dataframe to hold the metadata, but executing the merge command on the empty frame results in a different column ordering than a non-empty frame:

```python
In [10]: pd.merge(df1, df2, on='B').columns
Out[10]: Index([u'D', u'C', u'B', u'A', u'G', u'H', u'I'], dtype='object')

In [11]: pd.merge(df1.iloc[:0], df2.iloc[:0], on='B').columns
Out[11]: Index([u'D', u'C', u'A', u'G', u'H', u'I', u'B'], dtype='object')
```

It's not clear to me what the best path forward here is.

**Comment by mrocklin** [comment]
This comes up also with `.apply` where we would really like to know how a function behaves on a mostly empty dataframe.  I'm tempted to build a function that constructs a very small but non-empty dataframe with fake data.

**Comment by jreback** [comment]
Agreed I would actually do the calculation on a sample

**Comment by mrocklin** [comment]
Well, to be clear, we often don't actually have a sample of the data at this stage.  We would need to generate fake data.
