### ISSUE TITLE
Dask crashes terminal when trying to sort large CSV file

### ISSUE THREAD

**Issue by GhostDog98** [dask/dask#9757]
**Describe the issue**:
When attempting to load and then sort a large CSV file (111Gb, 4,294,967,295 lines long), dask crashes without warning or error, and also crashes the current terminal instance with it.

**Minimal Complete Verifiable Example**:

```python
import dask
import dask.dataframe as dd

df = dd.read_csv("data.csv")
df.sort_values("column1", na_position='first')
df.to_csv("out.csv", sep=",", index=FALSE)
```

**Anything else we need to know?**:
Sample format of the data is:
```
11598,48,4,40,14,15,32
115789,29,14,32,12,47,27
```
And so on. 
**Environment**:

- Dask version: 2022.04.2
- Python version: 3.9.7
- Operating System: Arch Linux 5.15.82-1-lts (dask ran in a non desktop environment)
- Install method: pip

**Comment by GhostDog98** [comment]
Update: checking dmesg after the crash, I see an OOM kill. I'm still unsure as to why this happens...

**Comment by GhostDog98** [comment]
As expected, this didn't resolve the issue, most likely because I misread 2021 as 2022 on the version number 🤦‍♀️

**Comment by rjzamora** [comment]
Welcome @GhostDog98! While there are certainly ways to sort/shuffle large datasets in Dask, it is [well-known](https://docs.dask.org/en/stable/dataframe-best-practices.html#avoid-full-data-shuffling) to be a difficult and memory-intensive operation.

If sorting is necessary, then I definitely suggest that you use `distributed` to deploy a cluster (see [LocalCluster](https://docs.dask.org/en/stable/deploying-python.html#localcluster) documentation). This is because you need your tasks to be executed on `distributed` worker processes to benefit from features like memory spilling. If you are using `distributed`, you can also use the `shuffle="p2p"` option to (usually) improve memory stability. It looks like the `shuffle` kwarg may not be handled by `sort_values` yet (oops!), but `set_index` does (which sorts by the new index).

**Comment by rjzamora** [comment]
Hmm - I suppose your reproducer would be using a "disk" shuffle (which I'd expect to be slow, but to "work").

**Comment by GhostDog98** [comment]
I've since solved my issue by using some bash sed magic, but it might be worth adding to the sort documentation page something like "if you are not using a distributed instance of dask, the OOM killer may kill dask" as this isn't behaviour that I think is expected by many...
