### ISSUE TITLE
Use costomized lib

### ISSUE THREAD

**Issue by b-y-f** [dask/dask#9820]
I'm saving my repeated feature engineering code all in `\libs` directory and it's called `utl`, every time I want to use it I just `from utl import xx,xxx,xxx`. But it does not work in dask.

```python
sys.path.insert(0, '../libs/')
```

Dask gives me 

```
ModuleNotFoundError: No module named 'utl'
```

**Comment by jrbourbeau** [comment]
Thanks for the issue @b-y-f, it sounds like you have some custom code locally that you want to use on your Dask cluster. For this we recommend using [`Client.upload_file`](https://docs.dask.org/en/stable/futures.html#distributed.Client.upload_file) or the [`DirectoryUpload` plugin](https://distributed.dask.org/en/stable/plugins.html#built-in-nanny-plugins)

**Comment by b-y-f** [comment]
Ok, thanks do you mean I need to copy the `utl.py` to all the workers?

**Comment by ncclementi** [comment]
@b-y-f if you are using a Cluster that is not a LocalCluster, you workers are not aware of the files in the Client side. If this is your case then you need to have the file available in all the workers. The links that @jrbourbeau posted above will be the right documentation to follow. 

If you are ok, and since this is more of a usage question, I would suggest we close this issue, and if you have follow up questions related to usage then you can post on dicourse https://dask.discourse.group/

**Comment by jrbourbeau** [comment]
Going to close this issue for now as `Client.upload_file` and `DirectoryUpload` should be what you want @b-y-f
