### ISSUE TITLE
Consider migrating some Dask-SQL utility functions into Dask

### ISSUE THREAD

**Issue by sarahyurick** [dask/dask#9899]
**Describe the issue**:

In the [Dask-SQL project](https://github.com/dask-contrib/dask-sql), we have several datetime utility functions, some of which I was wondering might be more useful on the Dask side.

**Minimal Complete Verifiable Example**:

[is_datetime](https://github.com/dask-contrib/dask-sql/blob/88377b48ea08ac50d45dc563dc1ae8500af45cfa/dask_sql/utils.py#L33)
```python
def is_datetime(obj):
    """
    Check if a scalar or a series is of datetime type
    """
    return (
        pd.api.types.is_datetime64_any_dtype(obj)
        or isinstance(obj, datetime)
        or isinstance(obj, np.timedelta64)
    )
```

[convert_to_datetime](https://github.com/dask-contrib/dask-sql/blob/88377b48ea08ac50d45dc563dc1ae8500af45cfa/dask_sql/utils.py#L44)
```python
def convert_to_datetime(df):
    """
    Covert a scalar or a series to datetime type
    """
    if is_frame(df):
        df = df.dt
    else:
        df = pd.to_datetime(df)
    return df
```

[as_timelike](https://github.com/dask-contrib/dask-sql/blob/88377b48ea08ac50d45dc563dc1ae8500af45cfa/dask_sql/physical/rex/core/call.py#L44)
```python
def as_timelike(op):
    if isinstance(op, np.int64):
        return np.timedelta64(op, "D")
    elif isinstance(op, str):
        return np.datetime64(op)
    elif is_datetime(op):
        return op
    else:
        raise ValueError(f"Don't know how to make {type(op)} timelike")
```

**Anything else we need to know?**:
The general idea is to make working with datetimes in Dask a bit more robust and straightforward, since some of the special logic I've had to use in Dask-SQL could get a bit annoying. Let me know what you think about these examples or other possible ways to simplify Dask datetime logic 🙂

cc @charlesbluca I also wanted to know your thoughts on this?

**Comment by charlesbluca** [comment]
Would the idea be to expose these as external functions for users working with datetimes/timedeltas, or internal helper functions for Dask APIs working with them?

For the former, it would probably make sense to identify that these types of operations are pain points for general users first, as from my perspective these functions are biased towards the typical operations happening in Dask-SQL that are only dealing with columns or scalar values.

For the latter, instead of upstreaming these functions as is, would it make sense to look through Dask's datetime code to see if we can identify some repetitive patterns that can be consolidated, and then introduce utilities for those that could be adopted downstream by Dask-SQL (if possible)?

**Comment by sarahyurick** [comment]
Closing for now, as I no longer see a strong/clear advantage to adding these types of functions. Will keep in mind if I stumble upon anything specific/useful as I continue to work on datetime logic.
