### ISSUE TITLE
Get length of parquet-backed dask dataframe from metadata

### ISSUE THREAD

**Issue by LucaMarconato** [dask/dask#9973]
Using `pyarrow` one can get the length of a table stored in `.parquet` immediately.

```
from pyarrow.parquet import read_table
table = read_table('my_table.parquet')
print(len(table))
```

Dask dataframes instead store this quantity as a `Delayed`. I have a use case in which I only rarely modify the dask dataframe that I load from disk and I would like to immediately know their lenght.

Would it be possible for dask dataframes to read the length of a table from the `.parquet` metadata and store it, so that this value can be returned immediately, if the table length has not been modified? Of course if an operation like a subsetting is performed, then the new length must be computed, but dask may have the knowledge of which operation may alter the length and which not, so returning the cached length could be a nice feature.

**Comment by rjzamora** [comment]
Thanks for raising this @LucaMarconato!

There has certainly been some discussion on this topic:

- **Similar issues**: https://github.com/dask/dask/issues/6387, https://github.com/dask/dask/issues/5633
- **Related PRs**: https://github.com/dask/dask/pull/7912, https://github.com/dask/dask/pull/9473, https://github.com/dask/dask/pull/9706

I'm going to close this issue since there is so much overlap. However, I agree that this optimization should be addressed as soon as possible.
